### ISSUE TITLE
Read more - with tag, not word-count...

### ISSUE THREAD

**Issue by emanuel-s** [danpros/htmly#114]
It would be nice to have the feature of a word-tag to cut the text for the teaser. Like in Wordpress, where you can insert a tag like <-- more --> and this is used to cut/split the text for the front-teaser.

Background: now with the word-count of the teaser-text, it cuts also words itself and the paragraphs get lost too... but e.g. I want to have two paragraphs of my new post on the front-page, then the read more-link for the rest of the paragraphs/content. (Also to avoid troubles with blockquotes or image-positions in the content).

That would be great and would lead me to say Wordpress goodbye. Finally. :)

**Comment by danpros** [comment]
Latest release already have this feature. Set the teaser.type to full and use:

```
<!--more-->
```
