### ISSUE TITLE
3rd Party Photo Storage

### ISSUE THREAD

**Issue by Xarcell** [danpros/htmly#118]
For the sake of keeping bandwidth usage low, create a plugin that user's can install that will use their  photos from third party sources, such as: Flickr, Google +, SmugMug, Instagram, Dropbox, etc.

For photographers, keeping thousands of photos on your own server isn't ideal. these photographers depend on third party hosting services to host their images. It would also benefit those who host their sites on shared servers, which would be the majority of flatfile CMS user's.

**Comment by danpros** [comment]
Even now you can upload images using the markdown editor.
