### ISSUE TITLE
The Roadmap

### ISSUE THREAD

**Issue by Kanti** [danpros/htmly#119]
- ~~Add a Draft Feature~~
 - ~~Add Config Editor [with a Display that the File Permission aren't correct]~~
 - Add Refback/Trackback/Pingback/webmention
 - Add Threads [Posts could be grouped together]
 - Add  Tag  [see #114]
 - reorganize the Cache
 - Fulltext search
 - ~~Change time publish without change url #108~~
 - ~~Customize Permalink for post #87~~
 - ~~related posts widget sort by increase user engagement #117~~
 - use bower/(bower-installer) for frontend components

Some of the Features are just Dreams, but that's there I see HTMLy future.

**Comment by danpros** [comment]
We need new roadmap :smile:
