### ISSUE TITLE
FR: static Page export

### ISSUE THREAD

**Issue by snapo** [danpros/htmly#130]
Hi first thanks for this great app.... 
Would it be possible to have a button to create from the whole blog static pages?
- html files
- css files
- folder structure (same like if you browse the web)
- sitemap
- rss.xml
- atom.xml
- robots.txt

Reason why i would love this feature is , that i could use for example admin.mydomain.com for creating new entrys and www.mydomain.com where another server (rsync) delivers only static pages. This would fasten up the website. Also in this way i can provide load balancing by round robin dns (not that i need it i just like it). Also it prevents script kiddys from accessing the admin page and there is no more need for a .htaccess file on the delivery-webserver.

**Comment by danpros** [comment]
This issue is too old, I will close this one. Please create new issue for possible improvements. Thanks
