### ISSUE TITLE
URLs without date

### ISSUE THREAD

**Issue by alex-hofstadter** [danpros/htmly#133]
Is there a way to have URLs without showing the date in blog post other than .htaccess? Say, if my blog is at alex-hofstadter.com, and the blog post title is 'HTMLy rocks', I want the URL to be alex-hofstadter.com/htmly-rocks rather than alex-hofstadter.com/2014/12/htmly-rocks. And, a suggestion: if another blog post has the same title as an older one, it can be something like alex-hofstadter.com/htmly-rocks-1

**Comment by ncang** [comment]
@fahmi182 of course :) , I've waited long enough for this realization was officially.

**Comment by fahmi182** [comment]
hi @Kanti , you can test it here https://www.anakseo.com/images/ghtmly.zip -- that resource htmly without date in url :) demo here: http://ghtmly-investra.rhcloud.com/

**Comment by byens** [comment]
How to use this feature?

**Comment by danpros** [comment]
Try the master branch. I already make a few changes for this.

**Comment by danpros** [comment]
This already available on newest version. https://github.com/danpros/htmly/releases/tag/v2.5.9
