### ISSUE TITLE
HTMLy in different languages

### ISSUE THREAD

**Issue by alex-hofstadter** [danpros/htmly#134]
@danpros and @Kanti don't speak English fluently themselves. So, why limit ourselves to English?
These are some languages I believe HTMLy should be in to start:
- English (already there)
- Spanish (Español)
- Portuguese (Português)
- Italian (Italiano)
- German (Deuscht)
- French (Français)
- Catalan (Català)
- ...

I speak Spanish myself, so if anyone needs help with it I'm here. :D

**Comment by Kanti** [comment]
Hi @alex-hofstadter,

This is in deed a very good feature suggestion. We have thought about that. If someone could find the time and implement some multi language feature. I don't have the time.

@alex-hofstadter if you find misspelling in the source. Please feel free to edit these and create a pull request.

**Comment by alex-hofstadter** [comment]
@Kanti What do you mean by "pull request"? And, by the way, I was thinking about a folder called /languages, which would have .lng files (e.g. en.lng, es.lng, etc.), and having a settings.php file (which also would have options for the dateless URLs) with a variable like this:
HTMLy Language = en (English as default; any other language, written in English too, would load their respective .lng file). We would have to have HTMLy.com with different languages too, with subdomains; e.g. es.htmly.com.

**Comment by Kanti** [comment]
That sounds like a good idea.
Maybe this will help: [Pull Requeast](https://help.github.com/articles/using-pull-requests/)

**Comment by alex-hofstadter** [comment]
@kanti By the way, I was talking about the text on the HTMLy blog being in Spanish -- this does not include the posts themselved. This should be paired with the 'blog in different languages' suggestion.

**Comment by danpros** [comment]
@alex-hofstadter well after the #177 fixed we can creating the multi-language feature easily

**Comment by MichelePalmieri** [comment]
HTMLy of samples in different languages
https://github.com/MichelePalmieri/htmly

**Comment by iidbae** [comment]
Hai @danpros saya bisa bantu untuk Bahasa Indonesianya. Kalau bisa sih file formatnya Bahasa Indonesianya .txt

Hi Dan, I can help you for Bahasa Indonesia. Kindly send the file in txt.

Please send me a message if this project start.

Thanks.

**Comment by danpros** [comment]
@iidbae well need additional improvements before we can add language let say as txt file.

**Comment by RalfZim** [comment]
I uploaded pull request #317, which adds language support and has English and German for now.
Adding more languages is easy.

**Comment by danpros** [comment]
Hello, this has been added. I will close this one.

Thanks,
