### ISSUE TITLE
Can't Appear Blog menu If pointing to Tag?

### ISSUE THREAD

**Issue by pram22** [danpros/htmly#136]
Hello, I just want asking, i am try anything to apper blog menu that pointing to tag,i try to see the problem is if blogmenu pointing to internal link like a tag (not page) is not apper, and if pointing to external link it can apper. I hope the problem can be fix. Thanks :) i am try to apper tag on blog menu on https://www.pram-software.com and my config.ini (blogmenu) http://pastebin.com/raw.php?i=hx8gyFmD

Thank You.

**Comment by Kanti** [comment]
hi,
Have you changed anything on your HTMLy installation?
On my test system it is not a problem http://test.kanti.de/ .
Have you any php Warnings or Errors in the log while you tried it.

**Comment by pram22** [comment]
Hi.

I don't change anything, and i have same problem on localhost. in test.kanti.de the tag is external link to my blog. and if you pointing in your tag (internal link) like test.kanti.de/tag/tutorial can't apper,

Thanks :)

**Comment by Kanti** [comment]
oh, my stupidity.
I have made a BUGFIX. Download the newest master [here](https://github.com/danpros/htmly/archive/master.zip).
You just need to replace the ``system/`` dir.

**Comment by pram22** [comment]
Thank You it Work. :+1:
