### ISSUE TITLE
My Two Cents

### ISSUE THREAD

**Issue by alex-hofstadter** [danpros/htmly#138]
I have a suggestion.
Why not using Splitbrain's (My Two Cents)[http://www.splitbrain.org/projects/my_two_cents] commenting script for HTMLy?
If you, developers, haven't coded a comment system yet, here's my little suggestion. :)

**Comment by Kanti** [comment]
Hi Alex,

Thank you for the suggestion. But this script works with mysql. And HTMLy is a flat file based platform. That will not work.

**Comment by alex-hofstadter** [comment]
@Kanti I'm sorry. I thought you could modify its database behavior somehow. Sorry again. D:
