### ISSUE TITLE
Set up user role

### ISSUE THREAD

**Issue by lululelucid** [danpros/htmly#139]
Hi,
first, it is a really nice blog engine that you provide, and I thank you for that.
Now my concern is the fact that User roles does not work, I create a user I have set admin role and user role it does not change anything between the both and even more if I don't specify any role it still the same as admin role or user role,
what I would like to do is set a role where the user would be just an editor for example ( the user will not have access to Add page/Import/Backup/Config/Clear cache in the admin interface, he would just be able to click on Admin/Posts/Mine/Add post/Edit profile/Logout).

Do you think it would be possible to do that and how if you think so?

Cheers.

Lululelucid

**Comment by Kanti** [comment]
Hi @lululelucid,

Thank you. I will look over it. This is probably a Bug.

currently there is nothing you can do. sorry.

**Comment by Kanti** [comment]
Hi @lululelucid,

I need to correct me. The current status is:
- Admin can edit/create everything.
- User can edit/create everything **except post's from other users**.

Therefore the tab ``Posts`` should not be visible for Users.

**Comment by lululelucid** [comment]
Hi Kanti,

Thank you for your reply, Yes I have noticed that yesterday, I just didn't see it ^^"
and in fact I have been able to create another User type (as Support) without difficulties,
just needed to understand the code.

Thanks for your help anyway, I might come back to you later maybe!

All the best,

lululelucid.
