### ISSUE TITLE
Warning: readfile() has been disabled for security reasons

### ISSUE THREAD

**Issue by Raff80** [danpros/htmly#143]
After installing 2.5 I have this warning:

Warning: readfile() has been disabled for security reasons in /home/nowa9752/public_html/system/includes/functions.php on line 1691

What should I do with this?
Thank you

**Comment by Kanti** [comment]
which version did you have before?
this problem must bin there for you since 2.0

**Comment by Raff80** [comment]
I dont remember. I Think I used 2.0 before. I tried to upgrade into 2.5 by clicking upgrade button in the admin panel then showed up "[site.url] is not set" then I read this: https://github.com/danpros/htmly/issues/142 so I downgraded it into 2.4.1 then I didint see "[site.url] is not set" anymore. But I could only see this on my homepage: "Warning: readfile() has been disabled for security reasons in /home/nowa9752/public_html/system/includes/functions.php on line 1691". But I have already fixed it by changing:

        readfile($cachefile);
become:        
        
        echo file_get_contents($cachefile);

**Comment by arianfar62** [comment]
hello every one
I had this error in error log file in  root folder of site:

PHP Warning:  readfile() has been disabled for security reasons in /home/mysite/public_html/mysite.com/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-cache.php on line 180

i changed

readfile( $cache_filepath );
to
echo file_get_contents ( $cache_filepath );

in class-cache.php on line 180

By this change, My problem was solved!
But the question:
Do this change , Creates any problem In wp-rocket plugin performance?

What do these changes mean?
echo file_get_contents ( $cache_filepath );

thank you [mrhomestay](https://github.com/mrhomestay) and everybody
