### ISSUE TITLE
SQlite3?

### ISSUE THREAD

**Issue by Xarcell** [danpros/htmly#145]
Has there ever been consideration for SQLite3? It would still be a flat-file system, just not database-less.

**Comment by ncang** [comment]
i don't know, just see the tagline "Databaseless Blogging Platform"

**Comment by Xarcell** [comment]
Some advantages would be that it's quicker, and if your site ever outgrows it you can always port it to MYSQL. Currently like it is or with SQlite, you'll start seeing performance issues after daily 100K views 1K online at once. That's not something most bloggers have to worry about, but then 100K/1K isn't really alot either. 

It's just an adjustment solution I think. Gives HTMLy the ability to grow with you.

**Comment by Xarcell** [comment]
It's true adopting SQLite would mean it's no longer database-less, but it still means it's just a file and there no database to setup. Most major entities are adopting SQLite: Mozilla Firefox/Thunderbird, Google Business Apps, Adobe Reader/Lightroom, Dropbox, Skype,  Apple iProducts, Microsoft Games, etc...

The only big issue is the db file gets locked when being written to. So comments could be an issue, but if your using FB/Disqis comments then there's no problem.

**Comment by ncang** [comment]
my record on HTMLy is more than 500 online at once (real / no bot) . You know what happened? server down, when upgrading everything goes back to normal.

**Comment by fahmi182** [comment]
HTMLy have cache static, 500 online on vps 512BM Ram, only 30% Cpu used. :)

**Comment by Xarcell** [comment]
I'm still a fan of SQLite. However, there are plenty of other blogs that support sqlite3, but not that many that support file upload. After more careful consideration, I think HTMLy should stay as it is. So I'm gonna close this issue.
