### ISSUE TITLE
featured post

### ISSUE THREAD

**Issue by irgaabd** [danpros/htmly#147]
cool project guys..
keren

anyway, is it possible to add "featured post"  options??
it'll be pratical addition for people who wants slider in their blog

I tried implement slider with posts that has "feature image", but I dont think its an ideal solution

![edar](https://cloud.githubusercontent.com/assets/1941464/6741504/7ec78632-ceba-11e4-9b98-a011a09137ac.png)

**Comment by danpros** [comment]
Well you can do like this actually, just creating tag->featured and call that using get_tag functions, later on the template using foreach etc.

````
// get the posts with featured tag, as 1 page, 4 posts, random false
<?php $featured = get_tag('featured', 1, 4, false);?>

<?php foreach($featured as $f):?>

// the div etc. goes here.
<div class="slide-example">
    <div class="image"><img src="<?php echo $f->image; ?>"></div>
    <div class="title"><?php echo $f->title; ?></div>
    //etc....
</div>

<?php endforeach;?>
````

With this than let say we already have a template just change the value accordingly.
