### ISSUE TITLE
Your rewriteRule is not ready to use.

### ISSUE THREAD

**Issue by sirpauley** [danpros/htmly#154]
Your rewriteRule is not ready to use.

thats the error I am getting. I haven't found a solution for it. Maybe I aint getting the setup right or missing something somewhere.

**Comment by danpros** [comment]
Can you explain more?

**Comment by user00815** [comment]
Same here, copied the "installer.php" file into a new directory (e.g. www.example.com/blog/installer.php), when I try to run the installer, I'll get the following warning: "Your rewriteRule is not ready to use."
see screenshot
![screenshot](https://cloud.githubusercontent.com/assets/13449641/8822808/4498cf74-3068-11e5-8bf0-a9b0ab7a98db.png)

**Comment by Kanti** [comment]
maybe this will Help?

https://www.garron.me/en/mac/how-to-enable-htaccess-apache-mac-os-x.html

**Comment by user00815** [comment]
Thanks, for the fast reply. This is exact the setup I use, and I still get that warning.

**Comment by geraldhansen** [comment]
Hi, I've got the same problem with apache on ubuntu mod_rewrite is setted but I got this warning on installer.php too and even if I run the installer I got 404 on the pages afterwards - /admin /add/post and so on.
I tried already to setup the given lighttpd rewrite rules for apache, but I failed - is there no apache example?

**Comment by danpros** [comment]
I use CentOS:

````
NameVirtualHost *:80
NameVirtualHost *:443

<VirtualHost *:80>
    ServerAdmin dan@example.com
    DocumentRoot /var/www/html/example
    ServerName www.example.com
	ServerAlias example.com www.example.com
	ErrorLog /var/log/httpd/example_error
	<Directory "/var/www/html/example">
		Options FollowSymLinks Indexes
		AllowOverride All
		Order Allow,Deny
		Allow from all
		DirectoryIndex index.php
	</Directory>
</VirtualHost>

<virtualhost *:443>
    ServerName www.example.com
	ServerAlias example.com www.example.com
    ServerAdmin dan@example.com
	ErrorLog /var/log/httpd/example_error
    DocumentRoot /var/www/html/example
	<Directory "/var/www/html/example">
		Options FollowSymLinks Indexes
		AllowOverride All
		Order Allow,Deny
		Allow from all
		DirectoryIndex index.php
	</Directory>
	SSLEngine on
	SSLCertificateFile "/etc/httpd/ssl/example.crt"
	SSLCertificateKeyFile "/etc/httpd/ssl//example.key"
	SSLCertificateChainFile "/etc/httpd/ssl/example.ca-bundle"
</VirtualHost>
````

**Comment by geraldhansen** [comment]
thanks for the reply - I tried this, but I still got the "Warning: Your rewriteRule is not ready to use. Help!"

**Comment by ebookcode** [comment]
It's sometime not the real message. I met it and ignored it. The blog still worked

**Comment by geraldhansen** [comment]
the blog is working, but the admin interface for example is not reachable.

**Comment by ebookcode** [comment]
I met this message and still use the admin interface

**Comment by danpros** [comment]
@geraldhansen seems this is web server issue (configurations) try https://www.digitalocean.com/community/tutorials/how-to-configure-the-apache-web-server-on-an-ubuntu-or-debian-vps

**Comment by geraldhansen** [comment]
yes, it was the webserver - in the default apache ssl config was an entry "AllowOverride None" which was not overridable by a .htaccess file.
Thanks for your help and sorry for bothering.

**Comment by danpros** [comment]
@geraldhansen no problems :smile: I will close this one.
