### ISSUE TITLE
How do I log in?

### ISSUE THREAD

**Issue by Unwyn** [danpros/htmly#160]
I installed using the installer.php.  Yay!  IT worked.  But I did not make a post at that point.

Now... I closed my browser and seem to have no idea how to log back in to my website. I realize I did something wrong, what have I done wrong and how do I tease out any sort of login prompt?

**Comment by danpros** [comment]
The login URL is `example.com/login`

**Comment by navinsab** [comment]
Hi

I have no access to configure the server and thus cannot map the /login to a particular directory. Unable to login to the system by pointing to http://www.mysiteurl.com/system/admin/views/login
