### ISSUE TITLE
RSS import - tweak

### ISSUE THREAD

**Issue by Silverunit** [danpros/htmly#161]
Hi,

I'm new at this github thing. Found your blogging solution. Liked it alot. 
Now I try to import post from my wordpress.com account. Works fine but I'd like a tweak,
Is it possible to change the way the importer handles categories? I would like to add the tags from the wordpress platform to be the tags in this platform. Today you take the category and add that as a tag.

I tried to look through the code but had a hard time to find what I was looking for.

Best regards, Michael - Sweden

**Comment by danpros** [comment]
Well the code is at here https://github.com/danpros/htmly/blob/master/system/admin/admin.php#L419
