### ISSUE TITLE
Add Sitemap for user on HTMLy

### ISSUE THREAD

**Issue by m45rud** [danpros/htmly#163]
i think it's better if HTMLy have a sitemap for user. Because it can be make user more easily to explore the site. The sitemap is auto generate from content. 

@danpros @Kanti

**Comment by pram22** [comment]
Agree for this feautes i waiting for this features :+1:

**Comment by Anakinmi** [comment]
Any update on this? I like the system very much, but manually generating a new sitemap after every post is a bit tedious. I guess after every post isn't REALLY necessary, but at least after a new month was started, or when a new tag or category is created?
