### ISSUE TITLE
Feature Request: Nested Static Pages, more than 2 levels

### ISSUE THREAD

**Issue by gesundelehre** [danpros/htmly#164]
Would it be possible to add support for more than 2 levels static pages?

**Comment by Xarcell** [comment]
Can you be more specific? Do you mean as in sub-categories or nested menu items?

**Comment by wowthemesnet** [comment]
Hi @Xarcell,

I think they mean something like this:

`https://site.com/horoscope/daily-horoscope/aries
`
Currently it's possible only:

`https://site.com/horoscope/daily-horoscope`

**Comment by danpros** [comment]
This issue is too old, I will close this one. Please create new issue for possible improvements. Thanks
