### ISSUE TITLE
feature request : meta-referrer-tag

### ISSUE THREAD

**Issue by ncang** [danpros/htmly#165]
hello, can add some little meta tag "referrer" ? , some config.ini like webmaster tools verification or analytic code

    ; meta.referrer default=origin (none, none-when-downgrade, origin or origin-when-cross-origin)
    meta-referrer=origin

see resource at moz.com/blog/meta-referrer-tag
thx

**Comment by danpros** [comment]
And you can set the ````content=""```` using the config.ini?

OK let me add it.

**Comment by danpros** [comment]
But you can do manually actually:

Create new config.ini variable, example

````
referrer = none
````

Than you can add this on layout.html.php let say on head:

````
<meta name="referrer" content="<?php echo config('referrer') ?>">
````

Later you just need to change it like"

````
referrer = none-when-downgrade
````

**Comment by ncang** [comment]
thx, plz close this :)
