### ISSUE TITLE
Feature requests - easy templating

### ISSUE THREAD

**Issue by Silverunit** [danpros/htmly#166]
Hi,

We got our own template bought from themeforest. I have manage to implement HTMLy in that and are only using the "blogfeed". Not the pages, there are to much variations.
As the new update came I lost some minor fixes that I have done by my self. But that was something I was fully aware of.

So here are some thoughts, from my point of view, that could make the use of own templates easier.
1 Remove the div from function get_related($tag)
Let the one who make/use own templates set class and head according to their template

2 As for the tag cloud I would like to see a easier way to customize that but realize that all templates are different so it would be hard to fit them all. I have removed the h3 tag and are using my themes div here.

3 The same goes for the archive list. Do not have any smart or good thing to contribute with but I will figure something out sooner or later I guess.

Now I will start to import all earlier post from our old page. You could see the project here: www.silverunitsystems.net/nyheter/ when it is finished it will be moved to the .se adress

Best regards, and thanks for making this posting solution as we do not like other posting solutions like wp. They are becoming to much and the security and speed are not easy to maintain.

**Comment by danpros** [comment]
Hello,

Thanks for your feedback :smile: 

OK got it. I will remove those div from the functions and add it directly to the theme. I will moving out the title, description and canonical from the head_contents also. Wait my next commits for all of the changes.

**Comment by danpros** [comment]
Done https://github.com/danpros/htmly/commit/7de2b1b74494e98e88649c2a28adfbe3e5621196

Moving the title, description and canonical from the head_contents:
````
<title><?php echo $title;?></title>
<meta name="description" content="<?php echo $description; ?>"/>
<link rel="canonical" href="<?php echo $canonical; ?>" />
````
and from `$head_contents` becomes `head_contents()`

**Comment by Silverunit** [comment]
Nice!
You are fast. Thanks.
Will update my files.
