### ISSUE TITLE
Issue with sv language åäö

### ISSUE THREAD

**Issue by Silverunit** [danpros/htmly#167]
Hi,

Have just imported 92 posts from an old wp installation. But it seams that the UTF-8 standard are not working on the tags? Any thoughts about that?

Also the åäö in the Swedish language are not working in the description. But I am not sure if it hade to do with my settings in the temp url at wp.com or not. Just noticed it now. 

But the tag are not working with åäö regardless manual input.

Thanks for feedback,
Michael - sweden

**Comment by danpros** [comment]
Yes since it stripped, the source https://github.com/danpros/htmly/blob/master/system/admin/admin.php#L77

**Comment by Silverunit** [comment]
Ah, ofcourse, I will take a look at it. I would like to have the åäö seen in the page (tags) and still with the clean urls.
