### ISSUE TITLE
Feature Request / Bug Fix - Relative Hyperlinks/paths

### ISSUE THREAD

**Issue by gesundelehre** [danpros/htmly#169]
Is there somehow a way, to get it working, that both for static pages and blog-pages there can be used the same relative-hyperlink-structure?

eg. **static pages** display as _http://example.com/static_
**blogpostst** as _http://example.com/2015/07/blogpost_

now i have e.g. a picture located in http://example.com/files/pictures/image.png

to access it from the **static page** i need the _href_ to be "files/pictures/image.png"
and to access the same picture from the **blogpost** i need the _href_ to be "../../files/pictures/image.png"

Now i cannot just copy-paste the markdown-content from the static page to the blogpost, or vice-versa, because the relative links wont' work anymore, but I manually have to change them. 

**Request Nr. 1: Is there a way, to somehow make it possible, that the same relative links work on a static page and on a blogpost?**

**Request Nr. 2: If I add a picture to a blogpost with a relative src=""-path then the picture won't load on the preview-page where all the blogposts are displayed - instead an empty square will be displayed...**

**Comment by danpros** [comment]
How about using slash infront of it:

````
/files/pictures/image.png
````
If you installing it in folder than you need to add the folder also.

Please compare this (view source), I am uploading the image using the markdown editor:

Static
````
https://goo.gl/O9sLvu
````
Blog post
````
https://goo.gl/S2V5rP
````
Its work.

**Comment by gesundelehre** [comment]
But then the link is not relative anymore...

It would be great to have relative links, that they work at the same time (without need to change) on different locations (e.g. EasyPHP/XAMPP and online)

**Comment by danpros** [comment]
Well if using relative URL than let say on feed reader it will broken so HTMLy using absolute URL, even on image upload automatically add the full url `http://www.example.com/content/images/image.png`.

**Comment by danpros** [comment]
This is not bug but a limitation.

**Comment by zh-wowtv** [comment]
Let's say I have an image in http://www.example.com/content/images/image.png, how am I supposed to refer to it in my post?

**Comment by danpros** [comment]
@zh-wowtv well there is a upload image form on the editor so you can add those image using the editor toolbar,

**Comment by zh-wowtv** [comment]
@danpros I saw that already. Thanks.
