### ISSUE TITLE
Feature Request: Contact Form

### ISSUE THREAD

**Issue by gesundelehre** [danpros/htmly#170]
Would it be possible to add a simple implementation of a Contact Form?

**Comment by danpros** [comment]
Well how about using Google contact form? its an iframe so just embed it on the static page.

**Comment by gesundelehre** [comment]
For now, that's a good idea and I got it to work - maybe later you could implement this function into htmly - because not everybody wants to use google though...
Thanks for the idea

**Comment by Xarcell** [comment]
Styling becomes an issue with iframes. Will it work: yes, but does it looks professional for clients: no.

**Comment by danpros** [comment]
Please read this http://www.danpros.com/2015/12/creating-contact-form-on-htmly
