### ISSUE TITLE
PHP 5.2

### ISSUE THREAD

**Issue by robsdixon** [danpros/htmly#172]
My host only supports 5.2 and they are charging me £49 to upgrade to 5.3 (money I don't have to spare).

Is it possible for someone to make a PHP 5.2 version of HTMLy as it would really help me out.

If you want I can even get you more GitHub followers for helping me!

**Comment by danpros** [comment]
Well considering to change your web host than, there are many free hosting provider out there that support php 5.3

**Comment by robsdixon** [comment]
Please could you give me a few examples.

-Thanks

**Comment by danpros** [comment]
Please follow this link https://www.google.com/search?q=free+web+hosting result example https://byethost.com/index.php/free-hosting or http://www.hostinger.co.uk/free-hosting

**Comment by robsdixon** [comment]
I tried Hostinger before and my website kept going down, in the end I just gave up with them but I'm going to try Byethost

-Thanks

**Comment by fahmi182** [comment]
Try this https://gignode.com/
