### ISSUE TITLE
Feature Request: RSS-Content with Preview/full Post as content

### ISSUE THREAD

**Issue by gesundelehre** [danpros/htmly#173]
Would it be possible make a value within the config.ini to enable/disable a preview in the RSS-Feed resp. to choose from
1) without preview
2) with preview (and then add a second value of how many chars the preview would contain)
3) full post is being delivered by RSS

**Comment by danpros** [comment]
Well there are an options for that, open config page and find `rss.count` and `rss.char`

**Comment by gesundelehre** [comment]
Sry, didn't see that option. Ok, fine, thanks.
