### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by clausdus** [danpros/htmly#174]
Hi,

after updating to HTMLy 2.5.4 I'm only able to log in once.
I have to set the user pw in the ini file and after the successful login the password in the user file is empty and no futher login is possible.
This is caused somewhere in the update_user/ password_hash function.

Regards

**Comment by danpros** [comment]
How about using encryption = clear?

**Comment by clausdus** [comment]
that works, for one time only.
1: set pw to clear enc
2: login is successful
3: next login does not work - the value for password in the ini file blank now

**Comment by danpros** [comment]
I try it in my localhost and no problems found as long as the web sever can write in it. How about the folder permission for config and config/user folder? seems the web server can't write inside it. Try set the folder permisson to 775 first.

**Comment by clausdus** [comment]
I will check this. But the server can write cause it's deletes the pw from the file:
before:
password = test
encryption = clear
role = admin
after the login:
password =
encryption = password_hash
role = admin

**Comment by danpros** [comment]
Can you download it than copy and replace to overwrite the old files?

**Comment by clausdus** [comment]
Download what?
I get closer:
The compatibility lib is used:
vendor/ircmaxell/password-compat/lib/password.php
And there this if clause is valid:
            if (!is_string($ret) || PasswordCompat\binary\_strlen($ret) != $resultLength) {
                return null;
            }
And this writes the NULL into my file

**Comment by danpros** [comment]
I mean the latest version, just in case there if there are corrupted files.

Do you use php 5.3? please do the test https://github.com/ircmaxell/password_compat#requirements

**Comment by clausdus** [comment]
Ok, that's the reason: Note that Debian's 5.3.3 version is NOT supported.
:(
What a pity, htmly worked so fine before the update..

**Comment by danpros** [comment]
Well you can creating your own password hash than put it on username.ini and make the file as non writable so even the web server can write it :smile:

**Comment by clausdus** [comment]
Yes, or take this as the reason to finally update/upgrade the web server :-)

My temporary solution is this in admin.php:
    } else if (old_password_verify($pass, $user_enc, $user_pass)) {
//        update_user($user, $pass, $user_role);

Thanks, and beside that I like htmly a lot!

**Comment by danpros** [comment]
Please try to use the master branch, there are many new features, I need someone to test it actually :smile: 

Soon I will adding new theme so the featured video, audio, link, quote, image can match with the theme. Well I already test the theme at here https://goo.gl/t5mVd6 and I will add this theme also http://ironsummitmedia.github.io/startbootstrap-clean-blog/index.html

**Comment by gesundelehre** [comment]
https://goo.gl/t5mVd6 -> this is a new theme on your blog isn't it? It looked much different some days ago...
How long do you think it will take you to merge it into HTMLy? (I still wait on the submenu-items of static pages displayed with css - that's why I ask)

Greetings and thanks a lot in advance

**Comment by danpros** [comment]
@gesundelehre well a few days ago I am using this html template and port it to htmly http://firenze.different-themes.com/html/index.html so current master branch can creating a site like this easily. That is why I am adding new content type etc. and modify main function so we can creating custom style.

Those html template is not free so I can't distribute it. 

I will try as son as possible to add the theme on repo

**Comment by gesundelehre** [comment]
@danpros which html template of those two is not free?

**Comment by danpros** [comment]
@gesundelehre https://goo.gl/t5mVd6 current theme is free and I will make it as the default theme, it has dropdown menu. The original html template license is Creative Commons Attribution 3.0 License (CC BY 3.0) but I already contact her and she allow me to use those wire frame without attribution on the footer http://themes.3rdwavemedia.com/demo/developer/ well I will add credit on github, and the homepage.

**Comment by clausdus** [comment]
> Please try to use the master branch, there are many new features, I need someone to test it actually :smile:
I will do so - htmly is a great piece of software. What I like most is the simple and clean look. And it's not overfeatured. The Image upload (which for some reason does not work right now - maybe also because of my old php) is important since i do not need an additional gallery.

**Comment by clausdus** [comment]
In the latest version it seems that the 'view' and 'edit' button of a post are lying upon each other with a dot in front of:
o View
o Edit
But let me check that again..

**Comment by danpros** [comment]
@clausdus for image upload after browse the file you need to click insert. I will change this behavior, so after click upload its automatically added on the editor.

View, edit? yes I know that :smile: that is because I add the bootstrap style to the tab for the new theme but not yet change the old theme.

**Comment by danpros** [comment]
@clausdus 
@gesundelehre 

I already add new theme named `blog` please test it. If its fine I will releasing new release version.
