### ISSUE TITLE
Feature Request: Add Custom content in additional column next to the main content

### ISSUE THREAD

**Issue by gesundelehre** [danpros/htmly#175]
Would it be possible to add a feature to allow users to add their custom content in the column next to the content? (the same column where the tags, archive, about and latest blog post are being displayed)

such as
- pictures
- display the output of a custom php-file
- static text
- Links?

- - - 
In addition to that it would also be good to customize the order in which the content in that column appears

**Comment by danpros** [comment]
Yes that's possible :smile:

**Comment by byens** [comment]
Yes but as plugin is that possible? Each update my aside-ads always gone. Jadi disimpan kaya data .md kali ya mas hihi

**Comment by danpros** [comment]
$byen, don't modify the core, you can create new theme and put your ads there.

**Comment by byens** [comment]
@danpros thanks, i will just make child themes /blog-anak just like in wordpress. Tidak terpikirkan makasih mas

**Comment by Xarcell** [comment]
@danpros I think this issue can be closed now.
