### ISSUE TITLE
Feature Request: Import Backup-zip created by HTMLy

### ISSUE THREAD

**Issue by gesundelehre** [danpros/htmly#176]
Would it be possible to add a feature that allows one to import  a backup-zip created by HTMLy by clicking on the page **site_url()/admin/backup** on the link **site_url()admin/backup-start**?

**Comment by danpros** [comment]
Yes if we can import the zip file than it would be very handy. The backup missing the config folder also.

**Comment by gesundelehre** [comment]
Is there any one else, that would think this feature would come in handy? Or is there not really need for it?

**Comment by nightflasher** [comment]
Having a backup but no option to restore from backup, makes backups obsolete!?

FYI: I can't download my backups

**Comment by danpros** [comment]
This issue is too old, I will close this one. Please create new issue for possible improvements. Thanks
