### ISSUE TITLE
Feature request: Is there possible add version number to update page?

### ISSUE THREAD

**Issue by markosu** [danpros/htmly#178]
For example add version number to update page like this "You are using the latest HTMLy version (<version number>). Thanks.

**Comment by danpros** [comment]
Yes that's possible :smile:

**Comment by markosu** [comment]
How I know when update page has done something? How to check which version I have? 

There is new version waiting. https://github.com/danpros/htmly/releases/tag/v2.5.6

**Comment by danpros** [comment]
@markosu after this version you will find your installed version under update page, so just follow the link there to update your htmly.
