### ISSUE TITLE
I cant testing htmly

### ISSUE THREAD

**Issue by idefixxx** [danpros/htmly#179]
Hi,
i cant login. 
I get allways "Username not found in our record",
What am I doing wrong?
(sorry for my bad english)

Regards

**Comment by gesundelehre** [comment]
To set up HTMLY you need to do these 3 things:
1) duplicate **config/config.ini.example** and rename duplicate to **config.ini** -> within that file change the parameter site_url to the location where HTMLy is located e.g. **http://www.domain.com/**
2) duplicate **config/users/username.ini.example** and rename the duplicate to **myusername.ini** -> change the password within that file and save the file
3) login with the username **myusername** in navigating to the URL **http://www.domain.com/admin** or **http://www.domain.com/login** and enter **myusername** as username and the password you entered in the myusername.ini-file

You may give me a feedback if it worked.

**Comment by idefixxx** [comment]
THX it works!
i not rename the file in username, thats my mistake
