### ISSUE TITLE
RSS feed - more tag redundent?

### ISSUE THREAD

**Issue by Silverunit** [danpros/htmly#180]
Hi,

I have noticed a little thing today men I was going through some share feeds on social medias.
We have connected our RSS feed to Google plus business page, FB page, Linkedin profile, twitter accounts. When shareing a post, the tag "more" in the end seems to be unnecessary. Because the link to the post is always showing, in a short url way or in its full, depending on the social platform.

I have not looked at it in a RSS reader but I think the post would look cleaner with only ... in the end.

I will go in to the code and change it, but I now that will disappear when I update so therefore I let you know how I see it :)

Take care! 

(Some feeds in action with working og:tags )
https://plus.google.com/u/0/b/117983402225851979999/+SilverunitsystemsSe/posts
https://twitter.com/silverunit

**Comment by danpros** [comment]
Removed by my last commits and there are improvements. There is /blog URL that list recent posts like on the frontpage. Useful if you want frontpage as the landing page. See htmly homepage for an example.
