### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by silver0wn** [danpros/htmly#181]
Hi there, fairly new to website work, came across this and eventually with some fiddling got the main page to work.

However whenever I try to redirect my server to mywebsite/blog/login it always fails.
I noticed when I tried mywebsite/blog/upload.php then it redirects to login and fails. I am using an Apache server, but I don't think I have access to the server settings as its a server provider.

Is there some way I can get the Login page to load? I've tried setting all of my file permissions to 775 but to no avail.

**Comment by danpros** [comment]
Open your .htaccess file and remove all except this:

````
# Various rewrite rules.
<IfModule mod_rewrite.c>

  RewriteEngine on

# Uncomment the following to redirect all visitors to the www version
# RewriteCond %{HTTP_HOST} !^www\. [NC]
# RewriteRule ^ http://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

# Uncomment the following to redirect all visitors to non www version
# RewriteCond %{HTTP_HOST} ^www\.(.+)$ [NC]
# RewriteRule ^ http://%1%{REQUEST_URI} [L,R=301]

# If your site is running in a VirtualDocumentRoot at http://example.com/,
# uncomment the following line:
# RewriteBase /

# Pass all requests not referring directly to files in the filesystem to index.php.
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d 
  RewriteRule ^ index.php [L]

</IfModule>
````

**Comment by silver0wn** [comment]
Hi there Dan, 

I tried editing the .htaccess file to the above code and still not able to find the admin page. Thanks for the quick response though, I was impressed.

**Comment by silver0wn** [comment]
I've just tried the new installer and I've got this error at the top:

Warning: file_put_contents(): SAFE MODE Restriction in effect. The script whose uid is 8844 is not allowed to access /home/pasta/astrosoc/Aaron/cache owned by uid 25242 in /home/pasta/astrosoc/Aaron/installer(1).php on line 4276 Warning: file_put_contents(cache/ca_bundle.crt): failed to open stream: No such file or directory in /home/pasta/astrosoc/Aaron/installer(1).php on line 4276

**Comment by danpros** [comment]
Well tell your hosting provider about it since this is a server configuration problems.

**Comment by danpros** [comment]
You can try HTMLy on [OpenShift](https://www.openshift.com), follow the quickstart here https://github.com/danpros/htmly-openshift
