### ISSUE TITLE
[Fixed] Offline posting

### ISSUE THREAD

**Issue by tes5884** [danpros/htmly#182]
Hi,
I'm new to htmly, so please bear with me.

I uploaded a file to `../htmly/content/*my_user_name*/blog` for some reason it isn't showing up on the actual site.
- file name is formatted correctly `yyyy-mm-dd-hh-mm-ss_tags_title.md`
- same permissions as the other files in said directory `rw-r--r--`

Am i missing anything else?

Thanks!

**Comment by danpros** [comment]
Hello,

Try to clear your cache :smile: HTMLy create an index for any posts, page etc. so no need to lookup the directory every time to save the resources.

So htmly examine this index file let say when we need specific posts and than open those files.

**Comment by tes5884** [comment]
thought of that, but it still doesn't show up.

This is the actualy file -> http://pastebin.com/1Ad0rhtx

This is how I named the file: `2015-08-5-21-24-00_powershell,windows-7,server-2003,server-2012_Re-mapping-printer-shares-using-a-new-server.md`

Thanks for your time!

**Comment by danpros** [comment]
Seems the date format:

````
2015-08-5-21-24-00
````
it should:
````
2015-08-05-21-24-00
````

**Comment by tes5884** [comment]
Changed the name, still not working.

You mentioned refresh the cache, I was refreshing the cache on my browser.

Do I need to refresh something on the server?

Thanks

**Comment by danpros** [comment]
First fix the date format and refresh the cache inside your admin panel, there is a clear cache link there :)

**Comment by tes5884** [comment]
clearing the cache fixed it.
thanks @danpros

**Comment by danpros** [comment]
Great!

That because you upload it manually if using the admin panel to write your content than no need to do such things. If you let say create the content programmatically elsewhere than sync the content folder, you need to delete cache inside cache/index folder periodically.
