### ISSUE TITLE
CSRF Problem login Page (CF --> Nginx --> Apache)

### ISSUE THREAD

**Issue by snapo** [danpros/htmly#183]
Hello Htmly,
I know there is no support and i have a slight ugly constellation but maybe you guys could help me out to get it running. My Setup is as follow:

[Cloudflare]->[Nginx]->[Apache2]

Nginx is used as a reverse proxy for apache2 (no caching activated) and Cloudflare is used as worldwide CDN. Everything except for the login works.

Using Apache2 directly the login works.
Using Nginx directly to login does not work.
Using CF directly with apache without nginx, login works.

The only problem im figuring at the moment is that if i press the login Button it always pops up the CSRF error. So the Cross Site Scrpting Key is not transmitted somehow. 

Is the Key set to a cookie? or only as the post request for login?
Do you compare the ip to the csrf value?

If anyone could help me or tell me where else i should search, that would be great.

Best regards

**Comment by danpros** [comment]
@snapo ley me test it on nginx first

**Comment by danpros** [comment]
After testing it on nginx and yes nginx doesn't send the hidden form that contains the csrf token, weird but this must be with the nginx configurations itself. Still looking around for solutions here. If still can't than we should create an options to disable the csrf using the config.ini

**Comment by snapo** [comment]
if a turn off button in the config would be the most simple solution then this is ok for me. (does not solve the initial problem, but at least a workaraound) . I will also dive a little more in to ngingx and if this is possible to solve....

**Comment by danpros** [comment]
Seems related to this http://serverfault.com/questions/231578/nginx-php-fpm-where-are-my-get-params

htmly using get to catch the post for the token.

**Comment by danpros** [comment]
Wait seems this is programming problems.

**Comment by danpros** [comment]
When I use nginx at the first time seems the session problems. You don't have permission to write session. When I am execute this I can login (nginx).

````
chown -R nginx:nginx /var/lib/php/session
````

**Comment by snapo** [comment]
Hi danpros,
Thanks for the help, but im not using fastcgi for php (my nginx cant even recognize whats php) i use apache with standard virtual hosts. 
Nginx is only used as a reverse proxy , so my nginx config looks like this:

server {                                                                                                                                                     
        listen   80;                                                                                                                                         
                                                                                                                                                             
        root /var/www/html/;                                                                                                                                 
        index index.php index.html index.htm;                                                                                                                
                                                                                                                                                             
        server_name www.mydomain.com;                                                                                                                         
                                                                                                                                                             
        location ~ {                                                                                                                                         

        proxy_set_header X-Real-IP  $remote_addr;                                                                                                            
        proxy_set_header X-Forwarded-For $remote_addr;                                                                                                       
        proxy_set_header Host $host;                                                                                                                         
        proxy_pass http://url.to.my.webserver:8080;                                                                                                              
                                                                                                                                                             
         }                                                                                                                                                   
}   


in this way if a user requests something, nginx will transfer everything to the proxy_pass and acts as a reverse proxy. I also did turn off all caching probabilitys to exclude errors, also i did turn off caching in htmly for testing.

also there is no /var/lib/php/session on my system because (as mentioned before) i dont use fastcgi for php. PHP only runs as a apache module.

**Comment by danpros** [comment]
Well at least confirmed when you are using nginx directly is session write problems:

How about:

````
server {
  listen 80;
  server_name example.com www.example.com;
    location / {
      access_log off;
      proxy_pass http://url.to.my.webserver:8080;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_buffering    off;
      proxy_buffer_size  128k;
      proxy_buffers 100  128k;
    }
}
````

**Comment by snapo** [comment]
same error
.....

**Comment by danpros** [comment]
I can login by using the same setup as yours. This is session problems also, try
````
chown -R apache:apache /var/lib/php/session
````

**Comment by snapo** [comment]
well... i dont have a /var/lib/php folder
proxy pass to 127.0.0.1 is not possible otherwise apache does not recognize the vhost.
many pages are running on the same server with different ports , thats why i need nginx in front.

for me its more simple to turn of the csrf protection, because the admin portal is only accessed by another machine (so no problem with xss)

**Comment by danpros** [comment]
If you use php than there is a `session.save_path` so open your php.ini and find where is the path for it. Mine is in `/var/lib/php/session`

Related: http://stackoverflow.com/questions/6628275/how-to-get-my-session-to-write-to-apache

**Comment by snapo** [comment]
Hi Danpros,
For apache2 session.save_path was not activated, after activating it and grant full permission to www-date (default user ubuntu or debian i dont remember) it works.
Thank you very very much
Case can be closed and maybe it helps some one else by googleing it

**Comment by danpros** [comment]
Hi @snapo,

That's great you fixed it, you're welcome :smile: 

I will close this one.
