### ISSUE TITLE
Scandic letters (ö,ä,å) doesn't work in Meta Description (optional) field.

### ISSUE THREAD

**Issue by markosu** [danpros/htmly#184]
Text without scandic letters (ö,ä,å):
"Onko sinulla kysymyksi liittyen hyvinvointiteknologiaan tai esteett myyteen etk tied mist kysy ratkaisuja kysymyksiin"

Same text with scandic letters  (ö,ä,å)
"Onko sinulla kysymyksiä liittyen hyvinvointiteknologiaan tai esteettömyyteen etkä tiedä mistä kysyä ratkaisuja kysymyksiin?"

Why I can't even clear Meta... field?
First I clear field and then I click "Update post". Text is there again.

**Comment by danpros** [comment]
Yes that know issues, next release this should has been fixed. The meta field is automatically added.

**Comment by danpros** [comment]
Wait do you use the latest version?

**Comment by danpros** [comment]
Seems those description generated before htmly v.2.5.7 version. Please update and test it

**Comment by markosu** [comment]
I have latest version. Below is copy-paste from update page.
>Congrats! You have the latest version of HTMLy
Release Title: Maintenance release
Installed Version: v2.5.8

Still same thing happening.

**Comment by danpros** [comment]
@markosu I use this latest version and no problems with those char. How you upgrade it? using the master branch or the update link inside the panel? is this old post or new post. Try to creating new post. If old post than the description saved to the file and you need to replace it by set the description to new description.

**Comment by markosu** [comment]
@danpros I used update link inside the panel. Post is new, wrote using 2.5.8 version.
I created new post and published. Same happening.

I think the problem is that when editing old or new post and I don't touch meta field at all. HTMLy suggest the Meta without scandic letters. In blogfile it looks like this  (no meta.)

When I copy-paste same text with scandic letters to meta field in HTMLy editor then everything works and in blogfile there is meta field text between e.g.  with scandic letters.

**Comment by danpros** [comment]
@markosu ah got it, if the descriptions field is empty. Already test it and yes its stripped. I will try to fixing it.

**Comment by danpros** [comment]
@markosu how about now? try the master branch.

**Comment by markosu** [comment]
I just updated system directory because I use own copy of clean theme. Hope there isnt any changes in another directories.

Now scandic letters works but somehow HTMLy add <p>...</p> like in my test post "<p>test test äöäöäöäö</p>" and in file there is empty desc. field like .

Maybe this is another issue.
Hmm.. why the htmly force to add suggested meta to file?
If I clear meta field in editor and update post, then in file there is suggested desc.

**Comment by danpros** [comment]
So its fixed actually. Those triple dot because of the theme, open the post.html.php or main.html.php and you will figure it out.

Regarding the empty  is normal

You just need to save the suggested meta and ignore it, that's for SEO purposes :smile:

**Comment by danpros** [comment]
Seems this fixed on master branch.
