### ISSUE TITLE
no issue, just conjure up. HTMLy run on HHVM / openshift + HHVM

### ISSUE THREAD

**Issue by ncang** [danpros/htmly#185]
as noob i see , https://github.com/danpros/htmly-openshift/ 
how to combine with https://github.com/tengyifei/openshift-cartridge-nginx-hhvm ?
or run https://github.com/facebook/hhvm

**Comment by danpros** [comment]
Why don't just deploy it first https://hub.openshift.com/quickstarts/127-hhvm and than test it how its work on openshift.

**Comment by ncang** [comment]
of course,
    	hhvm-investra.rhcloud.com
Created 9 days ago in domain investra and the aws-us-east-1 region

Service Temporarily Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.2.15 (Red Hat) Server at hhvm-investra.rhcloud.com Port 80

config nginx ??

**Comment by danpros** [comment]
Wait just fixing a few bugs for description and title tags.

**Comment by ncang** [comment]
nice, how to implement hhvm on my sweet free gignode apartement :dancer: ,

**Comment by danpros** [comment]
Well you can search on Google, HHVM on OpenVZ :smile:

**Comment by ncang** [comment]
okay :D , ASAP

**Comment by ncang** [comment]
wow, but can't login

http://hhvm-investra.rhcloud.com/login

**Comment by danpros** [comment]
Well there must be some additional config needed.

BTW check the new version, permalink without `/year/month/title` but `/post/title` :smile:

**Comment by ncang** [comment]
wait so long, at least :D great job , tag release plz - non-pre

**Comment by danpros** [comment]
@ncang done. You can try it on openshift.

**Comment by ncang** [comment]
new release good, updated !
wait for openshift hhvm htmly.
