### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by love-decay** [danpros/htmly#187]
I have been trying to get categories here but could not. Any folders hierachy ?

How can I achieve this 

Home
   - Pages 1
   - Pages 2
   - Pages 3
      - subPages 1 
      - subPages  2
      - subPages 3

**Comment by danpros** [comment]
The only categorization is using tags if you want page like that than the only way is using static pages and add the sub pages .

**Comment by love-decay** [comment]
shoot -  i guess its back to grav. This would have been the perfect tool for SEO but it does not have categories... danpros [why]

webmasters use categories for groups items - tags are for searching for information.

You can have a category blue switches , red switches, yellow switches, and several tags like , homemade, cheap, affordable, plastic. So when a user comes into a site he may simply click the blue switches navigation to go straight into the blue switches folder/category.

a user may also decide to search using tags - like amazon or ebay, especially when you have thousands or hundred of posts. If they are well organised they be in categories and also have tags (these tags can be indexed/followed or vice-versa.

Using categories and tags information can be group for proper retrieval by both the user and searcn engine. Please consider this in your next update , this entire page,category,tag and post system need to be updated. With this htmly cannot be stopped.

PS: We also need docs grav , has extensive docs.

**Comment by danpros** [comment]
Tumblr only have tag, and blogspot only label and that's fine actually since htmly support multi tags also :smile:

````
Post 1 the tags > general, seo
Post 2 the tags > general, seo.tools
````
Call the general will include both. Call seo will only give you post 1 etc.

You can try to use the `www.example.com/search/blue` this will searching the slug and the tags contains blue.

Regarding the docs, yes we need to creating proper docs.

**Comment by danpros** [comment]
But let see how I can improve the category things.

**Comment by love-decay** [comment]
See here http://www.bruceclay.com/seo/silo.htm

This structure and concept is based in information architecture. All sucessful sites on the web are built on this concept and it is what i am trying to achieve - wordpress can do this and be speeeedy

**Comment by danpros** [comment]
If we want that kind of structure than we need to move current post with this order or at least similar:

Regular post
````
content/username/blog/category/post/filename.md
````
and for video post etc.
````
content/username/blog/category/video/filename.md etc.
````
Very neat actually but need more works on coding side. With those order we can let say list the latest post, latest video also etc.

Problems: taking care existing post. But we can move old post to uncategorized category.

**Comment by love-decay** [comment]
I love it.... i am looking forward to this change. htmly is a solid!

**Comment by danpros** [comment]
@love-decay removing mark the accepted feature request since people will waiting it like crazy :smile: 

But I already have working category in my localhost. Just need to fix the draft, content creation etc.

**Comment by danpros** [comment]
Please discus it in here #194
