### ISSUE TITLE
Adding multiple tags always adds a comma in between

### ISSUE THREAD

**Issue by bbyrdhouse** [danpros/htmly#188]
It seems that when you add more than one tag that the only way to get the tags to be separate is to place a comma in between (I'm talking about in the admin area where you create a post.) However, the comma's get added to the page.

Shouldn't the comma's not show up on the page?

**Comment by danpros** [comment]
Yes need to add a comma if you need to tag specific post with more than one tag, and its normal behavior the comma added to the page as separator, when you inspect the element you will find its separate the tag and not part of the tags, example:

````
<span>
    <a href="https://www.danlogs.com/tag/htmly">htmly</a>
</span>, 
<span>
    <a href="https://www.danlogs.com/tag/openshift">openshift</a>
</span>
````

**Comment by bbyrdhouse** [comment]
It's not always standard behavior and in many cases the comma just looks weird. 
Example: You can go to my blog page where I am using HTMLy and see what I am talking about: 
http://kuler.solutions/blog/2015/08/new-blogging-platform

or you can notice in the image below:

![new blogging platform - kuler blog](https://cloud.githubusercontent.com/assets/7376298/9440375/3aa116ee-4a34-11e5-81c8-5a63361d5151.png)

I suppose I could write a bit of javascript to look for and remove the commas but it would be great if there was a way to just not have them.

**Comment by bbyrdhouse** [comment]
It appears that on line 286 of the `functions.php` file that reads:

`     $post->tag = implode(', ', $url); `
You can remove the comma and add another page like this:

`     $post->tag = implode('  ', $url);`

And this will then remove the commas ... I don't see any problem that this will create

**Comment by bbyrdhouse** [comment]
There is another issue with adding tags though and that is that whenever you add a tag that has two words the space is removed. Example:

`Blue Pants` becomes `BluePants` ...

**Comment by danpros** [comment]
Hello @bbyrdhouse 

Yes you can remove that for quick solutions but in the next release this should has been fixes. 

Regarding the space, it should fixes also. This is because of this https://github.com/danpros/htmly/blob/master/system/admin/admin.php#L100 (example line).

**Comment by bbyrdhouse** [comment]
Wonderful! ... I look forward to it!

**Comment by danpros** [comment]
This has been fixed on the latest commit and as a bonus there is category feature but you need to move the content manually. for related post you need to call like this `get_related($p->related)`. Please see this #194
