### ISSUE TITLE
Feature Request: Ability Robots

### ISSUE THREAD

**Issue by fahmi182** [danpros/htmly#190]
Can we have abitily to handle bot, meta index and no index, example, we have new site, and we must create first until site is ready.. and add no index robot to prevent indexing search engine.

Option:

1. ability to index or no index
2. ability to no index tags
3. ability to no index author page
4. ability to no index archive page

Thanks. :)

**Comment by danpros** [comment]
Actually we can creating custom config and add that on the template :smile:
