### ISSUE TITLE
custom homepage

### ISSUE THREAD

**Issue by lexbmeyer** [danpros/htmly#197]
I setup the blog page as "true", but the homepage still shows the blog. What do I need to do to get a custom homepage that I can edit the content?

**Comment by danpros** [comment]
Custom homepage is planned in the future but currently you can only edit the homepage by hardcoded it in the layout.html.php.

First create folder for your theme, let say `mytheme`. We want to use blog theme so copy all of the contents of it. Open layout.html.php and replace `themes/blog` to `/themes/mytheme'. 

Now creating text that only show up on the homepage.

Find this:
````php
            <div class="primary col-md-8 col-sm-12 col-xs-12">
            <?php echo content();?>
            </div><!--//primary-->
````
and put it inside `isset` condition:
````php
<?php if (isset($is_front)) { ?>
            <div class="primary col-md-8 col-sm-12 col-xs-12">
            Your custom content here
            </div><!--//primary-->
<?php } else {
            <div class="primary col-md-8 col-sm-12 col-xs-12">
            <?php echo content();?>
            </div><!--//primary-->
<?php } ?>
````

**Comment by lexbmeyer** [comment]
I will give that a try. Thanks

**Comment by lexbmeyer** [comment]
Thanks, that worked. 
I added a get file command, so I can keep the home content separate from the template.

<?php
$homepage = file_get_contents('home.md');
echo $homepage;
?>

**Comment by danpros** [comment]
@lexbmeyer glad it worked :smile:
