### ISSUE TITLE
Cannot add link

### ISSUE THREAD

**Issue by ebookcode** [danpros/htmly#198]
I use "Add content" > "Link post, Creating blog post with featured link", and then fill all the field, then submit, then I'm brought back to the "/mine" link and I see all my old posts there but I cannot see the new "Link post" I've tried to create.

**Comment by ebookcode** [comment]
p/s: I check the /link folder and see all links I've created there. Example

File name: 2015-08-29-01-31-35_hoctudau_hoctudaucom-1.md
File content:





:(

**Comment by danpros** [comment]
@ebookcode wait I will tracking it. If its not available than its a bugs. This because new file structure.

**Comment by danpros** [comment]
Confirmed if its  a bugs. Well no much tester before I release new version :smile:

**Comment by danpros** [comment]
This has been fixed. Please update to the latest version.

**Comment by ebookcode** [comment]
Thanks @danpros , you are very actively :D , this is the first time I use github. I thought "oh, someone deleted my post" and try to find my post. Finally I found this :D, very happy

**Comment by danpros** [comment]
Well I use it for my personal site and project so I must fix it asap any bugs :smile:
