### ISSUE TITLE
"reCaptcha not correct"

### ISSUE THREAD

**Issue by walterbyrd** [danpros/htmly#199]
New installation. 

I added my login in config/users just as instructed in README.md. I created a walterbyrd.ini file and edited the password. I have this hosted on my local machine, and I am not using an encrypted password, at this point. 

I am positive that I am using the correct password. 

But I keep getting that error message, and I am unable to log in.

Also, I see no place to enter a captcha. 

----
I think I might have worked around this by going into config.ini, and commenting out these lines:

;google.reCaptcha = "false"
;google.reCaptcha.public = ""
;google.reCaptcha.private = ""

If that is the right thing to do, maybe it should be documented?

I can get to the panel, but my posts, and pages, are not appearing.

**Comment by danpros** [comment]
What error message?

**Comment by danpros** [comment]
Is this fixed already?

**Comment by ebookcode** [comment]
I met this bug already. I temp fix it by changing lines 56-58 in config.ini

;google.reCaptcha = "false"
;google.reCaptcha.public = ""
;google.reCaptcha.private = ""

I added ";" in the start of line to "comment out" them.

**Comment by ebookcode** [comment]
I met this bug yesterday and worked around it. It seems fixed by @danpros some hours ago?

**Comment by danpros** [comment]
And there is a bugs again on cache, ah redeploy it again with same tags a few minutes ago, to reinstall simply change the file:
````
cache/installedVersion.json
````
to lower version eg.
````
  "tag_name": "v2.6.2"
````

After doing this when visiting the update page there is update link again.
