### ISSUE TITLE
Posts, Pages, Tags, are not appearing. do not seem to be published.

### ISSUE THREAD

**Issue by walterbyrd** [danpros/htmly#200]
I have tried creating posts, pages, and tags. 

I have permissions set to 755.
I have an admin account. 

- I login. 
- I click Create Content. 
- Click Regular Post, or Static Page
- Add content, and tag
- Click Publish

I am taken to /htmly/admin/mine

I get the message: 

My posts
No posts found!

**Comment by danpros** [comment]
If its regular post than it will show up on the admin/mine if its static page it will only show up in the /admin only.

**Comment by walterbyrd** [comment]
I have no htmly/system/admin/mine directory. It was not created when I installed. 

The posts are not showing up anywhere. 

The file I downloaded is: htmly-2.6.2.zip. 

I unziped the file, as root, in my /var/www directory. 

I changed the directory name from htmly-2.6.2 to just htmly

I changed all directories, and files, to 755 permissions

# chmod -R 777 htmly

No content directory was created. No admin/mine directory was created. 

Trying to create posts does nothing. Whatever I try to enter is just lost.

**Comment by danpros** [comment]
I already deploy a fix for the featured link bugs and for your case we need to tracking it again. (htmly-2.6.3).

You are using apache? if yes try 

````
chown -R apache:apache /var/www/
````
The web sever need to have write access to write in htmly installation.

**Comment by walterbyrd** [comment]
Changing owner worked. 

I did it slightly different. 

  # chown -R www-data:www-data /var/www/htmly

Then I restarted apache2

**Comment by danpros** [comment]
Great! 

Fix the recapthca problems also, redeploy it a moment ago. Please test it in new installation if you don't mind and using the latest version.
