### ISSUE TITLE
Please elaborate on how to create new file stucture

### ISSUE THREAD

**Issue by walterbyrd** [danpros/htmly#201]
If directories need to be created after install: maybe you could tell users exactly what directories, and where the directories go. 

As I understand it: the new structure is supposed to look like this.

content/username/blog/category/type/file.md

1) for username: are users supposed to use the .ini extension? i.e. "walterbyrd.ini" ?

2) for category: are users supposed to create whatever they want?

3)  for type: what specific wording should be used? For markdown, do users use "markdown" or "md" or something else? Does upper of lower case matter? For HTML, I assume you use "html" ? What other types are there?

4) Would this be correct?

/var/www/htmly/blog/travel/markdown/file.md

**Comment by danpros** [comment]
1. No its automatically generated by read the `username.ini` in `config/users`
2. if you don't creating categories in admin/categories than it will use "uncategorized" as the category.
3. `type` This is the content type: post, audio, link, video etc.
4. If you don't create category yet and its a regular post the correct is:

/var/www/htmly/blog/uncategorized/post/file.md

**Comment by danpros** [comment]
Read this, I already updated the readme https://github.com/danpros/htmly#both-online-or-offline

**Comment by walterbyrd** [comment]
I am using HTMLy 2.6.2 and Debian 7 wheezy x86_64

No content directory was created. I had to go to the command line and manually create that directory. 

So, of course, no sub directories were created either. 

I renamed the htmly-2.6.2 directory to just htmly. could that cause such problems?

**Comment by danpros** [comment]
Seems this has been fixed :smile:
