### ISSUE TITLE
after using installer.php to install the site,  2 things unexpected happened

### ISSUE THREAD

**Issue by ebookcode** [danpros/htmly#202]
1) I used /installer.php and 
1a) I don't know the percent of the installing process. And when it's 100% finish, I saw a blank page What I had expected to see is an announcement that the process was done (and a guide how to do next).
2a) After installing done, I went to /installer.php again and saw the message "Your rewriteRule is not ready to use". What I had expected is  is an announcement that I cannot install again and a link to the setting page for admin. And one more, my rewriteRule is ready to use, no problem with that, the message seems not right.

2) when I went to root (/) , I see the [site.url] is not set, I searched and found that in the number 2 of config/config.ini.example
; The URL of your blog. Include the http or https if you are using Facebook or Disqus comments. 
site.url = "".

What I expected is a blog (and I can change site.url in the installer, with an example how to fill it)

**Comment by danpros** [comment]
Simply add your website URL eg.
````
site.url = "htp://www.example.com"
````

Or if in folder
````
site.url = "http://www.example.com/blog"
````

**Comment by ebookcode** [comment]
Why don't you @danpros add one 'site.ur' field (with the examples above) to the installer page? 

I'm a coder and I can work around with some problems like that, but it's not good for all others.

**Comment by ebookcode** [comment]
It's not a bug, it's just a suggestion for better UX

**Comment by danpros** [comment]
This should go to https://github.com/Kanti/htmly-installer
