### ISSUE TITLE
How to use HTMLy to make a home page like https://www.htmly.com ?

### ISSUE THREAD

**Issue by ebookcode** [danpros/htmly#203]
I'm very impressive with the home page of HTMLy and I wonder if @danpros can make it by using HTMLy source code (or ít's just a normal HTML file or it's a PHP file separating from HTMLy ?).

Can @danpros or someone give me a guide or show me the source code to do that?

I have an idea to work around that we can make a category by HTMLy and include the .md files in that category to the homepage by a PHP function. If I choose this solution, it's better if I can hide that category (from displaying in the blog, because it is show in the homepage already)

**Comment by danpros** [comment]
You can check this one for better example http://goo.gl/8SS472

htmly have a few function to do that and undocumented yet but if you look at includes/functions you will find the codes.

````php
// TRUE if the current page is an index page like frontpage, tag index, archive index and search index.
function is_index()
{
    $req = $_SERVER['REQUEST_URI'];
    if (stripos($req, '/category/') !== false || stripos($req, '/archive/') !== false || stripos($req, '/tag/') !== false || stripos($req, '/search/') !== false || stripos($req, '/blog') !== false || $req == site_path() . '/' || stripos($req, site_path() . '/?page') !== false) {
        return true;
    } else {
        return false;
    }
}
// TRUE if the current page is the front page.
function is_front($value = null)
{
    if (!empty($value)) {
        return true;
    } else {
        return false;
    }
}
// TRUE if the current page is the blog page.
function is_blog($value = null)
{
    if (!empty($value)) {
        return true;
    } else {
        return false;
    }
}
// TRUE if the current page is tag index.
function is_tag($value = null)
{
    if (!empty($value)) {
        return true;
    } else {
        return false;
    }
}
// TRUE if the current page is archive index.
function is_archive($value = null)
{
    if (!empty($value)) {
        return true;
    } else {
        return false;
    }
}
// TRUE if the current page is search index.
function is_search($value = null)
{
    if (!empty($value)) {
        return true;
    } else {
        return false;
    }
}
// TRUE if the current page is category index.
function is_category($value = null)
{
    if (!empty($value)) {
        return true;
    } else {
        return false;
    }
}
// TRUE if the current page is profile page.
function is_profile($value = null)
{
    if (!empty($value)) {
        return true;
    } else {
        return false;
    }
}
// TRUE if the current page is post page.
function is_post($value = null)
{
    if (!empty($value)) {
        return true;
    } else {
        return false;
    }
}
// TRUE if the current page is static page page.
function is_page($value = null)
{
    if (!empty($value)) {
        return true;
    } else {
        return false;
    }
}
// TRUE if the current page is sub static page.
function is_subpage($value = null)
{
    if (!empty($value)) {
        return true;
    } else {
        return false;
    }
}
// TRUE if the current page is 404 error page.
function is_notfound($value = null)
{
    if (!empty($value)) {
        return true;
    } else {
        return false;
    }
}
````

Ley say I want to display specific component on the frontpage only: https://github.com/danpros/htmly/issues/197#issuecomment-135580721

Or example:

````php
function get_category($category, $page, $perpage)
```
Want to call specific category result from the frontpage?

````php
// get the travel category, as 1 page, 5 posts
<?php $posts = function get_category('travel', 1, 5);?>
```
Later use the foreach:

````php
<?php foreach ($posts as $p):?>
<div>
    <h3><?php echo $p->title;?></h3>
   <?php<?hp echo $p->body;?>
   etc.  
<div>
<?php endforeach;?>
````

**Comment by fahmi182** [comment]
We must create default template using home layout, so user can learn from it :)

**Comment by ebookcode** [comment]
Can you edit something in the homepage, like "Welcome To Our Website! IT'S NICE TO MEET YOU", by using admin interface of your blog?

I wish you can open source http://www.danetsoft.com @danpros as an example, so I can and ask less questions.

**Comment by danpros** [comment]
Nope this "Welcome To Our Website! IT'S NICE TO MEET YOU" but actually we can edit like the service, portfolio, about etc. how? just creating portfolio category, service and we call it directly from the homepage. Seems WP also has the same technique. Let say just tagging some post with featured and we can call it using get_tag();

The theme is an opensource actually http://startbootstrap.com/template-overviews/agency

**Comment by ebookcode** [comment]
>  just creating portfolio category ...

it means I can find them (the content in the homepage) in the "portfolio category " in the blog?

**Comment by danpros** [comment]
Well that is just an example. You need to creating it by yourself.

**Comment by ebookcode** [comment]
My idea is create some drafts (so visitors cannot see them in the blog), and display them in the homepage.

**Comment by ebookcode** [comment]
Which functions are used to find drafts @danpros 

> Want to call specific category result from the frontpage?
> 
> // get the travel category, as 1 page, 5 posts
> <?php $posts = function get_category('travel', 1, 5);?>

get_category find posts and drafts (or only posts?) ?

**Comment by danpros** [comment]
Use the get_draft()

**Comment by vvcares** [comment]
Hi, bump again. So exactly what we have to do to get the front page same as 'https://www.danetsoft.com/'
