### ISSUE TITLE
Nicer url

### ISSUE THREAD

**Issue by ebookcode** [danpros/htmly#204]
It seem HTMLy can auto transform the title to URL, but sometime it's not good. Example

Good:
Title: HTMLy is a blog
URL (auto): htmly-is-a-blog

Bad: 
Title: HTML là một nền tảng blog
URL (auto): htmly-la-một-nền-tảng-blog (It doesn't work when you click, so you cannot use this title and have to word around by typing the url yourself)

Should be:
Title: HTML là một nền tảng blog
URL (shoult auto be): html-la-mot-nen-tang-blog

Solution: Google "nicer url php"

**Comment by ebookcode** [comment]
If you give me a guide to submit my code to your project, I can Google and fix it myself @danpros

**Comment by danpros** [comment]
The non Latin char for Asian is not covered yet https://github.com/danpros/htmly/blob/master/system/admin/admin.php#L77 so we need to add this char or replace current remove_accent() with a better one. And it would be great if htmly support Chinese or Japanese char :smile: 

Install gihub client and read this https://help.github.com/articles/using-pull-requests/

**Comment by ebookcode** [comment]
@danpros 

> There are two popular models of collaborative development on GitHub: Fork & pull and shared repository.

Which models do you use?

**Comment by danpros** [comment]
Tins one `Fork & pull `

**Comment by ebookcode** [comment]
@danpros when I'm installing Githut client, there is a message 
![git-1](https://cloud.githubusercontent.com/assets/3851020/9607848/8667f526-50f5-11e5-8b07-2aa119c2af91.png)

Is this dangerous (anyone will have access to my email?)

**Comment by danpros** [comment]
Its safe actually.

**Comment by ebookcode** [comment]
I've installed. 

So first step is forking htmly?

![git-3](https://cloud.githubusercontent.com/assets/3851020/9610627/1094a640-5105-11e5-8c81-f84732b06c68.png)

**Comment by danpros** [comment]
Yes, that's right. So you already added the replacements?

**Comment by Xarcell** [comment]
@ebookcode Did you get this issue resolved?

**Comment by ebookcode** [comment]
@Xarcell not resoldved. I found this good lib https://github.com/jbroadway/urlify but having no time to convert it to function remove_accent($str) https://github.com/danpros/htmly/blob/master/system/admin/admin.php#L77

**Comment by danpros** [comment]
@ebookcode I alreadyimplemented it in my local dev and it work great well we just need to do doing this:

```
// Clean URLs
function remove_accent($str)
{
    return URLify::downcode($str);
}
```

**Comment by ebookcode** [comment]
@danpros do you have any plan to use URLify in your next version?

**Comment by danpros** [comment]
@ebookcode yes, now I am working on it and add some missing language. Current htmly the Slovakian is work as expected but the URLify broken, so I must add it manually. I will commit the changes soon so you can test it.

**Comment by danpros** [comment]
@ebookcode please test the master branch.

**Comment by ebookcode** [comment]
I've just tested.

good news: it works
bad news: not as good as expected

fact: đ => dj
expect: đ => d

**Comment by danpros** [comment]
@ebookcode at least not broken :smile:  So only those char? anythings else?

**Comment by danpros** [comment]
See this https://github.com/danpros/htmly/blob/master/system/plugins/urlify/URLify.php#L105 seems just need to change it to `dj` or `DJ'

**Comment by ebookcode** [comment]
No, no, I want "d" but I met "dj", I read the code, line 116 about vn is correct 'Đ' => 'D', 'đ' => 'd' , so don't fix it.

The problem may be the line 125 & 126
        'sr' => array ( /* Serbian */
            'ђ' => 'dj', 'ј' => 'j', 'љ' => 'lj', 'њ' => 'nj', 'ћ' => 'c', 'џ' => 'dz', 'đ' => 'dj',
            'Ђ' => 'Dj', 'Ј' => 'j', 'Љ' => 'Lj', 'Њ' => 'Nj', 'Ћ' => 'C', 'Џ' => 'Dz', 'Đ' => 'Dj'
        ),

I recommend you the solution: just change the line 125 & 126, so "đ" => "d" instead of "dj" (and keep the 105 no change). Because I'm a Vietnamese and using HTMLy. 

In the future, if a Serbian using HTML, you should add one line to your config file so user can choose their language, and then the code use suitable way of URLify.

**Comment by danpros** [comment]
@ebookcode fine, I will revert my latest changes for the char.

**Comment by danpros** [comment]
Release new version contains this.
