### ISSUE TITLE
Search Field Is not working for other languages

### ISSUE THREAD

**Issue by harshsingh2855** [danpros/htmly#205]
Hello,
I have been looking for a cms like htmly which is neat, simple and very user friendly. I want to use it for hindi language. The only bug that i found was searching text in hindi would result in no results. Please suggest a way to work it out.

**Comment by danpros** [comment]
Current htmly is only search the filename actually, related to this #204 

Current solutions is use the Google CSE.

**Comment by danpros** [comment]
The master branch can have slug in hindi so for search the content discuss it here #42
