### ISSUE TITLE
blog.menu links open in blank target - how to config as target self?

### ISSUE THREAD

**Issue by svenjuhnke** [danpros/htmly#206]
Hello,

if i configure a blog menu like your config.ini.example

    ; Custom menu link. 
    ; See example below:
    ; "Google->http://www.google.com|Wikipedia->http://www.wikipedia.org". 
    blog.menu = "MyMenuLink1->http://www.example.com|MyMenuLink2->http://www.example.com/aboutme"

the source contains the links as 

    <a target="_blank" href...
    <a target="_blank" href...

How/Whre can i get menu links without blank targets?

**Comment by danpros** [comment]
Hello @svenjuhnke ,

Sadly if the link is not page or subpage than it will added target blank to the menus. You can try hardcoded it first directly on the layout.html.php before we have a menu manager.

**Comment by svenjuhnke** [comment]
Thank you. In my case the menulinks refer to the same domain. Therefore no blank targets. maybe it's possible, "page or subpage" extend to the domain?

**Comment by danpros** [comment]
@svenjuhnke did you mean different domain? a bit unclear with your questions :smile:

**Comment by svenjuhnke** [comment]
example.com
example.com/example-dir/
example.com/another-example-dir/aboutme/
example.com/yet-another-example-dir/
example.com/**htmly-dir**/
...

For example: htmly blog menu link (home in *example.com/htmly/...*)  to *example.com/another-example-dir/aboutme/*

**Comment by svenjuhnke** [comment]
So?

    $menulink = 'http://www.example.com/another-example-dir/aboutme/';  // is this anc[1] ??
    
    if (substr_count($menulink, filter_input(INPUT_SERVER, 'SERVER_NAME')) !== 1) {
      <a ... "target='_blank" ...
    } 
    // else without blank target

**Comment by svenjuhnke** [comment]
Or better vanilla JS?

    var links = document.links;
    for (var i = 0, linksLength = links.length; i < linksLength; i++) {
        if (links[i].hostname != window.location.hostname) {
            links[i].target = '_blank';
        }
    }

What do you think about? 

Source: <a href="http://stackoverflow.com/a/4425214" target="_blank">http://stackoverflow.com/a/4425214</a>
<a href="http://jsfiddle.net/GdSVn/" target="_blank">jsFiddle</a>

**Comment by svenjuhnke** [comment]
Sorry for unintentionally close

**Comment by danpros** [comment]
Well JS is the most convenience :smile: 

Seems fixed. Will close this one.
