### ISSUE TITLE
Admin Menu Code Location?

### ISSUE THREAD

**Issue by Xarcell** [danpros/htmly#208]
I wanted to experiment with rearranging the admin menu, but I can't seem to find it. Can you tell me which file it's in, assuming there is a template for it.

I was thinking it would be better to place some of the link in a dropdown and organize it like so:
(- top level, -- sub-level)

Manage:

- Categories

- Content
-- Review Posts
-- Review Drafts
-- Add Regular Post 
-- Add Image Post
-- Add Video Post 
-- Add Audio Post 
-- Add Link Post 
-- Add Audio Post 
-- Add Quote Post
-- Add Static Page

- Profile
-- Edit Profile
-- My Posts

- System
-- Config
-- Update
-- Backup
-- Import
-- Clear Cache

- Logout

**Comment by danpros** [comment]
Its available on functions.php
````
function toolbar()
````

**Comment by Xarcell** [comment]
Ok thanks. I appreciate you taking the time to answer issues.

**Comment by Xarcell** [comment]
I started tinkering with this. The default theme uses bootstrap, but bootstrap isn't called in the admin areas. 

Although, I'd much rather not even use bootstrap, I can't stand it. That being said, if I decided to do it my own way, where would a proper place to put the jQuery and CSS for the toolbar? I think it would be best to put in the default theme folder. Do you agree?
