### ISSUE TITLE
Standards?

### ISSUE THREAD

**Issue by Xarcell** [danpros/htmly#209]
I just wondered what the leaders here thought about the use of javascript. Do your prefer it only when necessary, must HTMLy work without javascript, what is the minimum support for IE browser, progressive enhancement, WAI, microdata, etc, etc.

I'm gonna start fiddling with HTMLy a bit and didn't want to put work into anything that had no chance of getting merged due to standards. 

FYI, I'm not a developer, but a designer. Good with UI & UX. Even wrote my own lightweight CSS framework that you've probably never heard of. My personal preferences are 100% javascript free(CSS trickery instead), but clients complain when not able to have an editor for posting and that's a hurdle I haven't been able to jump over yet.

**Comment by danpros** [comment]
It's fine using JS as long we thinking about mobile user in mind. So I am prefer use JS when necessary. IE browser? IE8.  Progressive enhancement, WAI, microdata, etc, etc.? you can use anythings as long as its work on mobile browser nicely :smile: but use any resource as light as possible.

Current admin panel is terrible in term of coding also, there are many un-needed files inside admin/views. Let say creating featured image post need add-image.html.php, we should creating just one file to creating all content add-content-html.php. I will cleaning it up soon so you can styling it easily without change many files.
