### ISSUE TITLE
change breadcrumbs to schema.org

### ISSUE THREAD

**Issue by morrow95** [danpros/htmly#212]
I noticed the breadcrumbs are in rdfa and was going to change them to schema.org like the rest of the site structure is.  Seems simple enough with a few changes in the functions.php and htmly.php, but I keep getting an error related to the sitemap : 

```
Parse error: syntax error, unexpected '<' in /home/test/public_html/blog/system/includes/functions.php on line 1913


// Generate sitemap.xml.
function generate_sitemap($str)
{
    $default_priority = '0.5';

    header('X-Robots-Tag: noindex');

    echo '<?xml version="1.0" encoding="UTF-8"?>';
    ***points to this empty line***
```

Can you provide any insight there?  I don't see how the sitemap has anything to do with changing the values of ```$post->categoryb``` and ```$bc[]``` in functions.php.

**Comment by danpros** [comment]
`$post->categoryb` is for breadcrumb and `$bc` is for `$post->tagb` also breadcrumb. You can use 2 types of breadcrumb, using category or tag.

**Comment by morrow95** [comment]
Yeah those are the values I am changing... the problem is the generate_sitemap() function is throwing that error I mentioned above and I don't see how it is even related in this case.  How is generate_sitemap() using ```$post->category```  and  ```$bc[]``` I guess is the question.

**Comment by morrow95** [comment]
Figured out after looking more in depth.
