### ISSUE TITLE
functions.php : is_**() functions?

### ISSUE THREAD

**Issue by morrow95** [danpros/htmly#213]
There are 11 or so of these in the functions.php page and serve no purpose at all as is : 

```
// TRUE if the current page is category index.
function is_category($value = null)
{
    if (!empty($value)) {
        return true;
    } else {
        return false;
    }
}
```

Each is a different name, but as you can see they do nothing... if you pass anything at all into them it will return true.  Is this something planned for the future or...?  I actually had a need for is_search() and is_notfound() which is when I noticed all this.

**Comment by danpros** [comment]
Well perhaps you want to display specific text based on those page type or different style etc. etc. :smile:

**Comment by morrow95** [comment]
@danpros - The functions themselves do nothing and are pointless in the functions.php.  You set these in htmly.php such as ```'is_notfound' => is_notfound(true)``` in the array.  You can just as easily do ```'is_notfound' => true``` or whatever else you want directly.  In the pages they are accessed by their variable name ```$is_notfound``` and so on.

**Comment by danpros** [comment]
@morrow95 ah you are right, that function previously is not like that and no one notice that function before :smile: yes its unfinished since when I add that I am focusing on content type, draft, image upload, category etc. I will change it later.
