### ISSUE TITLE
robots.txt file isn't necessarily setup right

### ISSUE THREAD

**Issue by morrow95** [danpros/htmly#214]
Setting this up with some modifications for my own use.  I noticed you are relying on the robots.txt file to 'block' certain paths such as : 

```
# Disallow paths
Disallow: /search/
Disallow: /admin/
```

This isn't a foolproof solution.  If another domain were to link to these pages, especially in the case of /search/*anything here*, it can still be indexed and shown in search results.  See https://support.google.com/webmasters/answer/6062608?hl=en

The right solution here is to include a conditional statement in the head of layout.html.php which adds a ```<meta name="robots" content="noindex">``` on those pages.  With that solution in place, you need to ALLOW them in the robots.txt or the meta tag will never been seen.  See https://support.google.com/webmasters/answer/93710

With that said, you can use ```$is_search```, ```$is_notfound```, etc on layout.html.php to create conditionals to do this.

**Comment by danpros** [comment]
You can make a pull request to change that :smile: I will starting to clean up for the admin side.

**Comment by Xarcell** [comment]
This topic should be linked to the pull request right?

**Comment by danpros** [comment]
Well, you can change it manually so marked this as closed.
