### ISSUE TITLE
sitemap.author.xml is completely wrong

### ISSUE THREAD

**Issue by morrow95** [danpros/htmly#215]
The sitemap.author.xml file is wrong.  It adds the category names to the end of /author/ rather than actual author names.

An example of what produces : 
```
<urlset><url><loc>http://blog.example.com/author/testcat</loc><priority>0.5</priority></url></urlset>
```

In this example, 'testcat' is a category I created NOT an author.  I haven't looked at the code yet, but if you know where this is occurring off the top of your head let me know so I can fix it.

**Comment by morrow95** [comment]
sitemap_post_path() in functions.php

```
        // Author string
        $str = explode('/', $replaced);
        $author = $str[count($str) - 3];
```
printing $str shows something along the lines of : 
```
(
    [0] => content
    [1] => Staff
    [2] => blog
    [3] => testcat
    [4] => post
    [5] => 
)
```

The line should be changed to ```$author = $str[count($str) - 5];``` for the correct author name.

**Comment by danpros** [comment]
You are right forgot to check the sitemap part when I am change the folder structure :smile:

**Comment by morrow95** [comment]
You also might want to add in a sitemap for categories while you're at it - everything else has one.

There are a few parts to add, but it only took me a few minutes.

**Comment by danpros** [comment]
@morrow95 yes I will add the sitemap category as well. You should make a pull request with your fixes and improvements :smile:

With current folder structure we can let say displaying the latest images, videos etc. etc. without performance degradation.

**Comment by morrow95** [comment]
@morrow95 yes I will add the sitemap category as well. You should make a pull request with your fixes and improvements :smile:

- I am making these changes on my side and they are probably a little too customized for others to use.

With current folder structure we can let say displaying the latest images, videos etc. etc. without performance degradation.

- I don't understand what you mean here.  Only display the latest x items in the sitemaps?

**Comment by danpros** [comment]
@morrow95 already fixing the bugs and updateing the composer as well.

Regarding the category its off-topic :smile:

**Comment by danpros** [comment]
@morrow95 last commit added sitemap.category.xml
