### ISSUE TITLE
Sitemap error in sitemap.static.xml

### ISSUE THREAD

**Issue by svenjuhnke** [danpros/htmly#216]
Without static pages htmly generates a sitemap.static.xml that contains only

    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"/>

That's all. Without any XML-tags.

Greetings, Sven

**Comment by danpros** [comment]
Hi Sven,

How about the source code?

**Comment by danpros** [comment]
Seems resolved.

**Comment by Shimeri** [comment]
This is still an issue
