### ISSUE TITLE
Auto Update Error(2.6.4)

### ISSUE THREAD

**Issue by Xarcell** [danpros/htmly#217]
When auto updating from 2.5.2 to 2.6.4 I get the following errors:

    Updated to
    [ Notice: Undefined variable: info in /xxxxxx/htmly/htmly-2.3/system/admin/views/updated-to.html.php on line 2 ] 
    Notice: Undefined variable: info in /xxxxxx/htmly/htmly-2.3/system/admin/views/updated-to.html.php on line 2
    Notice: Undefined variable: info in /xxxxxx/htmly/htmly-2.3/system/admin/views/updated-to.html.php on line 3
    Notice: Undefined variable: config_file /xxxxxx/htmly/htmly-2.3/system/upgrade/run.php on line 3
    Fatal error: Class 'Kanti\HubUpdater' not found in /xxxxxx/htmly/htmly-2.3/system/upgrade/run.php on line 5

This was not on a live site, so I do not need support for this. No harm done.

Edit: actually I think may have been v2.3.2 to 2.6.4. That's what the package was, and I had never auto updated before.

**Comment by danpros** [comment]
Seems too much different between v2.3.2 and v2.6.4. Try v.2.6.3 to or v.2.6.4 and if the problems still exist than its bugs.

**Comment by Xarcell** [comment]
Ok thanks.
