### ISSUE TITLE
500 error?

### ISSUE THREAD

**Issue by Xarcell** [danpros/htmly#218]
V2.6.4

I uploaded the files and renamed config.ini.example to config.ini. The site shows a 500 error.

**Comment by danpros** [comment]
Are you sure this is not server related problems?

**Comment by Xarcell** [comment]
I got on my desktop and started debugging. There was an error that says the site url wasn't set in the config. I forgot about that. However, when I visit the URL in IE Touch(I use my windows surface alot), it shows a 500 error, but when viewed in chrome and FF on Ubuntu, it says the site URL wasn't set.

So the fault was mine, although we also know now that errors aren't showing on IE Touch(500 error). We might want to look at that. I'll close the issue for now. Thanks.
