### ISSUE TITLE
[ Feature Request ] - Post By Email

### ISSUE THREAD

**Issue by Xarcell** [danpros/htmly#219]
Beyond my skill, but I wanted to request it. I know this feature is unlikely to implemented, but it doesn't hurt to ask right?

I think it would a nice feature to have. Allow users to mass email associates and post to their site at the same time. It's also an excellent marketing tool, since alot of people still use email as their newsletter. Not to mention, markdown format and email format go hand in hand.

**Comment by danpros** [comment]
I like post by email either actually, well let see what can we do to implement this feature.

**Comment by istek** [comment]
it's a good feature to have. +1

**Comment by nickbe** [comment]
Thumbs up for this. Write an email in markdown, attach an image and use the subject as the article title.
Security could be provided by using a predefined mail key, which is then send within the subject:

Mailto: post@myniftyblogsite.org
Subject: <mailkey>:My practical take on the new INTEL Mainboard Series
-------

Would be great!

**Comment by boniatillo-com** [comment]
+1

**Comment by danpros** [comment]
This issue is too old, I will close this one. Please create new issue for possible improvements for htmly.  Thanks.
