### ISSUE TITLE
[ Feature Request ] - Homepage Option

### ISSUE THREAD

**Issue by Xarcell** [danpros/htmly#220]
I think there should be an option to have a homepage. Either by toggling on/off a dedicated page for it, or setting a created custom page to the homepage. Which ever is easier to implement.

I think homepages is an important feature to have, even for blogs.

**Comment by Kanti** [comment]
:+1:

**Comment by Xarcell** [comment]
@Kanti On an unrelated comment, I'm going through issues trying to clean them up a bit. You have a "to do list" issue that's blank and locked. Can you please close it? Thanks.

https://github.com/danpros/htmly/issues/131

**Comment by danpros** [comment]
Yes this options should available :smile:

**Comment by gesundelehre** [comment]
Is this issue still somehow under construction?

**Comment by danpros** [comment]
@gesundelehre yes :smile:

**Comment by danpros** [comment]
Please test it the master branch I already add an options to enable the static frontpage. Still very basic but no bugs found I will release new version soon that include this feature.

Add below line to config.ini to enable it.

```
static.frontpage = "true"
```

**Comment by danpros** [comment]
Already available on the latest version.

**Comment by gesundelehre** [comment]
If one uses the option static.frontpage = true - how does one have to implement the frontpage? which directory? index.html? index.php? Does the link-structure change? in what way?

**Comment by danpros** [comment]
@gesundelehre just visit the homepage and you will see edit link. If you need total control for the layout use:

```
$is_front
```

But later perhaps we need some template file eg. front.html.php (planned).

**Comment by gesundelehre** [comment]
so there isn't already a file one could edit and use as a front-landing page? (e.g. NOT markdown :-) )

**Comment by danpros** [comment]
Well in markdown you can write html either, but the layout still using layout.html.php. It just like set the static page as frontpage on WP. For now, if you need truly custom layout for the frontpage you can use `$is_front` variable inside layout.html.php.

**Comment by gesundelehre** [comment]
how should one use $is_front in that file? in which file is the function defined?

**Comment by danpros** [comment]
@gesundelehre read this #197
