### ISSUE TITLE
Making a secure password

### ISSUE THREAD

**Issue by thobalose** [danpros/htmly#221]
Hi,

I am getting a 'Your username and password mismatch.' error when trying to login to my blog.
I had carefully followed the instructions and still no luck. 
```
php > echo password_hash('thisismyblogPASSphp', PASSWORD_BCRYPT);
$2y$10$qnwHQwln.90Cn3Nnn3FTSe1SxpyEJFEIlLt8cpWByGRmLqwK.FSKq
```
`myusername.ini` looks like:

```
;Password
password = $2y$10$qnwHQwln.90Cn3Nnn3FTSe1SxpyEJFEIlLt8cpWByGRmLqwK.FSKq
;this will be changed to use bcrypt
encryption = bcrypt
; encryption: not set, leave blank or set to clear or none to use plain text password for the user,
; else set to encryption algoritm supported by hash function of php to use the selected
; encryption

;Role
role = admin

```

$php newbie

**Comment by Xarcell** [comment]
The mismatch may be the username. 

Username:  myusername
Password: $2y$10$qnwHQwln.90Cn3Nnn3FTSe1SxpyEJFEIlLt8cpWByGRmLqwK.FSKq

**Comment by thobalose** [comment]
Hi Xarcell,

Thanks for the reply. I do not get it, I have tried logging in using `myusername` and `thisismyblogPASSphp`. Are you suggesting I should use the hash as the password?

**Comment by danpros** [comment]
Hi @thobalose 

You can try to use let say clear password first and if you can't login either it can related to server configurations as well.

**Comment by thobalose** [comment]
Hi @danpros 

Oooh, I had been successfully using a clear password. I didn't know that HTMLy  automatically changed it to a secure password.

Thanks for the insight. @Xarcell, thanks for the quick reply.

**Comment by thobalose** [comment]
Hi @danpros 

Do you mind explaining how HTMLy does this without specifying the algorithm to use for encryption?

**Comment by danpros** [comment]
@thobalose 

htmly use this https://github.com/danpros/htmly/tree/master/system/vendor/ircmaxell/password-compat

**Comment by thobalose** [comment]
@danpros 

Thank you for the help and insights.
