### ISSUE TITLE
Themes, Three Suggestions

### ISSUE THREAD

**Issue by Xarcell** [danpros/htmly#222]
After playing with the admin menu a bit, I noticed some things and wanted to offer some suggestions as it's beyond my skill to do myself.

To make theming easier, let new themes fallback to default files.

For example, if I create a new theme that only has a css file and maybe a layout.html.php file. Since other files are missing such as the main.html.php, it should use the one in the default folder instead.

So basically, any template file not present in a custom theme should use the one in the default folder. This eases the burden of cloning all the template files from the default folder to the custom one. It also makes updating themes easier because not all template files will have to be updated, since the ones not present in the custom theme folder will use the ones in the default folder.

I hope I'm not confusing anyone here.

---

Build templates in layers. If using the default fallback, it makes it simpler for designers to copy & modified what they want with the excess.

layout.html.php = include header.html.php, main.html.php, and footer.html.php
main.html.php = include content.html.php, sidebar.html.php
content.html.php = include all main/content template files depending on action.

**\* I might take a crack at this myself and submit a pull request.

---

Please use the same theme for the admin-view and the user-view of the site. From a designer stand-point it's alot better of one theme skins both front-end and back-end. Rather than having the admin separated from the user end.

**Comment by danpros** [comment]
htmly this small helper https://github.com/badphp/dispatch/tree/1.x so you can use partials https://github.com/badphp/dispatch/tree/1.x#views-and-partials

**Comment by danpros** [comment]
This issue is too old, I will close this one. Please create new issue for possible improvements. Thanks
