### ISSUE TITLE
[Feature Request] blog.menu links - option to toggle on/off - append to existing links instead of overwriting them

### ISSUE THREAD

**Issue by gesundelehre** [danpros/htmly#223]
Would it be possible to **append thhe links that are specified in the config.ini** _instead_ of **overwriting all the links in the menubar** (maybe with the **option to turn it on/off**?) 

How else would it be possible to have outgoing links in the menu bar plus at the same time menu-items that are in the 2nd level?

; Custom menu link. 
; See example below:
; "Google->http://www.google.com|Wikipedia->http://www.wikipedia.org". 
blog.menu = ""
**; Overwrite menu items with the line above OR append them to the already existing/dynamic menu-bar created from static-pages**
**blog.menu.overwrite_or_append = "append"**

**Comment by Xarcell** [comment]
I could be wrong, but I think a menu manager is planned. Anyone is welcome to create one and submit a Pull Request.

**Comment by danpros** [comment]
Yes we really need menu manager here. This is the missing part from HTMLy.

**Comment by danpros** [comment]
We already have menu manager. I will close this one.

Thanks,
