### ISSUE TITLE
[Help Request / Question] How can one use a custom landing page?

### ISSUE THREAD

**Issue by gesundelehre** [danpros/htmly#224]
Is it possible with the following configuration in the config.ini?

**; Show the /blog url as the blog homepage. Options "false" and "true"**
**blog.enable = "true"**

If yes, where do i have to place my landing page (index.html/php-file?) - or did I miss something and it works in another way?

**Comment by Xarcell** [comment]
Not yet implemented, but planned. See: https://github.com/danpros/htmly/issues/220

**Comment by danpros** [comment]
Lets talk on #220
