### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by demlak** [danpros/htmly#227]
Hi,
im testing HTMLy right now for the first time.. and i´m missing syntax highlighting by using markdown..

How to use syntax highlighting?

like this:
``` csharp
private void index(){ MessageBox.Show("hello world"); }
``` 
instead of this: 
``` 
private void index(){ MessageBox.Show("hello world"); }
```

**Comment by danpros** [comment]
Hello,

You need to enable it manually, see this https://github.com/jmcmanus/pagedown-extra#fenced-code-blocks

**Comment by demlak** [comment]
Ok,
1. i don´t understand why this has to be done by editing sourcecode.. would be much more comfortable as an option in the configuration.
2. i tried to add this functionality by editing source code.. did not get it to work
3. but nevermind.. as i now see, HTMLy does not support full-text-search.. (see: https://github.com/danpros/htmly/issues/42) HTMly does not fit my needs.. i will look for another CMS...

thx anyway

**Comment by danpros** [comment]
Well try WordPress than :smile:

**Comment by demlak** [comment]
nope =)

**Comment by Xarcell** [comment]
@demlak this is a databaseless web application, adding options for every little thing would be tricky and would add bloat. Having a databaseless web application has it's pros ands cons. The pros outweigh the cons if your expecting less than 100k views at any given moment on a shared server. It can handle more if your on a VPS or dedicated server.

**Comment by demlak** [comment]
well.. when it is included.. but not accessable.. then it won´t bloat anything, if you just add the option by giving access to already exiting code.. (speaking of syntax highlighting)

if you are talking about the search function.. i agree.. for sure, this is one function out of thousands.. and different people do have different needs.. HTMLy does not fit my need in this part.. that´s ok.. i don´t blame you anything in this part.. it´s ok.. i´ll move on =)

**Comment by danpros** [comment]
@Xarcell off-topic check this https://github.com/danpros/htmly-twentyfifteen (still beta).
