### ISSUE TITLE
Tweedledee RSS Import fails

### ISSUE THREAD

**Issue by malenki** [danpros/htmly#228]
I want to mirror my tweets in HTMLy and created a RSS feed of them using [Tweedledee](https://github.com/chrissimpkins/tweetledee). But the [resulting RSS](http://malenki.ch/tweetledee/userrss.php) doesn't work for HTMLy, other RSS feeds do.
Do you have any hints what the problem is?

**Comment by danpros** [comment]
It work fine using service like blogger, feedburner etc. even I can add it in my outlook so the problems must be on their app.
