### ISSUE TITLE
Not Seeing New Themes In 2.6.5

### ISSUE THREAD

**Issue by Xarcell** [danpros/htmly#229]
Just as the title says. Folders and files seem to missing from the branch.

**Comment by danpros** [comment]
You need to upload it manually. Well its ported theme so I decided not to add it on the package. That will listed on htmly homepage later :smile: 

What's new: The next and previous navigation now have any variable like regular post. Old medium.com have small description, image etc. on post navigation and now htmly support that as well. Example:

```
$next['image']

$prev['description']
```

**Comment by Xarcell** [comment]
Ok Thanks.
