### ISSUE TITLE
Error while upgrading

### ISSUE THREAD

**Issue by herby** [danpros/htmly#230]
When upgrading to 2.6.5, from 2.6.4, I got this message:

    Undefined variable: config_file in /Users/herby/www/blog.herby.sk/system/upgrade/run.php on line 3

in http://blog.herby.sk/admin/update. But when I click on [Update] button again, it says "Congrats! You have the latest version of HTMLy", even if I am afraid that the process of upgrade did not complete.

Don't you know what happened, if the upgrade is fully completed and if not, how to successfully retry it?

Thanks.

**Comment by danpros** [comment]
@herby you can ignore that error message. This is from this:

```
config('source', $config_file);
```

If the message say so than the upgrade is fully completed.

**Comment by herby** [comment]
Thanks.
