### ISSUE TITLE
Google Adsense 

### ISSUE THREAD

**Issue by ezmint** [danpros/htmly#231]
Is it possible use google adsense? I see in the config "google.publisher," is this for google adsense account? If it is, then do put "pub-xxxxxxxxxxxxx" or just "453453xxxxxxxx"?

By the way, I tried to insert google ads directly in the layout and it didn't work. 

Thanks

**Comment by danpros** [comment]
Of course its possible. Make sure to clear the cache after you add the codes. The Google publisher is for Google plus.

The best is creating new config and print that in your template. Go to example.com/admin/config. Create new key with the adsense full codes as the new value eg.
```
adsense.sidebar = your adsense code
```
and than open layout.html.php and print that in your template
```
<?php echo config('adsense.sidebar');?>
```

**Comment by danpros** [comment]
Marked this as resolved.

**Comment by ezmint** [comment]
Hi Luis,
Hope you had a fantastic day. Please don't do MIT license. It's for your
sake.

Best,
Shaun
Noble.bz (would love to install htmly, but need few specific things)
behindtalk.com (htmly)


Shaun Uddin, MPP, MBA
*"If you want to go fast, go alone; if you want to go further, go
together." - African proverb *

This email message and any attachments hereto is intended for use only by
the addressee(s) named herein and may contain legally privileged and/or
confidential information. If you have received this email in error, please
immediately notify the sender and permanently delete the original and any
copy of this message and its attachments.

**Comment by igeekyayush** [comment]
How easy it is to implement Google Adsense on this platform? I'm using WordPress from past 4 years. Thinking to make a shift with new blog.  It would be a tech bases blog. Also at later stage I will integrate Amazon CloudFront with it.

**Comment by ezmint** [comment]
​It's very easy ​


Shaun Uddin
*"If you want to go fast, go alone; if you want to go further, go
together." - African proverb *

This email message and any attachments hereto is intended for use only by
the addressee(s) named herein and may contain legally privileged and/or
confidential information. If you have received this email in error, please
immediately notify the sender and permanently delete the original and any
copy of this message and its attachments.

**Comment by igeekyayush** [comment]
What about implementing CDN service? Any user running full working blog on htmly?
