### ISSUE TITLE
Better user management

### ISSUE THREAD

**Issue by nickbe** [danpros/htmly#232]
In my opinion user roles should be enhanced. (a little)
A 'user' should not be able to change the config.
(The config could use some sort of grouping btw...)

**Comment by danpros** [comment]
@nickbe yes it should only user with admin role. And without any descriptions for each config it pretty confusing.

**Comment by nickbe** [comment]
What do you think about giving users rights on a per category basis.?

**Comment by danpros** [comment]
Well, that's possible. But we need to add it to the core. Let say we save the data to some kind of array (as file) and use the username as the key.

Do you use htmly for multi author blog?

**Comment by danpros** [comment]
The master branch already block regular user to editing the config. Will do a quick release later.

**Comment by nickbe** [comment]
Yes I'd like to do this.
I'm looking for a possibility to let users post to the community (only registered users), keep posts for themselves, or post to the public.

Beste Grüße | Best regards
Nick Berglmeir

MoJoMakerC o n s u l t i n g
Creative Ideas and knowledge power

Lindauer Str. 4, 87439 Kempten, Germany
+49 831 20699 877(tel:+49%20831%2020699%20877)• mail@berglmeir.com
HRB 1363 Kempten • DE281261678

**Comment by nickbe** [comment]
Good improvement :)

Beste Grüße | Best regards
Nick Berglmeir

MoJoMakerC o n s u l t i n g
Creative Ideas and knowledge power

Lindauer Str. 4, 87439 Kempten, Germany
+49 831 20699 877(tel:+49%20831%2020699%20877)• mail@berglmeir.com
HRB 1363 Kempten • DE281261678
