### ISSUE TITLE
really need to support Chinese

### ISSUE THREAD

**Issue by istek** [danpros/htmly#234]
i found that if my post's title is Chinese, i can post it successful, but i can't view it. it shows me File Not Found, the file is over there content/username/catagories/chinese-file-name.md .

at this particular example , file is   content/stanley/技术生活/2015-12-09-12-28-00_技术生活_vps安装debian后需要做的事情.md

**Comment by istek** [comment]
i think utf-8 is okay. is htmly supporting utf-8?

**Comment by danpros** [comment]
That is know issue. Yes supported.

Since it can save to the file than the problems is on route. I will try to improve it.

**Comment by danpros** [comment]
First you can try to romanized by adding it to this https://github.com/danpros/htmly/blob/master/system/plugins/urlify/URLify.php

**Comment by danpros** [comment]
Please try the master branch https://github.com/danpros/htmly/archive/master.zip it should fixed by now.

**Comment by danpros** [comment]
Fixed https://github.com/danpros/htmly/releases/tag/v2.6.9
