### ISSUE TITLE
can i use markdown extra additions?

### ISSUE THREAD

**Issue by istek** [danpros/htmly#235]
such as flow chart, latex formula,strikethrough  etc.
how can i enable extra? or somewhere in config.php, use default or extra for markdown editor properties.

anyway, thanks for supporting chinese file name.

**Comment by danpros** [comment]
Yes just releasing quick update since its very important.
 
HTMLy use markdown extra for the default so you don;t need to change or setup anytings.

For latex formula you can use Mathjax and you need to add it manually, see http://docs.mathjax.org/en/latest/start.html

**Comment by istek** [comment]
confirmed.... it works well.
okay. thanks.

**Comment by ramonskovitch** [comment]
HI Danpros and Istek

Could you please step me through the process of installing mathjax on to HTMLy. I just need to understand where to put the various things including where to alter the templates. 

Also I notice that footnotes don't seem to work  in the editor?

Thanks

Dan
