### ISSUE TITLE
Notice: Undefined property: stdClass::$views

### ISSUE THREAD

**Issue by nickbe** [danpros/htmly#236]
Always used the PHP Internal webserver:
PHP -S 127.0.0.1 -t <folder>

But since the last updates it doesn't work anymore.
Any idea why?

**Comment by danpros** [comment]
Any error log? and please explain more about "doesn't work anymore" :smile: 

Well on the latest version I just make the teaser so the utf8 char will displayed properly:

```
function replace_href($string, $tag, $class, $url)
{

    libxml_use_internal_errors(true);

    // Load the HTML in DOM
    $doc = new DOMDocument();
    $doc->loadHTML($string);
    // Then select all anchor tags
    $all_anchor_tags = $doc->getElementsByTagName($tag);
    foreach ($all_anchor_tags as $_tag) {
        if ($_tag->getAttribute('class') == $class) {
            // If match class get the href value
            $old = $_tag->getAttribute('href');
            $new = $_tag->setAttribute('href', $url . $old);
        }
    }
    
    return preg_replace('~<(?:!DOCTYPE|/?(?:html|head|body))[^>]*>\s*~i', '', utf8_decode($doc->saveHTML($doc->documentElement)));

}
```
I can use mb_convert_encoding to clean up those code but it need php-mbstring so decided to use preg_replace. 

Your report is very important so please give me more details.

**Comment by danpros** [comment]
New additional changes from get_teaser()

```php
    if ($teaserType === 'full') {
        $readMore = explode('<!--more-->', $string);
        if (isset($readMore['1'])) {
            $patterns = array('<a id="more"></a><br>', '<p><a id="more"></a><br></p>');
            $string = str_replace($patterns, '', $readMore['0']);
            $string = replace_href($string, 'a', 'footnote-ref', $url);
            return $string . '<p class="jump-link"><a class="read-more btn btn-cta-secondary" href="'. $url .'#more">' . $more . '</a></p>';
        } else {
            return $string;
        }
    } 
```

**Comment by danpros** [comment]
And this from get_posts()

```php
        $more = explode('<!--more-->', $content);
        if (isset($more['1'])) {
            $content = $more['0']  . '<a id="more"></a><br>' . "\n\n" . '<!--more-->' . $more['1'];
        }
```

**Comment by danpros** [comment]
The only changes in the theme is the get _teaser(). Previously: `get_teaser($p->body)` and now for `<!--more-->` feature you need to change it to `get_teaser($p->body, $p->url)`

**Comment by nickbe** [comment]
Ok. I think I've sorted it out. I reinstalled htmly and then suddenly everything worked again.

Two Problems though:
Posting an image article requires me to select a featured image even if I don't want this.
But when htmly is displaying an article with featured image then I receive this error:

Notice: Undefined property: stdClass::$views in C:\Temp_C\PHP\www\system\includes\functions.php on line 1504

- Wouldn't it be better to have a simple "Post Article" function and then be able to select between video, quote, and so on directly in the post, instead of all the preselects before posting?

**Comment by danpros** [comment]
> But when htmly is displaying an article with featured image then I receive this error:
> Notice: Undefined property: stdClass::$views in C:\Temp_C\PHP\www\system\includes\functions.php on line 1504

This is a bug, functions.php at line 356

```
if (config('views.counter') == 'true') {
	$post->views = get_views($post->file);
}
```

it should 
```
if (config('views.counter') == 'true') {
	$post->views = get_views($post->file);
} else {
	$post->views = '';
}
```

Try to add that manually and soon I will release new version with improvements.

> Wouldn't it be better to have a simple "Post Article" function and then be able to select between video, quote, and so on directly in the post, instead of all the preselects before posting?

Yes like this idea. I will try to creating that.

**Comment by danpros** [comment]
This has been fixed.

**Comment by nickbe** [comment]
Great - Thanks a lot!
