### ISSUE TITLE
Custom Content Tags

### ISSUE THREAD

**Issue by elpsykongroo** [danpros/htmly#237]
Is it possible create my own custom tags like   or Date ? How do I do that?

**Comment by danpros** [comment]
Yes but you need modify the core (https://github.com/danpros/htmly/blob/master/system/admin/admin.php) if you want to add that when adding/editing the post. If you add those tag manually you can use get_content_tag, example:

```
get_content_tag('L', $string);
```

**Comment by danpros** [comment]
Will close this one.
