### ISSUE TITLE
html in posts?

### ISSUE THREAD

**Issue by morrow95** [danpros/htmly#241]
Curious as to whether there is an easy change to make this possible.  I am the only one who will be posting (I realize that might not be the case for everyone), but I've come into situations where I would like to enhance the post with use of html code.

I'm not sure of how markdown works internally, but would this be as simple as removing the `remove_html_comments` function?

For instance in a call like this : 

`$desc->body = MarkdownExtra::defaultTransform(remove_html_comments($content));`

I'm going to play around with it a bit later, but if that is the case it might be a useful option in the config file and a really easy fix to test the condition of its value in the functions.php.

**Comment by danpros** [comment]
You don't need to change anythings, markdown also support html. Try to write your html tag in the editor to test it.

**Comment by morrow95** [comment]
Really?  I remember adding an image with the typical <img src=... and it wouldn't work.  I think I wanted to add a class around it or something.  I'll test it out again tonight to see what happens.

**Comment by morrow95** [comment]
Your right - it works fine.  I swear I had trouble with that before for some reason.

Off topic, but wasn't there a way to schedule the post for a future date?  As in it wouldn't be visible until that future date?  I thought I remembered that in the old version and now that I've update I see no way to do that.  Maybe I was confusing this was something else?

**Comment by danpros** [comment]
> Off topic, but wasn't there a way to schedule the post for a future date?

Not yet implemented :smile:

**Comment by danpros** [comment]
Will close this one.
