### ISSUE TITLE
HTMLy license Question

### ISSUE THREAD

**Issue by nickbe** [danpros/htmly#242]
Would you consider to change the license from GNU to MIT?
Cheers
Nick

**Comment by danpros** [comment]
Why MIT? :smile: is there any problems with GNU?

**Comment by nickbe** [comment]
The MIT License is much more open when it comes to using projects for our own, even commercial purposes, especially when it comes to sublicensing, which may be more restricted compared to the original license. See: https://opensource.org/licenses/MIT   

But I can understand if you don't want this. But If there's not reason for you not to grant MIT license it would defintely be a generous thing to do.

**Comment by danpros** [comment]
HTMly will always using GNU. I will close this one.
