### ISSUE TITLE
Upload image to current editing article folder

### ISSUE THREAD

**Issue by greenBaram204** [danpros/htmly#243]
i want to upload image fit for my purpose

firts one, repeated image on image folder
second one, article related image on article folder

but, the image upload interface no support second one. it uploads every image as first one. and insert from that image. i want to use related path.

so, what do i do if i want to change image upload interface as second one?

**Comment by danpros** [comment]
A bit confused with your questions here. HTMLy always upload image to `content/images` folder. And you need to add those images to the post using the editor. If you need to add multiple image to the post, you just need to upload it one by one in the editor.

**Comment by greenBaram204** [comment]
![_017](https://cloud.githubusercontent.com/assets/12525772/13449379/307b5654-e06e-11e5-8fd5-90c4b7236e32.png)

first one,
- if i change home url. every image broken.
- if i change specific image of specific article. I don't know what is orphan images. cause the name of images randomly generated. I can't find which image related on specific article.

second one.
- if i change home url. every images are safe. cause it has relative path.
- if i change specific image of specific article. I can recognize orphan image and i can remove that one.

**Comment by danpros** [comment]
Well, htmly work not like other flat-file cms. Its just like Drupal or WP do and yes that is current limitation, I mean we don't know  image that not used on post.

The blog folder is for the user posts, the images folder is just for images. Yes we should some kind of image manager.

**Comment by ramonskovitch** [comment]
danpros;

Is it possible to put images directly in the images folder and use a relative link not a FQDN link?

thanks
Dan

**Comment by danpros** [comment]
@ramonskovitch using the image uploader you need to change it manually after the image URL pasted to the text editor.

**Comment by mutwirimikez** [comment]
Thanks

**Comment by zh-wowtv** [comment]
But how am I supposed to refer to the image. For example, my url is http://myhome.com and my image is in images/myimg.jpg?

**Comment by danpros** [comment]
Close this one.
