### ISSUE TITLE
More documenting needed

### ISSUE THREAD

**Issue by greenBaram204** [danpros/htmly#245]
I want to limited teaser. but I can't find which value is limited teaser.

![_018](https://cloud.githubusercontent.com/assets/12525772/13449660/0678571e-e071-11e5-9546-f3a0f1407828.png)

so, i know current is full, but i don't know which value is not full. 
can i empty or input `disable` into that form?

need config property , avaliable value and it's description document.

**Comment by danpros** [comment]
There are 2 type, `trimmed` and `full` . If using trimmed than the `teaser.char` will used but the `read.more` text need manually changed on the theme.

If you use `full` than cut it using:

```
<!--more-->
``` 

Read the docs here https://docs.htmly.com/basics or you open config.ini.example inside config folder.

**Comment by dbYoung** [comment]
Thank you!
