### ISSUE TITLE
tags.lang

### ISSUE THREAD

**Issue by elpsykongroo** [danpros/htmly#246]
`tags.lang` file only updates when creating posts through dashboard, but doesn't update when adding posts manually with text editor. This causes some tags in popular tags widget to appear like `new-tag` instead of `New Tag`.

**Comment by danpros** [comment]
You must realize if I put the tags in file name is to speed up everything, yes when people visiting the tag page etc. and almost everything I put on the filename and folder. 

Your case is current htmly limitation and to update it just simply edit one post and change `new-tag` to `New Tag`. It should update it in instant.
