### ISSUE TITLE
new theme apex

### ISSUE THREAD

**Issue by byens** [danpros/htmly#247]
Hi, can we have this theme? https://www.competethemes.com/apex-live-demo/

**Comment by danpros** [comment]
Well, I will considered to ported it.

**Comment by greenBaram204** [comment]
+1

**Comment by danpros** [comment]
This also seems good http://independentpublisher.me

**Comment by kreativmind** [comment]
Both of those themes are very nice and would be great to have

**Comment by kazu2012** [comment]
I want somebody to make these themes onto HTMLY!
I may be able to make it but somebody eles is a lot better than me!

**Comment by kazu2012** [comment]
http://html5tutorial.byethost17.com/

I tried but I was not able to figure out. I guess css or js problem.

**Comment by Xarcell** [comment]
Right click the webpage, and select inspect element. You'll see an error down there.

**Comment by danpros** [comment]
This issue is too old, I will close this one. Please create new issue for possible improvements. Thanks

**Comment by kreativmind** [comment]
Is your project still under active development?

**Comment by danpros** [comment]
@kreativmind Yes of course, last release about 3 weeks ago.

**Comment by kreativmind** [comment]
> @kreativmind Yes of course, last release about 3 weeks ago.

I must say that I have not looked at or used HTMLy in a few years but after just installing it, I am impressed at how far development has come. Nicely done.

**Comment by danpros** [comment]
@kreativmind Thanks, credit to contributors also.
