### ISSUE TITLE
Multi Line contents rendering differently -> only use <br/> without <p>

### ISSUE THREAD

**Issue by greenBaram204** [danpros/htmly#248]
![_059](https://cloud.githubusercontent.com/assets/12525772/13528776/9a787f16-e25b-11e5-99de-f507fe77daa6.png)

In, markdown editor. Multi-Line contents is rendered properly.

But, On home pages - It's broken.

![_061](https://cloud.githubusercontent.com/assets/12525772/13528788/a207c390-e25b-11e5-89ec-27446345b7d8.png)

I think there's a different rules between editor and real pages.

**Comment by danpros** [comment]
Can you give me the markdown file so I can test it?

**Comment by greenBaram204** [comment]
@danpros 
Here is markdown file.
https://drive.google.com/file/d/0Bym2wVVSsnyBekhhOGNYdEYzVEU/view?usp=sharing

**Comment by danpros** [comment]
@greenBaram204 seems because of using

```
<p></p>
```

Try to remove it and its work. Weird behavior.

**Comment by dbYoung** [comment]
OK, Now It's O.K
