### ISSUE TITLE
Remove Unused(orphan) images Feature

### ISSUE THREAD

**Issue by mcdoyaji** [danpros/htmly#249]
OK. I cannot find which one is used and is not.

Some Image usage checking feature needed.

Anyway. 
DanPros, I always thank you for making such a good flat-file based blogging cms.

**Comment by danpros** [comment]
> OK. I cannot find which one is used and is not.

> Some Image usage checking feature needed.

Yes this is known issues. If we open the md file one by one will take many resources. I will try to find solutions without performance hit.

 > Anyway.
> DanPros, I always thank you for making such a good flat-file based blogging cms.

You're welcome! credit for contributors also. Spread the word about HTMLy :smile:

**Comment by danpros** [comment]
I will close this one. Thanks.
