### ISSUE TITLE
Error #404 with nginx in a subdir

### ISSUE THREAD

**Issue by Hulubulukulupulu** [danpros/htmly#250]
Hello
first of all a huge thank u for that beatiful project :)

I'm using nginx at a raspberry with a config kinda similar looking to the endresult at #52 

```
server {
    listen 80;
    listen [::]:80 default_server;
    server_name example.com;
    return         301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl default_server;

    root /var/www/;

    index index.php index.html index.htm;

    server_name example.com;

    #cutted out the various ssl parameters

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ [^/].php(/|$) {
        fastcgi_split_path_info ^(.+?.php)(/.*)$;
        if (!-f $document_root$fastcgi_script_name) {
                return 404;
        }

        fastcgi_pass unix:/var/run/php5-fpm.sock;
            fastcgi_index index.php;
            include fastcgi_params;
    }

    location ~ /blog/config/ {
        deny all;
    }

}
```

Now HTMLy works just fine when its root folder is "/var/www/" but when i want it at "/var/www/blog" i clean up & put it there and suddenly the /blog/login dont works anymore -> 404

What am i missing? :S

**Comment by danpros** [comment]
@Hulubulukulupulu perhaps this

```
root /var/www/blog/
```

**Comment by Hulubulukulupulu** [comment]
meh ... that's just changing the rootdir of the webserver...
my desired config looks like this:
root/landingpage+content
root/blog/blog-related-things

i already tried to add an extra location via
`    location /blog/ {
        try_files $uri $uri/ /index.php?$args;
    }`
but its still not going to work

**Comment by danpros** [comment]
Well you can using WordPress config actually since all almost the same, example:

http://robido.com/nginx/nginx-wordpress-subdirectory-configuration-example/
or
http://stackoverflow.com/questions/6154879/nginx-wordpress-in-a-subdirectory-what-data-should-be-passed
