### ISSUE TITLE
Add plugin feature

### ISSUE THREAD

**Issue by mcdoyaji** [danpros/htmly#251]
How about plugin feature?

For example, gist embed.

**Comment by danpros** [comment]
Seems we don't need plugin to embed gist, see this and scroll to the bottom: https://help.github.com/articles/about-gists/

So we just need to copy paste to the edit and done.

**Comment by JeroenSteen** [comment]
Can you give an example of what to copy paste in the HTMLy editor, to embed Gists?

**Comment by danpros** [comment]
@JeroenSteen perhaps: https://betterstack.dev/blog/how-to-embed-a-github-gist-in-your-website/#heading-how-to-embed-a-single-file-from-a-gist

**Comment by danpros** [comment]
I will close this one. Thanks,
