### ISSUE TITLE
Multi User

### ISSUE THREAD

**Issue by kreativmind** [danpros/htmly#252]
Maybe its because I am new to htmly but I do not see anything in the admin section related to setup of registration for users to join and colaborate, post, or comment. How do I open up the site for registration? I am needing many people to join and be able to blog? The documentation is very weak. Thanks.

**Comment by danpros** [comment]
@kreativmind current version don't have such feature, all user must created manually but this can change in the near future.

**Comment by kreativmind** [comment]
Oh okay. I asked because your site advertises that it does. Thanks.

**Comment by danpros** [comment]
@kreativmind well it does but you need to creating it manually each user.

**Comment by kreativmind** [comment]
Ah, ok. Thanks for clarifying that. I will have to keep looking at other CMS out there. Thanks again.

**Comment by JayCode-ORG** [comment]
Hi!

I was wondering, how exactly does one creates a login for another user?

Thanks,
Justin
https://zomblg1pogo.ml/blog

**Comment by ncang** [comment]
just create anotheruser.ini at config\users @JayCode-ORG

**Comment by kreativmind** [comment]
I was hoping multi-user and self-registration would have been implemented by now.

**Comment by danpros** [comment]
@kreativmind the code is already there (see admin.php), we just need to create the page and improve the role but not ETA for this.

**Comment by kreativmind** [comment]
Any updates to achieving this? I did see the code there but I am not a dev and it's beyond my intelligence to be able to create the remaining pages and functions to make this work.

**Comment by danpros** [comment]
@kreativmind please update to htmly latest version (2.9.9). Now we can create new user from admin panel.

**Comment by kreativmind** [comment]
I have the latest version 2.9.9. I am referring to user self registration.  That is what I have been waiting on for a few years now.
________________________________
