### ISSUE TITLE
Cannot delete files from ftp due to rights issue (550, 644, 33, 33)

### ISSUE THREAD

**Issue by malouvo** [danpros/htmly#253]
Hi, I just installed htmly today because I want to test several platforms before I choose one to build a website with.
I must say, I am rather new to coding in general and my assessment of the situation is based on google and some tinkering.

My problem now is that I cannot uninstall htmly from my ftp because I lack the rights to delete many of the files that were created by installer.php. The error I get is 550 Permission Denied, the rights settings of the files in question are set to 644 and the owner is 33, the user also 33.
I have tried creating and running a chmod 777 php as well as the obvious attempt to change rights in my ftp client (cyberduck, mac os). One of the many files is for example index-author.txt in /cache/index.
I also reinstalled htmly using the same username and password as is used for my ftp.
Renaming or replacing obviously also will not work.

As a last resort I will of course contact my hoster, but I hope there is another quick solution to it, also because I might want to reinstall and delete or change it again in the future.

Thank you very much for your help!

Edit: Oh yeah, I also can't even install new themes receiving the same message 550 …/themes/htmly-vapor-master: Permission denied.

**Comment by danpros** [comment]
Hello,

How you creating the FTP? provided by the hoster or you create it manually, make sure the FTP user have read and write permission.

**Comment by malouvo** [comment]
Hi, thanks for your quick reaction! It is provided by a hoster. I have never had any such issues before using wordpress though. I can also still read and write all other files and change rights, just not on those created by the installer.php.

However, your reply seems to suggest this is something I will have to sort out with my hoster, correct?

**Comment by danpros** [comment]
So you facing this problems when using WordPress also? yes you should contact your hoster about this problems.

**Comment by malouvo** [comment]
No, I am not facing this problem using WordPress. I meant to say that I have never had this problem while using WordPress, only now after running the htmly installer.php.

**Comment by malouvo** [comment]
Just got it solved after finding the right code in a drupal forum:

`<?php
   function rchmod($parent, $dmod, $fmod) {
         if (is_dir($parent)) {
                 $old = umask(0000);
                 chmod($parent, $dmod);
                 umask($old);
                 if ($handle = opendir($parent)) {
                         while (($file = readdir($handle)) !== false) {
                           if ($file === "." or $file === "..") {
                                         continue;
                                 } elseif (is_dir($parent . '/' . $file)) {
                     rchmod($parent . '/' . $file, $dmod, $fmod);
                                 } else {
                                         $old = umask(0000);
                                         chmod($parent . '/' . $file, $fmod);
                                     umask($old);
                                 }
                         }
                         closedir($handle);
            }
         } else {
                 $old = umask(0000);
                 chmod($parent, $fmod);
                 umask($old);
         }
    }
    rchmod('foldername/', 0777, 0666);
?>`

Replacing 'foldername' with the actual name of the folder (or file) that is to be be changed in permissions is all that needs to be done. Then place it as chmod.php right above that folder and run it in the browser. After that I was able to delete the files.

Thanks again and cheers!

**Comment by danpros** [comment]
Glad you found it :)
