### ISSUE TITLE
Cannot add post when using RewriteRule

### ISSUE THREAD

**Issue by mudeth** [danpros/htmly#254]
I have this in my .htaccess in '/' to transparently rewrite requests to '/htmly'.

```
RewriteEngine on
RewriteBase /

RewriteCond %{REQUEST_URI} !^/htmly/
RewriteCond %{REQUEST_URI} !^/files/

RewriteCond %{HTTP_HOST} ^(www\.)?myhost\.
RewriteRule ^(.*)$ /htmly/$1 [L]

```

When `site.url` is set to https://www.example.com/htmly, I can add new posts, no problem.

However, when I change `site.url` to https://www.example.com/, I get a blank page when I click submit.

I added
```

error_reporting(E_ALL);
ini_set("display_errors", 1);
```

to my `index.php`, and this is the output I get when I click 'Publish' from `/add/content?type=post`:

Notice: Undefined index: REQUEST_URI in /home/public/htmly/system/includes/dispatch.php on line 551

Notice: Undefined offset: 0 in /home/public/htmly/system/includes/dispatch.php on line 558

**Comment by danpros** [comment]
@mudeth why you put it on folder and not on the your domain root if you want such URL:

```
https://www.example.com
```

**Comment by mudeth** [comment]
Is that the problem?

I'm running on a shared host, and I find it easier to arrange directories like this when I'm working via ssh:

/files
/music
/projects
/htmly
etc.

Do you have any ideas what a fix may be? I'm willing to dig around a bit if you can point me in the right direction.

**Comment by danpros** [comment]
@mudeth how about set the rewrite base, eg:

```
RewriteBase /htmly/
```

**Comment by mudeth** [comment]
Thanks for the reply! In the meantime, I had moved the files over to the root directory and it works fine.

I'll try the rewrite rule if this comes up again.

**Comment by danpros** [comment]
Will closed this one.
