### ISSUE TITLE
clean theme broken after update

### ISSUE THREAD

**Issue by ghost** [danpros/htmly#257]
Style for `.post` is not applied (one that sets bottom-border and padding), even if content contains `class="post"` wrapper divs.

Not updated for long (maybe half a year).

**Comment by herby** [comment]
It seems to be because, somehow, `infront` class in content changed to `in-front`, but clean/style.css still contains `.infront .post`.

**Comment by danpros** [comment]
Ah yes the clean theme seems broken for some of the classes, well you can fix it by yourself, at least for now. Currently htmly is on stable state so new version will not released soon.
