### ISSUE TITLE
Way to store and retrieve Author Username, or arbitrary data

### ISSUE THREAD

**Issue by christopher-wilson** [danpros/htmly#258]
I'm setting this up, and in the posts, it gives the username. I can call my full name using `user()` but would it be possible to retrieve arbitrary data using the same `$p->field` syntax?

Maybe creating a Post Class so we have access to __get()? Would this be helpful?

**Comment by danpros** [comment]
Yes possible but need to add it on the core.

**Comment by jduerr** [comment]
how could i add a custom $->field in the core?

Is it possible i.e. to add some  kind of data in the Markdown file of a post and than have it processed via the theme php code?

**Comment by christopher-wilson** [comment]
@jduerr I don't know if it is possible with HTMLy, but I do know other platforms have metadata in a markdown files header.

**Comment by danpros** [comment]
Well at the moments we already have:

```
$author->url
$author->name
$author->bio
```

I will close this one. Thanks.
