### ISSUE TITLE
Admin Theming

### ISSUE THREAD

**Issue by christopher-wilson** [danpros/htmly#259]
It doesn't seem to be possible. Changing the admin area seems to requires altering the CSS/JS/etc, but no way to switch like there is in the front end.

I would like to make changes to the admin theme on my blog, and a similar system to the front-end would be user friendly, and consistent. It would also mean that we can package admin themes for other users.

**Comment by danpros** [comment]
Yes currently is not possible.

**Comment by danpros** [comment]
Please check the latest commit, we revamping the admin panel.
