### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by mklenke** [danpros/htmly#260]
Hi! I tried to change the english months-names to their german equivalents, e.g. March -> März and also the time representation, etc. For that, I edited the file _jquery-ui.min.js_ in directory _/web/system/resources/js/_
Short snippet as example:
`monthNames:["Januar","Februar","M&auml;rz","April","Mai","Juni","Juli","August","September","Oktober","November","Dezember"]`
Unfortunately no effect on the frontend (caches cleaned). Any idea? Any documentation on localization?

**Comment by mklenke** [comment]
Sorry, just found [https://github.com/danpros/htmly/issues/134](url) I would strongly support this ticket! But for now, it would be nice to have a quick (& maybe dirty) solution...

**Comment by RalfZim** [comment]
My pull request #317 also addresses this issue.

**Comment by danpros** [comment]
This fixed.
