### ISSUE TITLE
author.info = false not removing author info from page

### ISSUE THREAD

**Issue by Unwyn** [danpros/htmly#261]
On this page:

http://www.lxndr.com/post/test

I have author.info = "false"  which, it seems, SHOULD make the author info not show up on a particular post.  but nope, my entire author info is sprawled out on that entire page.  

How do I make it so that there's only a link to my author info and no info on that page?

**Comment by jaidenmedia** [comment]
You'll probably have to hard code the link into the post.html.php file.

**Comment by Unwyn** [comment]
So what's the purpose of this official setting?

**Comment by jaidenmedia** [comment]
I don't know. I went back to WordPress as it seems danpros has lost interest in this project.

**Comment by danpros** [comment]
That options only work on old theme version like Logs.

You need to modify the theme by yourself to meet what you needs.

>  lost interest in this project.

It already stable enough so not planning to release new version for a while.

**Comment by Unwyn** [comment]
Huh.  My bad, I thought I had whatever the default theme is.  And you'd think the option would work on the default?

Sorry!

**Comment by danpros** [comment]
@Unwyn that deprecated options actually :smile: 

HTMLy theming is so simple you can modify it as you wish. My concern from now is the stability, performance, and compatibility (seems OK for now). And current version already support PHP 7.

**Comment by jaidenmedia** [comment]
> It already stable enough so not planning to release new version for a while.

Yeah, we know. At least port some not-so-ugly themes in the meantime. You seem to like WordPress stuff, so look here: [Anders Noren](http://www.andersnoren.se/teman/). I recommend Lingonberry, Rams, Hoffman and Iwata. Beautiful, simple themes. More people would use HTMLy if you gave them more theming options. I also suggest you upgrade the admin area. See the [Bludit](https://github.com/dignajar/bludit) project for ideas.

Oh and please don't tell me to port themes myself. If I knew how to do that, I would.

**Comment by danpros** [comment]
@jaidenmedia I will considering to port those themes.

**Comment by Unwyn** [comment]
Can anyone help me on what steps I need to do to make sure author info doesn't show up on my pages? I can't seem to decipher the referenced "post.html.php" file.

**Comment by Anakinmi** [comment]
@Unwyn I'm using the Ignite theme, but I think this applies to all themes:

In post.html.php post the following two lines AROUND ```div class="author-meta"```

which should check your configuration for input in the config-page:

    <?php if (config('author.info') != "false"):?>
    <?php endif; ?>

I tested it on my site, for me it works. Please note that you have to input "false" EXACTLY like that, no spaces or uppercase, etc.
