### ISSUE TITLE
page not found 404. But second time requesting the page it get's 200

### ISSUE THREAD

**Issue by Kanti** [danpros/htmly#262]
if you request a not valid uri on htmly say http://kanti.de/cinema123456 that clearly is not a valid page
the first time anybody requests this uri the response has a 404 HTTP Status code.
But the second time the request has a 200 HTTP Status code.

@danpros I have no time to look into that, maybe you could fix this

**Comment by danpros** [comment]
Ah its seems because of those 404 page has been cached for logout users.

**Comment by danpros** [comment]
Fixed
