### ISSUE TITLE
Using widget functions in another folder

### ISSUE THREAD

**Issue by bengalli** [danpros/htmly#263]
Hello all,
In my website, htmly working in /blog folder. And i have another folders/html files outside htmly platform. Like this;
www.domain.com/folder a
www.domain.com/blog (installed htmly)
www.domain.com/folder b
...

If you want to check web site : www.contrastegitim.com

I am trying to show recent blog posts list/links in a html file in folder a. I tried php include etc. for recent post widget. But i can not do it, my php knowledge is not excellent :(

How can i do it? Is it possible? Can you give me example code.

Thank you very much for your help.

**Comment by danpros** [comment]
Well you can use jQuery to read the blog feed, example http://www.htmlgoodies.com/beyond/javascript/stips/displaying-feed-content-using-jquery.html

**Comment by bengalli** [comment]
Thank you very much. I will try this...
