### ISSUE TITLE
Softaculous Install Not Working Correctly

### ISSUE THREAD

**Issue by briankb** [danpros/htmly#264]
I've run this install via softaculous and it does not work. The files and folders seem to be there (see screenshot) but when you try to visit any of the pages they are forbidden or not found. I assume this is a permission error. 

robots.txt is a 404 (not found)
humans.txt is a 404 (not found)
index.php is a 403 (forbidden)
upload.php is a 403 (forbidden)

all of these files have file permissions set to 0644 after the softaculous script was finished.

**Any help in resolving this issue would be appreciated.**

![nslh-cpanel-htmly-install-script-installed](https://cloud.githubusercontent.com/assets/394215/15335847/ebd0f062-1c41-11e6-887f-11a34b8e5ce8.png)

![nslh-cpanel-htmly-installed-filelist](https://cloud.githubusercontent.com/assets/394215/15335852/f0969066-1c41-11e6-922f-f32e404abcc5.png)

**Comment by danpros** [comment]
Can you find the .htaccess file? if not try to creating one and copy paste the HTMLy default htaccess.

**Comment by danpros** [comment]
Seems because of missing the htaccess file.
