### ISSUE TITLE
CSRF Token not correct

### ISSUE THREAD

**Issue by boniatillo-com** [danpros/htmly#265]
Hi,

My blog was working fine until yesterday, that it is showing a `CSRF Token not correct` error message when I attempt to login.

I was changing the .htaccess files but I restored to the defaults and yet I get that error.

Please any tip can help me!

(by the way, I love htmly, this is my website: http://phasereditor.boniatillo.com/blog)

**Comment by boniatillo-com** [comment]
A workaround is welcome too, maybe to disable the CSRF validation or something.

**Comment by danpros** [comment]
Do you enable the repatcha? 

```
google.reCaptcha = "false"
```

**Comment by boniatillo-com** [comment]
No, it is set to false:

`google.reCaptcha = "false"`

I was looking into the code and maybe it has to be with the session expiration time.

the .htaccess files can change the expiration time? Other website I have installed there is giving to me session timeout just after login it. Maybe the problem is going there.

Right now I am 99% convinced it is  a problem of the web server and not htmly configuration :(

Thanks for your fast response!

**Comment by danpros** [comment]
> Thanks for your fast response!

You're welcome.

BTW you have a great project there, good luck  :)
