### ISSUE TITLE
Ignite theme menu link isse

### ISSUE THREAD

**Issue by ramonskovitch** [danpros/htmly#266]
I am using the ignite theme. I have set a menu item in config.ini at blog.menu. I have a static front page.

If i do a full cache clear and click my menu item on the top row, I get the correct static page.

However, if I first click a post on "Recent Posts" and then use the menu item again I get a "page not found error". 

From the URL I can see its looking for the wrong location:

1st time URL: http://mysite.com/htmly/my-static-page (correct)

then after first going to a recent post and then the menu item:

2nd time: http://mysite.com/htmly/2016/05/my-static-page (which causes the error).

same issue occurs if I come from the Tags or categories on the right hand sub menu.

Any help appreciated

Dan

**Comment by danpros** [comment]
Do you create the content using the admin panel or upload it manually? the static content will not available on this URL `http://mysite.com/htmly/2016/05/my-static-page`, the static page URL tipe is `www.example.com/my-static-page`

Are you sure the mod_rewrite module enabled in your server?

**Comment by ramonskovitch** [comment]
Dan,

I use the admin panel. issue is that if I am in a static page  and click
the top menu item it generates the correct URL and goes to the other static
page. However, if I view ,say, a blog post or a recent post THEN click the
menu item, it then gives the page not found error and i can see the URL is
wrong as you have said above: http://mysite.com/htmly/2016/05/my-static-page
,

I will check mod_rewrite settings

Thanks
Dan Raymond

Level 19 Waterfront Place, 1 Eagle Street Brisbane Qld 4000 Australia
Mail:   PO Box 7815 Waterfront Place, Brisbane 4001
Tel:    +61 733 600 255
Mob:  +61 400 551 920
Fax:   +61 733 600 222
Web:  http://ecourban.com.au

**Comment by danpros** [comment]
I will close this. Please re-open if this error not resolved yet.
