### ISSUE TITLE
[Feature Request] Move the html rendered by the head_contents() function

### ISSUE THREAD

**Issue by ColonelBlimp** [danpros/htmly#269]
Hi,
I've just started to use HTMLy - much appreciate all the good work done.

Could I request that the html contained within the `head_contents()` function be placed into a separate template file (e.g. head.html.php) so that the tags can be easily modified?  For instance, I wanted to remove the
`<meta http-equiv="X-UA-Compatible" content="IE=edge" />`
from the head, but keep some of the other tags.  I did not want to modify the code as I suspect it might be overwritten when upgrading to the next version.

**Comment by danpros** [comment]
Good idea, so we have a fall back, if no head.html.php we can use the default. Planning this in the next release. Or you can creating pull request :smile:

**Comment by ColonelBlimp** [comment]
Thanks.  Let me see what I can do on a pull request - php is not a language I have done a lot of work with.

**Comment by danpros** [comment]
This issue is too old, I will close this one. Please create new issue for possible improvements. Thanks
