### ISSUE TITLE
URL form // plugin

### ISSUE THREAD

**Issue by CiprianStoicescu** [danpros/htmly#270]
You do a good job with the Htmly. I have some questions.
There is a collection of plugins are valid? And how can I change form one link. Example:
**domain dot com/04/2016/article-post** to Exchange **domain dot com/article-post**

**Comment by danpros** [comment]
Instead the default permalink, currently htmly only support `example.com/post/slug`. Let see for the next release.

**Comment by cipriiulian98** [comment]
Oh, ok . Thank you for the reply. Why not make a page for support in Gitter for live support?

**Comment by danpros** [comment]
This planned but no timeframe. I will close this one. Thanks,
