### ISSUE TITLE
Static page named "search"

### ISSUE THREAD

**Issue by tacojones** [danpros/htmly#271]
If you make a static page named "search" you will be unable to edit or delete it.

**Comment by danpros** [comment]
This slug used by search page result but yes we need to improve it.

**Comment by tacojones** [comment]
Just wanted to say, wonderful job on HTMLy, guys. It's awesome. Thanks very much.

**Comment by danpros** [comment]
@tacojones credit to the contributors also :smile:

**Comment by danpros** [comment]
This is expected because it used by `/search/` slug. I will close this one. Thanks.
