### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by zh-wowtv** [danpros/htmly#272]
I think it would be nice if the following features added:

1. Featured video, audio with html video, audio tag
2. Plugin to upload audio, video, image

Thanks.

**Comment by danpros** [comment]
For featured video etc. you can creating "featured" tag and than use get_tag functions (read the docs).

Indeed you can't upload audio or video yet.

**Comment by zh-wowtv** [comment]
Thanks for your reply. I'll go through the document.

Why can't upload audio and video?

**Comment by danpros** [comment]
> Why can't upload audio and video? 

Because this features not available yet.

**Comment by zh-wowtv** [comment]
@danpros I see. I though you said it's not possible. Thanks anyway.
