### ISSUE TITLE
Bulk edit category and tag features

### ISSUE THREAD

**Issue by mcdoyaji** [danpros/htmly#274]
Bulk edit category and tag features needed

**Comment by dbYoung** [comment]
OK. category bulk edit possible.

just move article files to another category forlder.

![_282](https://cloud.githubusercontent.com/assets/11155414/16892320/ffda1ebc-4b49-11e6-81ce-978d72aa1d87.png)

then, how could i change tags???

**Comment by danpros** [comment]
> then, how could i change tags???

Not possible for this time and need additional programming to change the tags in bulk since it hardcoded to the filename. We need to improve the admin panel for sure.
