### ISSUE TITLE
Poem not displaying correctly

### ISSUE THREAD

**Issue by mstuckless** [danpros/htmly#275]
Hi there,

When I enter a poem with say 4 lines and 4 stanzas it looks fine on the edit page.  But when I publish it, the 4 individual lines become two or three with no break after each line.

So when I enter this:

Oh Lord of the New Year, use me I pray, 
I give this new year unto Thee. 
It is yours, see me through, give me power anew, 
To be what you want me to be.

I get this on the blog:

Oh Lord of the New Year, use me I pray, I give this new year unto Thee. It is yours, see me through, give me power anew, To be what you want me to be.

How can this be fixed?

Thanks,

Mark

**Comment by danpros** [comment]
Yes I can considering it as bug. For the mean while you can use the `<br>` tag to creating new line.

**Comment by mstuckless** [comment]
Thank you, I will try that.

**Comment by Snip1** [comment]
It is probably a markdown render bug, btw.  I am on Ello, and it happens there quite a lot as well.

**Comment by fugo** [comment]
I tried it with `<br>` but this also not worked, also 2 empty space on the end or a empty line

**Comment by Libralop** [comment]
To create a line break (<br> tag) with Markdown, place two whitespaces at the end of the line.

But: It would be fantastic if this would work without whitespaces.

**Comment by danpros** [comment]
Its from markdown behavior. I will close this one. Thanks.
