### ISSUE TITLE
new bikintheme request

### ISSUE THREAD

**Issue by maulvi** [danpros/htmly#280]
Can we have this theme bang 
https://bikinwebsite.com/bikin-website-13-free-magazine-wordpress-theme/
or this 
https://bikinwebsite.com/bikin-website-09-blog-news-wordpress-theme/

**Comment by danpros** [comment]
Nice clean theme :+1:

**Comment by danpros** [comment]
This issue is too old, I will close this one. Please create new issue for possible improvements. Thanks
