### ISSUE TITLE
Not an issue, but...

### ISSUE THREAD

**Issue by Snip1** [danpros/htmly#281]
Can someone 'document' for me how to add og: and twitter: metatags to the blogging system?  I am sure it has to do with the admin>config area for starters, and then some sort of integration into the actual template pages, but atm I don't know how to start or what to do.  Any clues would be greatly appreciated!

BTW: You can see where I am at so far as regards integration at [h2only.ca/blog](http://h2only.ca/blog/).  It has been an enjoyable experience.  Thanks for having HTMLy out there!

**Comment by danpros** [comment]
Well you can use existing variable:

The page title
```
<?php echo $title; ?>
```

The page URL:
```
<?php echo $canonical; ?>
```

The descriptions:

```
<?php echo $description; ?>
```

See the docs for more https://docs.htmly.com/theming/2-variables

**Comment by Snip1** [comment]
I'll see what I can do with that... I've already been there, but maybe I missed something or don't understand what you are showing me (likely)... 
 I need something like this:

`<meta name="twitter:title" content="TITLE OF POST OR PAGE">
<meta name="twitter:description" content="DESCRIPTION OF PAGE CONTENT">
<meta name="twitter:image" content="LINK TO IMAGE">
<meta name="twitter:site" content="@USERNAME">
<meta name="twitter:creator" content="@USERNAME">`

I can see where your answer above will get me most of the way, but where/how do I create the "twitter:image" tag, for instance... and most importantly of all, where do I put these?  Ideally, of course, they auto-populate, so I don't have to do them during the post creation phase (so into the head includes I already have) but which ones?

**Comment by Snip1** [comment]
Ahhhh... getting closer!

From the variables list: something along the lines of <?php echo $p->image; ?>, so:

<meta name="twitter:image" content="<?php echo $p->image; ?>">

OK... I'll be able to hack that together.

But where does it go?  My main 'head' include (sitewide) or somewhere specific within the HTMLy file system?

**Comment by jaidenmedia** [comment]
This is what I used:

<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@twitter_handle">
<meta name="twitter:title" content="<?php echo $p->title; ?>">
<meta name="twitter:description" content="<?php echo $description; ?>">
<meta name="twitter:creator" content="@twitter_handle">

<meta name="twitter:image:src" content="<?php echo $p->image; ?>" /">

Put this code in the layout.html.php of your theme. It should be placed above the closing head tag. Replace "twitter_handle" with your own Twitter username.  You may need to allow Twitter bot in your robots.txt file.

**Comment by Snip1** [comment]
OK… I guess I spoke a tad too soon when I said I’d hack this together.  Not quite getting there.  
  
So this is where I am at:  

In an .md file (created via the admin interface) I have this: 
 
  
`



<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content=“@h2only” />
<meta name="twitter:title" content="<?php echo $title;?>" />
<meta name="twitter:description" content="<?php echo $description; ?>" />
<meta name="twitter:image" content="<?php echo $image; ?>" />
  `
	 

 When visiting [this URL](http://h2only.ca/blog/2016/08/dont-recycle-replace) (which will resolve the .md snippet above) I get this: 

`
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content=“@h2only” />
<meta name="twitter:title" content="Don&#039;t recycle - replace! - H2Only Blog" />
<meta name="twitter:description" content="There&#039;s a much better way than 500ml bottles." />
<meta name="twitter:image" content="" />
` 
	  
As you see, the image meta returns no value.  

Where’d I go wrong?

**Comment by jaidenmedia** [comment]
`<meta name="twitter:image:src" content="<?php echo $p->image; ?>" /">`

Make sure you allow Twitter bot in robots.txt

**Comment by Snip1** [comment]
**YES!!** It worked: passed the Twitter card validator!

I had tried the `$p->image`, but without success... it was the :src that was missing.  Where is *that* documented?

Thanks, jaidenmedia... happy man now ;)
