### ISSUE TITLE
Disable Blog Logic

### ISSUE THREAD

**Issue by frankred** [danpros/htmly#283]
Is it possible to completely disable the blog feature? So that things in the frontend like "RECENT POSTS" or "ARCHIVE", "TAGS" disappear?

BTW: I <3 htmly

**Comment by danpros** [comment]
Thanks, you can remove it manually from the template. Available widget: https://docs.htmly.com/theming/4-widget

**Comment by danpros** [comment]
Note: you can use static frontpage also for it. Read the options here https://github.com/danpros/htmly/blob/master/config/config.ini.example

**Comment by frankred** [comment]
Thanks a lot for your help! Maybe it would be nice to have every template in a "static " and in a "blog" version.

**Comment by frankred** [comment]
I can contribute it, if you say ok that makes sense !

**Comment by danpros** [comment]
You can modify this theme, no widget added https://github.com/danpros/htmly-vapor
