### ISSUE TITLE
Theme request

### ISSUE THREAD

**Issue by CiprianStoicescu** [danpros/htmly#284]
Hi, I'm trying to adapt a theme for htmly but I never succeeded. The content was not rendered, and other problems. Can you help me please to adapt a theme for my new site? This is the theme 

https://freehtml5.co/lesser-free-html5-bootstrap-template/

sorry to bother you, thanks!

**Comment by danpros** [comment]
Well that's nice theme actually 👍

**Comment by kazu2012** [comment]
How about Twenty Seventeen on WordPress?

**Comment by danpros** [comment]
This issue is too old, I will close this one. Please create new issue for possible improvements. Thanks
