### ISSUE TITLE
Не могу войти в админ панель.

### ISSUE THREAD

**Issue by VladimirGoncharenko** [danpros/htmly#285]
Здравствуйте.
Не могу войти в админ панель.
Пишетт - Username not found in our record.
http://сайт/login
логин-admin
пароль-admin
Что делаю неправильно?

Hello.
I can not access the admin panel.
Writes - Username not found in our record.
http: // website / login
login-admin
Password-admin
What I doing wrong?

file username.ini

;Password
password = admin
encryption = clear
; encryption: not set, leave blank or set to clear or none to use plain text password for the user,
; else set to encryption algoritm supported by hash function of php to use the selected
; encryption
;Role
role = admin

Спасибо.
Thank you.

**Comment by ncang** [comment]
do you change username.ini to "your user name".ini eg

vladirmir.ini

password = admin
role = admin

?

2016/09/22 22:59 GMT + 07: 00 VladimirGoncharenko < notifications@github.com
