### ISSUE TITLE
Search function enhancement

### ISSUE THREAD

**Issue by nickbe** [danpros/htmly#288]
Would it be possible to enhance the search function, so that it searches not only title and tags but also the contents? (Maybe have a switch: search.extend = true|false)

Also it would be more easy to handle tags if there would be a tag cloud|list from which to select the tags for a new post. That way you prevent typos.

**Comment by danpros** [comment]
Will try to enable this feature in future release. It should disable by default.

**Comment by nickbe** [comment]
Thanks :)

**Comment by badstue** [comment]
Any updates on this one? Would be great to see tags already used in other posts. So we dont add variants but use already added instead.
