### ISSUE TITLE
Allow authors access on a per category basis

### ISSUE THREAD

**Issue by nickbe** [danpros/htmly#289]
Having a small community of authors for support texts also means I don't want everyone writing posts in every category.

So being able to allow category access per user (for non admins) as "Reader" or "Author" would be great!

**Comment by danpros** [comment]
This is good idea, we just need to tweak some of the codes.

**Comment by nickbe** [comment]
Great. I'm happy you like the idea. Managing a community of authors with distinct fields of interest or reading rights will be super easy with this. :)

**Comment by danpros** [comment]
This issue is too old, I will close this one. Please create new issue for possible improvements. Thanks
