### ISSUE TITLE
How to add Telegram Font Awesome

### ISSUE THREAD

**Issue by marcosrocha101** [danpros/htmly#294]
How to add Font Awesome telgram to htmly layout ?

**Comment by fugo** [comment]
Go to the fontawsome site [fontawesome.io/get-started/](http://fontawesome.io/get-started/) put your email in the field to get the code.
You will shortly get a mail with a code like this `<script src="https://use.fontawesome.com/123x34xyz12.js"></script>` (this code is **not** working)
Put this code in your theme file (layout.html.php) near to  `</head>`. 

`## Test it <i class="fa fa-telegram"></i>`

**Comment by marcosrocha101** [comment]
Muito obrigado, acabei usando o 
fa-paper-plane, e deu certo muito obrigado  brother.

**Comment by fugo** [comment]
De Nada! :+1: 
If you like it colorful and a bit bigger (`fa-lg`):smile: 
`<span class="fa-stack fa-lg"><i style="color:steelblue;" class="fa fa-circle fa-stack-2x"></i><i class="fa fa-paper-plane fa-stack-1x fa-inverse"></i></span>Telegram`

The black one is the normal size:
![icon telegram](https://3.downloader.disk.yandex.com/disk/1af406b6249340104a8bf993f4613d62b376f405c8bf8fc131de0b9375331b93/586264f6/Dt2dEFre5oDcFcKTccwbl5fEQFJQtygj_kP5T0cmLncd6ZkeNx8o7SlazAbUWr1nN0yXFEA1_rKrEthv-34XOw%3D%3D?uid=0&filename=fa_icon_telegram.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=7127&hid=1623ecc971e3b7300f767fe6a95c353f&media_type=image&tknv=v2&etag=bed43b267493337acec3e34ab036f040)

**Comment by danpros** [comment]
Thanks @fugo 

I will close this one.
