### ISSUE TITLE
request - custom breadcrumb

### ISSUE THREAD

**Issue by morrow95** [danpros/htmly#296]
Would like to see the ability to create a custom breadcrumb similar to the other widgets.  I would like to have access to an array variable that has each title/link of the current hierarchy of the page.  Few reasons for this : 

1 - I don't want to use http://rdf.data-vocabulary.org/# that is built in, but would rather use schema.org which uses a completely different structure.

2 - The default breadcrumb does not show a link for the last link / current link you are on.  I'm not sure if this is by design or what, but that link should be available.  For example, "Blog » Test » some test post" by default will have links for the first two and not the current "some test post by"... this should be linked for proper breadcrumb markup.

3 - Would allow more freedom with styling such as using <ol>...<li>something</li>...</ol> rather than the default div/span method.

If we had access to an array of the breadcrumb hierarchy this would let us do whatever we want with it and would solve both of the issues above.  This should be a 'widget' just like the others at https://docs.htmly.com/theming/4-widget.

I haven't looked at the code in awhile (probably well over a year) and I am using an older version which I made lots of modifications to, but at that time the breadcrumbs were hardcoded in and it was not a fun

**Comment by danpros** [comment]
I will use schema.org for the next maintenance release.

**Comment by danpros** [comment]
Fixed
