### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by k1ngf15h3r** [danpros/htmly#302]
Hi guys, I tried a lot but could not install htmly with current release on my server. I use nginx with php7 and used your nginx conf from the docs. Only thing I see when connecting to installer.php is that I would be redirected. Also tried zip and tar.gz archives but tar and unzip are not able to extract the archives. Can you help me to get htmly running?

**Comment by k1ngf15h3r** [comment]
Installed apache2 with php7 on my local linux system and had no problem. Maybe nginx related issue?

**Comment by danpros** [comment]
The docs: https://docs.htmly.com/web-servers/nginx
