### ISSUE TITLE
Is there a way to justify texts?

### ISSUE THREAD

**Issue by n00b12345** [danpros/htmly#307]
All my posts are left aligned by default. Can I justify the text alignment?

Thanks.

**Comment by FakePlasticBees** [comment]
The alignment is done via a style sheet (css) and depends on the template you use.  One way to change that is to find the p element in style.css and add (or adjust) text-align:justify.

```
p {
  text-align: justify;
}
```

**Comment by n00b12345** [comment]
Thanks so much :)
