### ISSUE TITLE
search not working?

### ISSUE THREAD

**Issue by ragnar76** [danpros/htmly#309]
All i get is a "Search results not found!" no matter what i'm searching for

**Comment by ncang** [comment]
currently HTMLy doesn't have full text search, limited (title, tag).
example, 

- http://bkhome.org/news/search/test
- http://bkhome.org/news/search/admin
- http://bkhome.org/news/search/reading (not found)

**Comment by bkauler** [comment]
Thanks for the info!

**Comment by danpros** [comment]
I will close this one
