### ISSUE TITLE
Can't make image posts

### ISSUE THREAD

**Issue by abugambo** [danpros/htmly#310]
Hi,
I noticed this problem yesterday. From the "add content" page, clicking on every content type opens the page to let me add content except for the "Image post" content type. If I click on it, the browser will keep trying to load the page without any success until it times out.  I tried it on different browsers and have cleared the cache but the problem persists.

What could be causing this issue?

**Comment by abugambo** [comment]
Appears like my problem is not from the server side. It worked when I connected to the Internet using a different router.

**Comment by ncang** [comment]
Nice work, glad to hear that 🙋
