### ISSUE TITLE
Links not working after upload.

### ISSUE THREAD

**Issue by abugambo** [danpros/htmly#312]
On my development system I have the site within a subfolder of the web root folder e.g /mysite.
But I uploaded it to the web root of my hosting server /.
I edited the image image paths in the markdown files and removed 'mysite' from their url which works fine on images displayed on the home page. But clicking on a post links doesn't take one to the post but shows the "page does not exist" page.
It's like the old url for posts is stored somewhere that I cannot find. I checked the markdown files of the posts but couldn't find any path information.

How do I get post urls to work on the live server?

**Comment by CodeAlDente** [comment]
Did you check the record `site.url` in your ~/config/config.ini ?
