### ISSUE TITLE
If i edit content i have 1970 year in my posts.

### ISSUE THREAD

**Issue by nothingmsr** [danpros/htmly#313]
Hello, many thanks for your script.

If I make any changes to the post, I get that the date for 01-01-1970 changes in the record.
And such an error in the logs of php.

Uncaught exception 'Exception' with message 'DateTime::__construct() $time = new DateTime($t);

I ask for your help, thank you.

**Comment by CodeAlDente** [comment]
Your report is a few weeks old. Do you still face this issue? Which version of htmly do you use?

**Comment by danpros** [comment]
No response, seems fixed.
