### ISSUE TITLE
A private blog option

### ISSUE THREAD

**Issue by n00b12345** [danpros/htmly#314]
An option in the settings to make a blog private, asking the user to enter username and password to access it, would really be great.

Please consider having this.

**Comment by CodeAlDente** [comment]
Why not using http authorization via .htaccess?

**Comment by n00b12345** [comment]
I already do that. Like I mentioned in the other issue, for some weird reason Fail2ban is giving me some trouble with htaccess. That's why I asked if a private blog option could be enabled. 

You're very kind, thank you so much for helping.

**Comment by CodeAlDente** [comment]
Alright, let us see if we can fix the issue with the Fail2Ban block so you can continue to use this option.
