### ISSUE TITLE
For some reason, Fail2Ban, always blocks HTMLy login attempts

### ISSUE THREAD

**Issue by n00b12345** [danpros/htmly#318]
Whenever I try connecting remotely to my blog, (I use .htaccess to protect it) even after I enter the correct password, my attempt gets counted as a wrong attempt to log in. 

This happens only with HTMLy, and not with other software I use on my server. Is there anything specific within HTMLy that does this?

**Comment by CodeAlDente** [comment]
It sounds more like a misconfiguration in your filters. Could you please provide us with them?

**Comment by n00b12345** [comment]
@CodeAlDente thank you *so* much for helping. I really appreciate it. 

Everything is set as default and the apache configure in jail.local (which I use for configuration of fail2ban) is this:

[apache]

enabled  = true
port     = http,https
filter   = apache-auth
logpath  = /var/log/apache*/*error.log
maxretry = 2
bantime = -1
banaction = iptables-allports

**Comment by CodeAlDente** [comment]
Thank you.

I assume you are using the original filter `apache-auth` which can be found here: https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/apache-auth.conf

Could you please provide the following information in order to check this:

- matching lines from your error.log (feel free to mask your ip-address)
- your fail2ban logfile

According to http://stuffphilwrites.com/2013/03/permanently-ban-repeat-offenders-fail2ban/ , you may change your `bantime` to something like `31536000` (1 year) which is more practical than a "forever ban".

**Comment by n00b12345** [comment]
This is the output of /var/log/fail2ban.log

    2017-05-28 08:16:18,339 fail2ban.jail   [1324]: INFO    Jail 'apache' started
    2017-05-28 09:43:00,072 fail2ban.actions[1324]: WARNING [apache] Ban x.x.x.x


This is the output of /var/log/apache2/error.log

    [Sun May 28 09:42:54.091041 2017] [access_compat:error] [pid 1282] [client x.x.x.x:44014] AH01797: client denied by server configuration: /var/www/html/blog/
    [Sun May 28 09:42:59.714891 2017] [access_compat:error] [pid 1281] [client x.x.x.x:20011] AH01797: client denied by server configuration: /var/www/html/blog/
    [Sun May 28 09:42:59.728045 2017] [access_compat:error] [pid 1281] [client x.x.x.x:20011] AH01797: client denied by server configuration: /var/www/html/blog/index.php

/etc/fail2ban/filters.d/apache-auth.conf is untouched and is exactly the same as https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/apache-auth.conf

This is the content of /usr/bin/fail2ban-regex


        # Add the default logging handler
        stdout = logging.StreamHandler(sys.stdout)

        fmt = 'D: %(message)s'

        if opts.log_traceback:
                Formatter = FormatterWithTraceBack
                fmt = (opts.full_traceback and ' %(tb)s' or ' %(tbc)s') + fmt
        else:
                Formatter = logging.Formatter

        # Custom log format for the verbose tests runs
        if opts.verbose > 1: # pragma: no cover
                stdout.setFormatter(Formatter(' %(asctime)-15s %(thread)s' + fmt))
        else: # pragma: no cover
                # just prefix with the space
                stdout.setFormatter(Formatter(fmt))
        logSys.addHandler(stdout)

        print
        print "Running tests"
        print "============="
        print

        cmd_log, cmd_regex = args[:2]

        if len(args) == 3:
                fail2banRegex.readRegex(args[2], 'ignore') or sys.exit(-1)

        fail2banRegex.readRegex(cmd_regex, 'fail') or sys.exit(-1)

        if os.path.isfile(cmd_log):
                try:
                        hdlr = open(cmd_log)
                        print "Use         log file : %s" % cmd_log
                        test_lines = hdlr # Iterable
                except IOError, e:
                        print e
                        sys.exit(-1)
        else:
                print "Use      single line : %s" % shortstr(cmd_log)
                test_lines = [ cmd_log ]
        print

        fail2banRegex.process(test_lines)

        fail2banRegex.printStats() or sys.exit(-1)

**Comment by CodeAlDente** [comment]
Thank you.

Both logfiles look good as expected. The reason for the ban is that your request itself has been denied ("denied by server configuration") due to your server configuration, see https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/apache-auth.conf#L17

Could you provide the content of your .htaccess please?

And you can remove everything below your line "This is the content of /usr/bin/fail2ban-regex" as we do not need the content but the actual output when you run the following command:

`/usr/bin/fail2ban-regex /var/log/apache*/*error.log /etc/fail2ban/filters.d/apache-auth.conf`

**Comment by n00b12345** [comment]
This is what my my edited .htaccess looks like. These are the first few lines. The rest is the same as https://github.com/danpros/htmly/blob/master/.htaccess

I have allowed access for certain IPs on my local network.

    AuthUserFile /home/user/.htpasswd
    AuthType Basic
    AuthName "My Secret Folder"
    Require valid-user
    Order Deny,Allow
    Deny from all
    Allow from 192.168.1.2
    Allow from 192.168.1.3
    Allow from 192.168.1.4
    Allow from 192.168.1.5
    Satisfy Any

And this is the output of /usr/bin/fail2ban-regex /var/log/apache*/*error.log /etc/fail2ban/filters.d/apache-auth.conf

Running tests
=============

Use   failregex line : /etc/fail2ban/filters.d/apache-auth.conf
Traceback` (most recent call last):
  File "/usr/bin/fail2ban-regex", line 430, in <module>
    fail2banRegex.readRegex(cmd_regex, 'fail') or sys.exit(-1)
  File "/usr/bin/fail2ban-regex", line 227, in readRegex
    'add%sRegex' % regextype.title())(regex.getFailRegex())
  File "/usr/share/fail2ban/server/filter.py", line 95, in addFailRegex
    raise e
server.failregex.RegexException: No 'host' group in '/etc/fail2ban/filters.d/apache-auth.conf'

**Comment by CodeAlDente** [comment]
Thank you.

I am so sorry. The command to run has a mistake. It should point to the "filter.d" folder and not to "filters.d" as this is my custom configuration at my local machine. Please run the command again on the "filter.d" folder as follows:

`/usr/bin/fail2ban-regex /var/log/apache*/*error.log /etc/fail2ban/filter.d/apache-auth.conf`

Make sure that you get banned by fail2ban before you run that command. In the output you should see the ip address that has been banned. Please confirm that it is none of the allowed ip addresses from your .htaccess file. In there you tell the webserver to block access from all ip-addresses (deny by all) except those listed below. That works good in most cases but you would probably run into problems if you using an IPv6 address (which is not listed in your .htaccess yet).

**Comment by n00b12345** [comment]
This is what I get when I run /usr/bin/fail2ban-regex /var/log/apache*/*error.log /etc/fail2ban/filter.d/apache-auth.conf

------------

Running tests
=============

Use   failregex file : /etc/fail2ban/filter.d/apache-auth.conf
Use         log file : /var/log/apache2/error.log


Results
=======

Failregex: 3 total
|-  #) [# of hits] regular expression
|   1) [2] ^\[[^]]*\] \[(:?error|\S+:\S+)\]( \[pid \d+(:\S+ \d+)?\])? \[client <HOST>(:\d{1,5})?\] (AH01797: )?client denied by server configuration: (uri )?\S*(, referer: \S+)?\s*$
|   2) [1] ^\[[^]]*\] \[(:?error|\S+:\S+)\]( \[pid \d+(:\S+ \d+)?\])? \[client <HOST>(:\d{1,5})?\] (AH01617: )?user .*? authentication failure for "\S*": Password Mismatch(, referer: \S+)?$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [19] WEEKDAY MONTH Day Hour:Minute:Second[.subsecond] Year
`-

Lines: 19 lines, 0 ignored, 3 matched, 16 missed
|- Missed line(s):
|  [Tue May 30 06:25:14.438449 2017] [auth_digest:notice] [pid 1269] AH01757: generating secret for digest authentication ...
|  [Tue May 30 06:25:14.712787 2017] [ssl:warn] [pid 1269] AH01906: 127.0.1.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
|  [Tue May 30 06:25:14.713076 2017] [ssl:warn] [pid 1269] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
|  [Tue May 30 06:25:14.718864 2017] [ssl:warn] [pid 1269] AH01909: o:443:0 server certificate does NOT include an ID which matches the server name
|  [Tue May 30 06:25:14.721724 2017] [mpm_prefork:notice] [pid 1269] AH00163: Apache/2.4.10 (Raspbian) OpenSSL/1.0.1t configured -- resuming normal operations
|  [Tue May 30 06:25:14.721863 2017] [core:notice] [pid 1269] AH00094: Command line: '/usr/sbin/apache2'
|  [Tue May 30 12:58:54.475858 2017] [mpm_prefork:notice] [pid 1269] AH00169: caught SIGTERM, shutting down
|  [Tue May 30 12:59:08.389809 2017] [ssl:warn] [pid 1189] AH01906: 127.0.1.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
|  [Tue May 30 12:59:08.391834 2017] [ssl:warn] [pid 1189] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
|  [Tue May 30 12:59:08.399920 2017] [ssl:warn] [pid 1189] AH01909: o:443:0 server certificate does NOT include an ID which matches the server name
|  [Tue May 30 12:59:08.659817 2017] [auth_digest:notice] [pid 1265] AH01757: generating secret for digest authentication ...
|  [Tue May 30 12:59:09.265110 2017] [ssl:warn] [pid 1265] AH01906: 127.0.1.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
|  [Tue May 30 12:59:09.265491 2017] [ssl:warn] [pid 1265] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
|  [Tue May 30 12:59:09.270381 2017] [ssl:warn] [pid 1265] AH01909: o:443:0 server certificate does NOT include an ID which matches the server name
|  [Tue May 30 12:59:09.300594 2017] [mpm_prefork:notice] [pid 1265] AH00163: Apache/2.4.10 (Raspbian) OpenSSL/1.0.1t configured -- resuming normal operations
|  [Tue May 30 12:59:09.300879 2017] [core:notice] [pid 1265] AH00094: Command line: '/usr/sbin/apache2'

-----------------

And this is in the log file of fail2ban (/var/log/fail2ban.log)

2017-05-30 13:21:52,174 fail2ban.actions[1519]: WARNING [apache] Ban x.x.x.x

**Comment by CodeAlDente** [comment]
Thank you.

Did you check the ip-address that has been banned (Ban x.x.x.x)? Is it listed in your .htaccess file (one of those 192.168.x)?

**Comment by n00b12345** [comment]
Yes, the IP address was indeed banned and it didn't include any of those in the .htaccess exceptions. 

The original issue persists, i.e. the IP address is banned even after entering the correct credentials for .htaccess

(Thank you again for responding. I really appreciate the help)
