### ISSUE TITLE
Can't use certain passwords for login

### ISSUE THREAD

**Issue by reinoldus** [danpros/htmly#321]
Hi,

I've installed the latest version (2.7.4) using the installer.php, but if I try to use this password: "erlkgjw§$$2434gt" without ", I can't login after logging out.

I have no time to investigate the issue further, but the app shows quite odd behaviour:

After a fresh install using the password from above the password is hashed using sha512, when I reset it to plaintext in order to login. The plaintext password gets hashed with (I assume) bcrypt.

Best Regards
Stefan

**Comment by CodeAlDente** [comment]
First of all, you are totally right. It should be allowed to use any desired password.

I guess the problem might be the dollar sign here. Could you please test it?

**Comment by CodeAlDente** [comment]
Seems like this issue only occurs using installer.php to set up htmly.

If you [change the password like described here](https://docs.htmly.com/tips-trick/change-password) everything works for me. I have tried this with the latest release (which is v2.7.4 at the moment).

**Comment by danpros** [comment]
Thanks, I will close this one.
