### ISSUE TITLE
Missing icons for jquery-ui

### ISSUE THREAD

**Issue by CodeAlDente** [danpros/htmly#322]
While I was creating a new post in the backend I found some error messages given by ~/system/resources/css/jquery-ui.css which could not be loaded. A quick view into that file clearly showed that they are not presented at all.

For example: https://github.com/danpros/htmly/blob/master/system/resources/css/jquery-ui.css#L856
	
I could solve this issue by putting the missing images ( you can find them here: https://github.com/julienw/jquery-trap-input/find/master ) into the ~/system/resources/images folder. By doing so, I also had to adjust the path to them in ~/system/resources/css/jquery-ui.css.

**Comment by danpros** [comment]
Hi,

Thanks. It should fixed in the latest master repo.
