### ISSUE TITLE
jQuery uploader does not work with Google's opt out addon for Analytics

### ISSUE THREAD

**Issue by CodeAlDente** [danpros/htmly#323]
If you are using the chrome extension [Google Analytics Opt-out Add-on](https://chrome.google.com/webstore/detail/google-analytics-opt-out/fllaojicojecljbmefodhfapmkghcbnh?hl=en) the jQuery uploader is no longer working for you as it adds the following to the response: 

> window["_gaUserPrefs"] = { ioo : function() { return true; } }

With this in the front, the check here: https://github.com/danpros/htmly/blob/master/system/admin/editor/js/editor.js#L46 does not work properly anymore.

I just do not understand why I am focusing this issue even while I do not use Google Analytics at all on my site. The analytics id is empty in the config file.

**Comment by CodeAlDente** [comment]
Alright, I found a quick and very, very dirty fix for this. But it works!

**1. Open ~/system/admin/editor/js/editor.js**

**2. Search for the following line (must be at L 45) ...**

```javascript
var uploadComplete = function(response) {        
```

**3. ... and place these following lines right under it:**
```javascript
/* dirty fix for output google analytics problem // start */
/* see: https://github.com/danpros/htmly/issues/323 */
var _gaUserPrefsStr = 'window["_gaUserPrefs"] = { ioo : function() { return true; } }';
if (response.indexOf( _gaUserPrefsStr ) != -1){
	response = response.replace( _gaUserPrefsStr, "");
	response = JSON.parse("[" + response + "]");
	response = response[0];
}        
/* dirty fix for output google analytics problem // end */
```

First, we define the Google Analytics stuff and we make sure, that the request (response) contains it before we even touch it. If this is the case, we replace the defined stuff with nothing. This results in deleting it. Now we convert the string into an object and assign the first block of it so the script can use it later on. Yay!

I have tested this and it works like a charm with the latest version (v2.7.4 at the moment). I hope this helps others as well.

**Comment by fahmi182** [comment]
Thanks! You can create patch and pull request.

**Comment by CodeAlDente** [comment]
I am not sure if we should add this to the main code as it is only a quick-and-dirty fix. What do you think?
