### ISSUE TITLE
avatar

### ISSUE THREAD

**Issue by Ricco-S** [danpros/htmly#327]
Hello is it possible to create a upload and change image field for a avatar that displayed in backend and display them also in frontend

Sorry iam just a beginer in php
so need help

**Comment by jsebean** [comment]
I am not quite sure what you're asking but if you're asking to have your avatar displayed on each blog post, consider using a custom key with the image url to your avatar and including it in your template files. Then you can easily change it on the config screen if you decide to change it.

**Comment by danpros** [comment]
You need to change the template manually. Thanks.
