### ISSUE TITLE
Simple Comment System

### ISSUE THREAD

**Issue by lightonflux** [danpros/htmly#33]
It would be great if htmly had a simple comment system so you don't have to depend on third parties. 

It should be plain text like the posts. I know thats not great for performance if you have many comments, but for small blogs it wouldn't matter.

**Comment by danpros** [comment]
After thinking it for some times we should just use third party comment system like Disqus or Facebook comment.

**Comment by HLFH** [comment]
...... so HTMLy is useless. Who cares about Disqus? If we want our own blog platform, we want also our own commenting system. If you are not able to support that idea, we are not able to support HTMLy. It's a critical issue. Please reopen.

**Comment by danpros** [comment]
@HLFH actually using partial we can print the comment form solely https://github.com/danpros/htmly/blob/master/system/includes/dispatch.php#L277

**Comment by ebookcode** [comment]
Keep it simple, if I want to use a full featured blog I will choose another one (like Wordpress). I like HTMLy because I can read and understand the code and it's simple to install, run and use. Any extra thing makes HTMLy more complicate is not necessary.

Again, I pick HTMLy from dozens ones because it's simple and just works.

**Comment by chrwick** [comment]
I also vote for simple comment system.
A good example for simple clean blog with a simple comment system is this one:
https://blog.thimbleweedpark.com/

**Comment by 5Hu** [comment]
I found this one: https://github.com/rosslagerwall/simplecommentsystem

The form works but I have problems getting the actual filename out of the HTMLy source code. That's important to read and write the comment file.

Maybe someone else can add this in HTMLy (and add comment counter and captcha :wink:)?

**Comment by danpros** [comment]
This issue is too old, I will close this one. Please create new issue for possible improvements to htmly.  Thanks.

**Comment by nightflasher** [comment]
> I found this one: https://github.com/rosslagerwall/simplecommentsystem
> 
> The form works but I have problems getting the actual filename out of the HTMLy source code. That's important to read and write the comment file.
> 
> Maybe someone else can add this in HTMLy (and add comment counter and captcha 😉)?

can you get the current URL and split it by "/"? all comments in a main subfolder with the url as html file for the comments?
