### ISSUE TITLE
Does HTMLy need to connect to the internet?

### ISSUE THREAD

**Issue by n00b12345** [danpros/htmly#331]
I ask because when trying to access HTMLy without an internet connection on a local network, the initial page loading is longer than when the local network is connected to the internet.

**Comment by jsebean** [comment]
Just quickly looking over the header of my own HTMLy blog, there are some google fonts that load in. I didn't look beyond that but that is one example of a resource that is attempting to load from the internet. The platform should function without the internet beyond things like that, so check your theme over, for example and remove/modify anything that does this if you don't want the endless loading bar when offline.

**Comment by danpros** [comment]
Thanks @jsebean 

I will close this one.
