### ISSUE TITLE
wrong category of  rss feed

### ISSUE THREAD

**Issue by achadidi** [danpros/htmly#333]
I have such categories as Poetry, Painting, Prose. In "admin/categories" it listed on russian, but
i use in "Url (optional)"  an english worlds, and in "/content/data/category" i have a same files: painting.md, poetry.md etc.  
 
![htmly-cat-normal](https://user-images.githubusercontent.com/29279030/27980197-d9303856-6384-11e7-88e3-1b7227ebe017.PNG)

But in rss feed i see wrong category, like Risunki instead of Painting,    

![htmly-cat-rss](https://user-images.githubusercontent.com/29279030/27980196-d92bb6dc-6384-11e7-9a9a-833037c63fbc.png)  

Rss categories are  translation of russian worlds, while the site uses english category names.
I tried to rename, but each time I see only the transliteration of the Russian word in the category name, but there is no such category in the system, er.404

Please tell me how to fix this problem for category Url names - it need be dont changed or translatable.

Thankful in advance, Anna

**Comment by danpros** [comment]
Hi,

This 6a3c968 should fix the issue.

Thanks,
