### ISSUE TITLE
Request: Recent comments

### ISSUE THREAD

**Issue by bkauler** [danpros/htmly#335]
Hi guys,
I installed HTMLy a couple of days ago, still evaluating it.
Quite a nice little blog. My site:

[http://bkhome.org/news/](http://bkhome.org/news/)

My previous blog was a derivative of PPLOG, a perl script. I was forced to disable comments, as someone went on the attack, posting comments with links to pornographic sites. We implemented various blocks, but that person used disposable email addresses.

Eventually, I gave up and disabled comments.

Comments via the Facebook plugin is OK, however, someone could still send spam comments. If they did so to older posts, how would we know? 

PPLOG has "Recents posts" as well as "Recent comments", so I was immediately able to see if anyone was making an inappropriate comment.

My feature request is, could we also have "Recent comments" on the blog sidebar?

**Comment by ncang** [comment]
i use disqus comment system,
"Recent comments" already on the blog sidebar

Have not tried yet fb comment
