### ISSUE TITLE
Usernames with (_) underscores.

### ISSUE THREAD

**Issue by shcleste** [danpros/htmly#336]
I used the installer to install the latest version 2.7.4 and chose a username ending in an underscore "abc_"
When creating the first test post the application dies.

    [Wed Aug 23 23:21:49.046093 2017] [:error] [pid 23304] [client 168.251.239.2:28047] PHP Notice:    Undefined offset: -3 in /var/www/html/system/includes/functions.php on line 267
    [Wed Aug 23 23:21:49.046134 2017] [:error] [pid 23304] [client 168.251.239.2:28047] PHP Notice:  Undefined offset: -1 in /var/www/html/system/includes/functions.php on line 268
    [Wed Aug 23 23:21:49.046144 2017] [:error] [pid 23304] [client 168.251.239.2:28047] PHP Notice:  Undefined offset: -1 in /var/www/html/system/includes/functions.php on line 275
    [Wed Aug 23 23:21:49.046153 2017] [:error] [pid 23304] [client 168.251.239.2:28047] PHP Notice:  Undefined offset: -1 in /var/www/html/system/includes/functions.php on line 283
    [Wed Aug 23 23:21:49.046439 2017] [:error] [pid 23304] [client 168.251.239.2:28047] PHP Fatal error:    Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (abc) at position 0 (b): The timezone could not be found in the database' in /var/www/html/system/includes/functions.php:293\nStack trace:\n#0 /var/www/html/system/includes/functions.php(293): DateTime->__construct('abc')\n#1 /var/www/html/system/htmly.php(72): get_posts(NULL, 1, '10')\n#2 [internal function]: {closure}()\n#3 /var/www/html/system/includes/dispatch.php (497): call_user_func_array(Object(Closure), Array)\n#4 /var/www/html/system/includes/dispatch.php(561): route('GET', '/index')\n#5 /var/www/html/system/htmly.php(3275): dispatch()\n#6 /var/www/html/index.php(5): require('/var/www/html/s...')\n#7 {main}\n  thrown in /var/www/html/system/includes/functions.php on line 293

* I renamed my /config/username/abc_.ini to abc.ini
* I deleted the test post from content
* I deleted all the txt files in the /cache directory.
* I was able to then login then create a new post

I'm guessing it has something to do with:

    // Extract the date
    $arr = explode('_', $filepath);

    // Replaced string
    $replaced = substr($arr[0], 0, strrpos($arr[0], '/')) . '/';

    // Author string
    $str = explode('/', $replaced);
    $author = $str[count($str) - 5];

But I haven't looked too deep into it.

Thanks

**Comment by danpros** [comment]
Its not bug but limitations. The filename explode the underscore so you must not use underscore for it. Thanks.
