### ISSUE TITLE
BrightSmart-BT3-htmly Themes for HTMLy CMS based on BootStrap 3.3.7

### ISSUE THREAD

**Issue by deependhulla** [danpros/htmly#337]
Hi,
This is not a Bug/issue ; but a Theme made to support multiple-css of bootswatch for use in htmly cms.

[https://deependhulla.com/html-themes/brightsmartbt3-htmly](https://deependhulla.com/html-themes/brightsmartbt3-htmly)

Hope its ok to post here.
Thanks in Advance.

-Deepen Dhulla.

**Comment by tacojones** [comment]
Those are great themes. Thanks.

**Comment by painteros** [comment]
Hi.
Bright Smart-BT3 is a great theme.
Is it possible to use Custom Background for specific pages.
If possible please tell me.
Thanks.

**Comment by deependhulla** [comment]
Hi,
As of now its only custom header support for specific pages.
not background.
will keep that in mind  as a feature.

-Deepen.

**Comment by painteros** [comment]
Thanks.

**Comment by danpros** [comment]
Please add the github repo so people can look into it. Thanks
