### ISSUE TITLE
Sorting posts by date ascending (old to new) ?

### ISSUE THREAD

**Issue by netzjahre** [danpros/htmly#350]
How can I do this ?
Which file can I modify ?
Thx in advance for your hints.

**Comment by bttrx** [comment]
Probably few years too late, but you just need to change `<` to `>` in [function sortfile()](https://github.com/danpros/htmly/blob/6a3b464c401b48e972f26f6ac933dc93dbaeb296/system/includes/functions.php#L162). This will reverse the order of posts in cache/index/index-sorted.txt and for draft posts. To take effect, clear HTMLy's cache from the dashboard after.

**Comment by bttrx** [comment]
@danpros I guess, you can close this.

**Comment by danpros** [comment]
Ok thanks.
