### ISSUE TITLE
Change Password not worked

### ISSUE THREAD

**Issue by AlexL777** [danpros/htmly#353]
Hi Developers,

Unfortunately, your method does not work with the tip as I can change the password. My users.ini looks like this.

`password = mypassword as a text = password_hash
role = admin
 = encryption = clear`

But if I want to login in the frontend under `/login` me, indicated that users + password are not correct.

Can you possibly help me to fix it?

Thanks in advance.

**Comment by m45rud** [comment]
It does work, you just need to set empty on encryption.
ex:

password = mypassword
encryption = 
role = admin

Just like that.

**Comment by AlexL777** [comment]
Yes, now my Problem is solved 👍  Big Thanks!!
