### ISSUE TITLE
More than 25.000 posts - No problem for HTMLy

### ISSUE THREAD

**Issue by badstue** [danpros/htmly#356]
Sorry for being in the wrong spot. This is not an issue. But since there isnt any forum I'll do it here.

I just did some tests with more than 25.000 randomly generated posts, written in markdown. Imported them all. And even on a crappy shared hosting package the speed is crazy. The hit on cpu is extremely light. HTMLy runs amazingly fast.

I would love to see the development restart. Maybe as a new project. Because GRAV, one of the competitors, is really slow in comparison. Maybe setup a pro version with support.

**Comment by painteros** [comment]
Also I want to check on my hosting,
where can I get a test certificate or how to generate it?
Prompt.

**Comment by Suleman-Elahi** [comment]
https://github.com/certbot/certbot
