### ISSUE TITLE
Admin Page Issue

### ISSUE THREAD

**Issue by hav0ck** [danpros/htmly#357]
I just installed HTMLYy and when I opened the installer.php file I got this message

`Your rewriteRule is not ready to use.`

I did the install and everything seems fine except the Admin page has no options on it. I've checked to make sure that my .conf file appears like this:

`<Directory /var/www/html>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
</Directory>`

The .htaccess file is in the correct location and I assume it's working but I don't know for sure

Thanks for any help that can be given.

**Comment by ncang** [comment]
hope same case like https://github.com/danpros/htmly/issues/106

**Comment by hav0ck** [comment]
It doesn't seem like this is the same issue, but I do see some similarities especially the 'Dumb User' identification :)

 So HTMLy is installed in a folder on a sub-domain. Here is a screen shot of the admin page.
![image](https://user-images.githubusercontent.com/815295/35747785-9b598c82-0819-11e8-998c-0007f6717840.png)

Thanks,

**Comment by hav0ck** [comment]
Should my admin page have more options?

**Comment by ncang** [comment]
no, except you have some page / post
more option see config tab
