### ISSUE TITLE
Need co-maintainer

### ISSUE THREAD

**Issue by danpros** [danpros/htmly#358]
Hello,

Due to my busyness in other things then right now I just have a little time to manage this project properly, sorry for that. So anyone who wants to be a co-maintainer can volunteer, but keep in mind that HTMLy uses [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) so it should be as simple as possible. 

Tasks of co-maintainers eg. help to review the pull request and merge it etc.

Thanks,

**Comment by badstue** [comment]
Anyone? :-)

**Comment by badstue** [comment]
Really?

**Comment by badstue** [comment]
I bet HTMLy could be a new hit among the other flatless CMS and maybe even among the top CMS. HTMLy have something special. Reliable, light and simple. Things you need today. And you can host HTMLy on a really crappy shared plan with tons of content on your site, and still runs blazing fast. Thats utopia. But thats just how HTMLy is.

**Comment by medmen** [comment]
I am willing to volunteer and help as best as i can. 
Beware: I have only limited knowledge around GIT and maybe not enough time.
But i would love to see HTMLy grow and live, and if more people are willing to help, this might be just enough...

**Comment by SaleRise** [comment]
Hi @danpros I am willing to stand up and maintain HTMLY. Please let me know if you are keen?

Cheers

**Comment by wasim117** [comment]
Yes

**Comment by bluebirch** [comment]
Is there a fork that integrates any further developments?

**Comment by medmen** [comment]
Not to my knowledge. But it might be a good idea, since development has stalled here...
Let me know if you are willing to fork and maintain this, I'll see how i can help..

**Comment by bluebirch** [comment]
I have forked it and begun working on a Swedish translation and completing language support (it has not been implemented in all themes yet). I'm looking into adding SmartyPants also for some additional processing of markdown files (most notably converting -- and --- to en-dashes and em-dashes, respectively), as suggested over at the php-markdown site.

Although I'm not a php developer, I might be able to maintain development. I can handle Git and GitHub at least. :-)

**Comment by ColonelBlimp** [comment]
How far did this idea get?  Unfortunately, I have just seen this.  I am retried now and have time to maintain?

**Comment by Lavatari** [comment]
HTMLy definitely deserves more love. I'm using it to study coding and web development! I would love to promote it to friends and colleagues but it's hard to use since there's so little themes, plugins and documentation available... Is there an active community of HTMLy enthusiasts somewhere on the internet?

**Comment by Hjertesvikt** [comment]
I am using a heavily modified HTMLy at [www.padiracinnovation.org/News](url).
My mods mostly :
1. add stats from the Apache log (something specific as not all HTTP servers are Apache)
2. most huge files like htmly.php are replaced with small files doing only one thing. This brings more clarity to the structure.
I tried a bit also to separate more presentation from business logic.
Indeed all this is tied to my needs and would not be very useful for HTMLy in general.

One roadblock in all those softwares is that making it useful for a large population, means introducing of lot of configuration options and framework idiosyncrasies (API, plugins,etc). Something that HTMLy does not, and I feel it is one of its strength.

**Comment by ColonelBlimp** [comment]
I will gladly help maintaining the code.  Well, I tried to contact the owner via his website... unfortunately nothing.

I think Htmly is dying (great shame), even pull requests are not attended too - hence I have been working on my own replacement...

**Comment by Hjertesvikt** [comment]
Then ColonelBlimp, create a fork (using the Github button) and add manually the pull requests and invite those guys in that page that look to be interested in HTMLy.
If Danpros comes back it would be easy for him to resync his code with the fork, or some decision could be made about new maintainers for HTMLy.

**Comment by ColonelBlimp** [comment]
@Hjertesvikt, thank you for the suggestion. I did not want to do it this way (I started down this route, but abandon it), but okay, let use this route and see how it goes...

**Comment by bluebirch** [comment]
I maintain a fork at https://github.com/bluebirch/htmly and try to stay as close as possible to @danpros original. All my own additions are kept in the experimental branch (https://github.com/bluebirch/htmly/tree/experimental). I will definitely support any actively developed fork, if you choose to create one, @ColonelBlimp.

**Comment by ColonelBlimp** [comment]
Okay. Fork done and some work started.

Initially, I will go through the Issues list here and see what should (IMHO) be included in a release - which will be a maintenance release.

**Comment by dirmanhana** [comment]
okay
