### ISSUE TITLE
theme not changing

### ISSUE THREAD

**Issue by robbiecren07** [danpros/htmly#360]
so i have installed and setup htmly blog on a test site, and i downloaded the ignite theme and place it into the theme folder and made the chnage in the config.ini file. but when i view the blog the only page that has the ignite theme is the http://web2.robbiecrenshaw.com/blog/ignite page and the main blog page is the default theme and the blog post page is a different theme aswell. can anyone shed some light on what im doing wrong.

**Comment by ncang** [comment]
hmm, have u clear the cache ??

just for make sure, do u set config.ini
`site.url='"ttp://web2.robbiecrenshaw.com/blog/ignite"`
`views.root = "theme/ignite'`

**Comment by robbiecren07** [comment]
nope i had the site.url set to: http://web2.robbiecrenshaw.com/blog/
because there is no ignite folder in the blog directory, so figured the site url was the default blog directory with the main files. 

does the site url need to point to the theme folder? as i changed the config.ini and now there is no style at all.

**Comment by m45rud** [comment]
To add and use new theme, you just need to copy theme (ignite) and put in tho folder themes. 

Then you change the views.root to `views.root = "themes/ignite"` and make sure your site url end with backslash `http://web2.robbiecrenshaw.com/blog/`.

**Comment by ncang** [comment]
oh ok, see @m45rud comment

**Comment by danpros** [comment]
I will close this one
