### ISSUE TITLE
Page Views gone or reset

### ISSUE THREAD

**Issue by badstue** [danpros/htmly#366]
Hi,

I just experienced a minor thing. A thing that irritates me just a bit.
That bit is the views of my pages or blog content. All the views has been reset to 0 or 1. My host has not been down or experienced any issues.

Any ideas of what went wrong? And where do I even find the views for each page ?

All the best,
Rasmus

**Comment by m45rud** [comment]
Maybe the views.json file changed to empty

**Comment by badstue** [comment]
Thanks. I've changed the counters after what I remembered.

**Comment by badstue** [comment]
No. The file wasnt empty. All the post-details was there. Except the viewcounter for each post. That was reset back to 1.

**Comment by badstue** [comment]
This happened again. All my views was reset to -1. 
Luckily I do keep backups for each day so I restored the views.json

**Comment by badstue** [comment]
Still a problem in 2021. Anyone else experiencing the same?

**Comment by Hjertesvikt** [comment]
Same for me, views are regularly emptied .
When the cache is cleared, clear-cache.html.php is called 
In it there is this piece of code:
if (!empty($files) || !empty($draft)) {
    migrate_old_content();
}

and afterward in migrate_old_content() there is:  "unlink('content/views.json');"

if (file_exists('content/tags.lang')) {
        rename('content/tags.lang', 'content/data/tags.lang');
        unlink('content/views.json');
}

Why should "migrate_old_content();" be called when we clear the cache?

**Comment by danpros** [comment]
Hello, this seems like a pretty random problem. Those function actually for the old version and only delete the old views json (/content/views.json). The new views.json is in /content/data/views.json folder.

**Comment by danpros** [comment]
This should fixed in latest version (2.7.7)

**Comment by Hjertesvikt** [comment]
Many thanks, out of curiosity what caused this problem?

**Comment by danpros** [comment]
This line:

```
file_put_contents($filename, json_encode($views, JSON_UNESCAPED_UNICODE));
```

Previously missing the `JSON_UNESCAPED_UNICODE`

**Comment by danpros** [comment]
If the problems still persist I will change to use the serialize in next version and not using JSON.

**Comment by danpros** [comment]
I will close this one. If the problems still exist please re-open it. 

Thanks,

**Comment by thorsten-panknin** [comment]
Happened to me twice now. I can't reopen this issue.

**Comment by AutomationMan808** [comment]
Happening on one of my sites.

**Comment by danpros** [comment]
@thopanX did you edit the folder structure or the filename manually? the views id is the filename path so if the views reset than the filename path has changed (need to edit the views.json manually), if your are using the admin panel, every post/page edit (change tags, category etc. it has function to update  the views.json.
