### ISSUE TITLE
How to make link open new tab in post? 

### ISSUE THREAD

**Issue by agus-salim** [danpros/htmly#368]
such as : use target="_blank"
Gimana caranya bos, biar link di pos bisa open new tab? please hehe :-), saya lagi nyoba htmly : https://agus.maarif-sintang.org/

Thank You

**Comment by danpros** [comment]
Gunakan misal:

`<a href="URL" target="_blank">Title</a>`

**Comment by agus-salim** [comment]
wah, danpros udah lama gak muncul. hehe, makasih mas.
