### ISSUE TITLE
RSS feed formatting problems

### ISSUE THREAD

**Issue by hamishmacdonald** [danpros/htmly#370]
I’ve been happily using HTMLY for a while, but am thinking of switching back to WordPress — just for the ease of being able to use a client that lets me write offline and will automatically resize my images.

It seems that the only way to move my content is by having WordPress read/slurp up HTMLY’s RSS feed, but I’m having problems with that: My posts come across as big, unstyled blocks of text, and none of the images carry over.

I checked my feed by subscribing to it in Feedly, and it looks the same over there: no formatting, no images. So even if I did keep using HTMLY, I’m concerned that subscribers aren’t seeing my posts’ content properly.

Do you have any suggestions for how to improve the quality of my RSS feed, or how else I might export my content to WordPress?

Thanks!

**Comment by achadidi** [comment]
I can help you a little because I also have a website, I do publications through  feedburner.google.com ,  dlvrit.com  and they are perfectly shown by repost on Google and Facebook from there

**Comment by hamishmacdonald** [comment]
Thanks for the help! I looked at both of those services, but unfortunately they both say that my blog exceeds their file-size limit.

**Comment by hamishmacdonald** [comment]
Okay, how about this: Is there any way to have HTMLy show a full-text feed? Right now it only serves up a tiny truncated bit of text, and nothing I enter in the HTMLy config page seems to change this.
http://hame.land/htmly/feed/rss

**Comment by ncang** [comment]
i see at https://github.com/danpros/htmly/blob/master/config/config.ini.example
; RSS feed description length. If left empty we will use full page.
rss.char = "200"
maybe
rss.char = ""

**Comment by hamishmacdonald** [comment]
GENIUS!!! That worked! Thank you so much! You have no idea how much trouble you've just saved me. I'm so grateful!
