### ISSUE TITLE
Please convert this theme for HTMLy

### ISSUE THREAD

**Issue by cnhsn** [danpros/htmly#371]
https://bikinwebsite.com/flat-blog/ > Please convert this, I really want to use this script with this theme.

You can convert other bikinwebsite themes for rich theme directory :D

**Comment by aaz1887** [comment]
and also this wordpress theme, thanks :  https://oceanwp.org/

**Comment by ColonelBlimp** [comment]
> 
> 
> and also this wordpress theme, thanks : https://oceanwp.org/

Which theme from this site?

**Comment by danpros** [comment]
The website not loaded. I will close this one. Thanks
