### ISSUE TITLE
Is it possible to use PHP includes inside posts?

### ISSUE THREAD

**Issue by iagovar** [danpros/htmly#372]
I want to call html files inside posts, and It would be nice to use php includes, is it possible?

**Comment by samirank** [comment]
Yes, in your theme root folder create an HTML template and name it **static--yourpageslug.html.php**. Replace 'yourpageslug' with your page slug. You can use php includes too.

**Comment by danpros** [comment]
@samirank thanks. Yes it is, just editing the `post.html.php` for blog post
