### ISSUE TITLE
disable cache on 404 error

### ISSUE THREAD

**Issue by medmen** [danpros/htmly#374]
I stumbled across a "disk full" problem recently on my server. While the main problem was not HTMLy's fault, i noticed some strange caching behavior: 

HTMLy seems to create a cache page for every get-request, even if it results in a 404 error

this crowded my cache directory with well over 40000 files (on a web server mostly visited by bots).
I could not wrap my mind around the way HTMLy exactly renders a page, but it should not cache a page when a 404 is given, as this might be a possible vector for flooding a server to death.

**Comment by danpros** [comment]
Fixed in new version. Thanks.
