### ISSUE TITLE
page add in cross site scripting vulnerability

### ISSUE THREAD

**Issue by ismailtasdelen** [danpros/htmly#376]
Hello Development Team,

When I was a security researcher and student, I wanted to discover and report "XSS" vulnerability.

Vuln url address : https://localhost/HTMLy/add/content?type=post

Screenshot : 

![screenshot from 2018-07-18 13-01-52](https://user-images.githubusercontent.com/15425071/42874956-1fa0d664-8a8b-11e8-9449-4ba6b011bbd3.png)

![screenshot from 2018-07-18 13-01-27](https://user-images.githubusercontent.com/15425071/42874958-1fbfddac-8a8b-11e8-886f-797e35bf87dd.png)

Payload : "><img src=x onerror=alert('ismailtasdelen')>

Thanks

**Comment by aalfiann** [comment]
I think that not xss, because you have authority to create or add post and you want to post javascript into your website.

So you have responsible to what happend about your website. 

XSS is when someone dont have authority able to post script into your website.

**Comment by ismailtasdelen** [comment]
Thanks for the came back :+1:
