### ISSUE TITLE
HTMLY feature

### ISSUE THREAD

**Issue by StarRico** [danpros/htmly#383]
Help! I've lost the featured box for posts where you put in the video / image / quote. Can anybody help me as it'll mean saying goodbye to HTMLY if not.

**Comment by m45rud** [comment]
Do you edit the system core of htmly?

**Comment by StarRico** [comment]
Hi, no I don’t touch the core, just the theme. I’ve since got it working as I was actually adding the embed code rather than the link code. User error!

**Comment by m45rud** [comment]
Could you attach the screenshot please.

**Comment by StarRico** [comment]
Hi, this is now resolved!
