### ISSUE TITLE
Advisory from Netsparker - HTMLy 2.7.4 - Reflected XSS, Stored XSS

### ISSUE THREAD

**Issue by DanielBishtawi** [danpros/htmly#386]
Hello,

While testing the Netsparker web application security scanner we identified Reflected and Stored XSSes vulnerabilities in HTMLy 2.7.4. Can you please advise whom shall we contact to disclose the vulnerability details so it can be fixed?

For the technical details please email me: daniel@netsparker.com

Looking forward to hearing from you.

Regards,

Daniel Bishtawi
Marketing Administrator | Netsparker Web Application Security Scanner

**Comment by danpros** [comment]
Hello,

Seems similar with this issue: #382 

This marked as won't fix.

**Comment by DanielBishtawi** [comment]
Hello,

The XSS vulnerabilities we found is a separate issue from #382.

Please email me at daniel@netsparker.com for the technical details.

**Comment by danpros** [comment]
@DanielBishtawi Hello, if this is related to markdown things than I will state it as won't fix.
