### ISSUE TITLE
Adding logo

### ISSUE THREAD

**Issue by therobotguyllc** [danpros/htmly#389]
Sorry for bringing up what is probably a very simple thing. I cannot see a place to load a site logo. I was able to get a favicon uploaded to replace the existing default one but nothing for a logo yet. Is there a method for uploading/changing the logo?

Also, I am using the ignite theme. I saw other themes but no logos in there either. 

thanks,
Justin

**Comment by wepals** [comment]
Where where you able to change the favicon? I uploaded mine in main dir without success.

**Comment by StarRico** [comment]
Right or wrong, with my limited knowledge, I just removed the original logo and posted an image file on the layout php. Seems to work - http://www.thefringefiles.com/

**Comment by danpros** [comment]
You need to upload it to your theme directory.
