### ISSUE TITLE
Not issue, but a few questions...

### ISSUE THREAD

**Issue by fatmanm** [danpros/htmly#391]
Hello, I'm new.. Just installed HTMLy, I have no coding, programming knowledge, but I liked HTMLy, it's fast, doesn't need database...

I tried searching but couldn't find anything, I want to change/rename/translate a few things, texts, month names etc. And how can I change theme colors? Thank you.

![IMG_20191203_204400](https://user-images.githubusercontent.com/58482711/70076345-a5311800-160f-11ea-971b-0a5b5924d598.png)

**Comment by Torsten-K** [comment]
In the file _layout.html.php_ within the theme that you use. You will need an FTP client like FileZilla and a text editor. Search for _<h3>Recent Posts</h3>_ etc. and change to your needs.

**Comment by fatmanm** [comment]
Thank you @Torsten-K , I managed to change most of them using language file, (.ini) edited the ones I needed, but another problem emerged... Some letters not showing up like ö,ş,ı,ü etc. (In my language:) these letters show up just fine in posts (I was using WordPress, I used RSS import for posts), but not in fields like Archives, Category etc.

But so far so good, my website runs extremely fast, I liked Htmly, it is ten times faster than WordPress, It uses very little server resources, CPU...

**Comment by Torsten-K** [comment]
Oh, that’s a better solution than mine, I’d say.

The issue with the specific letters might have something to do with the encoding in the theme’s index page or so, which should be UTF-8 and should look like this (HTML5):

```
<!DOCTYPE html>
<html lang="de">
<head>
	<meta charset="utf-8">

```
But I must say, I don’t use HTMLy any longer. The further development seems to be frozen, and there are security issues, as reported here some time ago.
I love using Bludit, (bludit.com) which is being actively developed, databaseless as well, and as easy to use as HTMLy. It has a forum with an active and friendly community and so on.

**Comment by fatmanm** [comment]
Thanks a lot, I will try to edit that file.

I will check bludit, I heard it before.
