### ISSUE TITLE
Bullet Points on Related Posts (Vapor)

### ISSUE THREAD

**Issue by StarRico** [danpros/htmly#392]
![Capture](https://user-images.githubusercontent.com/43246556/75154180-13641300-5705-11ea-9a15-705ef8f075fc.JPG)

Does anybody know how to switch off the bullet points for the related posts? I've tried everything. I think it's driven by class (related) but I can't find it anywhere.

**Comment by bluebirch** [comment]
What theme are you using?

**Comment by StarRico** [comment]
Hey bluebirch, I'm using the Vapor theme by Seth Lilly - [https://github.com/danpros/htmly-vapor](https://github.com/danpros/htmly-vapor) - Any assistance would be soooooo gratefully received. I'm loving HTMLY and really don't wanna move away from it.

**Comment by m45rud** [comment]
Try to inspect element and find its code. I gues its from css.

**Comment by danpros** [comment]
I will close this one. Thanks
