### ISSUE TITLE
I can't post new blog content on 2 of my htmly blog

### ISSUE THREAD

**Issue by weblord** [danpros/htmly#393]
Hello there, 

Last April 29, 2020 I was able to post and suddenly this week I'm trying to solve and exhausted all researches and i can't post new blog content to it. 

How to fix this?

I've already set up php version 5.3 for it since it both resides in subdomains.

I've already set the error reporting to all on index.php but it does not report at all.

After I painstakingly formatted the new blog content it just returned me to the list of previous contents but the new content is not included.

Please help me

**Comment by ncang** [comment]
Can see error log on the server (apache or nginx)?
Perhaps it's just permission setting,

**Comment by weblord** [comment]
Thanks for the reply. 

No apache error logs at all. 

All folders are set to 755 and all files set to 644. I never changed any permission except the ones instructed on the installation instruction. 

It's just not me, another colleague of mine tested it from another country, browser and o.s. still same issue. I have this installed since August, 2018.

All of a sudden it somehow stopped receiving new blog posts.

**Comment by danpros** [comment]
How about clearing the cache?

**Comment by weblord** [comment]
Thanks for the reply sir danpros.

Yes I did that too. Everyday I clear cache. I used firefox and chrome same results.

I also added the error message display on index.php and it displayed nothing. After posting a blog, it just redirected me to my old posts and then my post was not there.

**Comment by danpros** [comment]
That's a weird problems. Logout first than try to delete the cache index under cache folder using file manager. The cache folder must rewrite-able. And try to create a post than check the .md file using manager, the file exist or not. You can reach me at `dan <at> danpros <dot> com`

**Comment by weblord** [comment]
mysubdomain.com/cache/page < = is this the folder you're talking about? 
these are the files on that folder:

there are lots of files inside that folder that starts with ## so all of those files needed to be deleted?

**Comment by weblord** [comment]
I've deleted the folder index under cache folder, re-created the blog post and posted it. Nothing happened. No .md file showed up.

**Comment by weblord** [comment]
What am i going to email you? is this still free service if we move to email help?

**Comment by weblord** [comment]
Thank you very much for all the help. I figured it all out. Don't bypass the 200 character tags or keyword input or you won't be able to post. make sure you use only 200 characters or near it. my case my old tags are about 398 characters and downsized to 204 characters and i was able to post.

Issue resolved. Great databaseless blog cms. I'll keep using it and am using it on my 3 blogs already and another 3 blogs are coming in.

**Comment by danpros** [comment]
@weblord that's great. Well its filename length limits on Linux, you can still increase it though (depend on your hosting provider).

**Comment by weblord** [comment]
wow, you have resolved the limitation of blogger/blogspot itself because they limit label which is tag or keywords in blog to 200 characters, now htmly is unlimited, no restrictions and unbeatable.

Looking forward for an update of the htmly blog cms in the near future. how about version 3? 

I'm all excited to it.
