### ISSUE TITLE
Documentation for theme creation

### ISSUE THREAD

**Issue by noquierouser** [danpros/htmly#40]
Even though the themes shipped with the HTMLy standard install are quite didactic, I'd like to know the API that the themes use to display content. HTMLy has a "Doc" link that leads to the Readme.md of the repository.

**Comment by stingray82** [comment]
I have just used the above link to skin mine, the same as my website once i removed the crossed CSS tags in the PHP it was quite simple and even better, its a pull from my MODX site which means i update in modx it updates the blog theme to :) so thank you for the above link. Site: www.home-heroes.co.uk/blog/

**Comment by danpros** [comment]
There is a docs but not completed yet https://docs.htmly.com/theming
