### ISSUE TITLE
Possible User enumeration under /login

### ISSUE THREAD

**Issue by andresesam** [danpros/htmly#406]
Hey everyone, after I just set up htmly locally I noticed the following security problem,
Under version 2.7.5 it is possible to enumerate valid user names via the non-generic error messages of a failed login attempt.

If you enter a valid user and a wrong password, the following error message is displayed:
![wrong_password](https://user-images.githubusercontent.com/39090774/84573154-0c8a0a80-ad9f-11ea-8292-cf7bbf513c47.png)
However, if you enter a non-existent user, you will receive a different error message:
![wrong_user](https://user-images.githubusercontent.com/39090774/84573156-0d22a100-ad9f-11ea-8616-8ebe82021909.png)
This allows an attacker to enumerate valid user names and could serve as a basis for further attacks.

I would recommend to use a generic error message.

**Comment by danpros** [comment]
Please check the latest commit, I already change it to more generic message
