### ISSUE TITLE
Arbitrary file deletion vulnerability was found in v2.7.5

### ISSUE THREAD

**Issue by whiskey-jj** [danpros/htmly#412]
**Vulnerability description**

Arbitrary file deletion vulnerability was found in v2.7.5.Hackers need administrator rights and they can use any absolute directory to delete any file in the server.

**Steps to reproduce the problem**

Using GitHub source code to build the local environment.
PHP7.3  Apache2.4 Windows10
![image](https://user-images.githubusercontent.com/40733224/86409232-024a9480-bceb-11ea-86d7-8e5c8a0a432a.png)

Enter the backup page.Create a backup and delete it. At the same time, use burpsuite to capture the package.

![image](https://user-images.githubusercontent.com/40733224/86408626-ea264580-bce9-11ea-994e-b106b03e09f3.png)

Enter the absolute path of the file you want to delete here.
The relative path is OK
![image](https://user-images.githubusercontent.com/40733224/86408399-84d25480-bce9-11ea-906d-17be49ed7bfe.png)
The file has been deleted.
![image](https://user-images.githubusercontent.com/40733224/86408425-91ef4380-bce9-11ea-883f-17ad7837b33d.png)

I think there's something wrong with the code here.
\system\admin\views\backup-start.html.php
```
<?php
if (login()) {
    if (isset($_GET['file'])) {
        $file = _h($_GET['file']);

        if (!empty($file)) {
            unlink($file);
        }

    }
}
?>
```
It does not control the path entered by the user, nor does it detect whether the file belongs to backup

**Comment by danpros** [comment]
Hello,

Thanks for reporting this, yes we need to limit it to the backup folder. But at least at the moment we need the administrator permission to do that so is relativity safe.

You can creating pull request to improve those code.

**Comment by danpros** [comment]
I am limiting the unlink to backup folder. 2b147eb

It should fixed the problems.

Thanks,
