### ISSUE TITLE
Can't /login 

### ISSUE THREAD

**Issue by efiopops** [danpros/htmly#413]
Hi everyone. When i try to login on local server everything is perfect but on remote server i got error. Help to resolve that please.

Error link:
![Screenshot_2](https://user-images.githubusercontent.com/48172415/87435126-f9fc2e80-c5f3-11ea-9fc7-940f2f1bb280.png)

**Comment by bluebirch** [comment]
See #71. Look into mod_rewrite.

**Comment by danpros** [comment]
@bluebirch Thanks. I will mark it as fixed.
