### ISSUE TITLE
After install with softaculas tried to create a new post and it failed!

### ISSUE THREAD

**Issue by atiqsu** [danpros/htmly#414]
I have created a sub-domain to test this thing and I failed to create a simple post with one image - 

https://prnt.sc/u9reix and it shows error when try to save as draft or publish - https://prnt.sc/u9rexd .

The version information could not find though most probably the latest version.
Also I have not touch anything in config page.

**Comment by ColonelBlimp** [comment]
The version info is located in the 'cache' directory in the file named 'installedVersion.json'. However, this should be the latest version.
I will try to reproduce here. Do you have access to the webserver error logs? If so, can check them for any indication of the server error.  Also, check that the fields in the config are correct.

**Comment by danpros** [comment]
This should addressed to softaculous team.
