### ISSUE TITLE
there is spelling error in polish translation. 

### ISSUE THREAD

**Issue by ArturLisowski** [danpros/htmly#415]
![image](https://user-images.githubusercontent.com/12079084/92921471-62b92900-f434-11ea-95fd-673c46d06564.png)

there is spelling error. Correct string should be an 'Konfiguracja'

**Comment by ColonelBlimp** [comment]
I will also update my fork with this.

**Comment by danpros** [comment]
Thanks, @ColonelBlimp I will close this one.
