### ISSUE TITLE
tags severely limited after update

### ISSUE THREAD

**Issue by CodeCatCool** [danpros/htmly#419]
After updating to the latest version of HTMLY the tags count went from lots of tags to about 5 or 6. The number of tags I can see on my blog are severely limited, I have a lot of tags and can't see them.

**Comment by ColonelBlimp** [comment]
> After updating to the latest version of HTMLY the tags count went from lots of tags to about 5 or 6. The number of tags I can see on my blog are severely limited, I have a lot of tags and can't see them.

Hi, have you tried to clear the cache from the Admin console?

**Comment by CodeCatCool** [comment]
Yes, I did.

**Comment by danpros** [comment]
@CodeCatCool The tags widget? that is just tiny theme change actually. You can download the old version of the theme and replace the widget code with the old one.

**Comment by CodeCatCool** [comment]
Awesome, that worked, THANKS!!!
