### ISSUE TITLE
Search in content not possible

### ISSUE THREAD

**Issue by cyberfish** [danpros/htmly#42]
Hi, First, thanks for htmly. Can I search only in Tags? I have tried to find a word inside the content, it don't work.

Best regads
cyberfish

**Comment by NuclearPrawn** [comment]
I'm looking to migrate my blog (Atomicshrimp.com) to a new platform (it's currently running on a flat-file PHP CMS called FuzzyLime, that was abandoned by its creator) - I really like the simplicity of HTMLy, but search within content is a dealbreaker for me too.

I have the source for a search function that a contributor added to the Fuzzylime project (when it was active) - pretty sure this could be adapted to work with HTMLY, but my own PHP skills are not up to the task...

**Comment by Kanti** [comment]
hi @NuclearPrawn,

my time is limited and I haven't enough to implement a full text search. But if you could create a pull request it would be nice. It need not be done but it should be the basic principle of how to implement something like this. Then I could finish it.

**Comment by fahmi182** [comment]
Ya, Search content is killer feature :+1:

**Comment by Xarcell** [comment]
If you implement a full text search feature, please make an option to disable or enable it. Full text search is more susceptible to DOS attacks. I wouldn't want my client's site shut down due to resource limit because some amateur hacker would think it's funny to spam search.

**Comment by nickbe** [comment]
I tested a full text search on 2000 posts filled with an average page contents. It's still pretty fast.
So I don't think it would be a problem to search withing the posts.

**Comment by Kanti** [comment]
@nickbe could you create a Pull Request for this feature?
Than we could test it.

**Comment by nickbe** [comment]
There's no official version for this. I had our intern fill a test installation with 2000 posts. After that he wrote a simple php routine to scan through the files. Also he tested grepping through the files. Both concepts are fast enough in my opinion. So I'd say you can simply add a feature to search through the complete posts and not only through title and tags

**Comment by danpros** [comment]
This issue is too old, I will close this one. Please create new issue for possible improvements. Thanks
