### ISSUE TITLE
[Feature request] automatically make link in post click-able (like github/gitlab)

### ISSUE THREAD

**Issue by recolic** [danpros/htmly#422]
In github/gitlab, if we use the following README.md, the link will be clickable:

```
### Download
Download me at https://some.website.com/this/is/a/very/really/really/long/url/1.exe . Enjoy!
```

But in htmly post, I have to write the link twice, like this:

```
### Download
Download me at [https://some.website.com/this/is/a/very/really/really/long/url/1.exe](https://some.website.com/this/is/a/very/really/really/long/url/1.exe) . Enjoy!
```

It's good if htmly can recognize links in the post, and automatically make it click-able.

**Comment by recolic** [comment]
https://github.com/michelf/php-markdown/issues/326

**Comment by recolic** [comment]
Workaround: https://daringfireball.net/projects/markdown/syntax#autolink

**Comment by danpros** [comment]
I will close this one. Thanks
