### ISSUE TITLE
why i can't post successfully

### ISSUE THREAD

**Issue by luckypoem** [danpros/htmly#425]
hi.

after i login in http://www.mydomain.com/login,and i publish a regular post,but actually when i visit http://www.mydomain.com, it just shows: "No posts found!"
why?how to fix it?

**Comment by ColonelBlimp** [comment]
Did you clear the cache by reindexing?

**Comment by luckypoem** [comment]
How to do reindexing?

**Comment by ColonelBlimp** [comment]
> How to do reindexing?

From the admin console.  There is an option to 'Clear cache'.

**Comment by luckypoem** [comment]
hi.

even after clicking 'Clear cache',when i visit http://www.mydomain.com, it still shows: "No posts found!"
headache,how to fix it?

**Comment by ncang** [comment]
Maybe same problem about permission,
https://github.com/danpros/htmly/issues/83

**Comment by luckypoem** [comment]
yes,
after running "chmod -R 777 /path/to/root-dir-of-the-website/", it's fixed.
