### ISSUE TITLE
there is no html editor when publishing  a post?

### ISSUE THREAD

**Issue by luckypoem** [danpros/htmly#427]
it seems there is no html editor when publishing  a post.how to fix the issue?

**Comment by medmen** [comment]
you are right - there is no html editor :) this is not a bug, it's a feature. 
htmly uses markdown for content formatting.
Just as using this textfield to create an issue in github, use the textfield to create your content and use the buttons on top to edit styling. If you need more complex styling, please refer to something like [markdownguide.org](https://www.markdownguide.org/cheat-sheet/)
The result is shown as you type/edit. Have fun!

**Comment by luckypoem** [comment]
<html>
    <iframe width="681" height="383" 
    src="https://www.youtube.com/embed/ASb1_Qi3lyY" 
    frameborder="0" allow="accelerometer; autoplay; 
    clipboard-write; encrypted-media; gyroscope; picture-in- 
    picture" allowfullscreen></iframe>
</html>

**Comment by luckypoem** [comment]
tks.i read https://www.markdownguide.org/basic-syntax/#code,it solved the issue
