### ISSUE TITLE
Cookie?

### ISSUE THREAD

**Issue by PetersOtto** [danpros/htmly#429]
Hi,
I have just a short question. Is it possible to run HTMLy without the cookie ("PHPSESSID") ?
Best regards.
O.

**Comment by sean1138** [comment]
i was able to get rid of a PHPSESSID cookie warning in firefox's console by deleting my site's cookies
https://stackoverflow.com/a/63821124

i'm still getting a `Cookie “” has been rejected as third-party.` tho.

**Comment by danpros** [comment]
This has been implemented. 

Thanks,
