### ISSUE TITLE
html5shiv js in admin layout = 404

### ISSUE THREAD

**Issue by sean1138** [danpros/htmly#432]
i really like the idea of htmly so i'm playing around with it a little.  I think i want to update/redo the admin template after finding a few small things that annoy me like floated elements and a horizontal scrollbar when there shouldn't be one.

![image](https://user-images.githubusercontent.com/6720184/104810038-1d30b200-57c0-11eb-9717-96a8b1a63ee5.png)

I never used html5shiv in any of my projects (i've been working with html & css professionally since 2007 and amateur/hobby since 97ish) so i'm not sure how useful it is in 2021.  I associate html5shiv with using html5 elements (header, footer, article, section, etc.) in browsers like IE7 that are not ever going to get updated to properly support the elements introduce with the html5 spec.

so my question is... would you object to html5 elements in the admin section without any concern for older browsers that might not support them?  What are the oldest browser versions you want this project to absolutely work properly with?

if i understood php better i'd consider adding admin templating/theming as a feature but that's more than i can handle.  I'd be fine with making a mostly table based layout template for old browsers if someone really wanted support for browsers more than 10 years old ;)

**Comment by danpros** [comment]
Well we use new dashboard theme so I will close this one. Thanks
