### ISSUE TITLE
Problem with rewrite rules

### ISSUE THREAD

**Issue by PrestaShark** [danpros/htmly#434]
Hi
Im getting problems with rewrite rules www to non-www and http to https.
When enabled in htaccess then post no longer available - 404.

Check also at:
https://www.demo.htmly.com/2015/07/premature-optimization-is-the-root-of-all-evil
and https://demo.htmly.com/2015/07/premature-optimization-is-the-root-of-all-evil

**Comment by jsebean** [comment]
Are you using Apache? Add a vhost for each

```
ServerName mycoolsite.com
Redirect 301 / https://www.mycoolsite.com/
```
Very simple config and more performant than htaccess.

**Comment by danpros** [comment]
This seems only server config. I will close this one. Thanks @jsebean
