### ISSUE TITLE
Settings in the admin area do not take hold.

### ISSUE THREAD

**Issue by Incognify** [danpros/htmly#435]
Clean install on nginx. Accessing the admin area, and if I modify the configuration, the page just simply reloads with the same information shown as before the changes were made. Nothing takes hold.

If I try to make a test post, and click 'submit', the page will just reload and the post is never made. Same if I try to add a category and make any adjustments via the web ui.

Any ideas?

**Comment by ncang** [comment]
It's sound like write access on file or folder,
Make sure the ownership bro,

**Comment by Incognify** [comment]
It doesn't appear to be permissions or ownership based.

**Comment by ncang** [comment]
Can u see server log? It's maybe help u
