### ISSUE TITLE
HTMLy 2.7.7 themes throws fatal error on PHP 5.3.0 and 5.4.0

### ISSUE THREAD

**Issue by prbt2016** [danpros/htmly#437]
Hello,

I tried to install HTMLy manually via zip file i.e :

https://github.com/danpros/htmly/archive/v2.7.7.zip

on PHP 5.3 and also on PHP 5.4.

However, I get the following error while starting manual installation on both the PHP versions i.e : 

 Fatal error: Can't use function return value in write context in /{{PATH}}/{{TO}}/{{HTMLY}}/themes/twentyfifteen/layout.html.php on line 54, i.e the following code is causing issue : 

`<?php if(!empty(config('social.twitter')) || !empty(config('social.facebook'))):?>`

However, script works fine on PHP 5.5.

Seems that PHP 5.5 syntax is being used and prior to PHP 5.5 empty() supports only variables.

Has the script requirement changed?.

Documentation mentions that PHP 5.3 or higher required
https://docs.htmly.com/basics/requirements

Could you please replicate the issue and fix this?

**Comment by danpros** [comment]
Hello,

If you really need running it on PHP 5.3, or 5.4 you just need to remove those line or use previous theme from HTMLy 2.7.6. 

For themes, the only differences is only those line actually.

I will update the docs for twentyfifteen and twentysixteen it need php 5.5 or newer.

**Comment by prbt2016** [comment]
Hello,

Thanks. It will be really good if you update the documentation so that user's would come to know regarding the same.

**Comment by danpros** [comment]
Already update it: https://docs.htmly.com/basics/requirements

Thanks,

**Comment by fabianosantosnet** [comment]
We already have PHP 8. The minimum requirement should be PHP 7. We need to remove old codes to improve speed in HTMLy in the future (v3.0 maybe?).

**Comment by danpros** [comment]
@fabianosantosnet htmly use the most basic function (glob, explode etc.) and that's already the best function to do the task. Yes but we need to refactoring it for code efficiency.

I will mark it as fixed.
