### ISSUE TITLE
is there a simply way to have only cookies on the backend/admin site and "no" cookies for the user? I try find a small blog without any cookies for the readers.

### ISSUE THREAD

**Issue by KPCG** [danpros/htmly#438]

**Comment by KPCG** [comment]
I only have static HTML5 websites and do not use cookies. Now I am looking for a small blog system that does not generate standard random PHP session cookies in the frontend for the reader of the content.

Is it possible to leave the cookies at htmly only for the admin / backend area and to omit them for the frontend. It is clear to me that I have to forego the advantage of editing on the frontend side. But it would be a great thing if I could do without this stupid European Union cookie banner despite the use of htmly.

**Comment by Hjertesvikt** [comment]
IMO the EU privacy directive is not about banning cookies per se but about asking users if they agree to be tracked. It is exactly the same thing that Apple will implement in Ios. The directive is technology neutral.
However those that are deemed to be "strictly necessary for the delivery of a service requested by the user", such as for example, cookies that track the contents of a user's shopping cart on an online shopping service, are exempted. 
So if you use only session cookies, I guess EU's user consent is not required.

**Comment by KPCG** [comment]
It's not that easy. You have to inform the user about cookies as soon as he can be identified and tracked and the corresponding identification cookies are saved. With the new e-privacy regulation this will be tightened even more this year.

In Germany we repeatedly have problems with warnings for session cookies that are not explicitly described and explained in the banner. You can use these session cookies without the user being able to switch them off, but you still have to give a note and inform the user about the purpose of these cookies. Even if there is no tracking.

It would be nice to minimize the legal risks and not to save cookies in the browser.

**Comment by danpros** [comment]
At the moment there is no way you can achieve that except modify the core.

**Comment by danpros** [comment]
Please check the latest version. Thanks
