### ISSUE TITLE
Not enable to post

### ISSUE THREAD

**Issue by amladloz** [danpros/htmly#441]
Hi.
Trying HTMLY, installed XAMP, all good. When i try to make a post, Regular post, i get the following error:

Warning: file_get_contents(content/data/tags.lang): 
Failed to open stream: No such file or directory in C:\xampp\htdocs\htmly\system\admin\admin.php on line 91

Fatal error: Uncaught TypeError: array_flip(): 
Argument #1 ($array) must be of type array, bool given in C:\xampp\htdocs\htmly\system\admin\admin.php:91 
Stack trace: 
#0 C:\xampp\htdocs\htmly\system\admin\admin.php(91): array_flip(false) 
#1 C:\xampp\htdocs\htmly\system\htmly.php(462): add_content('post1', Array, 'post1', 'hghthsthtrhstrh...', 'admin', '', NULL, NULL, 'uncategorized', 'post') 
#2 C:\xampp\htdocs\htmly\system\includes\dispatch.php(513): {closure}() 
#3 C:\xampp\htdocs\htmly\system\includes\dispatch.php(577): route('POST', '/add/content') 
#4 C:\xampp\htdocs\htmly\system\htmly.php(3742): dispatch() 
#5 C:\xampp\htdocs\htmly\index.php(5): require('C:\\xampp\\htdocs...') 
#6 {main} thrown in C:\xampp\htdocs\htmly\system\admin\admin.php on line 91

Any suggestions?

**Comment by danpros** [comment]
Hello,

Is this the latest version? if not please download the latest version

**Comment by danpros** [comment]
Testing it with the latest version a moment ago in xampp (new htmly install) and work fine.

**Comment by amladloz** [comment]
Hello danpros, thanks for answering so quick :)
Yes, have the latest version, freshly downloaded...
Installed Version: v2.7.8
Seems to me, that the tags.lang file is missing, even after hit the PUBLISH button, its not created form some reason.
For static page, the dir htmly\content\static is created, and the static page within. So, not a dir-writing problem.
The tags.lang file what info contains, and where suppose to be located?

**Comment by danpros** [comment]
Its seem htmly can't write the data dir, please make it writeable for the web server, the file contains the tags key and value, the value become the tag title (this used let say in sidebar for tag cloud).

**Comment by danpros** [comment]
Ah sorry, seems from the start its missing the file, before its created the admin.php already call it.

**Comment by danpros** [comment]
Hello, this has been fixed in master, please try https://github.com/danpros/htmly/archive/master.zip

I will try to release the fixes ASAP

Thanks,

**Comment by amladloz** [comment]
Hello danpros.
Downloaded the htmly-master. Unzipped. Installed. Coffe drinked. 
Published (Regular post). Worked like charm.... Thank you. :)
Now in Content folder, admin folder was created... (User-Who-Post-Folder) , inside all the subdirs needed.

**Comment by danpros** [comment]
Hello,

That's great. Its stupid mistake actually 😅 this not effected the old users, only new installed blog.

**Comment by amladloz** [comment]
Hello
Glad its worked out... :)
I make a new language file, where can i send to you?

**Comment by danpros** [comment]
@amladloz you can go here https://github.com/danpros/htmly/pulls to creating a pull request.

If you do not want to creating a pull request you can send it to my email dan[at]danpros.com after it I will make a quick release to fix the bugs.

Thanks,

**Comment by danpros** [comment]
Thank you @amladloz already added it d72186c

**Comment by danpros** [comment]
Already release it https://github.com/danpros/htmly/releases/tag/v2.7.9

Let me know if you facing similar problems.

**Comment by danpros** [comment]
I will mark it as fixed. Thanks.
