### ISSUE TITLE
Cookie consent implementation

### ISSUE THREAD

**Issue by 2-of-1** [danpros/htmly#446]
Hi.

I would like to have a cookie consent feature implemented. As far as I am aware, by now, just the php session cookie is set when deactivating all 3rd partys stuff, but this could cause trouble with the data protectors guard anywais. ^^ 
Furthermore the cookie consent dialogoue should be accessible for screen readers as well. 

Best regards

Richard

**Comment by danpros** [comment]
Hi Richard,

Yes, in the next release we should add this feature. At the moment you can use jquery plugin, example: https://github.com/ketanmistry/ihavecookies 

Put it in layout.html.php.

Regards,

**Comment by danpros** [comment]
Please check the latest version. The session created in login page/backend. Thanks.
