### ISSUE TITLE
2FA support for Authenticator Apps and U2F (or even Yubico OTP) keys

### ISSUE THREAD

**Issue by sorat0mo** [danpros/htmly#449]
I suggest making 2FA a default option in HTMLy since it is built with security in mind. At the very least authenticator apps should be available for 2FA. Best if other methods such as E-mail or hardware security keys are also available.

**Comment by danpros** [comment]
Hi, yes I will considering it.

**Comment by danpros** [comment]
Latest version already support MFA, credit to @KuJoe 

I will close this one.
