### ISSUE TITLE
Custom comment section script

### ISSUE THREAD

**Issue by sorat0mo** [danpros/htmly#451]
Hello, I would like to suggest allowing users pasting their own scripts for comment section. Currently HTMLy supports only Disqus and Facebook which is known to violate privacy to a great extent. It would be best if there was also an option which allows users paste their own code to embed in comment section!

**Comment by danpros** [comment]
Yes at this time we have to edit the theme file (`post.html.php`), if we want to change it. Create custom config eg. `my.comment.script` with value `<bla></bla>` than calling it from the theme `<?php echo config(comment.script);?>`
