### ISSUE TITLE
Post teaser and RSS description from meta description

### ISSUE THREAD

**Issue by ChelonianEgghead** [danpros/htmly#455]
Hello! First of all I just want to say thank you for this great blogging system. 

Anyway at present the RSS feed items are basically the first 200 or so characters of each post by default, with their description on the homepage being 500. Do you think you could add a new teaser type "description" that has the value of the posts' meta description, and a similar option to use the meta description as the RSS description? It looks like it should be easy enough to do this with the teaser, and probably RSS too, but I'm afraid I don't quite understand the code for RSSWriter. (I can't figure out what `$this` refers to in [htmly/system/vendor/suin/php-rss-writer/src/Suin/RSSWriter/Item.php](Item.php).)

**Comment by ncang** [comment]
Did you try set in config.ini?

 ; Teaser type: set "trimmed" or "full".
teaser.type = "full"

; Read more link text for "full" teaser type
read.more = "Read more"

; Teaser character count
teaser.char = "200"

; Description character count
description.char = "150"

**Comment by danpros** [comment]
Hello, well you can set the rss char in Config -> Reading. Scroll to the botom under `RSS Settings` you til find `RSS character`. Set it to eg. 500.
