### ISSUE TITLE
 The code has stored XSS vulnerabilities

### ISSUE THREAD

**Issue by g0h3aler** [danpros/htmly#456]
The XSS filtering of blog title, Tagline, and Description in config.html.php is not rigorous, resulting in the generation of stored XSS
![image](https://user-images.githubusercontent.com/38587657/114492298-e9441c00-9c4a-11eb-8eaa-7727cba993ac.png)
![image](https://user-images.githubusercontent.com/38587657/114492317-f4974780-9c4a-11eb-8e7e-23c025717ccc.png)
Front display
![image](https://user-images.githubusercontent.com/38587657/114492332-fcef8280-9c4a-11eb-90a0-a48de367d1a8.png)

**Comment by danpros** [comment]
Hello,

Thanks for reporting this but at least we need admin access to add it (HTMLy is safe as long as you don't hack your own blog). On any system if you can gain admin access it will be a disaster. 

I will look into it.

**Comment by danpros** [comment]
The description mostly used to generate the about widget on sidebar and usually we put a link or even script. Using custom config page we can inject script to our blog eg. for custom comment script, tweet etc. so this is not bug but a feature, and the config page only accessible by the admin. So at the moment I will mark it as won't fix. Thanks.

**Comment by danpros** [comment]
Please re open if non admin users or even not logged user can access and edit the config page.
