### ISSUE TITLE
Code error in a previous pull request

### ISSUE THREAD

**Issue by recolic** [danpros/htmly#458]
Refer to https://github.com/danpros/htmly/blob/e7848acf6fbece6debc449e908a8dcbabec913ae/system/includes/functions.php#L1892
and https://github.com/danpros/htmly/pull/423

I submitted the pull request to change `'{$url}'` to `getAbsolutePath('{$url}');`. It seems that someone fails to merge this in his PR. Please fix.

**Comment by danpros** [comment]
Its fixed now. Thanks.
