### ISSUE TITLE
new add on

### ISSUE THREAD

**Issue by acharjyanisankh** [danpros/htmly#459]
htmly should have inbuilt contact form feature instead of google form

**Comment by danpros** [comment]
To creating our own contact form we need a bit coding so yes there is no simple way except using third party solution. 

HMTLy allow custom template for each static page, category etc. Create `Contact` page (the slug `contact`), create `static--contact.html.php` and than put the email form there. Lot of tuts to creating php contact form on the net, we just need to copy and paste.
