### ISSUE TITLE
Question: Using PHP code in templates

### ISSUE THREAD

**Issue by oleteacher** [danpros/htmly#460]
Hello. I am on the search for a platform to use in school classroom environment since we cannot use mySQL. HTMLY looks perfect!

Doing some testing, found that cannot add php include in templates. Using this:

`<?php include "mathquiz.php"; ?>`

Once placed in a template, the site loads showing the raw page code and not actual HTML layout. 

Is there another way to use include in templates?

Thanks in advance,

Susan

**Comment by oleteacher** [comment]
Little update. I did search before even asking this question, but not right term. Found another issue (here in closed) asking basically same thing...

I added include to post.html.php and it works. Made a page static--mathquiz.html.php in theme root with my test content.

What I was trying to do is add it to layout.html.php sidebar under `<h3 class="widget-title">Stay in Touch</h3`> and that does not work, raw page code shown if using `<?php include "static--mathquiz.html.php"; ?>`. If it matters, using the occasio theme.

**Comment by danpros** [comment]
Hello Susan,

You can try the following, example:

```
<div id="tzwb-quiz" class="widget tzwb-quiz">
	<h3 class="widget-title">Quiz</h3>
	<div class="tzwb-content tzwb-clearfix">
	<?php $quiz = get_static_post('mathquiz');?> // static post slug `mathquiz`
	<?php echo $quiz[0]->body;?>					
	</div>
</div>
```

The available tag:

```
$quiz[0]->url;
$quiz[0]->title;
$quiz[0]->body;
$quiz[0]->readTime;
```

To insert sub page content, you can using:

```
<?php $mySub = get_static_sub_post('parent-page-slug', 'sub-page-slug'); ?>
<?php echo $mySub[0]->body;?>
```

If you just want to include specific php file:

```
<?php include 'your-php-file.php';?>
```

**Comment by oleteacher** [comment]
Thank you for the reply and the great info. Makes me see just how universal HTMLY is!

When trying to add manually to file with sidebar, the result is raw code shown in browser instead of the html layout. I have tried it with 3 themes and all the same results.

If I add `<?php include 'your-php-file.php';?>` anywhere in layout.html.php, it totally breaks the site. Raw html code is displayed in browser instead of the actual layout. Same result in any theme I have tried.

**Comment by danpros** [comment]
The `get_static_post` and `get_static_sub_post` limitation is only get the content from the .md file and not the template file. 

Current text editor accept html tag and script so try to put the html into text editor. For the php script just put it in `layout.html.php`

**Comment by oleteacher** [comment]
Ok, thanks. When you get time, try to introduce a php include into layout.html.php. Try on fairly or occasio. You will see that it does not work.

**Comment by danpros** [comment]
I can include PHP file directly to the template, try to clearing the cache if it not show up. I can include the let say `static--about.html.php`.

**Comment by oleteacher** [comment]
Yes, I cleared the cache every time during my testing. Once I add `<?php include 'your-php-file.php';?>`, all I get is raw HTML in browser like https://i.imgur.com/bGm5Diq.jpg

I have exhausted all my knowledge on the issue, guess it was just not meant to be.

Thank you very much for your help.
