### ISSUE TITLE
The title of the main page join the title of other pages

### ISSUE THREAD

**Issue by Kotgo** [danpros/htmly#468]
Please tell me how to change the value of the title so that in static pages and in normal pages, the title of the main page does not join the title of other pages? If a blog has a long title, it is attached to other pages in the title, and this makes the pages not unique. 

**Example.**
**Blog title:** "This is a good blog about the life of pets and their dreams." 
**And if I make a new page, for example:** "How pets like to play." 
Then the top name of the blog is attached to this page and it turns out like this: 
"How pets like to play. This is a good blog about the life of pets and their dreams."

How can I fix this? 
Thanks.

Thanks

**Comment by danpros** [comment]
Hello,

At the moment its hardcoded to functions .php. Perhaps in our next release we can specify it via config page.

**Comment by danpros** [comment]
This has been fixed in latest version. Thanks
