### ISSUE TITLE
404 Not Found after fresh install v2.8.1

### ISSUE THREAD

**Issue by camillo777** [danpros/htmly#471]
Hello,
I did a fresh install of latest version v2.8.1, at the end of installation I got a 404 error.
Uploaded zip, extracted and accessed  http://mydomain/install.php; inserted data and go!

Page is redirected to:

http://mydomain/admin/content

But there is no admin/content folder, is there some rewrite url I have to add?

How to access this folder?
http://mydomain/admin
I cannot find any doc or config about this "admin" folder.

Apache Version: 2.4.46
PHP Version: 7.3.28

Thank you
Camillo

**Comment by danpros** [comment]
Hello,

Yes it need mod_rewrite for apache, example config: https://docs.htmly.com/web-servers/apache

**Comment by camillo777** [comment]
Hello @danpros 
Thank you but in that page i do not see any mention at the rewrite module, something like this:

RewriteRule ^prodotto/([0-9]+)/$ /prodotti.php?codice=$1

I usually see this configuration in .htaccess file.

**Comment by ProjectPatatoe** [comment]
@camillo777 The rewrite rules are in the .htaccess. Perhaps check if mod_rewrite is available / enabled. On ubuntu `sudo a2enmod rewrite` and then restart apache2.

**Comment by camillo777** [comment]
> @camillo777 The rewrite rules are in the .htaccess. Perhaps check if mod_rewrite is available / enabled. On ubuntu `sudo a2enmod rewrite` and then restart apache2.

Yes I know, but don't know how to set them for htmly.
Is htmly install php supposed to write them into .htaccess file or am I supposed to write them?
And I don't find any docs explaining how to set them for htmly.

Prestashop for example automatically write them to .htaccess file.

Thank you

**Comment by ProjectPatatoe** [comment]
The default .htaccess already has rewrite enabled. The site definition will need "AllowOverride All" or something similar for the .htaccess to take effect. Are you able to post your site definition?

**Comment by camillo777** [comment]
Hello @ProjectPatatoe ,
this is my current .htaccess file:

`# php -- BEGIN cPanel-generated handler, do not edit
# Set the “ea-php73” package as the default “PHP” programming language.
<IfModule mime_module>
  AddHandler application/x-httpd-ea-php73 .php .php7 .phtml
</IfModule>
# php -- END cPanel-generated handler, do not edit`

**Comment by ProjectPatatoe** [comment]
is this .htaccess the one in the root of htmly? Have you tried using the default one first?

Could you share your site definition file from apache? On ubuntu this is located in /etc/apache/sites-enabled/whatever-site-used

**Comment by camillo777** [comment]
Hello,
Sorry for the delay, I think I just need an example of Rewrite Rules for Apache, that's all.
I see there is an example for Lighttpd, but not for Apache web server.
Can anyone help?
Thank you!

**Comment by ProjectPatatoe** [comment]
https://github.com/danpros/htmly/blob/master/.htaccess

I would suggest to try using the original .htaccess that is included first. Inside, it will enable the rewrite engine if it is available.

**Comment by camillo777** [comment]
Thank you @ProjectPatatoe 
I added this to my exisitng ".htaccess" file and indeed it seems to work! :-)
I woyld suggest to add this hint to the "Web Server/Apache" docs.
Thank you!

**Comment by danpros** [comment]
@ProjectPatatoe thanks for the follow up. I will close this one.
