### ISSUE TITLE
Not an issue but I can't find a function

### ISSUE THREAD

**Issue by AutomationMan808** [danpros/htmly#473]
I want links a user makes in a post to have a false target   target="_blank">  I can't find the function to add that feature into user posts. I did find this (base target="_blank") use <> instead which gives everything a false target, but I'd rather have internal links open within the page. 

Any thoughts?

Rick

**Comment by danpros** [comment]
Hello,

You can modify the theme directly, for profile page is profile.html.php

**Comment by AutomationMan808** [comment]
> Hello,
> 
> You can modify the theme directly, for profile page is profile.html.php

What's the path to that I cannot find it?
