### ISSUE TITLE
Limit size of tag cloud

### ISSUE THREAD

**Issue by bluebirch** [danpros/htmly#477]
I happen to have a large number of different tags, which results in a (far too) huge tag cloud. I would like to be able to limit the size, either by setting a maximum number of tags for the cloud, or by a threshold that, for example, only tags with more than 2 occurrences is shown.

**Comment by danpros** [comment]
Hello,

That is good idea, we can add an option to set the max tags displayed.

**Comment by bttrx** [comment]
@bluebirch Would you mind to close your issue as it seems to be solved.
