### ISSUE TITLE
Where can I change the search path

### ISSUE THREAD

**Issue by AutomationMan808** [danpros/htmly#479]
I used readfile to port htmly blog index to my main page. The search feature doesn't probably due to virtual links. I need to edit that section.

Rick

**Comment by danpros** [comment]
Hello,

Bit unclear with your goal actually. 

```
<?php     
    if (isset($_GET['search'])) {
        $search = $_GET['search'];
        $url = site_url() . 'search/' . remove_accent($search);
        header("Location: $url");
    }
```

The `/search`/ is in htmly.php

**Comment by AutomationMan808** [comment]
My apologies I need to be able to search from my main index of which htmly is now copied as the main index page with a little PHP from the subfolder where the blog actually resides.

Rick
