### ISSUE TITLE
Redirect content's url

### ISSUE THREAD

**Issue by ariv80** [danpros/htmly#480]
Hi Mr Dan, I have a site that used drupal before, and I want  migrate to htmly

My contents url are :
1. domain.com/categoriesA/content1
2. domain.com/categoriesB/content2
How to redirect urls above tobe : 
1. domain.com/post/content1
2. domain.com/post/content2

**Comment by danpros** [comment]
Hello,

Well you can use htaccess (RedrectMatch), try to experiment it first in your localhost.

Example:

```
RedirectMatch 302 ^/categories(.*)/(.*) /post/$2
```

**Comment by ariv80** [comment]
ok thankyou, I will try this
