### ISSUE TITLE
Menu editor

### ISSUE THREAD

**Issue by ariv80** [danpros/htmly#483]
there is a bug in menu editor... I have menu by category

1. categoryA, slug = /category/categoryA
2. categoryB, slug = /category/categoryB
3. categoryC, slug = /category/categoryC

when I click menu categoryA the url is domain.com/category/categoryA
then I click menu categoryB the url is domain.com/category/categoryA/category/categoryB
and so on.
or if I click article then I click menu categoryA the url is domain.com/post/category/categoryA
and so on
How to fix it?

**Comment by danpros** [comment]
Hello,

Please add slash before the slug, eg. `/category/categoryA`
