### ISSUE TITLE
Tag recreated from file name (?) instead of tag comment in file

### ISSUE THREAD

**Issue by bluebirch** [danpros/htmly#486]
For some reason, tag names are created from file names, not from the `<!--tag tagname tag-->` in the markdown files, resulting in all tags being lowercase and some tags having really weird names.

Example:

![Screenshot of broken tag names](https://user-images.githubusercontent.com/4832639/127501278-bb613ec8-7cd7-41f8-a2f0-6bf1204caab6.png)

The tags "Agnäsbacken" and "Bjurholm" I have fixed by editing the corresponding blog entries and saving them again. But I can't do that will *all* posts!

Sometimes, numbers (current date and time) is added to the tag names as well.

**Comment by bluebirch** [comment]
It's the `tags.lang` file that is broken. Can this be recreated somehow?

**Comment by bluebirch** [comment]
The solution in #246 is not applicable, since only tags in that particular post is updated -- and the tags are also suffixed with the current date.

**Comment by bluebirch** [comment]
I made a quick and dirty Perl hack to recreate the `tags.lang` file, but I think this should be a function available in the admin panel.

**Comment by danpros** [comment]
Seems already fixed. I will close this one. Thanks
