### ISSUE TITLE
login function uses PHP_SESSION_NONE

### ISSUE THREAD

**Issue by Hjertesvikt** [danpros/htmly#487]
Currently in /system/includes/session.php there is:
if (session_status() == PHP_SESSION_NONE) return false;

Shouldn't it be?
if (session_status() != PHP_SESSION_ACTIVE) return false;

As:
PHP_SESSION_DISABLED if sessions are disabled.
PHP_SESSION_NONE if sessions are enabled, but none exists.
PHP_SESSION_ACTIVE if sessions are enabled, and one exists.

Thanks!

**Comment by danpros** [comment]
This just checking whether the specific session already available/started or not. I will close this one. Thanks.
