### ISSUE TITLE
Softculous Theme Adding Issues 

### ISSUE THREAD

**Issue by dustin2551** [danpros/htmly#488]
![Picture1](https://user-images.githubusercontent.com/28645433/128551214-5d4bbe1f-6cda-434f-822d-a0f32d4ee6b9.png)

How do I fix this issue? It happen on any theme I add that's not built in Softaculous already.

I am using Softaculous as the installer in cPanel Manager v3.

**Comment by Vdriod** [comment]
How about you check config file to see if your web address begins with https:// or http://

**Comment by dustin2551** [comment]
It starts with both of those.
