### ISSUE TITLE
[Question] Can Publii Themes be Ported to HTMLy?

### ISSUE THREAD

**Issue by Suleman-Elahi** [danpros/htmly#490]
For example, consider this theme: https://marketplace.getpublii.com/product/technews/

This theme is similar to HTMLy's Occasio but a bit more polished. I wonder how much of a work it would be to port that Publii theme to HTMLy? Any ideas?

Thanks

**Comment by danpros** [comment]
This issue created during my hiatus back then. Well porting a theme to htmly is not that hard actually, please read the [docs](https://docs.htmly.com/theming). I will try to create a tutorial on how to crating a htmly theme later. I will close this one. Thanks.
