### ISSUE TITLE
PHP Warning: readfile() has been disabled for security reasons in /home/mysite/public_html/mysite.com/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-cache.php on line 180

### ISSUE THREAD

**Issue by arianfar62** [danpros/htmly#491]
hello every one

I had this error in error log file in  root folder of site:

PHP Warning:  readfile() has been disabled for security reasons in /home/mysite/public_html/mysite.com/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-cache.php on line 180

i changed

readfile( $cache_filepath );
to
echo file_get_contents ( $cache_filepath );

in class-cache.php on line 180

By this change, My problem was solved!
But the question:
Do this change , Creates any problem In wp-rocket plugin performance?

What do these changes mean?
echo file_get_contents ( $cache_filepath );

thank you [mrhomestay](https://github.com/mrhomestay) and everybody

_Originally posted by @arianfar62 in https://github.com/danpros/htmly/issues/143#issuecomment-899369933_

**Comment by Vdriod** [comment]
Are you sure you are referring to htmly software?

**Comment by arianfar62** [comment]
thank you [Vroid ](https://github.com/Vdriod)for replay

I Get Help from Under issuecomment and I followed it:
[https://github.com/danpros/htmly/issues/143#issuecomment-75504080](https://github.com/danpros/htmly/issues/143#issuecomment-75504080)

I am not developer!
I have some error or warning in my error_log file and I try resolve them.

What I did , Does it damage the site?

**Comment by Hjertesvikt** [comment]
It might be that it is an issue with your host provider, if that's true maybe you could ask for their advice to the plugin's creators [on their GitHub page](https://wp-rocket.me/support/?utm_source=github&utm_medium=wp_rocket_profile)?

Best luck!

**Comment by arianfar62** [comment]
Oh
This is a great tip
I will definitely follow up on the issue through the link you sent.
Thank you very much
I hope everyone is happy with you.
