### ISSUE TITLE
Blank screen after publish post

### ISSUE THREAD

**Issue by vallyol** [danpros/htmly#505]
There are problems with creating posts.
After publishing the post (and saving the draft), the site stops working (blank screen). Also a blank screen in the admin panel on pages /admin/posts, /admin/draft and /admin/mine.
Publishing static pages does not cause problems.

Deleting a md-file (in the file system) returns the functionality of the admin panel and the site itself.

The problem is not related to themes. I have activated each of the pre-installed themes - it is not possible to post a post.
Changed permissions to access files and directories. Now 777 is installed - the result is the same: after publishing a post or saving a draft, I see a blank screen instead of a website. 

HTMLy - v. 2.8.1
php - v. 7.2
Site with ssl

**Comment by Hjertesvikt** [comment]
Can you enable the display of PHP errors?

**Comment by vallyol** [comment]
@Hjertesvikt 
Yes! Log:
`[Mon Nov 01 13:39:28 2021] [error] [pid 6203] sapi_apache2.c(362): 
[client client_IP:49208] PHP Fatal error:  
  Uncaught Exception: DateTime::__construct(): Failed to parse time string (Val) at position 0 (V): The timezone could not be found in the database in /public_html/system/includes/functions.php:305\nStack trace:\
  n#0 /public_html/system/includes/functions.php(305): DateTime->__construct('Val')\
  n#1 /public_html/system/includes/functions.php(742): get_posts(Array, 1, '10')\
  n#2 /public_html/system/htmly.php(863): get_profile_posts('Admin Web ', 1, '10')\
  n#3 /public_html/system/includes/dispatch.php(506): {closure}()\
  n#4 /public_html/system/includes/dispatch.php(570): route('GET', '/admin/mine')\
  n#5 /public_html/system/htmly.php(3597): dispatch()\
  n#6 /public_html/index.php(5): require('...')\
  n#7 {main}\n  thrown in /public_html/system/includes/functions.php on line 305`

Server PHP info
`date/time support | enabled
timelib version | 2016.05
"Olson" Timezone Database Version | 2018.7
Timezone Database | internal
Default timezone | Europe/Moscow`

On the same server, I have 7 sites on Wordpress and 2 on Drupal. There are no problems with time zones anywhere. 
The timezone value (Europe/Moscow) in the HTMLy settings was set automatically.

**Comment by Hjertesvikt** [comment]
Maybe this would help:
https://stackoverflow.com/questions/34861317/datetime-timezone-not-found-in-database

But this part of the code is old and nobody complained until now.

Could you provide what tells your config/config.ini for time zone?
For myself it is:

> ; Your timezone
> timezone = "Europe/Paris"

**Comment by vallyol** [comment]
@Hjertesvikt 
My config (zone part)

> ; Your timezone
timezone = "Europe/Moscow"
; Date format. See: https://www.php.net/manual/en/function.strftime
date.format = "%d %B %Y"

I honestly don't understand why the claim is to the time zone. Everything is beautiful there in the code.

I have a guess. Which is associated with the username. I have a space in my username (for security reasons, I always add a space inside the username). I guess the problem comes from here ... 

`$filepath = $v['dirname'] . '/' . $v['basename'];
`
Is that possible?

**Comment by vallyol** [comment]
@Hjertesvikt  and All!!!

I solved the problem!

To do this, I created a new user with a regular nickname (only letters, no special characters). The system works perfectly and without errors
