### ISSUE TITLE
Seperate options for activating access counter and popular widget

### ISSUE THREAD

**Issue by sb0001** [danpros/htmly#506]
I'd suggest to make two options available:
1. option: activate counter for accessed pages
2. option: show popular widget (only available if above is active)

As an alternative the existing fields in *configuration>widgets* could be used like this:
1. Rename "*Popular_posts_widget*" to "*Activate access counter*"
2. If "*Popular_posts_widget_at_most*" equals 0 the widget itself will be hidden

**Comment by danpros** [comment]
Please create a pull request. Apologies this issue created during my hiatus back then. I will close this one. Thanks
