### ISSUE TITLE
How to override functions in HTMLy?

### ISSUE THREAD

**Issue by vallyol** [danpros/htmly#507]
Hi All!
If my question seems stupid - excuse me)

Question: how to override (or add your own) function without changing the platform source code?

For example.
I want to use the built-in image uploader to load images in webp format.
The easiest way is to $whitelist the image format. But then, to support php versions less than 7.1, I need to create my own handler and include it in the upload.php file.
In any case, I am changing the source code of the platform. And my additions will get lost on update ...

Now I have created a text file in the root of the site, in which I describe the changes as "line number: + or - changed". It's bad ...

Thanks!

**Comment by AutomationMan808** [comment]
I'm no expert, but could you use an include statement somehow so you would only have to write one line of code when there's an update?

**Comment by Hjertesvikt** [comment]
I never used them but aren't plugins designed for that usage?

**Comment by AutomationMan808** [comment]
I've never used plugins but I have added lines of php code to the Functions.php. When I can't do that I edit the layout.html.php in themes but, that would be overwritten and is proprietary to that theme. I'm sure someone more knowledgeable will come up with a better solution.

**Comment by vallyol** [comment]
@Hjertesvikt 
Yes, right.
It is a pity that the "plugins" catalog is empty. No examples, like "Hello Dolly" :) 
To understand how these plugins must be included...

@AutomationMan808 
> When I can't do that I edit the layout.html.php in themes but, that would be overwritten and is proprietary to that theme

I will try something like that. Only I will first make my own theme ...

Friends, sorry for, maybe stupid questions. I use HTMLy only a few days. Until all system files looked...

Thanks!

**Comment by vallyol** [comment]
Friends, I settled on this solution:
custom theme + functions file in theme directory. 
Then I just connect it to layout.html.php template (require_once). 

Everything works and overrides :)

The easiest way, IMHO

@AutomationMan808 - thanks for the idea!

**Comment by Hjertesvikt** [comment]
It's good that found a solution for your needs :-)
I was not aware that plugins disappeared (I use a much modified and quite old version of HTMLy). Now the plugins are in the system/vendor folder and are updated with composer.

**Comment by vallyol** [comment]
@Hjertesvikt 
> Now the plugins are in the system/vendor folder and are updated with composer.

Yes... I saw.
Now you will have to write three times more code :)  OOPHP ...
