### ISSUE TITLE
Long Chinese titles translate to too long file names for HTMLy's cache

### ISSUE THREAD

**Issue by Hjertesvikt** [danpros/htmly#510]
I have a few posts in Chinese on my site, but when they are read, there is an unsuccessful attempt to put them in cache because the file name is too long due to the URL encoding conversion that triple the length.
For example:
`突触核蛋白敲低肽的开发及其在帕金森病模型中的疗效评估`
becomes:
`%E7%AA%81%E8%A7%A6%E6%A0%B8%E8%9B%8B%E7%99%BD%E6%95%B2%E4%BD%8E%E8%82%BD%E7%9A%84%E5%BC%80%E5%8F%91%E5%8F%8A%E5%85%B6%E5%9C%A8%E5%B8%95%E9%87%91%E6%A3%AE%E7%97%85%E6%A8%A1%E5%9E%8B%E4%B8%AD%E7%9A%84%E7%96%97%E6%95%88%E8%AF%84%E4%BC%B0`
I manage that by forbidding cache in the case of a too long file name but I wonder if it makes sense to encode URLs when caching them?

**Comment by danpros** [comment]
Hello,

`$_SERVER['REQUEST_URI']` is always url-encoded so now htmly decoded it back before save it as cache filename. See [eb495f2](https://github.com/danpros/htmly/commit/eb495f2525f88ed413e9bd2ae9ff5ba544ab77e5)

Thanks,

**Comment by danpros** [comment]
This has been fixed in master branch. Thanks
