### ISSUE TITLE
Where is the code to generate the rss feed?

### ISSUE THREAD

**Issue by AutomationMan808** [danpros/htmly#516]
I want to add a guid to the feed so I can use the online rss feed service I use post updates to my already existing posts.

Thanks
Rick

**Comment by bttrx** [comment]
https://github.com/danpros/htmly/blob/master/system/includes/functions.php#L2330
https://github.com/danpros/htmly/tree/master/system/vendor/suin/php-rss-writer/src/Suin/RSSWriter

**Comment by AutomationMan808** [comment]
Thank you
