### ISSUE TITLE
Search () function not working

### ISSUE THREAD

**Issue by 20pictures** [danpros/htmly#518]
I have tried searching for known elements in posts ...but the result is always a fail

**Comment by Hjertesvikt** [comment]
Search works satisfactorily for me, at least most of the time.
What is your website?

**Comment by 20pictures** [comment]
Blog not live yet. All my pages are Static ...does this make a difference ...I just read the search is for Tags only?

**Comment by Hjertesvikt** [comment]
> I just read the search is for Tags only?
It's quite possible, the best thing would be to look at the code.
My HTMLy site is not standard but search() uses this code:
    $posts = get_keyword($keyword, $page, $perpage);
So yes it is perhaps only for tags.

**Comment by 20pictures** [comment]
Thanks ...I'll look into that.
