### ISSUE TITLE
Error while installing 

### ISSUE THREAD

**Issue by cinetube** [danpros/htmly#521]
```
Fatal error: Uncaught Error: Class "ZipArchive" not found in /var/www/html/online-installer.php:4336 Stack trace: #0 /var/www/html/online-installer.php(4312): Updater->unZip() #1 /var/www/html/online-installer.php(4547): Updater->update() #2 /var/www/html/online-installer.php(4534): Settings->install() #3 /var/www/html/online-installer.php(4501): Settings->runForm() #4 /var/www/html/online-installer.php(4566): Settings->__construct() #5 {main} thrown in /var/www/html/online-installer.php on line 4336
```

I am getting this error while installing htmly. How to resolve this error?

**Comment by ca-rso-n** [comment]
Did you unzip it?

**Comment by taufik-nurrohman** [comment]
You are missing PHP `zip` extension on your server.

**Comment by cinetube** [comment]
> You are missing PHP `zip` extension on your server.

php zip extension is installed on the server but still getting this issue.

**Comment by nosbig** [comment]
Did you restart the Apache process after installing the zip extension?  How did you install the extension?  If you run a phpinfo() call, does php-zip show up as an active module in your PHP installation?

**Comment by danpros** [comment]
I will close this one. Thanks.
