### ISSUE TITLE
Title autocomplete

### ISSUE THREAD

**Issue by dotziph** [danpros/htmly#524]
![image](https://user-images.githubusercontent.com/52331073/152661384-c803af79-fc87-4956-b788-a2dc55e3531a.png)
This really bugs me and probably a few other people. I did try fixing it myself but I don't know that much about coding. Also thank you for making this its really great and easy to setup.

**Comment by bttrx** [comment]
That's a feature of your web browser. You could either clear your browser's cache before adding a new post or by removing previous entries from the list by pressing the `Del` key when the entry is highlighted.

**Comment by dotziph** [comment]
> 

Thanks! But still adding something to have it not happening would be great.

**Comment by Hjertesvikt** [comment]
Hi dotziph,
Please can[ you try if this could be coded](https://www.codingnepalweb.com/search-bar-autocomplete-search-suggestions-javascript/) in your theme?
thanks!
