### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by dotziph** [danpros/htmly#526]
This would be a great option for readers and posters alike. Having it not hard-coded into the website also allows for a preference. If you would like help making themes into a dark mode, I could help.

**Comment by dirmanhana** [comment]
hi, I just created a theme where you can change at will to dark mode or light
![water](https://user-images.githubusercontent.com/35218057/159422603-9830fac9-1d10-4628-b281-c7695e22e4b5.png)

**Comment by ca-rso-n** [comment]
Would be nice if official ones had this.

**Comment by danpros** [comment]
Thanks @dirmanhana
