### ISSUE TITLE
PayPal subscription pull down menu not working

### ISSUE THREAD

**Issue by AutomationMan808** [danpros/htmly#527]
It just goes to PayPal itself but doesn't pass any information. I solved it temporarily by using a flexible iframe, but if there's some code I can change that would be great.

Rick

**Comment by ca-rso-n** [comment]
This isn't part of htmly so why did you make a issue ticket?

**Comment by AutomationMan808** [comment]
It's an HTMLy issue because paypal subscription pull down menu code will not work in the GUI. PayPal is a popular payment gateway. If users cannot put code in to make a PayPal pull down menu work as we can with other HTML code that's an issue.

**Comment by AutomationMan808** [comment]
Working now. My working theory is I tested it while on school WIFI. I have the school's wifi security mess with my scripts before.

Thanks all
Rick

**Comment by ca-rso-n** [comment]
Again not something to make a ticket about you are adding something to the code it's not something they put in.
