### ISSUE TITLE
 Menu, no way to configuree it and to use it

### ISSUE THREAD

**Issue by gillesMioni** [danpros/htmly#528]
If we can create a menu. It seems there is no way to 
to use it and complete it with items.
Is there some examples of menus?
Thanks for a littele help.

**Comment by Hjertesvikt** [comment]
Yes it would be nice to have a way to create and manage menus. On my site I created them the old way by inserting HTML in layout.html.php

To make things smoother in case of changes, I make the changes in a header.html and footer.html and include those files automatically in layout.html.php.

But I do not know how to manage them from an admin interface.
<head>
...
        <script type="text/javascript" src="<?php echo site_url(); ?>/theme/js/includefiles.js"></script>
    </head> 
...

         
        <div class="container"> 
            <div include-header="/theme/header.html"></div> 
            <script>
                includeHTML("include-header");
            </script>
...

        <footer class="footer">
            <div class="container text-center">
                <div include-footer="/theme/footer.html"></div> 
                <script>
                    includeHTML("include-footer");
                </script>
            </div>
        </footer>

Here is the content of includefiles.js:

function includeHTML(div_to_rewrite) {
  var z, i, elmnt, file, xhttp;
  /*loop through a collection of all HTML elements:*/
  z = document.getElementsByTagName("*");
  for (i = 0; i < z.length; i++) {
    elmnt = z[i];
    /*search for elements with a certain atrribute:*/
    file = elmnt.getAttribute(div_to_rewrite);
    if (file) {
      /*make an HTTP request using the attribute value as the file name:*/
      xhttp = new XMLHttpRequest();
      xhttp.onreadystatechange = function() {
        if (this.readyState == 4) {
          if (this.status == 200) {elmnt.innerHTML = this.responseText;}
          if (this.status == 404) {elmnt.innerHTML = "Page not found.";}
          /*remove the attribute, and call this function once more:*/
          elmnt.removeAttribute(div_to_rewrite);
          includeHTML();
        }
      }      
      xhttp.open("GET", file, true);
      xhttp.send();
      /*exit the function:*/
      return;
    }
  }
};

**Comment by bttrx** [comment]
> If we can create a menu. It seems there is no way to to use it and complete it with items. Is there some examples of menus? Thanks for a littele help.

By default, you create a static page for each menu entry. Each static page will be added right after the "Home" link.

Is it that, what you mean?

**Comment by gillesMioni** [comment]
I'm referring to **menuEditor** admin function:
"At the moment, you are using _auto generated_ menu"
I didn't succeed to generate one.
Probably, I do not know how to use that function.
Must create static pages?

**Comment by bttrx** [comment]
> I'm referring to **menuEditor** admin function: "At the moment, you are using _auto generated_ menu" I didn't succeed to generate one. Probably, I do not know how to use that function. Must create static pages?

Yes, you have to create static pages.

**Comment by danpros** [comment]
I will close this one.
