### ISSUE TITLE
Create a static page without an automatic menu item

### ISSUE THREAD

**Issue by CharliePoole** [danpros/htmly#536]
I'm trying to create a static page, which is linked only from a particular post. I don't want it to appear as a menu item.

I was able to do this by creating menu items for all the pages I __do__ want to appear... but that's a lot of pages in my case. I would prefer to use automatic menu building and just exempt a single file from the menu. My current workaround is to use a link to an external page, but that's not ideal. If there were some setting in the creation of a static page, which told HTMLy whether to create a menu item, that would seem like the ideal approach.

**Comment by dirmanhana** [comment]
you can set it in the editor menu
![image](https://user-images.githubusercontent.com/35218057/159422253-121384d2-8d93-4cbf-ae44-5cb4a700226c.png)

**Comment by CharliePoole** [comment]
Sorry... I didn't explain well.... I akready do as you suggest.

But I wanted to use automatic menu items EXCLUDING a certain page... maybe with a check box in the page editor to generate or not generate a menu for that page. Is that a feature you would accept?

**Comment by dirmanhana** [comment]
if you enable custom menu, your static page should not automatically enter the menu bar

**Comment by CharliePoole** [comment]
How can I enable custom menu for a single page but not for others?

**Comment by bttrx** [comment]
> but that's a lot of pages in my case

And expressed in a number?

**Comment by CharliePoole** [comment]
One static page for each person in my family tree... 500 or so.

**Comment by bttrx** [comment]
No offense, but why on earth you want to do this with HTMLy?
Maybe a flat-file CMS or wiki like, e.g., DokuWiki or PmWiki, better fits your needs.

**Comment by CharliePoole** [comment]
None taken. I'm experimenting with several apps and HTMLy sounded like a possibility. 
Funny, I had forgotten about DokuWiki... I used it some years back for software documentation.

**Comment by danpros** [comment]
Please use the Menu Editor instead. I will close this one. Thanks

**Comment by CharliePoole** [comment]
That's too bad. Of course I've worked around the issue by now anyway.

Back when I asked if you'd accept a PR for the feature, I had time on my hands, which I no longer do anyway. From one open source guy to another... that's what happens if you don't give volunteers a yes/no answer fairly quickly. I've probably done the same myself once or twice. :-(
