### ISSUE TITLE
Guest bloggers?

### ISSUE THREAD

**Issue by AutomationMan808** [danpros/htmly#540]
Is there a way to have guest bloggers?

**Comment by dirmanhana** [comment]
actually you can create more than 1 user other than admin

**Comment by AutomationMan808** [comment]
Guess not

**Comment by AutomationMan808** [comment]
Found it!
Config>users>copy username.ini.example
Make the person writer instead of admin
Tried making two writers. They could not see each others drafts.

More hidden jewels via HTMLy programmers thank you!

**Comment by AutomationMan808** [comment]
Oops sorry
