### ISSUE TITLE
Export posts to wordpress

### ISSUE THREAD

**Issue by badstue** [danpros/htmly#542]
Hi,
Are there an easy way to export all content from our HTMLy blog to wordpress?
But that I will abandon HTMLy. I just need some content from a HTMLy blog, to be used in a wordpress setting instead.

I tried a Import markdown plugin, but that was only taking 1 file at a time.

**Comment by badstue** [comment]
Am I the only one that want this feature?

**Comment by Hjertesvikt** [comment]
I guess it's more an issue for Wordpress than for HTMLy?
Can you download this plugin and modify it according to your needs?
[****](https://wordpress.org/plugins/import-markdown/)

**Comment by badstue** [comment]
@Hjertesvikt Thanks for the tip. I already tried that. But in the current state, the plugin cannot import more than 1 post per import. And I don't have the skills to modify it.

**Comment by dolibarr95** [comment]
@badstue maybe just have to edit the _import-markdown.1.09.zip\import-markdown\admin\view\import.php_ file to select several files instead of just one?

**Comment by JPLeRouzic** [comment]
Please could it be possible to close this issue?
