### ISSUE TITLE
RSS feed by category

### ISSUE THREAD

**Issue by thopanX** [danpros/htmly#543]
Is there a way to generate another feed based off of a category? Or filter the feed to a category?

**Comment by AutomationMan808** [comment]
The category is in the feed so you could parse it yourself off the original feed.

**Comment by JPLeRouzic** [comment]
Please could it be possible to close this issue?

**Comment by bttrx** [comment]
Why shall this be closed? I understand it as a valid feature request.

**Comment by JPLeRouzic** [comment]
Did not @AutomationMan808 provided a good alternative?

**Comment by bttrx** [comment]
> parse it yourself off the original feed

Are we talking about the feed reader site here? Not everybody has a reader allowing parsing or filtering.

**Comment by JPLeRouzic** [comment]
That true, sorry for any inconvenience.

**Comment by bttrx** [comment]
No problem. Your energy regarding HTMLy is welcome!

**Comment by danpros** [comment]
This feature already added in master branch. Simply add `/feed` to any posts collection (category, tag, type, archive, search, author) to generate feed. Example: `example.com/tag/newsletter/feed` or `example.com/author/username/feed`

**Comment by danpros** [comment]
@thopanX Yes, you can test it in localhost for insight. You're welcome!

**Comment by danpros** [comment]
This feature has been added in the latest release. I will close this one.
