### ISSUE TITLE
Any directions on installing HTMLy on Linux Mint

### ISSUE THREAD

**Issue by AutomationMan808** [danpros/htmly#545]
I'm new to installing onto Linux. I've only installed HTMLy on website servers.

Thanks
Rick

**Comment by taufik-nurrohman** [comment]
Linux Mint derived from Ubuntu. You can search for a way to install LAMP stack. Since HTMLy is flat-file, you can focus only on how to install Apache web server and PHP environment.

**Comment by AutomationMan808** [comment]
I found this which was very helpful https://websiteforstudents.com/install-htmly-cms-on-ubuntu-16-04-18-04-lts-with-apache2-php-7-2-support/
Unfortunately after clicking the install button I received a page not found error. This is probably my own lack of experience.
Rick

**Comment by AutomationMan808** [comment]
It gets stuck right here right after clicking install
http://blah.localhost/add/content?type=post

Not Found
The requested URL was not found on this server.

Apache/2.4.29 (Ubuntu) Server at blah.localhost Port 80

**Comment by taufik-nurrohman** [comment]
Make sure `mod_rewrite` module is enabled.

**Comment by AutomationMan808** [comment]
Thank you for the reminder. I had done that as part of the setup.

**Comment by AutomationMan808** [comment]
Found it! $sudo chmod -R 777 /opt/lampp/htdocs

Thank you for your help
