### ISSUE TITLE
Meta tags for facebook and twitter

### ISSUE THREAD

**Issue by btc-usd** [danpros/htmly#546]
- need to add meta tags for facebook graph and twitter card
- option to disable category (no category)

**Comment by graphixela** [comment]
They should be native. In case anyone needs them.
    <meta name="twitter:card" content="summary"/>
    <meta name="twitter:title" content="<?php echo $p->title;?>"/>
    <meta name="twitter:description" content="<?php echo $p->description;?>"/>
    <meta name="twitter:url" content="<?php echo $p->url;?>"/>
    <meta name="twitter:image" content="<?php echo $p->image;?>"/>
    <meta property="og:url" content="<?php echo $p->url;?>"/>
    <meta property="og:type" content="article"/>
    <meta property="og:title" content="<?php echo $p->title;?>"/>
    <meta property="og:description" content="<?php echo $p->description;?>"/>
    <meta property="og:image" content="<?php echo $p->image;?>"/>

**Comment by JPLeRouzic** [comment]
Please could it be possible to close this issue, as it looks to be just creating another theme?

**Comment by danpros** [comment]
This feature has been added. I will close this one.
