### ISSUE TITLE
Http vs. Https

### ISSUE THREAD

**Issue by weblord** [danpros/htmly#547]
Hello there,
Hoping you are all in excellent condition when this email reaches you.

Images and blog entries are out of place?

How come when i present
http://blog.nabaza.com
as insecure the layout are good, but when i present it as secure
https://blog.nabaza.com
the layout became bad and all blog entries seem to be out of place?

Please kindly help and guid me on what I'm doing wrong.

Thank you very much for superb support.

**Comment by Hjertesvikt** [comment]
Please check all links in your page. You could also use Chromium developer's tools.
There are many errors in your page, for example:

> Mixed Content: The page at 'https://blog.nabaza.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://blog.nabaza.com/themes/clean/css/style.css'. This request has been blocked; the content must be served over HTTPS.

**Comment by weblord** [comment]
Hello,
How do I replace this with secure http:
<link href="<?php echo site_url() ?>themes/clean/css/style.css" rel="stylesheet"/>

**Comment by weblord** [comment]
Sorry for not telling at the start.
I'm not a programmer or even a modder.
I just needed something of a database less blog because I ran out of databases. So now came htmly.

This template that im using on blog.nabaza.com i just downloaded the default theme actually never remembered that i've downloaded it. It comes with the htmly default files.

Back those days, non-secure http is ok until chrome interferes and it became https:// which is ok for me since I'm all for security as we all are here.

Seems like htmly templates  just like the one Im using is the clean template. 
Can someone be requested here for free to rewrite this time a htmly clean template for https:// ?

> The function site_url() basically outputs what you wrote as "site.url" in your config page. What did you wrote there?
where can i see that? what file these variables are declared?


> Please check all links in your page. You could also use Chromium developer's tools. There are many errors in your page, for example:
> 
> > Mixed Content: The page at 'https://blog.nabaza.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://blog.nabaza.com/themes/clean/css/style.css'. This request has been blocked; the content must be served over HTTPS.

how to use chrome developer's tools to detect all http and turn into https://?

**Comment by weblord** [comment]
I don't mean to close. sorry

**Comment by Hjertesvikt** [comment]
- You did not answer my question about your config parameters.

> Can someone be requested here for free to rewrite this time a htmly clean template for https:// ?

There is no meaning in this. The code is independent of the fact a web site is able to be used with HTTPS.

What is important is to install a SSL certificate on your HTTP server (Apache/Ningx/etc).

A free SSL certificate is available from Let's encrypt, but it's not that easy to use.

What I do is using Cloudflare free server certificate, then asking Cloudflare to manage all traffic to my website on HTTPS:

https://developers.cloudflare.com/ssl/get-started

> how to use chrome developer's tools to detect all http and turn into https://?
Again this has no meaning.
Chrome's developer tools are a feature of the browser. There is a similar tool in Firefox. It will never make your site available on HTTPS, it's used to detect errors on web sites.

**Comment by Hjertesvikt** [comment]
Frankly you should close this issue, it has nothing to do with HTMLy

**Comment by weblord** [comment]
I already have let's encrypt installed try it with https:// it's not a beauty.

> Frankly you should close this issue, it has nothing to do with HTMLy

yeah you're right, thanks.
