### ISSUE TITLE
2.8.2 – view numbers keep resetting after a while

### ISSUE THREAD

**Issue by thopanX** [danpros/htmly#548]
I noticed it twice now that the view numbers in admin reset to very low numbers or even -1 (as if nobody had viewed the post at all). No update inbetween.

What other info do you need?

**Comment by Hjertesvikt** [comment]
It's a problem several users have encountered and was never solved. I proposed a correction a few months ago. On my web site it never reappeared.
I can't find any trace of my proposal but it involved removing an obsolete section of code which bizarrely should not be called now. 
HTMLy as many other PHP frameworks involves long files, so it makes understanding them and tracing a bug very difficult. What I did was separating htmly.php in mutiple files, one with only one clear function.

**Comment by Hjertesvikt** [comment]
https://github.com/danpros/htmly/issues/366

Danpros says that it was an issue with JSON and should be change with serialized.

My web site still uses old HTMLy code (2.7.5) so what I say may not be applicable to new version of HTMLy.

**Comment by bluebirch** [comment]
I would have thought this issue had to do with concurrent for access our something. One thread of htmly writing while another reading. That sort of problem.

**Comment by gillesMioni** [comment]
@Hjertesvikt Any leads on how to identify these lines of code?
Because with the latest version of HTMLy, an user encountered
this problem very recently.

**Comment by Hjertesvikt** [comment]
[What I proposed was integrated in 2.7.7.](https://github.com/danpros/htmly/issues/366)

@danpros said at the time:

> If the problems still persist I will change to use the serialize in next version and not using JSON.

I suppose he meant in function add_view($page)

**Comment by danpros** [comment]
The latest release should fix this problems. I will close this one. Thanks
