### ISSUE TITLE
Multiple site.urls?

### ISSUE THREAD

**Issue by AmyMoriyama** [danpros/htmly#549]
So, I want to run a website that can be accessed from tor and i2p but htmly doesn't seem to want to allow this. It seems to only want to work with one or the other and it seems it's due to the site.url config in the config file.

Is there a way around this? If not, I request some feature be added to allow multiple site urls.

**Comment by Hjertesvikt** [comment]
Please do not hesitate to submit a patch.

**Comment by neilzone** [comment]
> Is there a way around this?

+1 for the feature request.

I had this working for a while, with a bit of a manual bodge: I had a second instance of htmly, used by the webserver config for the .onion URL. This used symlinks to the files of the main installation, as well as the content directory. I *think* I kept a separate cache as, whenever I wrote a new post, I needed to clear the cache on the Tor instance too.

I meant to take a proper look at it, to see *how* the site.url config is used, and what it would take to extend it to cover multiple URLs (i.e. could relative paths be used in more places, most probably), but never got round to it.

**Comment by ombhs** [comment]
how do i get plugins ?

**Comment by taufik-nurrohman** [comment]
Replace this line:

https://github.com/danpros/htmly/blob/d3b6a67a57321afcb320bc1bbbe57a3ba62c6980/system/includes/dispatch.php#L21

With this:

~~~ php
return rtrim('https://' . $_SERVER['HTTP_HOST'], '/') . '/';
~~~

**Comment by fabianosantosnet** [comment]
> how do i get plugins ?

This feature is not implemented yet.

**Comment by danpros** [comment]
This feature already added in master branch.

**Comment by danpros** [comment]
This feature has been added in the latest release. I will close this one.

**Comment by ashraf21c** [comment]
> Replace this line:
> 
> https://github.com/danpros/htmly/blob/d3b6a67a57321afcb320bc1bbbe57a3ba62c6980/system/includes/dispatch.php#L21
> 
> With this:
> 
> ```
> return rtrim('https://' . $_SERVER['HTTP_HOST'], '/') . '/';
> ```

Where to set the second URL?
- I already enabled "multi-site" in the settings (Config/ Performance), but the question is: where to add the second URL?

> ```
> return rtrim('https://' . $_SERVER['HTTP_HOST'], '/') . '/';
> ```

**Comment by ashraf21c** [comment]
> > Replace this line:
> > https://github.com/danpros/htmly/blob/d3b6a67a57321afcb320bc1bbbe57a3ba62c6980/system/includes/dispatch.php#L21
> > 
> > With this:
> > ```
> > return rtrim('https://' . $_SERVER['HTTP_HOST'], '/') . '/';
> > ```
> 
> Where to set the second URL? I already enabled "multi-site" in the settings (Config/ Performance), but the question is: where to add the second URL?

Temporarily, I disabled the feature and used redirecting instead. It works. However, I would prefer using the built-in feature "named multisite".
