### ISSUE TITLE
Internal server error following installation

### ISSUE THREAD

**Issue by deuxlames** [danpros/htmly#550]
Hello,

I downloaded the lastest version in zip format. I uploaded to the server (I'm using a IONOS hosting). Unzipped and ran the installation. 

Then i get an internal server error as all urls that are not the root one.
I commented the rewrite conditions and the error disapears, but of course i loose all redirections :-(
Any ideas ?

**Comment by Hjertesvikt** [comment]
Wrong .htaccess?

**Comment by fabianosantosnet** [comment]
Maybe there is a wrong php version enabled. Try change it.

To setup the installation go to yoursite.com/install.php

You can try use only this script that download and install
https://github.com/danpros/htmly/releases/download/v2.8.2/online-installer.php

Enable Debug:
https://www.ionos.com/help/hosting/troubleshooting-for-php/enabling-error-logs/

**Comment by danpros** [comment]
I will close this one.
