### ISSUE TITLE
Probleme of array (php) with a new post

### ISSUE THREAD

**Issue by gillesMioni** [danpros/htmly#551]
After created and published a new post, I've this problem when consulting site :
Message seen on the page read :
Warning: array_combine(): Both parameters should have an equal number of elements in .../htmly/system/includes/functions.php on line 346
Warning: Invalid argument supplied for foreach() in .../htmly/system/includes/functions.php on line 347
Warning: Cannot modify header information - headers already sent by (output started at .../htmly/system/includes/functions.php:346) in .../htmly/system/includes/dispatch.php on line 351
I cleared the cache but no effect. 
I've to say I didn't understand the problem.
May I have a little help to find how to fix that?
Thanks.

**Comment by Hjertesvikt** [comment]
This is weird, this is an part of code which works well. I propose you two insert two debugging small patches:

1. Please could you include those two lines of code at the beginning of /system/includes/functions.php, and try to replicate the bug?

ini_set('display_errors', 'On');
error_reporting(E_ALL);

2. Please could insert this between lines 345 and 346
   345       $tl = explode(',', rtrim($tagt, ','));
                 echo '<br>t: ' ;
                 var_dump($t) ;
                echo '<br>tl: ' ;
                 var_dump($tl) ;
   346         $tCom = array_combine($t, $tl);

Do not forget to remove them when the bug will be solved.

**Comment by gillesMioni** [comment]
Thanks a lot for the tips.
But unfortunately, after changing functions.php.
Nothing appears apart a blank line

Modified lines
  _346      if(!empty($tagt)) {
  347          $tl = explode(',', rtrim($tagt, ','));
  348	         **echo '<br>t: ' ;
  349            var_dump($t) ;
  350            echo '<br>tl: ' ;
  351            var_dump($tl) ;**
  352       $tCom = array_combine($t, $tl);_
  
  Message when reading page
  **Warning: array_combine(): Both parameters should have an equal number of elements in .../htmly/system/includes/functions.php on line 346

Warning: Invalid argument supplied for foreach() in .../htmly/system/includes/functions.php on line 347**

**Comment by Hjertesvikt** [comment]
Gilles, vous n'avez pas mis les var_dump à l'endroit que je vous avais indiqué, donc c'est normal de ne rien voir!

**Comment by Hjertesvikt** [comment]
Lines numbers look weird. 
In one case:
**352** $tCom = **array_combine**($t, $tl);
*Warning: **array_combine**(): Both parameters should have an equal number of elements in .../htmly/system/includes/functions.php on line **346**

Are you sure you introduced the var_dumps between 
`$tl = explode(',', rtrim($tagt, ','));`
and
`$tCom = array_combine($t, $tl);`

**Comment by gillesMioni** [comment]
Bonjour,
Merci beaucoup pour votre aide.
Mais, j'ai bien vérifié, j'ai ajouté les lignes
selon vos indications.
Les n° de ligne indiqués ont changé avec
l'ajout des deux premières lignes au début du script
functions.php. À moins de n'avoir pas compris :
_Veuillez inclure ces deux lignes de code au début de /system/includes/functions.php_

**Comment by gillesMioni** [comment]
As I wrote in french, The line numbers shown have changed with
the addition of the first two lines at the beginning of the script
functions.php as indicated:
ini_set('display_errors', 'On');
error_reporting(E_ALL);

**Comment by Hjertesvikt** [comment]
OK, mais les numéros de lignes de code ne correspondent pas aux numéros de ligne des messages d'erreurs!

Dans un cas array_combine est en ligne 352, dans l'autre en ligne 346

**Comment by gillesMioni** [comment]
Voici les modifications apportées à functions.php une image png.
Lien vers mon home Nextcloud [https://gendem5.me/index.php/s/gtJQzanABwCn629](url)

**Comment by Hjertesvikt** [comment]
Dans ce cas on ne peut pas avoir le numéro de ligne suivant dans le message d'erreur:
 ```
  **Warning: array_combine(): Both parameters should have an equal number of elements in .../htmly/system/includes/functions.php on line **_346_**


```

**Comment by gillesMioni** [comment]
Bonsoir,

Le débogage semble fonctionner :
J'ai vidé le cache du navigateur web, relancé, et j'obtiens maintenant ceci sur le post qui désorganise
l'affichage.
_t: array(9) { [0]=> string(16) "fille-a-la-natte" [1]=> string(10) "tymoshenko" [2]=> string(7) "ukraine" [3]=> string(6) "guerre" [4]=> string(5) "khyiv" [5]=> string(6) "trauma" [6]=> string(24) "politique-internationale" [7]=> string(8) "telegram" [8]=> string(20) "devochka-s-kosichkoi" }
tl: array(10) { [0]=> string(17) "fille à la natte" [1]=> string(10) "Tymoshenko" [2]=> string(7) "Ukraine" [3]=> string(6) "Guerre" [4]=> string(6) "Khyïv" [5]=> string(6) "guerre" [6]=> string(6) "trauma" [7]=> string(24) "politique internationale" [8]=> string(8) "Telegram" [9]=> string(34) "Девочка с косичкой" }
Warning: array_combine(): Both parameters should have an equal number of elements in /exports/www/html/gendem5.org/htmly/system/includes/functions.php on line 352

Warning: Invalid argument supplied for foreach() in /exports/www/html/gendem5.org/htmly/system/includes/functions.php on line 353_
Cette valeur de tl => string(34) "Девочка с косичкой" ne correspond pas au nombre de caractères de la chaîne en russe (18 plutôt que 34).
D'autre part, la valeur de t correspondante esst retranscrite en caractère latin => string(20) "devochka-s-kosichkoi"
J'avoue que je ne sais pas intgerprété ce qui ne va pas.
J'avais enlevé cette chaine en cyrilique, mais sans pour autant  régler le problème.
Encore merci pour votre attention à ce problème.

**Comment by Hjertesvikt** [comment]
I write in English again for future readers.
array_combine() will throw a [ValueError] if the number of elements for each array is not equal, which is the case here. 
In $_t array, there are 9 rows and in $tl there are 10 rows, so the function throws an error.

I will try to understand what $_t and $tl represent, to better understand how this mismatch is possible.

By chance do you code recently some new form?

**Comment by Hjertesvikt** [comment]
Did you modify manually a tag in the content folder?

**Comment by Hjertesvikt** [comment]
Did you hard coded a file path in a form, or modified manually a file path?

**Comment by Hjertesvikt** [comment]
I looked at your web site and guess that you modified manually the content of one of those tags:
 "fille-a-la-natte" 
"tymoshenko" 
"guerre" 
 "khyiv" 
"trauma" 
"politique-internationale" 
telegram" 
"devochka-s-kosichkoi"

**Comment by gillesMioni** [comment]
Thanks for the answer.
No, I didn't modify tags in a post neither coded a path nor modify manually a path (I understand change the name of a post and move a post from a directory to another)
I suppressed the post and recreate it within the interface. I tried to modify tags, but with the editor (suppress Cyrillic words).

**Comment by Hjertesvikt** [comment]
You did create two  tags where probably you meant only one:
'Guerre' vs 'guerre'

**Comment by Hjertesvikt** [comment]
![image](https://user-images.githubusercontent.com/28840268/167271192-c8e47738-9b2b-4188-9bb7-82a1d924a4e6.png)

**Comment by gillesMioni** [comment]
I couldn't remember exactly that I wrote within the editor. Especially, I deleted and rewrote the same post several times.
I removed the Cyrillic words without success.
 Obviously, I repeated Guerre and guerre, but in the post source there are the two tags.
 **I am really confused not to have noticed it by myself!**
So if I deleted the superfutory tag, perhaps the problem is solved?
      **Thank you very much for the help**. 
The file name itself and a part of the markdown source
The post that is wrong :
2022-05-07-13-42-04_fille-a-la-natte,tymoshenko,ukraine,guerre,khyiv,trauma,politique-internationale,telegram,devochka-s-kosichkoi_la-fille-a-la-natte.md

the post itself with tags
tag fille à la natte,Tymoshenko,Ukraine,**Guerre**,Khyïv,**guerre**,trauma,politique internationale,Telegram,Девочка с косичкой tag-->
Is it a bug, the fact that two same tags one in tiny letters and the other with the first letter in capital letters is notified only once?

**Comment by gillesMioni** [comment]
All is fine. You did a great job.
Thank you very much for the time spent, and have a nice weekend.

**Comment by Hjertesvikt** [comment]
I agree, there should be some clearer error message, something like:

```
if(count($_t) != count($tl)) { 
echo '<div class="error-message"><?php echo 'You some incorrect tags' ; } ?></div>
```

Anyway I will add that in my own web site:
https://padiracinnovation.org/News/

Jean-Pierre 
(Le Minihic sur Rance)

**Comment by gillesMioni** [comment]
Thanks for your help, Jean-Pierre.
