### ISSUE TITLE
How do I make a child theme?

### ISSUE THREAD

**Issue by graphixela** [danpros/htmly#552]
There's no documentation. Thanks

**Comment by bttrx** [comment]
Sorry, but what is child theme?

**Comment by Hjertesvikt** [comment]
In Wordpress you can modify a theme, not by changing the code in the theme, but by changing code in a child theme. That way when the theme is updated (which can be done automatically on Wordpress) you do not loose your modifications.
I guess Graphixela wants something like that.

**Comment by Hjertesvikt** [comment]
A more general requirement would be the possibility to have user plugins or code snippets (as in Wordpress) that could modify HTMLy without being erased by any update.

**Comment by bttrx** [comment]
> A more general requirement would be the possibility to have user plugins or code snippets (as in Wordpress) that could modify HTMLy without being erased by any update.

This will probably never happen, because the HTMLy website reads: "Ever heard of complaints about unsafe, outdated, and slow plugins for specific CMS out there? We will not follow the same steps. Any new features will be added to the core and go through security audit."

**Comment by bttrx** [comment]
> In Wordpress you can modify a theme, not by changing the code in the theme, but by changing code in a child theme. That way when the theme is updated (which can be done automatically on Wordpress) you do not loose your modifications. I guess Graphixela wants something like that.

I see. A child theme adds an extra layer on top of the existing theme.

**Comment by graphixela** [comment]
Yes, just a simple child theme. I imagine the themes aren't updated often and would need to be manually approved first but this adds an extra fail safe so you don't lose your work.
[Wordpress has them.](https://developer.wordpress.org/themes/advanced-topics/child-themes/)
[Grav which is a flat file CMS also has them.](https://learn.getgrav.org/17/themes/customization#theme-inheritance)

**Comment by Hjertesvikt** [comment]
> Any new features will be added to the core 
This is not a better route than rogue plugins, because not everybody needs all plugins (I don't) and it creates an unnecessary large security attack surface.

> and go through security audit."
Please can you point out to HTMLy security audit protocol?
Even Wordpress has no security audit official protocol, you only have to trust Automattic (which I don't).

**Comment by Hjertesvikt** [comment]
> Grav which is a flat file CMS also has them.

Frankly Grav is an horribly complex CMS, even Wordpress is preferable for beginners.
It's funny they state that Grav is much simpler than Wordpress, Joomla or Drupal. Because it is so untrue.

**Comment by graphixela** [comment]
> > Grav which is a flat file CMS also has them.
> 
> Frankly Grav is an horribly complex CMS, even Wordpress is preferable for beginners. It's funny they state that Grav is much simpler than Wordpress, Joomla or Drupal. Because it is so untrue.

That's subjective.
I hated Drupal, Joomla and Wordpress. They are all so clunky and dated. I could never do the simplest things in them.
I use Grav on a few of my sites. Initially, I found it to be a bit complex and how to do things were unclear.
I left for OctoberCMS/WinterCMS which I liked a lot. But I wanted to get rid of databases entirely so I went back to Grav.
The second time around I grasped it better and the documentation improved.
Adding custom fields is way simpler than it is for Wordpress or Winter.
Once you learn it, it's easy and there's so much you can do.

**Comment by Hjertesvikt** [comment]
>  left for OctoberCMS/WinterCMS which I liked a lot. But I wanted to get rid of databases entirely 

You can use SQlite with WinterCMS. It's not that different from a flat file database.

**Comment by bttrx** [comment]
> > > Any new features will be added to the core
> 
> This is not a better route than rogue plugins, because not everybody needs all plugins (I don't) and it creates an unnecessary large security attack surface.

I agree, but it was not **my** decision, because I'm not the author of HTMLy.
If you want a system with plugins, maybe [FlatPress](https://www.flatpress.org/) fits better for you, although I found its source code very "dated" and confusing.

> > > and go through security audit."
> 
> Please can you point out to HTMLy's security audit protocol? Even Wordpress has no security audit official protocol, you only have to trust Automattic (which I don't).

Maybe @danpros will do so.

**Comment by graphixela** [comment]
> > left for OctoberCMS/WinterCMS which I liked a lot. But I wanted to get rid of databases entirely
> 
> You can use SQlite with WinterCMS. It's not that different from a flat file database.

It's still a database. I'm happy with the way things are now. I don't want to keep redoing it.

I forgot to mention Moodle was the worst thing I ever worked with. I just gave up.

**Comment by graphixela** [comment]
> > > > Any new features will be added to the core
> > 
> > 
> > This is not a better route than rogue plugins, because not everybody needs all plugins (I don't) and it creates an unnecessary large security attack surface.
> 
> I agree, but it was not **my** decision, because I'm not the author of HTMLy. If you want a system with plugins, maybe [FlatPress](https://www.flatpress.org/) fits better for you, although I found its source code very "dated" and confusing.
> 
If you want something simple with plugins, [Typemill](https://typemill.net/) or [Bludit](https://www.bludit.com/) is probably better than FlatPress. I considered both before using HTMLy.

**Comment by JPLeRouzic** [comment]
Please could it be possible to close this issue, or is it a feature request?

**Comment by danpros** [comment]
Using latest version you just need to copy an existing theme than rename it to eg. `my-theme` and you can enable it via admin panel. I will close this one. Thanks.

**Comment by oleteacher** [comment]
I understand this is closed, but for anyone that comes along...

Just as Dan states, duplicate / rename the theme. But in my case had to also make adjustments in layout.html.php. For example:

`<link rel="stylesheet" href="<?php echo site_url();?>themes/occasio/css/style.css" type="text/css" media="all">`

Make sure to also change the instances of the theme name in the css/ js links within layout.html.php

**Comment by oleteacher** [comment]
@bttrx I have learned something new :)

Must admit, I am using an older theme version with mods so it was missing `theme_path()`

Thanks for the tip.

**Comment by bttrx** [comment]
@oleteacher You are welcome!
