### ISSUE TITLE
Tag limit

### ISSUE THREAD

**Issue by graphixela** [danpros/htmly#554]
Is there a limit to the number of tags on a post? It seems to not allow more than eight or nine. Every time I update the post, it removes the tag.

**Comment by bttrx** [comment]
I added "tag1,tag2,tag3,tag4,tag5,tag6,tag7,tag8,tag9,tag10,tag11,tag12,tag13" to one of my posts in my HTMLy installation. No problems.
What HTMLy version do you use?
What operating system are you running HTMLy on? Maybe it's a path+filename length issue?

**Comment by graphixela** [comment]
It's defiantly something. Tag count is the wrong word choice. I put 30 tags and it was okay but it stopped after that. It's probably the length.
I'm using the Latest HTMLy and I'm on a CentOS 7 server.

**Comment by Hjertesvikt** [comment]
I do not know if it's related but once I encountered problems with very long post titles (in Chinese)

**Comment by graphixela** [comment]
How long is long?

**Comment by Hjertesvikt** [comment]
+200?

https://github.com/danpros/htmly/issues/510

**Comment by fabianosantosnet** [comment]
Maybe the problem is in your theme. Change the theme and see if the behavior is the same.

**Comment by graphixela** [comment]
I ended up moving the site to Grav and had no issues. Before that I switched the server from CentOS 7 to Ubuntu 20 and still had the problem. It's something with HTMLy.

**Comment by danpros** [comment]
Since htmly put the date, tag, slug in filename so the limit is the max allowed filename length by the OS. htmly using the folder and filename to get specific list of contents (by date, category, tag, type etc.) and open only the needed files if the filter match.
