### ISSUE TITLE
html only

### ISSUE THREAD

**Issue by rlpalov** [danpros/htmly#557]
Hello, I neglected to renew my domain on time. (the SSL went over to the holder - i believe that is the correct description) I have since renewed, my website is back ... but... now my HTMLy, which is in it's own directory for 'news' is only HTML on both the front page and admin page. it looks like all is working otherwise and I can add content from the admin. t

hanks for recommendations help for fixing.

**Comment by Hjertesvikt** [comment]
Can you use your browser developers tools on your website and report if there are errors?

**Comment by rlpalov** [comment]
hello, thanks for the reply!
I think this is what you are requesting .. it's kinda a mess... an insecure mess... haha!
 
30
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure element '<URL>'. This request was automatically upgraded to HTTPS, For more information see <URL>
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20220519160916-Screen%20Shot%202022-05-19%20at%2010.07.15%20AM.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20220325011123-5%20R%20Palov%20SAT%20FEST%202022.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20220325001240-hub_march.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20211215221529-PN-pointing-byKL.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20211110002740-Screen%20Shot%202021-11-09%20at%205.50.05%20PM.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20211110002810-Screen%20Shot%202021-11-09%20at%205.50.19%20PM.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20210711013121-Screen%20Shot%202021-07-10%20at%207.07.58%20PM.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20210430180133-Screen%20Shot%202021-04-26%20at%209.55.18%20PM.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20210430180538-copt01.00_12_34_14.Still001.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20210512181821-164684348_246035727236072_4943211518411210447_n.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20210512181733-164495870_240770814429230_3708203162531998016_n.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20210512181911-150904521_217176620121983_4771335906610116879_n.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20210512181843-172758722_255626652943646_485305649390269597_n.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20210512182011-148258284_212013277304984_490896775488958524_n.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20210516012639-grid-small02.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
rebekkahpalov.us/:157 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20220519160916-Screen%20Shot%202022-05-19%20at%2010.07.15%20AM.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
rebekkahpalov.us/:157 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20220325011123-5%20R%20Palov%20SAT%20FEST%202022.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
(index):475 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20220325001240-hub_march.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
(index):475 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20211215221529-PN-pointing-byKL.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
(index):475 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20211110002740-Screen%20Shot%202021-11-09%20at%205.50.05%20PM.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
(index):475 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20211110002810-Screen%20Shot%202021-11-09%20at%205.50.19%20PM.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
(index):475 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20210711013121-Screen%20Shot%202021-07-10%20at%207.07.58%20PM.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
(index):475 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20210430180133-Screen%20Shot%202021-04-26%20at%209.55.18%20PM.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
(index):475 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20210430180538-copt01.00_12_34_14.Still001.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
(index):475 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20210512181821-164684348_246035727236072_4943211518411210447_n.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
(index):475 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20210512181733-164495870_240770814429230_3708203162531998016_n.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
(index):475 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20210512181911-150904521_217176620121983_4771335906610116879_n.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
(index):475 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20210512181843-172758722_255626652943646_485305649390269597_n.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
(index):475 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20210512182011-148258284_212013277304984_490896775488958524_n.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
(index):475 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure element 'http://rebekkahpalov.us/news/content/images/20210516012639-grid-small02.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
6
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure stylesheet '<URL>'. This request has been blocked; the content must be served over HTTPS.
rebekkahpalov.us/:15 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure stylesheet 'http://rebekkahpalov.us/news/themes/twentyfifteen/css/font.css'. This request has been blocked; the content must be served over HTTPS.
rebekkahpalov.us/:16 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure stylesheet 'http://rebekkahpalov.us/news/themes/twentyfifteen/genericons/genericons.css'. This request has been blocked; the content must be served over HTTPS.
rebekkahpalov.us/:17 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure stylesheet 'http://rebekkahpalov.us/news/themes/twentyfifteen/css/style_v2.css'. This request has been blocked; the content must be served over HTTPS.
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure stylesheet 'http://rebekkahpalov.us/news/themes/twentyfifteen/css/font.css'. This request has been blocked; the content must be served over HTTPS.
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure stylesheet 'http://rebekkahpalov.us/news/themes/twentyfifteen/genericons/genericons.css'. This request has been blocked; the content must be served over HTTPS.
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure stylesheet 'http://rebekkahpalov.us/news/themes/twentyfifteen/css/style_v2.css'. This request has been blocked; the content must be served over HTTPS.
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure script 'http://rebekkahpalov.us/news/themes/twentyfifteen/js/jquery.js'. This request has been blocked; the content must be served over HTTPS.
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure script 'http://rebekkahpalov.us/news/themes/twentyfifteen/js/jquery-migrate.js'. This request has been blocked; the content must be served over HTTPS.
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure script 'http://rebekkahpalov.us/news/themes/twentyfifteen/js/functions.js'. This request has been blocked; the content must be served over HTTPS.
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure script 'http://rebekkahpalov.us/news/themes/twentyfifteen/js/skip-link-focus-fix.js'. This request has been blocked; the content must be served over HTTPS.
rebekkahpalov.us/:1 Mixed Content: The page at 'https://rebekkahpalov.us/news/' was loaded over HTTPS, but requested an insecure favicon 'http://rebekkahpalov.us/news/favicon.ico'. This request has been blocked; the content must be served over HTTPS.

**Comment by Hjertesvikt** [comment]
So it's not an HTMLy issue, just change those links to 'http://rebekkahpalov.us to https://rebekkahpalov.us

You should make sure developers tools reports no errors

**Comment by AutomationMan808** [comment]
I don't know how much this will help. When one of my sites became corrupted I reinstalled HTMLy. Because it's ff all my previous work was still there. I did however need to redo my changes to system files. If you have a local backup you should be able to just upload everything again.

**Comment by rlpalov** [comment]
thanks! 
so where would i change the links? 
is this the same as changing the problem request from http to https, i wouldn't know where to do that, I'm on FTP so i could find it and make changes......  I would prefer to not need to reinstall, and unfortunately I don't know php, but for a reinstall would need to change the system>admin.php

**Comment by Hjertesvikt** [comment]
What site url did you declare in config?

**Comment by rlpalov** [comment]
it's http... i changed it, not effect, made a local copy, deleted the config.ini from my host... no effect... then how would I rerun the config file... i need to reinstall..

**Comment by AutomationMan808** [comment]
Wait a minute, if the only problem is the SSL that should fix itself after 2 or 3 days tops.

**Comment by Hjertesvikt** [comment]
> it's http... i changed it, not effect
Weird. Did you modify the theme files? (layout.html.php, main.html.php, post.html.php, etc..)

I guess I would make a search for the string "'http://" on your code base to see if it's hardcoded somewhere.

**Comment by rlpalov** [comment]
Hello all, and thanks this a wonderful support community, and love the project .....

Yes must have been an SSL related issue ... it fixed itself... the formatting is all back as it was - resolved.  

...helpful info if someone else has a similar problem 😇.
