### ISSUE TITLE
Could we get a distraction-free writing mode?

### ISSUE THREAD

**Issue by EzequielBruni** [danpros/htmly#560]
I'm so glad I've discovered HTMLy, as it has exactly the right amount of features for me in terms of actually managing the content. I'm actually planning on building a theme for it as well. Also, I have yet to see you all chewing people out for asking questions that are "too basic", so you have that going over the competition.

My only gripe so far is that the actual writing experience is a bit... cramped, maybe. And distracting. I know I could write most of the post elsewhere, and just add images, etc. in the admin UI, but I'd love to have a button that would allow me to open up a writing-focused view.

Here's a mockup that I made with the browser inspector and some static positioning (and a ::before pseudo-element on the body tag):

![image](https://user-images.githubusercontent.com/1215780/170154853-abddbe32-f113-4e33-910f-151a5ae00cdc.png)

**Comment by bttrx** [comment]
Did you notice you can collapse the left sidebar by clicking the Hamburger menu?

![Sidebar collapsed](https://user-images.githubusercontent.com/15858666/198839298-0bf9ce03-ce1d-48a9-be9d-c398bbba978d.png)

Maybe that's all you need?
