### ISSUE TITLE
404 after installation

### ISSUE THREAD

**Issue by MrGreen68** [danpros/htmly#561]
Hello,

I get error 404 after installation on my IONOS server. I start the installation with 
https://domain.com/blog/online-installer.php

The installation also works, but I get the 404 page with the following URL afterwards:
https://domain.com/blog/add/content?type=post

If I only enter the URL
https://domain.com/blog
the page loads after all with "No posts found!"

What am I doing wrong? 
Thanks in advance and best regards
MrGreen

**Comment by Hjertesvikt** [comment]
What tells the browser developer tools?

**Comment by MrGreen68** [comment]
For example if I search something:
GET   https://domain.com/blog/search/de   404

**Comment by Hjertesvikt** [comment]
I mean that kind of tools:
https://en.wikipedia.org/wiki/Web_development_tools

**Comment by MrGreen68** [comment]
Thanks for your reply, Hjertesvikt, but I have since been able to solve it myself. It was due to the not correctly edited .htaccess

**Comment by bttrx** [comment]
That's great. -- Please, be so kind to close the issues now. Thanks!

**Comment by MrGreen68** [comment]
Great job by the developers. Thanks a lot for this!
