### ISSUE TITLE
Draft/Publish on pages

### ISSUE THREAD

**Issue by sb0001** [danpros/htmly#563]
I'd like to have the possibility of saving a page as draft or publish it, like we have in posts. Maybe this is something more people would find useful?

**Comment by AutomationMan808** [comment]
What I do is create it as a post, then copy the code over to the page, but I agree that would be nice.

Rick

**Comment by danpros** [comment]
This feature already added to master branch. Please check it

**Comment by danpros** [comment]
This feature has been added in the latest release.
