### ISSUE TITLE
[Data damage] Backslash in markdown are interpreted or stripped while publishing a post

### ISSUE THREAD

**Issue by recolic** [danpros/htmly#564]
While writting a new post with the following content: 

``````
Hello! This is my new post! 
```
This is 4 backslash: \\\\
```
``````

After clicking "publish", it turns into

``````
Hello! This is my new post! 
```
This is 4 backslash: \\
```
``````

After clicking "edit" again, the content is still

``````
Hello! This is my new post! 
```
This is 4 backslash: \\
```
``````

Now click "publish" again, it turns into

``````
Hello! This is my new post! 
```
This is 4 backslash: \
```
``````

"edit" and then "publish" it again, and it will turn into

``````
Hello! This is my new post! 
```
This is 4 backslash: 
```
``````

HTMLY is eating my backslash! Here is screenshots: 

![Screenshot from 2022-06-13 17-26-54](https://user-images.githubusercontent.com/19610256/173324958-17731a77-712d-413b-8130-932bfdb286a0.png)
![Screenshot from 2022-06-13 17-27-06](https://user-images.githubusercontent.com/19610256/173324967-65f6d9a3-6763-4047-9f67-6fe67d9e8eb7.png)
![Screenshot from 2022-06-13 17-27-19](https://user-images.githubusercontent.com/19610256/173324969-060989bb-ec16-4d0a-a46f-1b01ffa8fd65.png)
![Screenshot from 2022-06-13 17-27-28](https://user-images.githubusercontent.com/19610256/173324972-58c11162-3b1a-4247-b62f-193109969ceb.png)

**Comment by recolic** [comment]
Javascript is sending correct web request: 

![image](https://user-images.githubusercontent.com/19610256/173328290-618a4802-a9fd-480a-b3c7-636af2b9ac5a.png)

But the markdown file stored in backend is incorrect. 

![image](https://user-images.githubusercontent.com/19610256/173328399-0187b4df-0daa-45b8-aca5-d9d4f3ce58fe.png)

**Comment by recolic** [comment]
I tried to understand the source code, but I don't know which PHP function is processing `content/edit?destination=post`. I failed and gave up. 
Waiting for someone else to look into this issue.

**Comment by recolic** [comment]
Hi. Anyone interested in solving this issue? Or just give me some hint about how to debug it

**Comment by Hjertesvikt** [comment]
Maybe stripslashes() in :

**Comment by recolic** [comment]
> Maybe stripslashes() in add_content() ?: https://github.com/danpros/htmly/blob/27cc9cbbff93f0d098737d66bd3902301f6ffd16/system/admin/admin.php

Exactly. The issue got resolved after removing the `stripslashes()` call. 

What's the purpose for this function? It looks weird to modify the post content without alerting the user, and it might cause shared code snippets to break silently...

**Comment by danpros** [comment]
Already remove it in latest master branch.
