### ISSUE TITLE
Disqus setup

### ISSUE THREAD

**Issue by afoster1955** [danpros/htmly#567]
I cannot seem to connect my Disqus to show comments to separate articles.  Right now, if I add a comment, that comments shows up under all the articles.  I assume the problem is in the code that is generated by Disqus when I set up the account.  Any help will be appreciated.  I also assume that the code generated by Disqus goes in the post.html.php file of the specific theme I am using?

I also tried to set up a different comment system with no luck at all.

**Comment by afoster1955** [comment]
Don't really know how it happened, but all of a sudden the Disqus comment system is working.  Comments can now be posted for each article without any of them repeating on any other article.  What I have to figure out now is how to limit the number of comments listed in the Latest Comment module in the right hand panel. Can anyone help me with that?

**Comment by danpros** [comment]
I will close this one. Thanks
