### ISSUE TITLE
Facebook comments setup

### ISSUE THREAD

**Issue by bluebirch** [danpros/htmly#568]
I have tried to set up the Facebook commenting system without any luck at all. Thinking of #567, maybe commenting system needs a review or at least documentation?

**Comment by MrBear777** [comment]
I have it working without issue. Trick is to use the https://developers.facebook.com/docs/development/create-an-app/ to create an Facebook app. This creates a facebook app ID that you can put in Config>widget .. subsection Comments 

![Capture](https://user-images.githubusercontent.com/122763947/215871785-858715be-d376-4107-962f-3e67551ae406.PNG)

**Comment by danpros** [comment]
I will mark it as fixed. Thanks @MrBear777
