### ISSUE TITLE
Config with multiple value

### ISSUE THREAD

**Issue by yenleidong** [danpros/htmly#569]
Hi, it's fun to learn HTMLY
Senang rasanya ikut belajar HTMLY.

I want to save and update config for custom page in admin section.
which confuses me, how to update the form for each config line by separating the values using a separator, here I use the "|" sign with PHP implode and explode code.

![Screenshot_2](https://user-images.githubusercontent.com/9006040/180126419-8b5a06a1-f559-411a-b63b-3857056a04e2.png)

![Screenshot_7](https://user-images.githubusercontent.com/9006040/180127155-01cc1812-0e74-4e9e-ac1d-ea31f5dc3dfb.png)

**Comment by danpros** [comment]
Hi, maaf baru sekarang replynya 😃 

This is out of htmly supposed to be, sorry I can't help with this specific matter
