### ISSUE TITLE
Category description translation

### ISSUE THREAD

**Issue by dolibarr95** [danpros/htmly#570]
Hello 

On my admin/categories page have the defaut value : 

**Sans catégorie : Sujets qui n'ont pas besoin de catégorie, ou qui ne conviennent à aucun catégorie existante.**

So everything is ok, but in the public blog if i chose all post "Sans catégorie" I have :

**Catégorie: Sans catégorie
Topics that don't need a category, or don't fit into any other existing category.**

---

Screenshots

![Capture](https://user-images.githubusercontent.com/24292300/180436890-b2536137-6107-4c2f-a119-2055994b542b.PNG)

![Capture2](https://user-images.githubusercontent.com/24292300/180436919-415d9a76-9161-4572-aa7d-1752a306e2b5.PNG)

---

Tks for reading

**Comment by bttrx** [comment]
Similar here on a German HTMLy installation.

You can fix this by adding a new line ```Uncategorized_comment = "Whatever it is in French"``` to your language's translation file, e.g., ```lang/fr_FR.ini```.

**Comment by bttrx** [comment]
The problem is in ```system/includes/functions.php```.

Search for and change from:
```
// Return default category
function default_category()
{
    $tmp = array();
    $desc = new stdClass;

    $desc->title = i18n("Uncategorized");
    $desc->url = site_url() . 'category/uncategorized';
    $desc->slug = 'uncategorized';
    $desc->body = '<p>Topics that don&#39;t need a category, or don&#39;t fit into any other existing category.</p>';

    $desc->description = 'Topics that don&#39;t need a category, or don&#39;t fit into any other existing category.';

    return $tmp[] = $desc;
}
```

to:
```
// Return default category
function default_category()
{
    $tmp = array();
    $desc = new stdClass;

    $desc->title = i18n("Uncategorized");
    $desc->url = site_url() . 'category/uncategorized';
    $desc->slug = 'uncategorized';
    $desc->body = '<p>' . i18n('Uncategorized_comment') . '</p>';
    $desc->description = i18n('Uncategorized_comment');

    return $tmp[] = $desc;
}
```

Clear HTMLy's cache afterwards.

**Comment by dolibarr95** [comment]
Hello
@bttrx thanks for the fix 👍

**Comment by bttrx** [comment]
@dolibarr95 Thanks for your PR. -- Otherwise _I_ would have had to lookup how to make a correct PR. ;-)
