### ISSUE TITLE
How to edit 'Tags' files

### ISSUE THREAD

**Issue by LeeUnd** [danpros/htmly#573]
I want to edit the tag file but the one I found at ........./content/data/ didn't work after I edited it. Does anyone know where the actual file that the system draws from for the tags is located?

**Comment by bttrx** [comment]
What are you trying to accomplish by editing the tags file?
How did you verify it "didn't work after"?

**Comment by LeeUnd** [comment]
Some of the tags got 'messed-up' and I wanted to edit the file.

I verified it b/c the site would not display with the edited file.

**Comment by bttrx** [comment]
1. Did you clear HTMLy's and your browser's cache afterwards?
2. Did you also edit your posts files? (Look for all the *.md files in ```content/your_username/blog```.)

**Comment by LeeUnd** [comment]
1. Yes.
2. No, I did not edit any other files at that time.

**Comment by bttrx** [comment]
1. OK
2. Then try this, please.

**Comment by LeeUnd** [comment]
I have removed this from the site so no need to do this. But thanks!

**Comment by JPLeRouzic** [comment]
Please, could you close this issue?

**Comment by LeeUnd** [comment]
Tags removed.
