### ISSUE TITLE
User-specific avatars

### ISSUE THREAD

**Issue by bluebirch** [danpros/htmly#575]
The recommended way of changing avatar is to replace the image in the theme template. However, HTMLy has support for multiple users or authors, in which case the same avatar would be shown for all users. I would suggest using a per-user avatar instead.

I'm not a PHP developer, but I have looked into the code and it doesn't seem to be impossible. It would only require some changes to the theme files, if I understand it correctly. I could certainly create a PR with some assistance from the community.

**Comment by danpros** [comment]
Just in case still using htmly. You can use get_image($string) to get the user image added in author bio:

```
get_image($author->about);
```

This will return the first image added in bio.
