### ISSUE TITLE
Is HTMLY abandoned? 

### ISSUE THREAD

**Issue by LeeUnd** [danpros/htmly#577]
@danpros Will HTMLY be updated and maybe some plugins created?

**Comment by Hjertesvikt** [comment]
Not the Danpros but there are 32 contributors, recent versions, so one can't say HTMLy is abandoned.

Maybe what it needs is people funding new proposals like is done on some projects (bounties, etc). Anyway as HTMLy targets a tiny segment of users, those willing not to or being unable to use a database, then it's unlikely that big companies may fund developments like Google do with "Google summer of code".

**Comment by LeeUnd** [comment]
Thanks. Is there a list of contributors somewhere?

**Comment by Hjertesvikt** [comment]
There are icons and links in the front page, otherwise the full list is here:

https://github.com/danpros/htmly/graphs/contributors

**Comment by LeeUnd** [comment]
Thanks!

**Comment by bttrx** [comment]
@LeeUnd

Regarding "maybe some plugins created" I'd like to quote from [the HTMLy website](https://www.htmly.com/):

> Ever heard of complaints about unsafe, outdated, and slow plugins for specific CMS out there? We will not follow the same steps. Any new features will be added to the core and go through security audit.

So, it's probably ok to expect new features some day, but these will not be plugins as in other blog software ecosystems.

**Comment by danpros** [comment]
Please see #629
