### ISSUE TITLE
Wordpress RSS to htmly

### ISSUE THREAD

**Issue by netzjahre** [danpros/htmly#581]
Thisis a question.

A time ago, I wanted to change from Wordpress (WP) to htmly. But then I did not so because I was not able to import WP content via RSS.
Then I tried this:
https://github.com/danpros/htmly/issues/343
But no success, no import happened.
Is there a newer solution?

**Comment by bttrx** [comment]
If you are able to do so, please re-open your old unsolved issue and close this new one. Thanks.

**Comment by AutomationMan808** [comment]
I believe a php script could be written for that reading the feed
Get the file contents
Add the heading lines for HTMLy
Then write to the content section 

Rick

**Comment by JPLeRouzic** [comment]
Please as "Wordpress to HTMLy" seems to work flawlessly, could you close this issue?

**Comment by netzjahre** [comment]
> Please as "Wordpress to HTMLy" seems to work flawlessly, could you close this issue?

Who can do it?

**Comment by JPLeRouzic** [comment]
> Who can do it?

The person (@netzjahre, you) who created it and Danpros.
The best is that you close this issue, if you agree.

![image](https://user-images.githubusercontent.com/18621529/211316907-0d7ba025-5486-4120-ba97-3ac77600a10b.png)
