### ISSUE TITLE
Selecting images from default image folder

### ISSUE THREAD

**Issue by AutomationMan808** [danpros/htmly#586]
Has anyone altered the graphic selection code to include a chance to browse and select an already uploaded image?

Rick

**Comment by bttrx** [comment]
No, but I'd like to see that feature too.

**Comment by AutomationMan808** [comment]
Okay so can someone give me a hint on where to look to edit the feature.

**Comment by JPLeRouzic** [comment]
I never delve in this but I think that the tiny editor that is found when you edit a post was borrowed from this project:
https://code.google.com/archive/p/wmd/

So in every place in the HTML code where there is:
"wmd-button-bar"
The user browser paints the tool bar on user's screen.

You can find HTMLy's code there:
https://github.com/danpros/htmly/search?l=JavaScript&q=wmd

Good luck!

**Comment by danpros** [comment]
Latest master branch already have this feature. You can test it.
