### ISSUE TITLE
Purpose plugins-directory

### ISSUE THREAD

**Issue by ctuxboy** [danpros/htmly#593]
- What is the purpose of the **plugins** directory?
- Is this to add code snippets?
- Will this directory be overwritten with a htmly-update?
- If this for adding code , how communicate with the functions in the htmly-core?

![Screenshot 2022-12-06 19 32 44](https://user-images.githubusercontent.com/10013632/205994133-9d104ea0-ecec-4025-afe6-46af0688dc78.png)

**Comment by bttrx** [comment]
HTMLy currently doesn't have a plugin system. The "plugins" folder is not referenced anywhere in the code.

**Comment by ctuxboy** [comment]
> HTMLy currently doesn't have a plugin system. The "plugins" folder is not referenced anywhere in the code.

Hi @bttrx,
Thanks for your answer.
Btw, it's one of the best CMS systems for blogging, i love it 😃
Have you any idea of 
@danpros planned new updates ? 
It is a long time without updates 😭

**Comment by JPLeRouzic** [comment]
> HTMLy currently doesn't have a plugin system. The "plugins" folder is not referenced anywhere in the code.

There were plugins in the past, and anyway the system/vendor folder is a plugin repository by another name.

**Comment by ctuxboy** [comment]
> > HTMLy currently doesn't have a plugin system. The "plugins" folder is not referenced anywhere in the code.
> 
> There were plugins in the past, and anyway the system/vendor folder is a plugin repository by another name.

Ah okay, it would handy if there is a folder where can add code-snippets that not override if there is an HTMLY-update. similar the functions.php-file on Wordpress.
Thank you for the help ;)

**Comment by bttrx** [comment]
> Have you any idea of
> @danpros planned new updates ?

No, sorry.

> It is a long time without updates

Yes, it's a pity.

I already thought about maintaining my own fork, but I fear, I don't have enough time.

Instead, I try to live with HTMLy's limitations and often document my way of using it at https://www.robertriebisch.de/ (in German only).

**Comment by JPLeRouzic** [comment]
> I already thought about maintaining my own fork, but I fear, I don't have enough time.

Same for me, but there are several problems:
- My own version is very different now => https://padiracinnovation.org/News
- It still has at least a dozen of bugs
- I don't want to be involved in problems that are not mine, like configurations on host that I don't know.

Yet if you fork it and if I like you code, I might help you.
In particular if:
- It uses small files instead of the horribly large htmly.php and functions.php.
- If the login functions are properly written.
- If you separate the infrastructure (the system/includes folder which comes for the dispatch folder) from the functionalities from the views:
![image](https://user-images.githubusercontent.com/18621529/209312692-522243cd-bfe3-41be-bb6e-2dcf3bd85d3a.png)
- If the is no HTML/JS code inbedded in PHP code of functionalities of infrastructure (like in today's code:
`render($pview, array(
            '...
            'breadcrumb' => '<a href="' . site_url() . '">' . config('breadcrumb.home') . '</a> &#187; Profile for: ' . $author->name,
            ...
        ), $layout);`
- If the code is PHP8.1 compliant

**Comment by JPLeRouzic** [comment]
My /model/ folder which contains one sub-folder by functionality and attempts at small files.
I am still unsatisfied and will try to reduce redundant code (there are a lot of snippets that are redundant)
![image](https://user-images.githubusercontent.com/18621529/209317729-9a6b0321-41af-4fc1-9bf7-7797f10606d5.png)

The /views/ folder contains the UI for administration and enables the usage of many themes that can be changed on the fly. I am still not satisfied as as told above there are still UI codes which are located in functionalities' folder.
![image](https://user-images.githubusercontent.com/18621529/209318150-30faa5f2-4950-4b71-a66b-7af88a5dd065.png)

**Comment by ctuxboy** [comment]
Wow! nice work guys :smiley:
Iḿ start blogging with htmly a few weeks ago https://gewoonsimpel.be/
Using an existing theme, but add some small snippets, like this one https://shareon.js.org/ for share icons on my posts

![Screenshot 2022-12-23 15 42 32](https://user-images.githubusercontent.com/10013632/209353755-6b9776c8-2168-430f-99de-0be9a6c16a96.png)

**Comment by bttrx** [comment]
> I'm start blogging with htmly a few weeks ago https://gewoonsimpel.be/

Now I'm hungry for a fresh bread.

**Comment by ctuxboy** [comment]
> > I'm start blogging with htmly a few weeks ago https://gewoonsimpel.be/
> 
> Now I'm hungry for a fresh bread.
:blush:

**Comment by ctuxboy** [comment]
> > I'm start blogging with htmly a few weeks ago https://gewoonsimpel.be/
> 
> Now I'm hungry for a fresh bread.

:blush:
