### ISSUE TITLE
A pointer for improvements

### ISSUE THREAD

**Issue by JPLeRouzic** [danpros/htmly#599]
Dear friends,
Like you I have been frustrated by the lack of activity in HTMLy since 5/6 years.
Like you I have maintained [an HTMLy instance](https://padiracinnovation.org/News), and modify it to introduce features and keep with the demands of the hard master: Google.
I provide here [my code](https://github.com/JPLeRouzic/Coralie/), therefore complying with HTMLy's license.

[Coralie](https://github.com/JPLeRouzic/Coralie/) (my code) enables a separation of infrastructure, features and views. For example it is possible to change of theme on the fly.
The code is much cleaner than in HTMLy (at least that is what static analysis tells).

Yet Coralie is not a replacement for HTMLy, not competition. I hope it will enable a new trend of innovation here.

**Comment by ctuxboy** [comment]
> Dear friends, Like you I have been frustrated by the lack of activity in HTMLy since 5/6 years. Like you I have maintained [an HTMLy instance](https://padiracinnovation.org/News), and modify it to introduce features and keep with the demands of the hard master: Google. I provide here [my code](https://github.com/JPLeRouzic/Coralie/), therefore complying with HTMLy's license.
> 
> [Coralie](https://github.com/JPLeRouzic/Coralie/) (my code) enables a separation of infrastructure, features and views. For example it is possible to change of theme on the fly. The code is much cleaner than in HTMLy (at least that is what static analysis tells).
> 
> Yet Coralie is not a replacement for HTMLy, not competition. I hope it will enable a new trend of innovation here.

Nice work!
I like HTMLy, but i'm afraid about there are no updates (anymore).
The lack of updates, it pushed me to another cms (Bludit), but i hope that people like you build a 'fork' from HTMLy, so it can grow and hope more activity.
I'm looking to your project, is it possible installing as test? Is there a tutorial how install your Colarie cms?

**Comment by JPLeRouzic** [comment]
Thanks for the kind words.
As written above I do foresee "Coralie" to compete with any flat file PHP CMS, I am a single person so for me it's not possible to compete with open source PHP projects that are backed by a SME (like Wordpress for example).

"[Coralie](https://github.com/JPLeRouzic/Coralie/)" is here to show what could be done in HTMLy in terms of modern coding style, easier maintenance and expansion. I will never make an installer or make "[Coralie](https://github.com/JPLeRouzic/Coralie/)" compatible with the myriad of hosting environments. If there were a community of people it would be different, but that community does not exist for HTMLy despite its 9 years existence, so the odds it happens for [Coralie](https://github.com/JPLeRouzic/Coralie/) are slim.

I guess what would make a difference would be many plugins/themes and good documentation. Alas this means lot of work for at least 5-10 full time people. 

I plan to make "[Coralie](https://github.com/JPLeRouzic/Coralie/)" compatible with some Wordpress themes. What I mean enabling people to dropping a Wordpress theme in the theme folder, declare it in config and that is all. Another feature would be to be able to design and modify presentation on the fly like in Wordpress (though it's not that easy on Wordpress). In general hijacking Wordpress features and resources could make a real difference for people.

About installing [Coralie](https://github.com/JPLeRouzic/Coralie/), I just uploaded it to [csrf.](https://csrf.4lima.de/News/) and it worked out of the box without needing to install anything. It seems people (including myself) can't install recent HTMLy on [Lima City](https://www.lima-city.de) because of a bug recently introduced in HTMLy session management.

Thank you again for your warm words and happy new year 2023!

**Comment by ctuxboy** [comment]
Oh, you do a lot of work. Hoped there was someone helped @danpros for develop and maintenance HTMLy, so keeps existing. When starting my blog in december 2022, i doubt HTMLy or Bludit.
HTMLy is really good for blogging and very efficient.
But Bludit has an active community and some plugins, so now i think change to Bludit, if there now activity/maintenance anymore for HTMLy.
Here my (beginning) blog in HTMLy https://gewoonsimpel.be/
and a temporaly test with Bludit https://bludit.gewoonsimpel.be/
I used the same theme, i mean, rebuild the HTMLy-theme to Bludit, so i can compare Bludit with HTMLy.
(sorry for my poor english)

**Comment by JPLeRouzic** [comment]
You have a nice blog!

I checked Bludit on Google trends, it seems on par with HTMLy.
I also checked Bludit with an [online static code analyser](https://www.exakat.io). It looks perhaps a bit more mature than HTMLy but not that much.
HTMLy:
![image](https://user-images.githubusercontent.com/18621529/210332290-d72a31b0-0a15-40c0-b14d-6b372c9a6075.png)
Bludit:
![image](https://user-images.githubusercontent.com/18621529/210332353-9163322b-fa03-4437-a68e-3e41bc847571.png)

Kirby has a test suite which makes it very professional (it can automatically detect regressions or bugs). This could be a nice addition to HTMLy.

**Comment by ctuxboy** [comment]
@JPLeRouzic thanks for the compliments.
I the past i was a Wordpress Specialist, but stoppped as 'proffesional' webdesigner a few times ago (burn-out), now i do webdesign and small webdev as hobby.
Starting this blog a month ago. I was started building my own theme, but find this existing HTMLy-theme really nice, why reinvent the wheel when it already exists :wink:
So for testing, i ported the theme to Bludit, and made yesterday the decision change my blog to this cms (Bludit), so in the meantime change my HTMLy blog to Bludit. The ported theme functions for 90%, at this moment, it's a work in progress.
Yes, i like HTMLy for blogging very mutch, it works very efficient, but the lack of updates made me decide switch to Bludit.
Okay, Bludit is not perfect, it is build as multipurpose-cms, but made a plugin for Bludit is relative easy, so it is possible for a basic-developer like me, made extra functionality in a relative simple way, for my own requirements, and it has a support-forum.
Kirby is a think a better choice, but not free :confused:

**Comment by AutomationMan808** [comment]
I played with Bludit and found HTMLy better for SEO purposes and easier to customize.

Rick

**Comment by ctuxboy** [comment]
> 

i understand, both cms-systems has its pro's en contra's.
Bludit has also no archive-page/plugin. A friend build a plugin yesterday in a evening.
But i'm also interesting in HTMLy.

**Comment by oleteacher** [comment]
Very nice work @JPLeRouzic .

Been using HTMLY for student classroom blogs for few years and have loved it. Lack of dev is concerning so looking for a similar flat-file CMS.

Will be keeping an eye on your release:)

**Comment by JPLeRouzic** [comment]
**Thank you so much Susan for your kind words!**

To have a large community, it seems to me it's important:
- To have a code base which is  easy to understand and easy to tinker with.
- To have plugins to enable someone to make small modifications that are not impacted by an upgrade of the core code and which are relatively safe as they call an internal API and can't directly access content or modify core features.

However this is not enough, as for example Bludit has all that yet it is not well known. I love that even Bludit core features call their API. 

On the contrary the code base for Wordpress is a nightmare. There is no formal process to validate plugins. Yet a lot of people love Wordpress (40% of Web domains use it) because there are so many themes and presentation could be (not so easily)  changed from the admin menu.

**What feature seems important for you?**

**Comment by oleteacher** [comment]
You are most welcome JP.

"What feature seems important for you?"

- Easy admin
- Simple themes
- Easy to tinker with

Like my husband says about new cars: can no longer work on them without a computer science degree. He misses the old days when an automobile only needs four things.  Oil, gasoline, air and a spark to run:)

In other words: keep it simple.

I have a love / hate relationship with WordPress. You can build about any kind (niche) of site, but it too is like a new automobile. Very complex.

In the classroom we cannot use WordPress. No mySQL of any type is allowed on local network. Use to be able to use SQLite but now that is frowned upon. IT department prefers flat-file.

Would love to see HTMLY updated to at least work with PHP 8+ so students could use their blogs in the future. I really like HTMLY but understand the time / energy / funds it takes to maintain.

**Comment by JPLeRouzic** [comment]
> Would love to see HTMLY updated to at least work with PHP 8+ so students could use their blogs in the future. 

[Coralie](https://github.com/JPLeRouzic/Coralie/) works on PHP 8.1 on [my web site](https://padiracinnovation.org/News/) and also on its [demo site here](https://csrf.4lima.de/News/).
![image](https://user-images.githubusercontent.com/18621529/214434256-100ff0d5-911b-40b9-bb59-f1f50c41880a.png)

Please could you share a few URLs of your and your students blogs,  to help me understand what features you and your students are using? If they are not offered today on Coralie (not all HTMLy features are in Coralie) I pledge to add them within than a month to [Coralie](https://github.com/JPLeRouzic/Coralie/).

**Comment by oleteacher** [comment]
I will have to try Coralie and see if HTMLY content can be imported.

All student blogs are on a local network and cannot be accessed from the internet.

**Comment by JPLeRouzic** [comment]
Thanks, but as stated Coralie is a pointer to change that could happen in HTMLy, it's not its competition.
Anyway content created with HTMLy is compatible with Coralie.
If you want the "listen the article" feature, you need to get a key from [responsivevoice](https://responsivevoice.org) and write it in layout.html.php

I just verified on [Bludit](https://www.bludit.com),  post created with HTMLy is correctly displayed on Bludit.

**Comment by oleteacher** [comment]
"it's not its competition." ???

I never said nor do I think this is a competition. Simply trying to find a replacement solution for students.

**Comment by AutomationMan808** [comment]
I look forward to trying Coralie. I love HTMLy but I wanted something more end user friendly for my clients so I tried 
 Grav. I don't know if it's because I'm self-taught so I could not find a way to edit the layout page to do what I wanted or because the first theme I tried to install ended up with errors but I'm uninstalling Grav now and will be uploading Coralie shortly.

If you have any tips I would appreciate them.

Thank you for your hard work.
Rick

**Comment by JPLeRouzic** [comment]
Hi Rick,
In Coralie, the themes are under the "view/theme" directory. You can choose it in the configuration menu and change it on the fly.
![image](https://user-images.githubusercontent.com/18621529/216925572-2a014c2c-8ec5-4a0d-9837-536dbf0c57f5.png)

![image](https://user-images.githubusercontent.com/18621529/216926334-dc864d80-3d0a-4a80-8710-98975a1e630c.png)


At the moment there is no internationalization, because I want to do what @raffaellarinaldi asked yesterday: Having a full internationalization, instead of a partial as of today. This is why you can see new small files in the 'view' folder.

In case you want to try things you can access the 'admin' menu of the demo site with 'admin' as login and password.

![image](https://user-images.githubusercontent.com/18621529/216926721-ea253928-b33a-44da-9400-426a70504f59.png)

**Comment by vdbhb59** [comment]
Coralie sounds good and simple enough for my blogs. I am still using this, but I will try it once on something different in a week or so. Hope, it works for me. I tried the admin interface as you stated, and it does seem to have things working in demo.

**Comment by AutomationMan808** [comment]
Yes it's a text file you can set someone up as a writer etc.. They can then only see and edit their own content.

**Comment by JPLeRouzic** [comment]
Yes, you can add a user in the text file, like this were there are two users, "admin" and "system":
![image](https://user-images.githubusercontent.com/18621529/227128121-df9449d5-e99d-4e79-b0c7-10b8edfaaca8.png)

But the sentence I answered to was :
"Although user function (add/remove/maintain/delete etc of another user) is not available."
There user management in HTMLy.

![image](https://user-images.githubusercontent.com/18621529/227127691-e74ecce5-502d-4238-ba04-96c8228b3aca.png)

**Comment by AutomationMan808** [comment]
Sorry I misunderstood.

**Comment by JPLeRouzic** [comment]
No problem, don't worry :-)

**Comment by vdbhb59** [comment]
> Yes it's a text file you can set someone up as a writer etc.. They can then only see and edit their own content.

@JPLeRouzic I meant this. Yeah HTMLy does not have it, I just thought it could be done, the way you mentioned a post below.

I hate Bludit, as it is very resource hungry. I love simple stuffs tbvh.

**Comment by JPLeRouzic** [comment]
Oh a user management through the admin interface could be created quickly if only one author write at a given time.
HTMLy does not do multi-author for a reason, it would mean implementing more database-like functions, so it would defeat the purpose of a simple flat file CMS.

A hack could be to manage access of authors to the database through the login function and forbid two authors accessing HTMLy at the same time.
Then basically one "only" have to:
- create a new page like edit-profile.html.php, but for user management, let say: user-management.html.php.
- create the wiring for a new entry in the admin menu
- create functions to:
    * create a new user (doing what we do manually)
    * edit an existing user
    * deleting an existing user

**Comment by danpros** [comment]
Looks great, good luck with the fork! Anyway, I will close this one. Thanks
