### ISSUE TITLE
Featured Image

### ISSUE THREAD

**Issue by GrandM1961** [danpros/htmly#610]
Question: Why do I have to provide a link to a image in a post in the backend when one can also upload one?

I have managed to upload a image and the text is replaced with that image I uploaded by simply put a upload file underneath the featured image, after saving the concept it is placed in the featured image field. And unfortunately it won't be published in the field above the post since it doesn't have the link towards the uploaded picture.

wouldn't it be easier to upload a picture and the link is altered to where the image is uploaded too?
![Scherm­afbeelding 2023-02-16 om 13 18 41](https://user-images.githubusercontent.com/19931368/219363549-47ec15ca-e0e5-4885-98ad-85d8a5de8011.png)
![Scherm­afbeelding 2023-02-16 om 13 18 54](https://user-images.githubusercontent.com/19931368/219363551-ab885794-4eea-4b09-b17c-a1dd9e4fd118.png)
![Scherm­afbeelding 2023-02-16 om 13 19 11](https://user-images.githubusercontent.com/19931368/219363555-8fd1bbb0-a6da-4d6d-8f5f-5fb460635d52.png)
![Scherm­afbeelding 2023-02-16 om 13 22 09](https://user-images.githubusercontent.com/19931368/219363557-e979d2f4-88b3-4376-9a91-8b8cdaea5805.png)

**Comment by danpros** [comment]
Hello,

Please make a PR if you still work on it. Perhaps we can improve it.

**Comment by danpros** [comment]
This feature already added to the latest version. Thanks
