### ISSUE TITLE
Number tags can only be applied to one post

### ISSUE THREAD

**Issue by Anamon** [danpros/htmly#614]
When trying to use numbers as tags, the admin interface will let each tag only be used for one post. Trying to add it to a second post will silently drop it.

# Steps to reproduce
1. Create a post or choose an existing one, and give it a tag that consists of a number, e.g. **2022**.
2. Choose a second post and give it a tag that consists of a different number, e.g. **2023**.
3. Choose a third post and give it the same tag as the post in step 1, e.g. **2022**.
4. Check the list of posts in the admin area or in the published pages.

# Expected results
Both posts from steps 1 and 3 have tag **2022**, and the post from step 2 has tag **2023**.

# Actual results
The post from step 1 has tag **2022**, and the post from step 2 has tag **2023**, but the post from step 3 doesn't have tag **2022**.

If the tag **2022** is added to the post from step 3 manually, by adding it to the content file and renaming the content file accordingly, the number tag works fine. However, the tag will be removed again when editing the post through the admin interface.

**Comment by JPLeRouzic** [comment]
I am not sure to understand exactly what you mean. For example at the end you tell about adding manually 2022 as tag in the third post which has already 2022 as tag.

Or do you mean 2022 appears only one time in the admin menu? It looks OK for me.
![image](https://user-images.githubusercontent.com/18621529/222948874-0372ef0e-f012-44ce-add9-466b559b423d.png)

HTMLy has to maintain several indexes for its content, and changing manually a a tag means also interfering with these indexes. I think it should be discouraged. After all flat files databases are still databases, it's just they don't use another internal server.

**Comment by Anamon** [comment]
> I am not sure to understand exactly what you mean. For example at the end you tell about adding manually 2022 as tag in the third post which has already 2022 as tag.

The manual addition of the tag was just an experiment to see whether it was just an editing problem in the admin interface, or if numeric tags were generally a problem. Maybe it was just confusing and I should have left it out of the bug report, sorry!

> Or do you mean 2022 appears only one time in the admin menu? It looks OK for me. ![image](https://user-images.githubusercontent.com/18621529/222948874-0372ef0e-f012-44ce-add9-466b559b423d.png)

That's strange. I really can't get this to work. I'm on v2.8.2 (also forgot this in the report, sorry).

I made a screencast to demonstrate what I observe. I add three tags to an existing post: 2016, 2017, and breaks. 2017 is a new numeric tag, so it works. breaks is a non-numeric tag that already exists on other posts, it also works. 2016 is a numeric tag that is already applied to one other post, and when I save the edit, 2016 is missing from the tag list. This happens for every post and numeric tag I tried. If I create another post after this and try to apply 2017 to it, it also won't be added (but stay on the first post with the 2017 tag).

https://user-images.githubusercontent.com/517549/222950770-2f677766-e32a-4002-ae7b-788b43b3b6dd.mp4

**Comment by danpros** [comment]
Hi, thanks for reporting this. Already commit a fix for it.

**Comment by Anamon** [comment]
> Hi, thanks for reporting this. Already commit a fix for it.

Awesome, thank you! 👍

I mentally prepared for trying to find and fix this myself, it was on my to-do list for 9 months. I never got around to it, I was probably afraid of how rusty I might have become with PHP 😄
