### ISSUE TITLE
Where's the code for the cache?

### ISSUE THREAD

**Issue by AutomationMan808** [danpros/htmly#616]
I need to remove it.

Rick

**Comment by JPLeRouzic** [comment]
You can easily disable the cache in config.ini:

> ; Switch on and off the file cache for development purposes. Options "false" and "true"
> cache.off = "false"

Most of the code is in dispatch.php, but there are some bits scattered here and there.
You can have a look at:
https://github.com/danpros/htmly/search?l=PHP&p=2&q=cache.

Yet mostly it's not really a true cache, it's just a hack.
