### ISSUE TITLE
deactivate banner of blog entries

### ISSUE THREAD

**Issue by DieselDriver** [danpros/htmly#619]
Hi,

is it possible to deactivate the banner (date, time, user of blogger) from the blogs?

![screenshot-blog heliopower net-2023 05 03-16_46_23](https://user-images.githubusercontent.com/45383499/235952447-5f38ddd4-c59e-40cc-989a-e98d074a4a36.png)

Thanks.

**Comment by JPLeRouzic** [comment]
I can't offer specific help but in general, you can modify your theme and save it with a new name (to mitigate the erasure of your modifications when there is an update)

Usually, the UI hacks/modifications are done in layout.html.php or post.html.php.
You can identify precisely the location by looking at the HTML source of the page with a browser.
here is an example:
![image](https://user-images.githubusercontent.com/18621529/235977704-c854b4db-c9bf-4453-afa4-315dbc4ce809.png)

Then you search in the PHP code for the place where this HTML code is emitted.
You will find something like this:

**Comment by danpros** [comment]
Thanks @JPLeRouzic
