### ISSUE TITLE
format of page is wrong 

### ISSUE THREAD

**Issue by Soyoukan** [danpros/htmly#635]
after transfer web hosting, the new space has a direct copy of the previous. however, the display is screwed up.   I dont know how to set back, and would prefer to keep the data and settings from before.  

![htmly-not-display-correct](https://github.com/danpros/htmly/assets/149935088/a1dfea85-03a3-40c2-a250-3cf083ccfe1d)

any ideas what to do?

**Comment by JPLeRouzic** [comment]
Open the "tools for Web developers" in your browser, then try to correct errors in your setup (probably JS/CSS files in the wrong place).
Good luck

**Comment by Soyoukan** [comment]
where do i find that?

**Comment by Soyoukan** [comment]
FYI  i think I found the answer.   it is the  http:// and https:// header, throwing off the loading - the page is expecting unsecured delivery but the site has now https (SSL).  I changed the link and it loaded correctly.
