### ISSUE TITLE
What happened about this?

### ISSUE THREAD

**Issue by yayalaressa** [danpros/htmly#636]
I can't access documentation.

![Screenshot 2023-11-24 011944](https://github.com/danpros/htmly/assets/16610358/d24cd999-a13c-41ec-9a81-f129b56f173a)

**Comment by vdbhb59** [comment]
It is up. Probably when Dan was making changes, it would have been down. Works now.
Also, probably close this out?

**Comment by danpros** [comment]
Marked as fixed. I will close this one.
