### ISSUE TITLE
[v2.8.4] List of posts shows wrong character encoding

### ISSUE THREAD

**Issue by bttrx** [danpros/htmly#639]
After updating from v2.8.2 to v2.8.4 today, German umlauts are displayed wrong for a post's body, i.e., my browser displays, e.g., 'FÃ¼r', when it should be 'Für'. But umlauts are fine in post title, single post view, admin panel, or when editing.

Example: https://www.robertriebisch.de/

**Update:** The problem affects existing posts only.

**Comment by danpros** [comment]
Hello,

Found the problems, its the `replace_href` function (previously `utf8_decode` (deprecated) and new version `mb_convert_encoding`). For time being please use `Summary` in blog posts display under `admin/reading` before we fix it.

**Comment by danpros** [comment]
This should fix the issue [71e2f00](https://github.com/danpros/htmly/commit/71e2f00fa9d5060bc7ad13095fe2cbec3ba4e0f6)

**Comment by bttrx** [comment]
I applied your proposed patch to my HTMLy installation manually and it worked fine. Thanks!

**Comment by danpros** [comment]
That's great!
