### ISSUE TITLE
Text "Tag" in "Add content" and "Edit" page is not translatable

### ISSUE THREAD

**Issue by MCUmbrella** [danpros/htmly#644]
Add content page:
![image](https://github.com/danpros/htmly/assets/40854260/1ed42fe9-b447-4bf8-91a9-b3b954674438)

Edit page:
![image](https://github.com/danpros/htmly/assets/40854260/78f9ac4a-b0ff-4980-88bf-f761032e4b90)

The fix is quite easy, just replace the hardcoded text with PHP code like:
![image](https://github.com/danpros/htmly/assets/40854260/c8e1290f-ea8f-48be-b042-4487f13835f2)
![image](https://github.com/danpros/htmly/assets/40854260/e2598412-aeef-45f0-b458-d26494b39c08)

**Comment by danpros** [comment]
Yes we need to change it in our next release.

**Comment by danpros** [comment]
Already implemented in latest version. I will close this one.
