### ISSUE TITLE
PHP-INTL date format

### ISSUE THREAD

**Issue by bttrx** [danpros/htmly#645]
Since I setup my HTMLy instance I used to have a custom date format, because I like to also display the time of a post.

Until HTMLy version 2.8.2 I could use a date format of `"%A, %e. %B %Y, %H:%M Uhr"`. Since version 2.8.3 I had to switch to `"EEEE, d. F Y, H:i 'Uhr'"`, because of the use of PHP-INTL.

My issue now is, days 1-9 are shown with a leading zero, because of the mangling in `format_date()`, i.e., "d" becomes "dd" automatically.

What I would like to see, is either a new custom date format config item, to which no format mangling is applied then. Or the removal of the format mangling at all.

``` php
function format_date($date, $dateFormat = null)
{
    if (empty($dateFormat)) {
        $dateFormat = config('date.format');
    }
    if (extension_loaded('intl')) {
        $format_map = array('s' => 'ss', 'i' => 'mm', 'H' => 'HH','d' => 'dd', 'm' => 'MM', 'M' => 'MMM', 'F' => 'MMMM', 'Y' => 'yyyy');
        $intlFormat = strtr($dateFormat, $format_map);
        $formatter = new IntlDateFormatter(config('language'), IntlDateFormatter::NONE, IntlDateFormatter::NONE, config('timezone'), IntlDateFormatter::GREGORIAN, $intlFormat);
        return $formatter->format($date); 
    } else {
        return date($dateFormat, $date);
    }
} 
```

References:
 * [PHP: strftime - Manual](https://www.php.net/manual/en/function.strftime "PHP: strftime - Manual")
 * [Formatting Dates and Times | ICU Documentation](https://unicode-org.github.io/icu/userguide/format_parse/datetime/#datetime-format-syntax "Formatting Dates and Times | ICU Documentation")
 * [Switch between date and IntlDateFormatter · danpros/htmly@89b637e](https://github.com/danpros/htmly/commit/89b637e9f54df79ddb19b761400605c19a90b615 "Switch between date and IntlDateFormatter · danpros/htmly@89b637e")

**Comment by danpros** [comment]
The `d` in PHP `date()` displaying date from 01-31, equivalent to `dd` in ICU and `j` to `d`  (w/o leading zero). We need to complete the `format_map` to get full conversion. 

In the mean file you can add those manually, add `'j' => 'd'` and in config.ini `EEEE, j. F Y, H:i`

**Comment by bttrx** [comment]
I see. You mean:
 * [PHP: date - Manual](https://www.php.net/manual/en/function.date.php "PHP: date - Manual")
 * [PHP: DateTimeInterface::format - Manual](https://www.php.net/manual/en/datetime.format.php "PHP: DateTimeInterface::format - Manual")

Adding `'j' => 'd'` and adjusting config.ini worked. Thanks a lot!

**Comment by danpros** [comment]
Already include it in latest release. I will close this one.
