### ISSUE TITLE
Just installed, nice app but...

### ISSUE THREAD

**Issue by webzdezign** [danpros/htmly#661]
When I go to edit a post, this happens:
Any suggestions? I've installed on Unbuntu/Apache/PHP 8.3/v2.8.8
![Screenshot 2023-12-15 at 01 10 39](https://github.com/danpros/htmly/assets/153460133/fb85c3c6-6167-4dab-8e00-7cd7908675eb)

**Comment by danpros** [comment]
Please see the server error log. Error 500 is generic error eg. Incorrect file and folder permissions, temporary connectivity issues, corrupted .htaccess file etc. Make sure mod_rewrite installed also.

**Comment by webzdezign** [comment]
> Please see the server error log. Error 500 is generic error eg. Incorrect file and folder permissions, temporary connectivity issues, corrupted .htaccess file etc. Make sure mod_rewrite installed also.

Thank you for your prompt response. I figured it was a server config error, just didn't know where. It's probably the mod_rewrite, as I haven't gotten to all the server settings yet. I'll try all that and report back.

**Comment by webzdezign** [comment]
I loaded the page, clicked edit, and checked the log: 
I don't understand this.

[15-Dec-2023 01:54:44 America/Chicago] PHP Warning:  Undefined array key -1 in /home/admin_support/public_html/system/admin/views/edit-content.html.php on line 46
[15-Dec-2023 01:54:44 America/Chicago] PHP Fatal error:  Uncaught DateMalformedStringException: Failed to parse time string (mgr) at position 0 (m): The timezone could not be found in the database in /home/admin_support/public_html/system/admin/views/edit-content.html.php:51
Stack trace:
#0 /home/admin_support/public_html/system/admin/views/edit-content.html.php(51): DateTime->__construct('mgr')
#1 /home/admin_support/public_html/system/includes/dispatch.php(352): include('/home/admin_sup...')
#2 /home/admin_support/public_html/system/htmly.php(3452): render('edit-content', Array)
#3 /home/admin_support/public_html/system/includes/dispatch.php(516): {closure}('2023', '12', 'support-site')
#4 /home/admin_support/public_html/system/includes/dispatch.php(580): route('GET', '/2023/12/suppor...')
#5 /home/admin_support/public_html/system/htmly.php(3693): dispatch()
#6 /home/admin_support/public_html/index.php(5): require('/home/admin_sup...')
#7 {main}
  thrown in /home/admin_support/public_html/system/admin/views/edit-content.html.php on line 51

**Comment by webzdezign** [comment]
My server time settings:
![Screenshot 2023-12-15 at 02 01 03](https://github.com/danpros/htmly/assets/153460133/9fae4aac-420f-4ac4-b378-c13e56822885)

**Comment by webzdezign** [comment]
Config > General Settings:
![Screenshot 2023-12-15 at 02 02 22](https://github.com/danpros/htmly/assets/153460133/849630dc-6a6f-4fe5-bf8c-62e91f074496)

**Comment by webzdezign** [comment]
Any suggestions?

**Comment by danpros** [comment]
Can you choose another timezone and date format first?

**Comment by webzdezign** [comment]
Yes. Should I go blank?

**Comment by danpros** [comment]
Yes and please set the `cache` and `content` folder as writeable. Its fine reupload the whole website, or just use online-installer.php.

**Comment by webzdezign** [comment]
They are both 777
![Screenshot 2023-12-15 at 02 29 42](https://github.com/danpros/htmly/assets/153460133/98e07151-cb75-4c3b-bc8b-c17c667414dd)

**Comment by webzdezign** [comment]
Yeah, nothing is working.
`[15-Dec-2023 02:32:27 America/Chicago] PHP Fatal error:  Uncaught DateMalformedStringException: Failed to parse time string (mgr) at position 0 (m): The timezone could not be found in the database in /home/admin_support/public_html/system/admin/views/delete-post.html.php:14
Stack trace:
#0 /home/admin_support/public_html/system/admin/views/delete-post.html.php(14): DateTime->__construct('mgr')
#1 /home/admin_support/public_html/system/includes/dispatch.php(352): include('/home/admin_sup...')
#2 /home/admin_support/public_html/system/htmly.php(3649): render('delete-post', Array)
#3 /home/admin_support/public_html/system/includes/dispatch.php(516): {closure}('2023', '12', 'support-site')
#4 /home/admin_support/public_html/system/includes/dispatch.php(580): route('GET', '/2023/12/suppor...')
#5 /home/admin_support/public_html/system/htmly.php(3693): dispatch()
#6 /home/admin_support/public_html/index.php(5): require('/home/admin_sup...')
#7 {main}
  thrown in /home/admin_support/public_html/system/admin/views/delete-post.html.php on line 14`

**Comment by danpros** [comment]
Sorry, I can't replicate it, even wrong path of temp/logs folder can cause `The timezone could not be found in the database` problems.

**Comment by webzdezign** [comment]
I removed and reinstalled it. I'm using Softalious if that helps, but it's the same issue. So I'm stuck. I won't be posting much, so I will just be sure not to have to edit or delete a post. :)

**Comment by webzdezign** [comment]
Everything else is great By The Way!

**Comment by danpros** [comment]
Is it possible if you use underscore characters for your username? because htmly currently doesn't support it. See #669

**Comment by danpros** [comment]
Please open new issue if you still find the problems in version 2.9.0
