### ISSUE TITLE
Add Content To Sidebar 

### ISSUE THREAD

**Issue by afoster1955** [danpros/htmly#662]
Is it possible to add content to the sidebar...i.e. another block where I could place a Subscribe form.  If so, how is it done?

**Comment by danpros** [comment]
Yes of course, modify the `layout.html.php` as needed. But before you do that, copy the theme to different folder first and rename to eg. `my-theme`, put back in `themes` folder.

**Comment by afoster1955** [comment]
It appears that using an include will not work, either that or I am not coding the include correctly.  Here is what I have done. I have placed this block of code right above the About block.

`<aside class="aside section">
                    <div class="section-inner">
                        <h2 class="heading"><?php echo i18n("subscribe");?></h2>
                        <div class="content">
                         <?php include "subscribe.php";?>                                  
                        </div>  
                    </div>                 
                </aside>`

**Comment by danpros** [comment]
Perhaps:

```PHP
<?php  include config('views.root') . '/subscribe.php';?>
```

**Comment by afoster1955** [comment]
I placed the subscribe.php file in the theme folder and added the following code in the layout.html.php file of the blog theme but unfortunately it does not appear in the side bar anywhere.

`<aside class="aside section">
                    <div class="section-inner">
                        <h2 class="heading"><?php echo i18n("Subscribe");?></h2>
                        <div class="content">
                         <?php  include config('views.root') . '/subscribe.php';?>                                  
                        </div>  
                    </div>                 
                </aside>`

**Comment by danpros** [comment]
In my test using echo, `<?php echo 'Work';?>` its work so I believe the problems is from the subscribe.php. I will close this one. Thanks
