### ISSUE TITLE
Some issues after the new installation

### ISSUE THREAD

**Issue by Aido21** [danpros/htmly#664]
Hi,
HTMLY was installed in a subdirectory.
Generally, everything looks fine except for some things due to them I cannot use HTMLy :-)

1. It is impossible to create any content - nothing happens when I click any link in the 'Add content' section
2. After I clicked Scheduled (in the Admin part or the top menu) I got a 404 error. All other links work fine.
3. After I clicked Admin or Dashboard I got a string 'HTMLy'

**Comment by Aido21** [comment]
I'm not sure if this is relevant, but every time I click on the link to add a post I see this in the log:
[Wed Dec 20 14:00:47.214322 2023] [fcgid:warn] [pid 27459] [client ** mod_fcgid: stderr: PHP Notice: Undefined index: type in /home/**/public_html/blog/system/htmly. php on line 409, referer: https://***/blog/admin/content

**Comment by danpros** [comment]
Hello, seems the query parameter ignored in your server (`?type=post`). Enable the mod_rewrite, try to modify the htaccess file. Eg. uncomment the `RewriteBase /` or use:

```
RewriteEngine On
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
```

In localhost I use xampp and no need any extra config except enabling the module needed (zip, intl etc.) For server, I use virtualmin and no need extra config either.

**Comment by Aido21** [comment]
Thanks,  it helped with the links.
but 
'Scheduled' and 'Posts' items still generate a 404 error
And Admin or Dashboard returns the  'HTMLy' string

**Comment by danpros** [comment]
The problems is your vhost config. In apache 2.4 should:

```
AllowOverride All
Require all granted
```
and 2.2:

```
Order allow,deny
Allow from all
```

**Comment by Aido21** [comment]
These lines exist in my config. It is running under Virtualmin.

You know I think the reason for the issue is that I installed HTMLy in a subdirectory
So I have a public_html folder with the main site and .htaccess  in it. 
And a subfolder `/blog` where I installed HTMLy. This folder has its own .htaccess

I have attached both .htaccess that you can have a look. I will very much appreciate any help.
[htaccess blog subfolder.txt](https://github.com/danpros/htmly/files/13736555/htaccess.blog.subfolder.txt)
[htaccess root.txt](https://github.com/danpros/htmly/files/13736557/htaccess.root.txt)

**Comment by danpros** [comment]
To debug it, restore the main site and htmly htaccess to the original one, start from there before adding your custom rule.

**Comment by Aido21** [comment]
Well. I disabled the root htaccess file but the issue is still here.
`mysite/blog/admin/posts,` `mysite/blog/admin/pages`, `mysite/blog/admin/draft`, etc can be opened correctly but
only `mysite/blog/admin` generates an error – Forbidden

**Comment by Aido21** [comment]
This is my current htaccess in the blog folder

```
RewriteEngine On
RewriteBase /blog/

RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /blog/index.php [L]
```

**Comment by Aido21** [comment]
so no idea why this script does not work as it should work

**Comment by danpros** [comment]
Yes I have no idea actually, I use the default htaccess and install it in sub folder and it work as it should be. It's a good idea to review how you set up your server (the virtual host etc.).

**Comment by bttrx** [comment]
@Aido21 Please post your `config\config.ini` and the _complete_ error message.

**Comment by Aido21** [comment]
Hi @bttrx 
Here it is
[config.ini.txt](https://github.com/danpros/htmly/files/13760977/config.ini.txt)

**Comment by danpros** [comment]
I'm sure this is related to server settings and not htmly itself. I will close this one. Thanks
