### ISSUE TITLE
How to customize <title></title>

### ISSUE THREAD

**Issue by bluesky0341** [danpros/htmly#667]
for example,
if my article title is ceramic cup,

then click view source code for this article

<title>ceramic cup</title> above is not good for google seo
i need <title>ceramic cup, cermic mug</title>,this is good for google seo

how can i do?

**Comment by danpros** [comment]
At the moment there is no easy way to change it eg. from admin/config, we must change it manually , edit `layout.html.php`, the title printed using:

```
    <title><?php echo $title;?></title>
```

**Comment by bluesky0341** [comment]
system/admin/views/layout.html.php    

it is as below: 

<title><?php echo $title;?></title>

**Comment by bluesky0341** [comment]
system/admin/views/layout.html.php

it is as below:

   <title><?php echo $title;?></title>

**Comment by bluesky0341** [comment]
system/admin/views/layout.html.php

it is correct as yours

**Comment by bluesky0341** [comment]
https://siliconcarbideinsert.vip/post/silicon-carbide-insert

you can check

the post title change into
silicon carbide insert, silicon carbide inserts

**Comment by bluesky0341** [comment]
i want post tile is different from <title></title> in the source code

**Comment by danpros** [comment]
No, inside the theme you are currently used. For post title go to your theme and edit `post.html.php`

**Comment by bluesky0341** [comment]
thanks
but it is difficult for me

if you can add below Input box，that will be much better

meta data
Title
Description
Keywords

**Comment by danpros** [comment]
This feature was planned but no ETA.

**Comment by bluesky0341** [comment]
thanks for reply
but this is very important function for google seo

when you have this function,we will use htmly

**Comment by danpros** [comment]
This feature has been added to the latest version. I will close this one.

**Comment by bluesky0341** [comment]
thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "danpros/htmly"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月15日(星期五) 下午4:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [danpros/htmly] How to customize <title&gt;</title&gt; (Issue #667)





 
This feature has been added to the latest version. I will close this one.
