### ISSUE TITLE
php-Warning in admin/updates 

### ISSUE THREAD

**Issue by cyberfish** [danpros/htmly#668]
Hi,

In the admin updates area I get the following php warning:

Warning: Trying to access array offset on value of type null in /../system/admin/views/update.html.php on line 27
The same in line 28, 31, 33.

Best regards
cyberfish

**Comment by danpros** [comment]
Hello,

Seems because there is no internet connection to check the latest version from github. You can ignore it at the moment, we need to add some code to display the error more clearly.

Regards,

**Comment by danpros** [comment]
Has been fixed in latest release. I will close this one
