### ISSUE TITLE
Can't edit or delete posts

### ISSUE THREAD

**Issue by Gagala-van-Org** [danpros/htmly#669]
Hi,
It is not possible for me to edit or delete posts. I already looked in the user .ini file under /htmly/config/users/, it said **role = "admin"**, I changed it to **role = admin**, but I still get error messages, several of them, please see attachments.
Can you help me, please and thank you?

[error_log.txt](https://github.com/danpros/htmly/files/13852333/error_log.txt)
[Fatal_Error_2.pdf](https://github.com/danpros/htmly/files/13852334/Fatal_Error_2.pdf)
[Fatal_Error_1.pdf](https://github.com/danpros/htmly/files/13852335/Fatal_Error_1.pdf)

**Comment by danpros** [comment]
Hi,

Already encountered the same error regarding ` The timezone could not be found in the database`. Did you create the content manually or via admin panel? try to check the file and folder permission either.

**Comment by Gagala-van-Org** [comment]
Automatically installed by cPanel / Softaculous. Permissions look normal, all folders 0755 and all files 0644.

**Comment by danpros** [comment]
Try to use file manager and paste the filename here, example: `2024-01-07-14-25-22_tag1,tag2,tag3,my_post_title.md`

**Comment by Gagala-van-Org** [comment]
Did my eMail arrive?

**Comment by danpros** [comment]
@Gagala-van-Org Yes, I will run it to my localhost. Thanks.

**Comment by Gagala-van-Org** [comment]
HTMLy is now working without problems. 
**Thank you Dan!**
Solution was to remove the appendix in the username, it was _gagala_htmly_, changed it to _gagala_ and all is well. Case closed.

**Comment by danpros** [comment]
You're welcome!

**Comment by danpros** [comment]
Latest release already support username with underscore, I will close this one. Thanks
