### ISSUE TITLE
Deprecated: rtrim(): Passing null to parameter #1 ($string) of type string

### ISSUE THREAD

**Issue by jbeuria** [danpros/htmly#670]
Hi

I am trying on php 8.2. I get the following error. 

Deprecated: rtrim(): Passing null to parameter #1 ($string) of type string

Any quick solution?

**Comment by danpros** [comment]
Hi,

What did you do before, which caused this message to appear? please provide the error message in full, so we can find out which line caused the error message. 

​

**Comment by danpros** [comment]
Please create new issue if you find this problems in version 2.9.0
