### ISSUE TITLE
Version 2.9.0 - i18n error

### ISSUE THREAD

**Issue by mrludwig** [danpros/htmly#672]
Hello Forum,
the update to version 2.9.0 causes errors on my websites.
I get the following display in the admin dashboard and on the pages for links and buttons:

_i18n_Posted_in_i18n_
_i18n_Tags_i18n_
_i18n_Uncategorized_i18n_

... and so on. Everything worked fine with the previous version. I also had no problems with the system language de_DE.

The error can be viewed at https://pilgerlanze.org
(This server has only an ipv6 address.)

I would be very grateful for any help.
Greetings
marolu

**Comment by danpros** [comment]
Hello,

Please make sure if the `de_DE.ini` is available in `lang` directory. Try to replace the language files with the new one (just in case corrupted), and select it again via dashboard and save it.

**Comment by mrludwig** [comment]
Unfortunately no change.
Are there any other ideas?

File de_DE from new HTMLy package recopied, in Dashboard first again to another language and back to de_DE, cache deleted, no change.

**Comment by mrludwig** [comment]
Solution:
I disabled (a2dismod) the mpm_event and proxy_fcgi on the Apache server and then ran 'a2enmod mpm_prefork' and 'a2enmod php8.1'. Everything worked again.

**Comment by danpros** [comment]
Hello,

I have blog using http/2 using mpm_event, php-fpm and didn't find any errors (PHP 8.3).

**Comment by mrludwig** [comment]
I have tested again:
My server has Ubuntu 22.4.3 Server LTS (not desktop!) with kernel 5.15 and php 8.1.2. 

I reactivated the modules mpm_event, php-fpm and http/2 - **and after a restart HTMLy works again!**

I think that it is not enough to just restart Apache (which I have done so far). There must be another service in the background that requires a restart after the HTMLy update.
Thanks for your support.

**Comment by kantoor** [comment]
I'm having the exact same problem. But i'm on shared hosting and can not restart the webserver. Any other actions I can take to get rid of this? It would pain me to deinstall HTMLy because of this.

**Comment by danpros** [comment]
Definitely the hosting you use enabling the server side cache for PHP file (ex. OPcache) for performance reason. So sometimes we edit certain PHP files and the new changes will take effect for a while. From OPcache config file:

```
; When disabled, you must reset the OPcache manually or restart the
; webserver for changes to the filesystem to take effect.
; For Development / testing, keep 1
; For performance / production, keep 0
opcache.validate_timestamps=0

;opcache.revalidate_freq How often in seconds should the code
;cache expire and check if your code has changed. 0 means it
;checks your PHP code every single request IF YOU HAVE 
;opcache.validate_timestamps ENABLED. opcache.validate_timestamps
;should not be enabled by default, as long as it's disabled then any value for opcache.
;revalidate_freq will basically be ignored. You should really only ever enable
;this during development, you don't really want to enable this setting for a production application.
opcache.revalidate_freq=0
```

So consult your hosting on how to change this. Usually hosting allows us to change options like this, allows `user.ini`

**Comment by mrludwig** [comment]
There are also cache systems that can be restarted on the console. There may be the following cache systems on the server:
(examples for Ubuntu) 

systemctl start memcached
service redis-server restart
systemctl restart php-fpm.service

# systemctl restart php5-fpm.service
# systemctl restart php7.0-fpm.service

However, I am not familiar with shared servers - I have my own server.

**Comment by kantoor** [comment]
Ok, ty both. I will try this. Hope I can resolve this issue.

**Comment by kantoor** [comment]
Was just about to delete my website due to this. Could not get it to work.

BUT THE LATEST UPDATE FIXED IT!

Thank you so much. This is great!
