### ISSUE TITLE
Looking to override some css

### ISSUE THREAD

**Issue by ZachBacon** [danpros/htmly#673]
So I'm basically porting a phpbb theme (prosilverdark) to htmly, and I have some minor success, but when it comes to loading posts, I'm having trouble overriding certain css elements. From what I've seen, it's done via systems/includes/functions.php But I rather not edit system files just to apply my style.

**Comment by danpros** [comment]
Hello,

Can you give an example, what kind of HTML structure do you want to achieve?

**Comment by ZachBacon** [comment]
ideally I'd like to stylize the contents of well... content(), as it stands it's overriding the current style I'm trying to adapt. I'm trying to make it look like for example like this https://board.visualboyadvance-m.org/viewtopic.php?t=816

But it's ending up more like this instead.
![Screenshot 2024-01-15 124614](https://github.com/danpros/htmly/assets/8948676/be09c17a-0bf6-4c20-b7f8-784b67a42d1a)

Mind you I'm not going for a full one on one full on copy, but it's not exactly taking on the css values I have.

**Comment by danpros** [comment]
The `content()` in `layout.html.php` is out putting the content html code generated from the template files, like main.html.php (post collection page/category, tags etc.), single post file (post.html.php), static.html.php and so on. So no need to modify the core.

**Comment by ZachBacon** [comment]
Gotcha, thanks for letting me know.

**Comment by danpros** [comment]
You're welcome. We need an improved docs, current docs is like for version below 2.7.

**Comment by danpros** [comment]
I will mark it as fixed. Thanks
