### ISSUE TITLE
Feature request: Adding Mastodon to Social Media links, adding user verification

### ISSUE THREAD

**Issue by MortenJuhl-Johansen** [danpros/htmly#679]
Due to the decentralised nature of Mastodon servers, a user gets a link to insert in a page to verify.
This is not exactly verification of identity, but it does at least assure that Mastodon user is also user who can edit a web page.

So with my account https://mstdn.dk/@mjj, I would get this snippet to insert into my page:

![image](https://github.com/danpros/htmly/assets/155162133/0eeee314-8556-4d8a-830e-36f9e0fc55d7)

On my Wordpress sites, I have put it in the footer, but an update could break that.
Now that I am getting into HTMLy and really appreciating the possibilities, I wonder if it would be possible to make room for getting the Mastodon verification link into the social media links?

**Comment by danpros** [comment]
Hello,

Yes we should adding more social link/profile in the next release. 

For verification, at the moment try add it in admin/config, under copyright line text (it allow html tags). The description text also allow html/JS but it depend on the theme, whether it displayed the description on sidebar or not.

**Comment by danpros** [comment]
Just releasing v2.9.3 with new social media links. Need to update the theme if you are using theme not included in package.
