### ISSUE TITLE
Installing Issue on armbian, lighty,

### ISSUE THREAD

**Issue by captain-wa** [danpros/htmly#681]
Hey there,
I downloaded the HTMLy version 2.9.2 onto a single-board computer with Armbian/Debian bookworm, lighty release 1.4.69-1 and php release ist 8.2+93
I unzipped the files into /var/www/html directory and changed owner + group to www-data for all files and subdirectories.
Then I started in my browser http://hostname/install.php and it seems it is creating smoothly the CMS.
But when I click on any entry of the menu I get every time the 404 Not Found page. Even I try to access by http://hostname/login I get 404 page.
A look on the file system shows me that the install.php was deleted and in ,/config/config.ini and in ./config/users there are new data. Data I entered before. When I enter local/system/admin/admin.php I get a blank page with the message "HTMLy" 
Is there any help for that issue? Thank you!

**Comment by danpros** [comment]
Hello,

Try to enable the mod_rewrite. Any server error log?

**Comment by captain-wa** [comment]
Thanks for the quick reply. I am not an expert I have only rudimentary knowledge of linux and webservers that's why i found htmly so interesting. 

HTMLy installs quickly, so I deleted the version I installed this morning and reinstalled it again. I have now looked at the log file of the lighty, there are no error messages and none were displayed in the browser during the installation.
Is there no log file for HTMLy?
I don't know what switching on mod_rewrite should do and how the parameter should be created. Can you help me with this or are there other ideas?
Thank you

**Comment by danpros** [comment]
Hello,

Please try `https://docs.htmly.com/web-servers/lighttpd`

**Comment by captain-wa** [comment]
Hi,
The problem is solved :-)
I checked the .htaccess file and found that there are options for local or internet use both are disabled. After activating local parameter the cms is running. :-)
Thank you for your support

**Comment by danpros** [comment]
That's great! 😃 

You're welcome
