### ISSUE TITLE
Question: HTMLy says server is offline for updates

### ISSUE THREAD

**Issue by MortenJuhl-Johansen** [danpros/htmly#690]
When I go into the Update section of the Admin page, I get:
_Can't check Github server for latest version. You are probably offline._
I wondered if it was a 'no update from web UI' setting, but I can not seem to find anything - could you help me in the right direction?

**Comment by danpros** [comment]
If we visiting the update page, the updater will try to open `https://api.github.com/repos/danpros/htmly/releases` to check if there is new version or not. Those message mean it fail to access the link, usually because there is no internet connection in our htmly installation.

**Comment by MortenJuhl-Johansen** [comment]
Not really sure how HTMLy on the server can be offline? I am accessing it over the web. Can it be a permissions issue?
![Skærmbillede fra 2024-02-27 21-03-07](https://github.com/danpros/htmly/assets/155162133/129774c4-d70e-46c1-9f9a-e6aa512f1501)

**Comment by danpros** [comment]
Oh I thought you were on local development environment. Yes permission problems, when checking the url it use the `file_get_contents` and need `allow_url_fopen` enabled in your php.ini. You can check it in your server error log for exact problems.

In the next release, we should add another alternatives, eg. using curl if the first try fail.

**Comment by danpros** [comment]
I will close this one. Thanks.
