### ISSUE TITLE
Teaser break handling (<!--more-->)

### ISSUE THREAD

**Issue by sb0001** [danpros/htmly#693]
I would like to suggest a different handling of teaser breaks.

If blog posts are displayed as "Full post"  should be ignored (as implemented).

If blog posts are displayed as "Summary" the summary should contain the set amount of characters, unless there is a manually inserted  in a post. Then the teaser should include everything from beginning to the teaser break - no matter whether there are more or fewer characters than specified in the settings.

If there is a teaser break in a post, the last word of the teaser should be followed by something like " ...", to make it more obvious, that it has been cut.

**Comment by danpros** [comment]
This is good idea. Regarding those `...` can be added to theme directly. Example in twentyfifteen theme:

```
    <div class="entry-content post-<?php echo $p->date;?>">
        <?php echo get_teaser($p->body, $p->url); ?>
        <?php if (config('teaser.type') === 'trimmed'):?>[...] <a class="more-link" href="<?php echo $p->url; ?>"><?php echo config('read.more'); ?></a><?php endif;?>
    </div>
```

**Comment by sb0001** [comment]
Works like a charm! Thank you! The "..." solution is definitely something for the docs - or maybe even better: an option in config?

**Comment by danpros** [comment]
Yes I already add it in my local dev. I will commit it soon, new config `teaser.ignore`.

**Comment by danpros** [comment]
Already releasing new version with this improvements. I will close this one
