### ISSUE TITLE
Function of "Meta description character" in config

### ISSUE THREAD

**Issue by sb0001** [danpros/htmly#694]
Improving the translation I came across the "Meta description character" setting in Config>Metatags. It's not clear to me what it does. In any case, it has no influence on the length of the meta description of a post. (<head><meta name="description" content="..." )

In order to find a good translation - can you please describe its function?

**Comment by danpros** [comment]
This is when the meta description leave empty during content creation (post/page/category etc.), htmly will excerpt it from the content for x char.

**Comment by sb0001** [comment]
Thanks!
