### ISSUE TITLE
show More than post

### ISSUE THREAD

**Issue by onasre** [danpros/htmly#696]
hello
i'm new with little HTML knowledge .. is there way to show more than Post per Row . right now am using Blog theme and it shows only post per row , i would like to show 2 Post's per row .side by side .. how so?
thx
![Untitled](https://github.com/danpros/htmly/assets/25161945/b530a9f3-40c8-4456-bfa5-f5d3e85355a6)

**Comment by danpros** [comment]
Hello,

By default, this theme only support one post per row, you need to change the HTML and CSS if you want to display eg. 2 posts per row. Try the following theme that use grid like layout:

- https://github.com/danpros/occasio
- https://github.com/danpros/gridzone
- https://github.com/danpros/gridzone

**Comment by onasre** [comment]
thx
