### ISSUE TITLE
I have added a translation into Croatian

### ISSUE THREAD

**Issue by m4rcus8** [danpros/htmly#699]
I have added a translation into Croatian

about = "O nama"
add_category = "Dodaj kategoriju"
add_content = "Dodaj sadržaj"
add_link = "Dodaj link"
add_menu = "Dodaj izbornik"
add_new_page = "Dodaj novu stranicu"
add_new_post = "Dodaj novi post"
add_source_link_optional = "Dodaj izvorni link (opcionalno)"
add_sub = "Dodaj podstranicu"
address_url = "Adresa (URL)"
admin = "Admin"
admin_panel_style_based_on = "Stil admin panela temeljen na"
all_blog_posts = "Svi blog zapisi"
all_cache_has_been_deleted = "Sva memorija predmemorije je izbrisana!"
all_posts_tagged = "Svi zapisi označeni"
archive_for = "Arhiva za"
archive_page_for = "Stranica arhive za"
archives = "Arhive"
are_you_sure_you_want_to_delete_ = "Jeste li sigurni da želite izbrisati <strong>%s</strong>?"
at_the_moment_you_are_using_auto_generated_menu = "Trenutno koristite automatski generirani izbornik."
audio_post = "Audio post"
audio_post_comment = "Stvaranje blog zapisa s istaknutim audio zapisom"
author = "Autor"
author_description = "Samo još jedan korisnik HTMLy-ja"
back_to = "Povratak na"
backup = "Backup"
blog_description = "U jednom odlomku, recite nam više o svom blogu."
blog_theme = "Tema bloga"
blog_title = "Naslov bloga"
blog_title_placeholder = "Moj HTMLy Blog"
blog_posts_displayed_as = "Blog zapisi prikazani kao"
breadcrumb_home_text = "Tekst početne stranice"
by_using_this_importer_you_are_agree_if_the_feed_is_yours_or_at_least_you_have_the_authority_to_publish_it = "Korištenjem ovog uvoznika pristajete ako je feed vaš ili barem imate ovlasti za objavljivanje."
css_class_optional = "CSS razred (opcionalno)"
cache_expiration = "Istjecanje predmemorije (u satima)"
cache_off = "Isključi predmemoriju"
cache_timestamp = "Oznaka vremena predmemorije"
cancel = "Otkaži"
cannot_read_feed_content = "Ne mogu pročitati sadržaj feeda"
captcha_error = "reCaptcha nije ispravna"
categories = "Kategorije"
category = "Kategorija"
check_update = "Provjeri ažuriranje"
clear_cache = "Očisti predmemoriju"
comma_separated_values = "Vrijednosti odvojene zarezom"
comment_system = "Sustav komentara"
comments = "Komentari"
config = "Konfiguracija"
congrats_you_have_the_latest_version_of_htmly = "Čestitamo! Imate najnoviju verziju HTMLy-ja."
content = "Sadržaj"
contents = "Sadržaji"
copyright_line = "Linija autorskog prava"
copyright_line_placeholder = "(c) Vaše ime."
create_backup = "Kreiraj backup"
created = "Stvoreno"
custom = "Prilagođeno"
custom_settings = "Prilagođene postavke"
dashboard = "Kontrolna ploča"
date = "Datum"
date_format = "Format datuma"
delete = "Izbriši"
description = "Opis"
disable = "Onemogući"
disabled = "Onemogućeno"
disqus_shortname = "Disqus kratko ime"
disqus_shortname_placeholder = "htmly"
draft = "Skica"
edit = "Uredi"
edit_category = "Uredi kategoriju"
edit_post = "Uredi"
edit_profile = "Uredi profil"
enable = "Omogući"
enable_blog_url = "Omogući /blog URL"
enter_image_url = "Unesite URL slike"
facebook_app_id = "Facebook ID aplikacije"
facebook_page = "Facebook stranica"
featured_audio = "Istaknuti audio"
featured_image = "Istaknuta slika"
featured_link = "Istaknuti link"
featured_quote = "Istaknuta citat"
featured_video = "Istaknuti video"
feed_url = "URL feeda"
filename = "Naziv datoteke"
follow = "Prati"
for_google_site_verification_meta = "Za meta provjeru Google stranice"
front_page_displays = "Početna stranica prikazuje"
full_post = "Cijeli post"
general = "Općenito"
general_settings = "Opće postavke"
get_one_here = "Dobiti jedan ovdje"
github_pre_release = "Github pretpregled"
google_analytics = "Google Analytics"
google_analytics_legacy = "Google Analytics (stari)"
google_search_console = "Google konzola za pretraživanje"
home = "Početna"
if_leave_empty_we_will_excerpt_it_from_the_content_below = "Ako ostavite prazno, izvat ćemo ga iz sadržaja ispod"
if_the_url_leave_empty_we_will_use_the_page_title = "Ako URL ostavite prazno, koristit ćemo naslov stranice"
if_the_url_leave_empty_we_will_use_the_post_title = "Ako URL ostavite prazno, koristit ćemo naslov posta"
image_post = "Slični post"
image_post_comment = "Stvaranje blog posta s istaknutom slikom"
import = "Uvoz"
import_feed = "Započni uvoz feeda"
import_rss = "Uvezi RSS"
import_rss_feed_2.0 = "Uvoz RSS feeda 2.0"
insert_image = "Umetni sliku"
invalid_error = "GREŠKA: Neispravno korisničko ime ili lozinka"
language = "Jezik sustava"
link_name = "Naziv linka"
link_post = "Link post"
link_post_comment = "Stvaranje blog posta s istaknutim linkom"
login = "Prijava"
login_page = "Stranica prijave"
logout = "Odjava"
menu = "Izbornik"
menus = "Uređivač izbornika"
meta_description = "Meta opis"
meta_description_character = "Meta opis znakova"
metatags = "Metatagi"
metatags_settings = "Postavke metataga"
mine = "Moje"
more = "Više"
my_draft = "Moja skica"
my_posts = "Moji postovi"
name = "Ime"
newer = "Novije"
next = "Sljedeće"
next_post = "Sljedeći post"
no_available_backup = "Nema dostupnih sigurnosnih kopija trenutno."
no_draft_found = "Nema pronađenih skica"
no_posts_found = "Nema pronađenih postova"
no_related_post_found = "Nema pronađenih srodnih postova"
no_scheduled_posts_found = "Nema zakazanih postova!"
no_search_results = "Nema rezultata pretraživanja"
nope = "Ne"
not = "Ne"
older = "Starije"
only = "Samo"
operations = "Operacije"
page = "Stranica"
page_generation_time = "Vrijeme generiranja stranice"
pages = "Stranice"
pass_error = "Polje lozinke je obavezno"
password = "Lozinka"
performance = "Performanse"
performance_settings = "Postavke performansi"
permalink = "Trajna poveznica"
popular = "Popularno"
popular_posts = "Popularni postovi"
popular_posts_widget = "Widget popularnih postova"
popular_posts_widget_at_most = "Widget popularnih postova najviše"
popular_tags = "Popularne oznake"
post_by_author = "Postovi ovog autora"
posted_in = "Objavljeno u"
posted_on = "Objavljeno"
posts = "Postovi"
posts_by = "Postovi od"
posts_draft = "Skice postova"
posts_in_archive_page_at_most = "Postovi na stranici arhive najviše"
posts_in_category_page_at_most = "Postovi na stranici kategorije najviše"
posts_in_front_page_show_at_most = "Postovi na početnoj stranici prikazuju najviše"
posts_in_profile_page_at_most = "Postovi na stranici profila najviše"
posts_in_search_result_at_most = "Postovi u rezultatima pretraživanja najviše"
posts_in_tag_page_at_most = "Postovi na stranici oznake najviše"
posts_in_type_page_at_most = "Postovi na stranici tipa najviše"
posts_index_settings = "Postavke indeksa postova"
posts_list = "Popis postova"
posts_tagged = "Postovi označeni"
posts_with_type = "Postovi s tipom"
pre_release = "Predačka verzija"
prev = "Prethodno"
prev_post = "Prethodni post"
preview = "Pregled"
profile_for = "Profil za"
proudly_powered_by = "Ponosno pokreće"
publish = "Objavi"
publish_draft = "Objavi skicu"
published = "Objavljeno"
quote_post = "Citirani post"
quote_post_comment = "Stvaranje blog posta s istaknutim citatom"
rss_character = "RSS znakova"
rss_feeds_show_the_most_recent = "RSS feedovi prikazuju najnovije"
rss_settings = "Postavke RSS-a"
read_more_text = "Tekst za pročitaj više"
read_more_text_placeholder = "Pročitaj više"
reading = "Čitanje"
reading_settings = "Postavke čitanja"
recaptcha = "reCAPTCHA"
recent_posts = "Nedavni postovi"
recent_posts_widget_at_most = "Widget nedavnih postova najviše"
regular_post = "Redoviti post"
regular_post_comment = "Stvaranje redovitog blog posta"
related_posts = "Srodni postovi"
related_widget_posts_at_most = "Widget srodnih postova najviše"
revert_to_draft = "Vrati u skicu"
save = "Spremi"
save_config = "Spremi konfiguraciju"
save_edit = "Spremi uređivanje"
save_menu = "Spremi izbornik"
save_as_draft = "Spremi kao skicu"
save_category = "Spremi kategoriju"
scheduled = "Zakazano"
scheduled_posts = "Zakazani postovi"
scheduled_tips = "Objavljivanje posta s budućim datumom ili vremenom, bit će dodano u zakazane postove"
search = "Pretraži"
search_for = "Pretraži"
search_results_for = "Rezultati pretrage za"
search_results_not_found = "Nisu pronađeni rezultati pretrage!"
secret_key = "Tajni ključ"
settings = "Postavke"
sign_in_to_start_your_session = "Prijavite se kako biste započeli svoju sesiju"
site_key = "Ključ web stranice"
sitemap = "Sitemap"
slug = "Slug"
social_media = "Društveni mediji"
static_page = "Statička stranica"
static_page_comment = "Stvaranje statičke stranice"
static_pages = "Statičke stranice"
summary = "Sažetak"
summary_character = "Sažetak znakova"
tag = "Oznaka"
tagcloud_widget_at_most = "Tag oblak najviše"
tagline = "Slogan"
tagline_placeholder = "Platforma za blogovanje bez baze podataka u PHP-u"
tagline_description = "U nekoliko riječi, objasnite o čemu se radi u ovom blogu."
tags = "Oznake"
this_is_legacy_code_usually_new_created_analytics_using_gtag_js = "Ovo je stari kod. Obično se novi stvoreni analitički podaci koriste pomoću gtag.js"
this_page_doesnt_exist = "Ova stranica ne postoji!"
time = "Vrijeme"
timezone = "Vremenska zona"
title = "Naslov"
to_using_disqus_or_facebook_comment_you_need_to_provide_disqus_shortname_or_facebook_app_id = "Za korištenje Disqus ili Facebook komentara morate pružiti svoje Disqus kratko ime ili vaš Facebook App ID."
token_error = "CSRF token nije ispravan"
tools = "Alati"
twitter_account = "Twitter račun"
type_to_search = "Upišite za pretraživanje"
uncategorized = "Nekategorizirano"
uncategorized_comment = "Teme koje ne trebaju kategoriju ili ne odgovaraju bilo kojoj drugoj postojećoj kategoriji"
universal_analytics = "Univerzalna analitika (gtag.js)"
unknown_feed_format = "Nepoznat format feeda"
update = "Ažuriraj"
update_available = "Dostupno ažuriranje"
update_draft = "Ažuriraj skicu"
update_post = "Ažuriraj post"
update_to = "Ažuriraj na"
upload = "Učitaj"
user = "Korisnik"
user_error = "Polje korisnika je obavezno"
valid_values_range_from_0_to_1.0._see = "Valjane vrijednosti su u rasponu od 0,0 do 1,0. Pogledajte"
video_post = "Video post"
video_post_comment = "Stvaranje blog posta s istaknutim videom"
view = "Pogled"
view_post = "Pogledaj"
views = "Pregledi"
widget = "Widget"
widget_settings = "Postavke widgeta"
would_you_like_to_try_our = "Biste li željeli isprobati naš"
yes_im_in = "Da, uključen sam"
yes_not_recommended = "Da (nije preporučeno)"
you_dont_have_permission_to_access_this_page = "Nemate dopuštenje pristupiti ovoj stranici"
your_new_config_key = "Vaš novi konfiguracijski ključ"
your_new_value = "Vaša nova vrijednost"
your_backups = "Vaše sigurnosne kopije"
your_latest_blog_posts = "Vaši najnoviji blog postovi"
your_recent_posts = "Vaši nedavni postovi"
by = "od"
hint_use_ctrlcmdf_to_search_for_your_config_key_or_value = "<u>savjet:</u> Koristite <code>Ctrl</code>/<code>CMD</code> + <code>F</code> za pretraživanje vašeg konfiguracijskog ključa ili vrijednosti."
homepage = "početna stranica"
instead = "umjesto"
item_class = "Unesite CSS razred"
item_slug = "Unesite URL linka"
now = "sada"
of = "od"
optional = "opcionalno"
post_your_post_slug = "/post/naslov-posta"
pro_tips_you_can_creating_custom_config_key_and_print_out_your_config_key_value_anywhere_in_your_template = "<u>pro savjeti:</u> Možete stvoriti prilagođene konfiguracijske ključeve i ispisati vrijednost vašeg konfiguracijskog ključa bilo gdje u vašem predlošku."
read_more = "pročitaj više"
widget_key_placeholder = "12345abcde"
year_month_your_post_slug = "/godina/mjesec/naslov-posta"
your_key = "vaš.ključ"

**Comment by m4rcus8** [comment]
Add in the next update

**Comment by danpros** [comment]
@m4rcus8 great, thank you! You can try [Create pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests) to credit it to you.

**Comment by danpros** [comment]
Already added it to master branch. See [b35ea37](https://github.com/danpros/htmly/commit/b35ea374b0e233170d46af5d37baa5e57ae25517)

**Comment by danpros** [comment]
Release new version that has this language. I will close this one
