### ISSUE TITLE
New install of HTMLY as of 3/15/2024

### ISSUE THREAD

**Issue by MrBear777** [danpros/htmly#702]
Everything great without a hitch with the install... Then ran into this issue when importing some my rss feeds. 
![poof](https://github.com/danpros/htmly/assets/122763947/e52ab11e-64b5-4ea4-b67f-94117513ff03)
Checked everything all php function enable.. I just must of missed something simple and cant figure it out..

**Comment by danpros** [comment]
Make sure to set it full text in your WP feed settings. htmly only takes data from the feed, so for example if the feed contains e.g. divs etc. then these elements will be saved too

**Comment by danpros** [comment]
Can you paste the content of the post here (the structure)? replace the text with lorem ipsum etc. or send example of the post to dan [at] danpros.com
