### ISSUE TITLE
Is it possible to center an image / text ?

### ISSUE THREAD

**Issue by RenaudILTIS** [danpros/htmly#703]
Hello, I'm a new user of HTMLy, first of all thanks for the great work 👏🙏

1. Is there a way to modify the menu label "Home" of the static homepage ?
2. And to edit this page, is there another way than the "Edit" button on the preview ?

Best regards,
R.

**Comment by danpros** [comment]
Hello, 

1. You can change it in `admin/config/metatags` and scroll to `Miscellaneous`. Change the `Breadcrumb home text`
2. Yes you can. Please read this for more info: [Custom template](https://docs.htmly.com/theming/structure#custom-layout.subpage-structurel)

Create `static--front.html.php`. Copy and paste the content inside `static.html.php` to `static--front.html.php` and you can edit it as you wish. For available variable for static page: [static.html.php](https://docs.htmly.com/theming/variables#static.html.php.subpage-variables)

Yes we need to update the docs 😃

**Comment by RenaudILTIS** [comment]
Thank you very much, I will check.
