### ISSUE TITLE
I can't install /ly/ not found

### ISSUE THREAD

**Issue by Coeur2louve** [danpros/htmly#705]
Hello,
I try to install HTMLy on local, to use as my personal diary.
I did on Macbook pro 10.13.6 5high Sierra)
My localhost is ok, I developed my website in and everything works great.
After running install.php , an html page with links is visible but if i click on a link this appears
**on admin** 
Not Found
The requested URL /ly/admin/
**on posts**
The requested URL /ly/admin/posts was not found on this server
Could you explain what i did wrong, please, or how to fix it ?
I also tried with online installer, it is worst... red and orange tables with a lot of warning .
Thank you for help
PS : I am french, hope i explain well

**Comment by danpros** [comment]
Hello,

You can paste the error message here or It would be simpler if you were willing to install [XAMPP for Mac](https://www.apachefriends.org/download.html)

**Comment by Coeur2louve** [comment]
Hello,
Thank you for your fast answer.
I did it again with Mamp and online installer, here the message :

Fatal error: Maximum execution time of 30 seconds exceeded in /Users/Capitan/Sites/Blog/htmly/online-installer.php on line 4339

**Comment by Coeur2louve** [comment]
I am not a coder, maybe it is because something is not correct with requirements ?

**Comment by danpros** [comment]
You can change the `max_execution_time ` in `php.ini`.

```
max_execution_time = 120
```

Please check the MAMP docs for how to change this file.

**Comment by Coeur2louve** [comment]
Hello Danpros,
Thank you so much ! Time set on 120 and HTMLy is now running on my mac.
So happy !

**Comment by Coeur2louve** [comment]
Oh my God, I thought I could use HTMLy, but, if I can go on admin panel an write my first post, when I click on to view like frontend (in mamp):
**Cette page ne fonctionne pas
Impossible de traiter cette demande via localhost à l'heure actuelle.
HTTP ERROR 500**

So, I passed threw local webserver (apache) to view whats happen : 

![Capture d’écran 2024-03-23 à 12 26 53](https://github.com/danpros/htmly/assets/164556605/f311832c-85c8-4900-8477-b6cdc2b482a9)
:-(

**Comment by danpros** [comment]
I'm not familiar with MAMP on MAC, read a little and you should put it in the htdocs folder. Let say put the folder in` htdocs/htmly`, and it accessible from `localhost:8888/htmly`

**Comment by Coeur2louve** [comment]
Here 
![Capture d’écran 2024-03-23 à 13 42 46](https://github.com/danpros/htmly/assets/164556605/182b27e6-c753-4349-a264-ecb825170658)

**Comment by Coeur2louve** [comment]
Good morning,
Finally, I have erased all HTMLy files because it seems that a lot of things were missing, then I have uploaded the local installer and TADA ! Backend and frontend are on the way.

**Comment by danpros** [comment]
@Coeur2louve that's great! glad you can solve it.
