### ISSUE TITLE
Sub-category ?

### ISSUE THREAD

**Issue by Coeur2louve** [danpros/htmly#706]
Hello again,
I wonder if it is possible to add sub-categories ? 
Example : I use HTMLy on local to store my Tarot learning exercises and spreads.
I wish to have the main category Tarot, and sub-categories like exercises, major arcanes, minor arcanes, families (swords, etc...) to centralise meaning of each cards (I have some books, it is not confortable to jump from each to find informations).
Is there still a setting I have missed ? 
Thank you.

**Comment by danpros** [comment]
Hello,

At the moment htmly only support one level category. A possible solution that can be applied in this case is to use tags

**Comment by danpros** [comment]
With the current folder structure, it is not possible to have more than one category per article. Thanks
