### ISSUE TITLE
Multiple users with different roles ?

### ISSUE THREAD

**Issue by RenaudILTIS** [danpros/htmly#707]
Hello, is it possible to add some writers, other than the admin, with different roles ?

Best regards,
R.

**Comment by danpros** [comment]
Hello,

Yes its possible, you need to create the user manually and set the role to `role = user`. This feature is still very basic, it needs to be developed further.

**Comment by RenaudILTIS** [comment]
OK, I will test it and see what is allowed to the user.
Thanks.

**Comment by RenaudILTIS** [comment]
I just tested it.

There are some issues : the user has access to all the buttons of the statics pages, and can edit all content by using the Edit button on the website view. Could you fix it ? I think that a "user" must only be authorised to modify a content if it's his content.
Simple rule : if there is a modification of a content and that the user is not the author, abort.

What do you think about it ?

**Comment by danpros** [comment]
At the moment it only show the access denied page when regular user try to edit other user content. Previously, development prioritized performance and features, where these features were very necessary for simple blogging, so even though the role already existed, it had not been implemented optimally.

So for the next versions, let's try to focus on blogging for several writers

**Comment by RenaudILTIS** [comment]
👍

**Comment by marcelklein1898** [comment]
Hello,
In the case of a site with many authors, I would like to add that I think it would be good to separate roles among three types of users:

1. Administrator: with all permissions. 
2. Editor: only with permissions to edit other authors' posts and, perhaps, the static pages. I'm not sure if the latter is recommended.
3. Writer: who can only edit his own posts.

Best regards

**Comment by danpros** [comment]
Hi,

That's good idea, let see how it goes

**Comment by danpros** [comment]
Please try the latest version (v.2.9.6), new users management and roles.
