### ISSUE TITLE
"TOC" showing in the post list widget

### ISSUE THREAD

**Issue by RenaudILTIS** [danpros/htmly#709]
Hello, with the "blog" theme, if I add a TOC at the beginning of a post, the preview of the post in the sidebar widget begins with "Table Of Content".

![image](https://github.com/danpros/htmly/assets/5601919/bae3c39f-1d61-4f82-82b0-31168e4875e7)

Is there a simple way to correct it ?

**Comment by danpros** [comment]
Hello,

The simplest way, edit `layout.html.php` and using `str_replace`. 

Replace the:

```php
<p><?php echo shorten($l->body, 75); ?>...</p>
```

To:

```php
<p><?php echo shorten(str_replace('Table of Contents', '', $l->body), 75); ?>...</p>
```

**Comment by RenaudILTIS** [comment]
OK, is it possible to use the TOC label variable ? (If the user change 'Table of Contents' label in the admin panel, it will not works.)

**Comment by danpros** [comment]
In htmly we can print config key value in `config.ini`, for TOC label is `toc.label`. To print the value:

```php
// config('toc.label')
<p><?php echo shorten(str_replace(config('toc.label'), '', $l->body), 75); ?>...</p>

Clear the cache.
```

**Comment by RenaudILTIS** [comment]
Great, thank you !

**Comment by danpros** [comment]
Just releasing new version that automatically remove those label when using the `shorten()` function. This should fix this issue

**Comment by RenaudILTIS** [comment]
Thanks a lot !
