### ISSUE TITLE
Try to add a "center" option for images in the markdown editor

### ISSUE THREAD

**Issue by RenaudILTIS** [danpros/htmly#710]
Hello,

I modified the [Markdown.Converter.js](https://github.com/danpros/htmly/blob/master/system/admin/editor/js/Markdown.Converter.js) file on line 713 with the following code.

With this code, if you replace **![image description][1]** by **![image description][1-center]**, the image is encapsulated in a div with "text-align:center !important" inline style.

It's OK in the article editor, but it's not on the website.

I tried to modify [Mardown.php](https://github.com/danpros/htmly/blob/master/system/vendor/michelf/php-markdown/Michelf/Markdown.php) without success.

Do you have a suggestion to allow the user to center the image in the editor (not in the theme files) ?

BR,
R.

Code JS :
`
		function writeImageTag(wholeMatch, m1, m2, m3, m4, m5, m6, m7) {
			var whole_match = m1;
			var alt_text = m2;
			var link_id = m3.toLowerCase();
			var url = m4;
			var title = m7;

			if (!title) title = "";

			// Check if the ID has the suffix -center and remove it
			var centerImage = false;
			if (link_id.endsWith("-center")) {
				centerImage = true;
				link_id = link_id.substring(0, link_id.length - 7); // Remove suffix -center
			}

			if (url == "") {
				if (link_id == "") {
					link_id = alt_text.toLowerCase().replace(/ ?\n/g, " ");
				}
				url = "#" + link_id;

				if (g_urls.get(link_id) != undefined) {
					url = g_urls.get(link_id);
					if (g_titles.get(link_id) != undefined) {
						title = g_titles.get(link_id);
					}
				} else {
					return whole_match;
				}
			}

			alt_text = escapeCharacters(attributeEncode(alt_text), "*_[]()");
			url = escapeCharacters(url, "*_");
			var result = "<img src=\"" + url + "\" alt=\"" + alt_text + "\"";

			title = attributeEncode(title);
			title = escapeCharacters(title, "*_");
			if (title) {
				result += " title=\"" + title + "\"";
			}

			result += " />";

			// style for center
			if (centerImage) {
				result = "<div style=\"text-align:center !important;\">" + result + "</div>";
			}

			return result;
		}`

**Comment by danpros** [comment]
The editor allow html tag, so wrap the image using html tag instead, eg.

```html
<span class="center">![enter image description here][1]</span>
```

Than create css `.center {text-align:center}`

or wrap with:

```
<center>![enter image description here][1]</center>
```

**Comment by RenaudILTIS** [comment]
OK, the second solution work in my case, thanks !
