### ISSUE TITLE
Confusion about static.html.php

### ISSUE THREAD

**Issue by CharliePoole** [danpros/htmly#711]
The docs do not make it very clear what this is used for. I had assumed it would be used as the main layout for any static pages, but I see that's not true. In fact, I can't find any code in either htmly.php or dispatch.php that uses this file and if I force it to be used, it doesn't work.

In the docs, you use the word "template" for this file and the code in it appears to be partial. So I'm assuming it should be copied into some other file. But I can't see any example of exactly how that is supposed to be done. Can you help?

My goal is to not display the post information in the aside column on some of my static pages.

**Comment by danpros** [comment]
Oh the layout for static page is `layout--static.html.php` (all static page), you can read about custom template [here](https://docs.htmly.com/theming/structure#custom-layout.subpage-structure). Please remember the `static.html.php` is printed using `content()` in `layout.html.php`

**Comment by CharliePoole** [comment]
OK, I was beginning to think that might be the case, but I had to actually read the code to get there. FWIW, I would have liked a bit more in the docs to point me in the right direction. Funny, I just had to answer an issue about unclear docs on one of my own projects, so karma. :-)

**Comment by danpros** [comment]
Yes, the documentation really needs to be updated, especially the information for customizing templates etc. 😃

**Comment by CharliePoole** [comment]
It's too bad the doc source isn't online - I'd try to write what I imagine
I could have used.

**Comment by danpros** [comment]
@thopanX Thanks! I will try to upload the docs to github so anyone can improve it.

**Comment by danpros** [comment]
@thopanX Already upload the docs to GitHub: https://github.com/danpros/htmly-docs

I will close this one. Thanks.
