### ISSUE TITLE
code behind 404-search.html.php re-direction

### ISSUE THREAD

**Issue by splifingate** [danpros/htmly#714]
Greetings.

I have adapted/incorporated a cohesive search function within a modified docs theme.

My primary question is "to where in the code that a failed search query hooks to the 404-search.html.php page, so that I may re-direct".

If I were to have my way, I would re-direct failed search functions to the primary blog page, thus eliminating the intermediary "Please search again, or would you like to visit our [homepage] instead?" step.

Seeking guidance, and enlightenment :)

**Comment by danpros** [comment]
Hello,

Its in `htmly.php` line 3026. But you can do that without modify the core, simply open `404-search.html.php` and add the redirection there, eg.

```php
<?php if (!defined('HTMLY')) die('HTMLy'); ?>
<?php $redir = site_url(); header("location: $redir");?>
```

**Comment by splifingate** [comment]
Ah!  Oh!  Cool.  Thank you.

I have already re-labeled it as "Docks", and it is enabled.

I'll explore, and report back.

**Comment by splifingate** [comment]
> add the redirection there

Worked beautifully!

Thank you so much.

btw, totally-fantastic soft you have created :)

**Comment by danpros** [comment]
Great, thank you!
