### ISSUE TITLE
(https://www.ascii-code.com/CP1252/191) "inverted question mark" automagically-added to each line of [post].md

### ISSUE THREAD

**Issue by splifingate** [danpros/htmly#715]
I am using HTMLy on a Mac, and use BBEdit as my primary editor.

For each post I add, I am seeing a red inverted question mark at the end of each line (when editing each [post].md in BBEdit).

I can choose "Text > Normalize Line Endings" to nix these Editor display-oddities.

Unfortunately, they re-appear after editing/updating a post in HTMLy

For all intensive purposes, these ¿ do not impact the display of anything *but* that which I see in my editor.

I normally use Firefox, but I do test in Safari.  I do not use Chrome.

I have yet to test things on the Win side of things, but I imagine (since Edge is now, basically, Chrome), observations will be the same.

I guess this is basically an enigma, wrapped in a conundrum;, thus has no real impact beyond what a user might see at the character:editor level.

Where in the code might I find such an addition?

Thoughts/observations?

Thank you.

**Comment by danpros** [comment]
Found it on [stackoverflow](https://stackoverflow.com/questions/58700632/use-bbedit-to-replace-cr-with-lf).

> A possibly simpler way to do this is to make sure you enable "Line Break Types" in BBedit's Preferences -> Appearance.
> I also turn on "Text Encoding" as well, in case I need to switch between UTF8 and UFT16 and others.)

**Comment by splifingate** [comment]
Yes; I have those selectors set.

The ¿ is always appended to each line-ending in the display of the body of the .md, no matter what option I select *shrugs*

<!--t, <!--d, <!--tag, <!--etc. in the .md do not have the ¿ appended

I am of the mind that .md should be .md, so I'm resolving this oddity back to the BBEdit .md processor (cmark, in this case).

I will further query my finding with the Author, and try a different code editor for comparison.

Thank you.

**Comment by danpros** [comment]
Yes please try it using other text editor, if the problem persists then something needs to be improved in htmly

**Comment by splifingate** [comment]
I will report back observations, when I can :)

**Comment by splifingate** [comment]
Hi again, Dan!

Author's reply to the question of the display:

> Bare Bones Software Technical Support wrote on 4/6/24 08:22:
> splifingate,
>
> Thanks for writing in again.
>
> The files that you're describing contain mixed line endings; the front matter is terminated with only Unix line breaks (LF only), but the remainder of the file uses Windows-style line breaks (CR/LF).
>
> Since BBEdit uses only the first line ending to determine the line-ending format of the entire file (for computing its internal representation during open and save), the CR used in the Windows line breaks appear as gremlins in the rest of the file.
>
> It is probably worth investigating HTMLy to see if there is a means to control its output format; failing that, filing an issue ticket requesting that the output format be internally consistent will make everyone's life better going forward.
>
> Regards,
>
> Rich Siegel
> Bare Bones Software, Inc.

I think understand a little more, and can now (I believe) identify from where the odd display is derived.

Each line in the `<!--front "matter" front-->` ends in `#0A` . . . `\n`

Each subsequent line in the .md ends in `#0D0A` . . . `\x{0D}\n`

I was looking around in /system/ a bit.

A couple of components have Eol checks:

/system/vendor/michelf/php-markdown/Michelf/Markdown.php

```
235		# Standardize line endings:
236		#   DOS to Unix and Mac to Unix
237		$text = preg_replace('{\r\n?}', "\n", $text);
238
239		# Make sure $text ends with a couple of newlines:
240		$text .= "\n\n";
```

And, in /system/admin/editor/js/Markdown.Editor.js

```
390    // Converts \r\n and \r to \n.
391    util.fixEolChars = function (text) {
392        text = text.replace(/\r\n/g, "\n");
393        text = text.replace(/\r/g, "\n");
394        return text;
395    };
```

...and it looks like they should be doing their job ;)

Could it be something to do with the difference (if any) there may be between `\r` and `\x{0D}\n`?

I will explore, further.

Thanks for your thoughts.

**Comment by danpros** [comment]
Seems the problems is from the text editor (pagedown). The editor used is similar with [Stackedit](https://stackedit.io) but they improved (developed it further). You can try using it to test the generated markdown, it has similar problems or not.

**Comment by danpros** [comment]
Is this perhaps because there is no new line after the content? example when saving the static page to file:

```php
 $post_content = '<!--t ' . $post_title . ' t-->' . $post_description . "\n\n" . $content;
```

It should:

```php
 $post_content = '<!--t ' . $post_title . ' t-->' . $post_description . "\n\n" . $content . "\n";
```

**Comment by splifingate** [comment]
Ah, it was worth a try ;)

I changed all `$content;`  in admin.php to `$content . "\n";`

Unfortunately, all this does is add a newline at the end of the original content (a newline, however which is `x0A`, and not `x0D0A`).

Thank you for the hint.

I've been exploring the current parsedown editor (adding others seems excessively tedious/overly bloated), and there *must* be a simpler solution for such a trivial thing) . . .

It will take some time, but I believe the `x0D0A` newlines are buried in the regex.  For ex:

`/system/admin/editor/js/Markdown.Editor.js`

`2355  regex = /((?:(?:[^\n]*?\|[^\n]*) *)?(?:\r?\n|^))((?:\| [...]`

I will explore further...

**Comment by danpros** [comment]
Yes please try to debug it. htmly use this one https://github.com/StackExchange/pagedown

How about this one?

```php
 $post_content = '<!--t ' . $post_title . ' t-->' . $post_description . "\n\n" . $content . PHP_EOL;
```

**Comment by splifingate** [comment]
I will persist, and will try that option in a while.

Currently testing regex variations, and my head is exploding ;)

I must say:  apart from that weird upside-down ¿ that is currently only displaying in my editor (and is driving me insane), everything with your soft is absolutely splendid . . . thank you :)

**Comment by splifingate** [comment]
"Edit: add PHP_EOL instead of \n"

This added a newline at the end of the document (the same as the previous `. "\n";` attempt did.

**Comment by splifingate** [comment]
I must set things down for a little while . . . this is just so overwhelming ;)

**Comment by splifingate** [comment]
ok . . . *breathes*

So, it's so: the regex path was twisty-windy, and cracked-and-broken, thought it has not yet reached it's end;  I did gain a much better understanding of pcre, however ;)

I will revisit this idea when my eyes have become un-crossed....

I did have something of a back-trace-breakthrough this eve.

I found a query on StackOverflow about the proper usage of PageDown ([How to use PageDown Markdown editor?](https://stackoverflow.com/questions/13013315/how-to-use-pagedown-markdown-editor)), and a User there cautioned another about whitespace in the `<texarea></textarea>`.

/system/admin/views/edit-content.html.php (Orig):

```
[...]
                <div class="col-sm-6">
                    <div>
                        <label for="wmd-input"><?php echo i18n('Content');?> <span class="required">*</span></label>
                        <div id="wmd-button-bar" class="wmd-button-bar"></div>
                        <textarea id="wmd-input" class="form-control wmd-input <?php if (isset($postContent)) { if (empty($postContent)) { echo 'error'; } } ?>" name="content" cols="20" rows="15"><?php echo $oldcontent ?></textarea><br>
                        <?php if ($isdraft[4] == 'draft') { ?>
                            <input type="submit" name="publishdraft" class="btn btn-primary submit" value="<?php echo i18n('Publish_draft');?>"/> <input type="submit" name="updatedraft" class="btn btn-primary draft" value="<?php echo i18n('Update_draft');?>"/> <a class="btn btn-danger" href="<?php echo $delete ?>"><?php echo i18n('Delete');?></a>
                        <?php } else { ?>
                            <input type="submit" name="updatepost" class="btn btn-primary submit" value="<?php echo i18n('Update_post');?>"/> <input type="submit" name="revertpost" class="btn btn-primary revert" value="<?php echo i18n('Revert_to_draft');?>"/> <a class="btn btn-danger" href="<?php echo $delete ?>"><?php echo i18n('Delete');?></a>
                        <?php }?>
                        <br><br>
                    </div>
                </div>
[...]   
```
/system/admin/views/edit-content.html.php (Mod):

```
[...]
                <div class="col-sm-6">
                    <div>
                        <label for="wmd-input"><?php echo i18n('Content');?> <span class="required">*</span></label>
                        <div id="wmd-button-bar" class="wmd-button-bar"></div>
                        <textarea id="wmd-input" class="form-control wmd-input <?php if (isset($postContent)) { if (empty($postContent)) { echo 'error'; } } ?>" name="content" cols="20" rows="15">
                        	<?php echo $oldcontent ?>
                        </textarea><br>
                        <?php if ($isdraft[4] == 'draft') { ?>
                            <input type="submit" name="publishdraft" class="btn btn-primary submit" value="<?php echo i18n('Publish_draft');?>"/> <input type="submit" name="updatedraft" class="btn btn-primary draft" value="<?php echo i18n('Update_draft');?>"/> <a class="btn btn-danger" href="<?php echo $delete ?>"><?php echo i18n('Delete');?></a>
                        <?php } else { ?>
                            <input type="submit" name="updatepost" class="btn btn-primary submit" value="<?php echo i18n('Update_post');?>"/> <input type="submit" name="revertpost" class="btn btn-primary revert" value="<?php echo i18n('Revert_to_draft');?>"/> <a class="btn btn-danger" href="<?php echo $delete ?>"><?php echo i18n('Delete');?></a>
                        <?php }?>
                        <br><br>
                    </div>
                </div>
[...]
```
. . . this added  25nbsp+newline+¿ to the beginning of the content, and 24nbsp at the end.

I then reverted to Orig, and the 25nbsp+newline+¿/24nbsp dis-appeared.

So, whitespace within the `<textarea></textarea>` block *does* affect the end product.

This got me to looking closer, which led me to $oldcontent

/system/admin/views/edit-content.html.php

```
17 $oldcontent = remove_html_comments($content);
```

which led me to $content

```
13 $content = file_get_contents($filename);
```
(which I further found in)

/system/includes/functions.php

```
697        // Get the contents and convert it to HTML
698        $content = file_get_contents($post->file);
```
This a mystery, wrapped in an enigma, for-sure ;)

I still can't escape (no pun intended) the idea that the addition of the \x0D0A at the end of each `</p>` is a result of something the [Markdown.(San/Ex/Ed/Con)].js in the PageDown code, but at-least I did affect a change in **something**!

Still searching....

**Comment by danpros** [comment]
@splifingate Thank you for your efforts to find where the problem is 😃 

Is this possible because when htmly save the content to file using?

```php
file_put_contents($dir . $filename, print_r($post_content, true), LOCK_EX);
```
Using `print_r` instead of:

```php
file_put_contents($dir . $filename, $post_content, LOCK_EX);
```

`admin.php` in `add_content` function.

**Comment by splifingate** [comment]
Mac/Win . . . should not matter ;)

I d/l SublimeText to check an alternative, and it merely displayed newlines (as if they were just LF) in each .md

Still, the content of .md's *as-edited* in HTMLy **do** have newlines as 0D(CR)0A(LF) (while the  lines are 0A(LF).  Another 16-bits(?) per line in the body, but not a show-stopper.

I (and others with whom I have shared) get some seriously nice output from the blog-thing I'm working to create <smile>

Per your suggestion, I subsequently replaced each `print_r($post_content, true),` with `$post_content,` . . .

. . . each line of the body *still* ends with 0D0A *shrug*

There's just something wonky with the antiquated PageDown .js code.

I took a look at the newer version of AdminLTE . . . the details of which are a bit beyond what I really understand.

However, the newer version does allow the incorporation of the [Summernote](https://github.com/summernote/summernote/) and [CodeMirror](https://codemirror.net/) editors.

I may play with such incorporations.

**Comment by splifingate** [comment]
ok, so . . . I went the roundabout with entertaining a different editor, and I found that this is a twisty-windy road of complication and bloat (no deprecation to those of you who would love to entertain the idea of replacing historically-outdated, yet still-functional, code ;)

The normalization of line-endings with github projects is **A Thing**; or, I should say, the clarification and normalization of line-ending with Projects that are mixed (between Win and Mac) often lead to CRLF *and* LF ambiguities, most (if not all) of which can be solved entirely from within git.

[Mind the End of Your Line](https://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/) eloquently describes the issue, and clarifies a solution:

> One final note that the [man page for gitattributes](http://schacon.github.com/git/gitattributes.html) mentions is that you can tell git to detect all text files and automatically normalize them (convert CRLF to LF):

`*       text=auto`

> This is certainly better than requiring everyone to be on the same global setting for core.autocrlf, but it means that you really trust Git to do binary detection properly. In my opinion it is better to explicitly specify your text files that you want normalized.

This being quoted/said, I have attempted to learn git (clone/mod/add/etc.) in an untimely manner.

Suffice it be said, that I may be experiencing an outlying (albeit *not* a show-stopper) situation that highlights such a scenario.

It is my proposition that the addition of `.gitattributes` (with the contents being `* text=auto` or `* text=auto eol=lf') at the root of Master might reconcile such a difference.

If I can get my poop-in-a-group, I may be able to share a PR from the Fork I have made (and am attempting to modify) ;)

I am facing a logarithmic learning curve, as some of these Tools are quite unfamiliar to me.

Regards.

**Comment by splifingate** [comment]
*whew*

I've been down-deep into things, and I just can't strip the `\x0D's` *grr*

I've been trying to work the angle from the hints you provided, above, by adding a str_replace() or preg_replace() at strategic locations.  For example:

```PHP
[...]

// [ln347 of admin.php] attempt to strip erroneous CR from $content
// multiple tries, with multiple functions, in multiple places

$content = str_replace("\r\n", '\n\n', $content);
$content = preg_replace('/\r/', '', $content);
$content = preg_replace('/\x0D/', '', $content);
$content = preg_replace('/\x{0D}/', '', $content);

$post_content = "<!--t " . $post_title . " t-->" . $post_description . $tagmd . $post_media . "\n\n" . $content;

[...]
```

Nothing I have tried works.

I ran-through the AdminLTE Edit Post in my browser (Firefox and Safari) with Web Developer/Inspector, and the content of the post.md is in two strings in the `<textarea id="wmd-input">`:

original (`"Shadow Content (User Agent)"`)

and edited (`<div contenteditable="plaintext-only">`).

Each string is appropriately `\n\n` between lines, but I lose the chain of events after I submit `Update post`.  This led me to wonder if `print_r()` or `file_put_contents()` is doing something odd.  Tried a lot of other `str_replace()` and `preg_replace()` variations (in *many* different places) to no avail.

I did find a reference to problems with `file_get_contents()` and UTF-8 (possibly rectified with `mb_convert_encoding()`, but I have not tried that, yet.

https://stackoverflow.com/questions/2236668/file-get-contents-breaks-up-utf-8-characters

In the process (to determine just where the `\x0D' addition happens), I did update to AdminLTE v3.2.0, bootstrap v4.6.1, jquery v.3.6.0, and jquery-ui v.1.13.0 with no errors . . . everything works and performs as splendidly as it did before!

No change in my .md files, however.

Everything works as expected (which is truly quite well), though this had no effect upon the erroneous `\x0D` characters.

I will keep looking as time permits.

**Comment by danpros** [comment]
Thank you for hard work! Googling and find: 
- `\x0D` is is the entity code for a carriage return (a line break) [(source](https://stackoverflow.com/a/43518545)). 
- `\x0D` is the escaped hexadecimal Carriage Return. The equivalent of \r. ([source](https://stackoverflow.com/a/9021756)).

Somehow even there is no line break in the end of the .md file the editor display those char.

**Comment by splifingate** [comment]
As frustrating as it has been to affect no change, it's been quite educational, and (at times) a lot of fun *smile*

I replaced the main *.min.js files with their respective full-blown *.js versions (current v.'s) so I could better debug/inspect the code.  Nothing odd happened, so I replaced those with their updated *.min.js, and everything works as expected.  I'm feeling a bit cautioned with relying on so much .js for basic functionality, but that's the Way of Things these days, so I guess I'm In.

I've used/tried/experimented/looked-for a **lot** of flat-file blog-type software over the past ten years, and HTMLy has been the most satisfying.  I used Grav for a few years, and--while performant, and pretty--it was basically *meh*  I need a tool; not a toolbox.

I can empathise with Shnugo in the [first link](https://stackoverflow.com/a/43518545) when he states:

"Not quite sure, what your problem is actually..."

I have been wondering the same *shrugs*

But, I'm determined to get to the bottom of it.

As time permits, I will diagnose, further.

**Comment by splifingate** [comment]
You said:

"Try ex. adding
in the end of the text content."

I do not understand.  Can you explain this a bit further?

**Comment by danpros** [comment]
> I've used/tried/experimented/looked-for a lot of flat-file blog-type software over the past ten years, and HTMLy has been the most satisfying. 

Thank you! The initial goal was just to create a simple blogging app, but even so, the stability, compatibility and speed should not be underestimated. Googling and found htmly blog with many post, seems atleast around 16k posts ([link](http://invenlight.com/studyhard/)).

> I do not understand. Can you explain this a bit further?

I mean try to creating post than in the end of the post add the `<br>` tag

**Comment by splifingate** [comment]
I added `<br>` (and `<br />`, for that matter) to, unfortunately, no effect.

I have been back-tracing `$_REQUEST` to try to see where the `\r\n | \r`additions/conversions are actually being made.

This is a recent `edit?destination=post` network Request back-trace from Firefox:

```json
{
	"title": "The+Wind+in+my+hair",
	"category": "haiku",
	"tag": "haiku",
	"description": "The+Wind+in+my+hair+Scatters+my+thoughts,+and+feelings.+The+Sun+warms+my+face.",
	"date": "2024-04-06",
	"time": "16:14:34",
	"url": "the-wind-in-my-hair",
	"is_post": "is_post",
	"oldfile": "content/splifingate/blog/haiku/post/2024-04-06-16-14-34_haiku_the-wind-in-my-hair.md",
	"csrf_token": "[long-HEX-string]",
	"content": "The+Wind+in+my+hair++\r\nScatters+my+thoughts,+and+feelings.++\r\nThe+Sun+warms+my+face.",
	"updatepost": "Update+post"
}
```

What I can't seem to do is back/forward-trace just *where* the `content` is actually being, er, actualized *smile*

I added:

```php
4501    $content = str_replace('\r\n', '\n\n', $content);
4502    $content = str_replace('%0D%0A', '\n\n', $content);
```

to htmly.php *to no effect*

https://www.php.net/manual/en/function.nl2br.php#121528

'chad' (in the previous link) had a situation where a PHP function was not happy with being in a `<textarea>`, and had to make accommodation.  

I am currently tracing adminlte and jquery for indicators that they might be manipulating the 'content' string....

**Comment by taufik-nurrohman** [comment]
Make sure you have `<meta charset="utf-8">` in your `<head>` secrion of your theme.

**Comment by splifingate** [comment]
> I added:
> 
> ```
> 4501    $content = str_replace('\r\n', '\n\n', $content);
> 4502    $content = str_replace('%0D%0A', '\n\n', $content);
> ```
> 
> to htmly.php _to no effect_

**whoa**

ok, so I worked on this a bit more, and I _finally_ achieved resolution:

```
 4501    $content = str_replace("\r\n", "\n", $content);
 4502    // $content = str_replace('%0D%0A', '\n\n', $content);
```

I re-visited the idea.

I was using `'` . . .

. . . found a post about [str_replace() in R](https://stringr.tidyverse.org/reference/str_replace.html), and noticed that their $string replace values were encapsulated with `"`

So, I modified my previous additions to htmly.php

```
 4501    $content = str_replace("\r\n", "\n\n", $content);
 4502    $content = str_replace("%0D%0A", "\n\n", $content);
```

. . . and I achieved *.md with **no** \x0D on each newline, but with progressively-additional newlines upon every edit.

Next edit was to filter the mods, for diagnosis:

```
 4501    $content = str_replace("\r\n", "\n\n", $content);
 4502    // $content = str_replace("%0D%0A", "\n\n", $content);
```

No \x0D, but *still* with progressively-additional newlines.

I changed this to:

```
 4501    $content = str_replace("\r\n", "\n", $content);
 4502    // $content = str_replace("%0D%0A", "\n\n", $content);
```

. . . and I gained standard *.md with no \x0D, and single newlines!

This edit persists from `Update post` to `Update post`!

Strangely, I am now getting an additional newline in the preview <textarea> with posts that have `%20%20%0A` line endings (which is additionally unfortunate, as the majority of my blog posts are haiku, and I use %20%20 on the first two lines to break for a threesome)

For Ex.:

```
The Wind in my hair  
Scatters my thoughts, and feelings.  
The Sun warms my face.
```

I am not experiencing `\n\n` on each newline with other .md documents.

I will need to re-base all Markdown.*.js, as I have probably sullied the four files to oblivion with my edits *shrugs*

Quite excited to experience this empirical progress, and am further energized to investigate, further *smile*

**Comment by splifingate** [comment]
> Make sure you have `<meta charset="utf-8">` in your `<head>` section of your theme.

I need to look, further . . . this should (as you point-out) be a simple solution.

thx

**Comment by taufik-nurrohman** [comment]
A, so I think this is related to the editor problem, when the value is passed to the text area, it may force the line ending with `\r\n` so when it posted, the value will always have them stored to the file. FYI, I always add this on top of the root file of my PHP application, just to make sure that any line ending posted from the form will be normalized before it is being processed:

![image](https://github.com/danpros/htmly/assets/1669261/d597c74a-ee58-414f-aac4-1697811620e9)

**Comment by splifingate** [comment]
> > Make sure you have `<meta charset="utf-8">` in your `<head>` section of your theme.

` 9   <?php echo $metatags;?>`

in layout.html.php provides that already.

I will explore your function() addition.  Thank you!

I'm still intent on finding the source of just what adds the x0Dx0A, so there would be no need for filtering . . . .

There are explicit newline normalization functions in the PageDown code, so it *must* be some previously-overlooked oddity inherent, or something that has not shown until its incorporation with all the other components in this Edit chain.

I can find no specific reference, anywhere, to erroneous de-normalization involving PageDown, let-alone any other .js <textarea> editor (I have searched for many days).

May I keep this issue Open, [Dan](@danpros), until I find the root?

**Comment by danpros** [comment]
@taufik-nurrohman thanks!

@splifingate sure, no problems!

For the function from taufik we can start it from `dispatch.php`

https://github.com/danpros/htmly/blob/4bcd6940f8d6c9ee79de5f5f851f9a5e8361a07c/system/includes/dispatch.php#L251

Perhaps:

```php
function from($source, $name)
{
    $map = array('\r\n' => '\n', '\r' => '\n');
    if (is_array($name)) {
        $data = array();
        foreach ($name as $k)
            $data[$k] = isset($source[$k]) ? trim(strtr($source[$k], $map)) : null;
        return $data;
    }
    return isset($source[$name]) ? trim(strtr($source[$name], $map)) : null;
}
```

**Comment by splifingate** [comment]
I added this to dispatch, commented-out my earlier edits to htmly.php, cleared cache and recent history.

The \x{0D}\n is back at the end of each line in in each .md when edited in either Firefox, or Safari.

I have not added [taufik](@taufik-nurrohman)'s earlier code example, mostly as I really don't know where to add it (I was guessing htmly.php?)

I really appreciate both of your thoughts on the matter *smile*

**Comment by splifingate** [comment]
> ```
>     $map = array('\r\n' => '\n', '\r' => '\n');
> ```

I changed this to:

```
    $map = array("\r\n" => "\n", "\r" => "\n");
```

And it looks as if it **does** strip the 0D's!

(just tested, again, and *Yes*: it strips \r from the edited .md's)

**Comment by danpros** [comment]
That's great! So the problems solved. I will release new version ASAP (especially because of security vulnerability).

**Comment by splifingate** [comment]
Thank you, @danpros.  I appreciate your attentiveness, and all the work you do to make HTMLy excellent. 

And thank you @taufik-nurrohman for your insights and example.  A very elegant solution.  I really appreciate your input on the matter *smile*

I'll still be trying to get to the root of the matter, but I'm gana Close this as Completed seeing as:

a) I and others can now save .md content that does not have unintended data, and

b) It's really a 0.000000000000001% edge-case with no actual impact on performance, or operability ;)
