### ISSUE TITLE
Custom layout update not used for anonymous user

### ISSUE THREAD

**Issue by CharliePoole** [danpros/htmly#720]
I'm not sure if this is a bug or just something I don't yet understand.

The front page of my blog at https://charliepoole.org is generated using a custom layout: `layout--front.html.php`. It's a very simple page, so all the content is included right in that file.

When I update the layout using the CPanel file editor, I am able to see the effect immediately, _provided I am logged into HTMLy_. When I log out, in order to make sure the update appears correctly to an anonymous user. I see some older version of the layout. I've made a number of changes to make sure this happens consistently, and it does. I have cleared my browser cache and the HTMLy cache to no effect.

It seems as if HTMLy must be saving my old custom layout somewhere in order for this to happen. Is this a known bug? Or is there some other explanation it? I'm using 2.9.5. In case it matters, I installed using Softaculous.

**Comment by CharliePoole** [comment]
I have cleared a number of times, sometimes manually by deleting index and widgets folders, other times using the clear cache command if I'm logged in. Can you tell me what name to look for in the pages folder?

By the way, the problem has now gone away. I guess there's some sort of timeout because that has happened before after a few hours. I'll try to recreate it again.

However, I still do not understand why a logged in user would see the changed front page sooner than an anonymous user.

**Comment by danpros** [comment]
Well any request from anonymous user is cached, example code:

```php
if (!login()) {
	file_cache($_SERVER['REQUEST_URI']);
}
```

By clearing the cache the layout should be changed instantly for both type of users. 

But if you only change the CSS than its browser level cache. Some hosting also using server level cache so any new changes only visible after some time (usually PHP files).

**Comment by CharliePoole** [comment]
Then that explains it fully. Thank you.

**Comment by CharliePoole** [comment]
FWIW, I just did some more work on my front page layout. I found that if I'm only changing the layout file, the simplest thing is to test anonymously and just delete `#.cache` each time I save a change to the layout.
