### ISSUE TITLE
Redirect after editing static page wrong?

### ISSUE THREAD

**Issue by phpSoftware** [danpros/htmly#721]
The edit_page() function in the system/admin.php redirects after editing a static page in the backend to the value of $destination but if I look up the form there is only the value 'static' inside. So I get a 404 error after saving.

I changed from: 
`$redirect = site_url() . $destination;`
 to
`$redirect = site_url() . $pUrl . '/';`

and this works for me...

**Comment by danpros** [comment]
The `$destination` is taken from `$_GET` request, so after saving the page it will redirect it. Example url:

```
http://localhost/htmly/about/edit?destination=admin/pages
```

After saving those `about` page it will redirected to admin/pages. This will ignore whether those URL available or not.

To redirect to the page/post usually the edit link:

```
http://localhost/htmly/about/edit?destination=post
```

After saving the `about` page it will redirect to those page also.

```php
        if ($destination == 'post') {
            if(!empty($revertPage)) {
                $drafturl = site_url() . 'admin/draft';
                header("Location: $drafturl");
            } else {
                header("Location: $posturl");
            }
        } else {
            $redirect = site_url() . $destination;
            header("Location: $redirect");
        }
```

**Comment by phpSoftware** [comment]
Oh, so only my edit link is wrong - thanks a lot for the fast hint

**Comment by danpros** [comment]
Yes just wrong edit link. You're welcome! I will close this one. Thanks
