### ISSUE TITLE
Seeking hints to input type="submit" name="updatepost" reference in /views/edit-content.html.php

### ISSUE THREAD

**Issue by splifingate** [danpros/htmly#723]
For the life of me, I cannot find where [input type="submit" name="updatepost"](https://github.com/danpros/htmly/blob/62cd98ac1ffbb874197f90186bea2b5407282ee4/system/admin/views/edit-content.html.php#L233) leads *shrugs*

I feel rather dumb at the moment, as I have looked *everywhere* to no avail.

Any pointer(s) you could provide?

thx

**Comment by danpros** [comment]
Sometimes it just to send POST to itself, the line https://github.com/danpros/htmly/blob/62cd98ac1ffbb874197f90186bea2b5407282ee4/system/htmly.php#L4479

**Comment by splifingate** [comment]
thx

That's certainly a lot to take-in, Dan ;/

Still doing debug on where the content is updated (replaced, after internal editing).

I am still learning, and certainly hope you forgive my odd explorations ;)

**Comment by danpros** [comment]
@splifingate htmly is actually very simple, but because most of the code is quite old code, so it's quite confusing 😄

**Comment by splifingate** [comment]
I am getting closer to understanding it better.  Thanks for your help :)
