### ISSUE TITLE
Upgraded HTMLy shows dates in strange format

### ISSUE THREAD

**Issue by NiccyB** [danpros/htmly#724]
I have just upgraded to the latest version (2.9.6) - I unzipped the latest version and copied over config/* and content/* from the old installation to the new installation - this is what I've always done to upgrade before renaming directories and making the new one live.
Unfortunately, while dates show correctly in the create/edit pages, on the blog pages, they show with a weird format:

This is what shows on the 'Edit' page:
![image](https://github.com/danpros/htmly/assets/31012803/ba356c92-e5a5-427c-9fda-4b2cefdc50fc)

This is what shows on the blog pages:
![image](https://github.com/danpros/htmly/assets/31012803/ca1980d7-ea12-42cd-bf50-f33c0d4338e6)

As you can see, the date is there, but there are three "%"s and a "62" which shouldn't be there in this example.

**Comment by NiccyB** [comment]
OK, so the format of config.ini has changed. It used to be dates in strftime format (i.e. with a '%') and now it isn't (despite the sample .ini saying that it is). The %'s aren't used any more and 'B' (formerly '%B') doesn't give the full month like it used to (I haven't worked out what it is doing, but it's definitely not the full month).

**Comment by NiccyB** [comment]
Another update. It seems that any month names (b, B and h) don't work any more.
a and A also don't work any more (they now show am/pm rather than the day).
I can only assume that strftime is no longer being used.

**Comment by danpros** [comment]
Hello,

Simply go to admin/config and choose your desired date format and click save, it should fix the problems.

**Comment by NiccyB** [comment]
Thank you for clarifying.
