### ISSUE TITLE
[Feature Request] Add links and images directly in the post editor, not via a reference at the bottom

### ISSUE THREAD

**Issue by thopanX** [danpros/htmly#725]
Would you consider making it configurable, how images and links (via the toolbar) are inserted into the Markdown?

This is probably a personal preference, but I really like the `[XXX](https:…)` style more than the "footnotes style". I can at once see where the link is leading or what image I inserted, instead of having to scroll to the bottom of the editor.

![grafik](https://github.com/danpros/htmly/assets/1814897/9d915b7e-20d6-46cf-9d73-1b5a3b90a4b6)

**Comment by danpros** [comment]
Yes, sometimes it is quite confusing, to achieve this we have to edit some parts of the `Markdown.Editor.js` example:

https://github.com/danpros/htmly/blob/62cd98ac1ffbb874197f90186bea2b5407282ee4/system/admin/editor/js/Markdown.Editor.js#L1807

**Comment by danpros** [comment]
It seems that changing the code in that line is enough:

```js
// var num = that.addLinkDef(chunk, linkDef);
chunk.startTag = isImage ? "![" : "[";
chunk.endTag = "](" + properlyEncoded(link)+ ")";
```

**Comment by danpros** [comment]
Its browser caching, try to reload the page in editor, if you are using cloudflare clear the cloudflare cache.

**Comment by danpros** [comment]
I will include it in future release
