### ISSUE TITLE
php-mbstring required for 2.9.x

### ISSUE THREAD

**Issue by KuJoe** [danpros/htmly#729]
I upgraded one of my blogs from an older 2.8.x version to the latest version and my home page (Your latest blog posts) would not load correctly but all other pages on the site loaded properly. After much troubleshooting it ended up being that my webserver was missing the php-mbstring module which I installed and fixed the home page immediately.

This module should be added to the documentation under Requirements just to avoid confusion like this in the future with new installs.

**Comment by danpros** [comment]
Hello,

Already updated the docs.

**Comment by danpros** [comment]
I will close this one. Thanks
