### ISSUE TITLE
<meta charset="utf8"> prepended to menu()

### ISSUE THREAD

**Issue by splifingate** [danpros/htmly#731]
When viewing the source of my main blog page, I noticed `echo menu();` is writing:

```html
<meta charset="utf8"><ul class="nav navbar-nav "><li class="item nav-item " [...] </ul>
```
In `functions.php`, if I change:
```php
2683	$doc->loadHTML('<meta charset="utf8">' . $html);
```
to
```php
2683	$doc->loadHTML($html);
```
I get
```html
<ul class="nav navbar-nav "><li class="item nav-item " [...] </ul>
```

I was correcting some tags I had not closed in /themes/[copy]/layout.html.php, and noticed this.

Browsers are _very_ forgiving :)

**Comment by danpros** [comment]
Hi,

This is to fix character encoding eg. Chinese char in menu, need to specify the charset before load it to the DOMDocument. Yes we should removed it in the output 😃
