### ISSUE TITLE
Admin - Clear Cache - Not working [V2.9.6 & V2.9.7]

### ISSUE THREAD

**Issue by vdbhb59** [danpros/htmly#732]
Hi Dan,
Till V2.9.5 and even before that admin > clear cache would always work and the cache folder data would get cleared/deleted recursively. However, that function seems to be broken.

I realized this when I kept getting no new updated from 2.9.6 to 2.9.7 just now and saw that the cache folder data remains as it is, and it is from the day 2.9.6 was released - 03.03.

I manually deleted the cache folder and I refreshed the admin > update, and it showed V2.9.7. After that I closed all browsers and logged back in, cleared cache (tried 2-3 times), but the folder data inside remained as is.

Now this was not the case in earlier versions as I mentioned. Even with 2.9.7, clearing cache does nothing.

Edit: This is with almost every other theme. I checked.

![image](https://github.com/danpros/htmly/assets/60728004/97bb3a8c-ae77-476f-8357-700f4cba2fcf)

![image](https://github.com/danpros/htmly/assets/60728004/87edde94-8af9-481f-aaaf-f231e5b40f1c)

![image](https://github.com/danpros/htmly/assets/60728004/235362f8-9c50-46ab-aa93-64e7ef559975)

**Comment by vdbhb59** [comment]
Already tried that several times. But seems nothing happens. Is there some config that I am missing? Anywhere in the code that I can see what I maybe missing?

**Comment by danpros** [comment]
Everytime clearing the cache, htmly automatically repopulate the index files, and the folder itself not deleted, so that's normal. htmly  only creating the folder if the folder does not exist (cache, index, page, and widget folder).

**Comment by vdbhb59** [comment]
Yes, that I know, but the downloadInfo.json (the updater indexing file) does not get cleared and hence the updater is unable to locate the updated version as well.

**Comment by danpros** [comment]
Ah the `downloadInfo.json` is updated when we visiting the update page. Then htmly compare the installed version with new downloadInfo.json. Try to delete the downloadInfo.json and visiting the update page, if the file not created the possibility the server can't connect to github server (make sure enable the `allow_url_fopen` in your php.ini)

**Comment by vdbhb59** [comment]
Ahh understood. Although `allow_url_fopen` is enabled, for some weird reason, the cached `downloadInfo.json` file was not getting deleted as well. FYI, does this need a look into the code? Since V2.9.5 and below, it used to work properly.

**Comment by danpros** [comment]
Its not getting deleted but updated, open the file and you should see, example:

```
        "url": "https:\/\/api.github.com\/repos\/danpros\/htmly\/releases\/153182234",
        "assets_url": "https:\/\/api.github.com\/repos\/danpros\/htmly\/releases\/153182234\/assets",
        "upload_url": "https:\/\/uploads.github.com\/repos\/danpros\/htmly\/releases\/153182234\/assets{?name,label}",
        "html_url": "https:\/\/github.com\/danpros\/htmly\/releases\/tag\/v2.9.7",
```

Please check your server error log for more info for those problems.

**Comment by danpros** [comment]
I will close this one, because seems this is a false positive. Thanks.
