### ISSUE TITLE
Batch upload...

### ISSUE THREAD

**Issue by lemarcgagnon** [danpros/htmly#735]
Hello,

I would like to upload quite a few md files, but i see that the listing of the md files is not adjusted automatically, unless i create anoter page, is there a way I can have le listing updated as soon as I put a new md file in the directory?

Amazing app.

Marc

**Comment by danpros** [comment]
Hi Marc,

Thanks! There are several ways:

1. First go to the dashboard and clear cache, or simply edit and save existing page/post also work.
2. Delete the index, widget, and page folder inside cache folder manually.

When using clear cache page, the function delete the contents inside index, widget, and page folder.

**Comment by lemarcgagnon** [comment]
Hello thank you so much for the help I will proceed as you say thank you so
much

**Comment by danpros** [comment]
I will close this one. Thanks
