### ISSUE TITLE
updating to new version

### ISSUE THREAD

**Issue by lemarcgagnon** [danpros/htmly#736]
Once again, such a nice work.

My question: If i want to update to your latest version, can i just upload the new files in the repertory and the files will be replaced and the new ones added, right? and my md files do not need to be affected.

Yours,

Marc

**Comment by lemarcgagnon** [comment]
Hello,

Thanks so much. What a wonderful app. Thanks for the work. I wish I were a
programmer to help you out too.

Marc

**Comment by danpros** [comment]
Marked as fixed. I will close this one. Thanks

**Comment by lemarcgagnon** [comment]
Awesome, thanks!

**Comment by lemarcgagnon** [comment]
Hello.

I have prepared myself many files to upload into the right content folder.
However in doing so, the articles are not being listed and the tags become
the blogs title.

I had a look and saw that a tag file is being created with all the listings
of the tags (content/data/tags.lang ) and it gets in the way for my bulk
uploads.  Which part of the code is responsible for creating this file, i
would like to see the logic in order to replicate it for the files I want
to bulk upload.

Thanks,

Marc

**Comment by lemarcgagnon** [comment]
@Google Drive wich part of htmly files in my drive is responsible for
creating the tags

**Comment by lemarcgagnon** [comment]
gee whiz i got it wrong, as seen in the picture, the tags column is being
replaced by the name fd the file for all uploaded files in the folder

**Comment by danpros** [comment]
Hello,

Those file auto generated and always updated with current contents.
