### ISSUE TITLE
Not is possible delete static pages, categories

### ISSUE THREAD

**Issue by trancallan** [danpros/htmly#737]
Hi, i have a HTMLy version 2.9.7, in version 2.9.6 the same thing happens

When I tried to delete categories or pages, these are not eliminated.
I adjust CHOMD 777 to folders content anda cache, but this has not worked.

When delete something, this is confirmed, but the page _http://...../contacto/delete?destination=admin/pages_ appear blank.
Attaced video

https://github.com/danpros/htmly/assets/68283397/c4b487c7-0d05-4741-b0ae-894db3090aa6

I take this opportunity to congratulate you on this easy and simple CMS. It would only slightly improve the editor or be able to select a more complete one.

Regards

**Comment by danpros** [comment]
Hello,

Thanks. Seems to be only for version 2.9.7 (after trying to fix the directory traversal vulnerabilities). I will release new version ASAP.

**Comment by danpros** [comment]
Hello,

This has been fixed in v.2.9.8. Thanks
