### ISSUE TITLE
/admin/update page not working on v2.9.7 (not showing v2.9.8 update)

### ISSUE THREAD

**Issue by KuJoe** [danpros/htmly#738]
I'm not sure if this is a caching issue or not, but none of my HTMLy installs (running v2.9.7) were showing the v2.9.8 update on the /admin/update page until I manually deleted the "downloadInfo.json" file in the /cache/ directory and revisited the page.

This might be an issue other users run into if they were on v2.9.7 like me so I wanted to let you know so you could possible post this information somewhere in the v2.9.8 release notes to have the users delete the /cache/downloadInfo.json file if they're not seeing the update.

Thanks!

**Comment by danpros** [comment]
Hello,

I am quite sure that this is due to cache, the default is 12 hours. We should decrease it, perhaps 3-6 hours.

**Comment by KuJoe** [comment]
Since this appears to be caching related, I'm closing this issue.
