### ISSUE TITLE
Spoiler

### ISSUE THREAD

**Issue by KridKon** [danpros/htmly#740]
How can I implement a spoiler?

**Comment by danpros** [comment]
htmly allow html tag in text editor so use `<details>` instead ([read the docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details)). Example:

```html
<details>
  <summary>Spoiler</summary>
  Something small enough to escape casual notice.
</details>
```

**Comment by danpros** [comment]
I will close this one. Thanks

**Comment by KridKon** [comment]
Thank you. can I add it to the panel using the button?

**Comment by danpros** [comment]
To add it to the editor toolbar you need to modify the `Markdown.Editor.js` in `/system/admin/editor/js/Markdown.Editor.js`. 

I consider adding this in the next release but there is no ETA.
