### ISSUE TITLE
H4 tags capitalized

### ISSUE THREAD

**Issue by AutomationMan808** [danpros/htmly#742]
Sorry I couldn't find a version number but it was the before this beta version and for now I plan on continuing to use this earlier version. I know most people probably don't even use h4 tags but when I do the text comes out in all capitals. Is there a place in the code where I can fix this?

Rick

**Comment by splifingate** [comment]
> use h4 tags but when I do the text comes out in all capitals

Are you talking about in the HTMLy Editor?

I get (what I think) are correct headings.  Using the following:

```markdown
# h1
## h2
### h3
#### h4
##### h5
###### h6
```

I get

# h1
## h2
### h3
#### h4
##### h5
###### h6

I can also--directly--add `<hX>Heading</hX>` to the document in the Editor, and it produces (what I believe is) correct results:

```markdown
<h2>H2 heading</h2>
A simple example.  
With a simple result.
```
Can you provide more context, and example(s)? :)

**Comment by danpros** [comment]
@splifingate thanks.

@AutomationMan808 you can use `inspect` feature in your browser (right click) to know which CSS value affect it ([link](https://www.w3schools.com/cssref/pr_text_text-transform.php)).

**Comment by AutomationMan808** [comment]
Yes I can sorry. I do all HTML code so if maybe that's the issue, but if you go here   https://busybusinesshosting.com/ and do a control f for COMES WITH PROGRAMS TO AUTOMATE YOUR ON-TOPIC CONTENT AND YOUR MARKETING!

When you do the same thing looking at the source you'll find 

<code><h4>Comes with programs to automate your on-topic content and your marketing! </h4></code>

**Comment by AutomationMan808** [comment]
> @splifingate thanks.
> 
> @AutomationMan808 you can use `inspect` feature in your browser (right click) to know which CSS value affect it ([link](https://www.w3schools.com/cssref/pr_text_text-transform.php)).
> 
> Edit: simply remove the line.

Thank you I'll look at putting some CSS onto the layout since on page takes precedence over CSS file links

**Comment by AutomationMan808** [comment]
This fixed it

<code>   <style>
                body h4 {
            text-transform: capitalize !important;
        }
    </style></code>
