### ISSUE TITLE
SEO standard invalid of META tags - Inside BODY tag

### ISSUE THREAD

**Issue by vvcares** [danpros/htmly#744]
1. SEO standard un-necessary META tags - Inside BODY tag
Sample File : https://github.com/danpros/htmly/blob/master/themes/blog/layout.html.php
Line : 28, 29

META tags should be in <head. 
NOT inside <body

2. NAVIGATION ROLE is un-necessary:
Line: 141 >> *** role="navigation"

3. functions.php >> 2688 >> Un-necessary META tag *** <meta charset="utf8"
4. The type attribute is unnecessary for JavaScript resources.

**Comment by danpros** [comment]
Hello,

Thanks. For number 3 to fix eg. Chinese char in menu actually but not removed in the output.

**Comment by vvcares** [comment]
So this #3-CHARSET supposed tobe removed for SEO. Is it ?
Im still seeing it not removed on v2.9.9

**Comment by danpros** [comment]
Already fixed it in master branch. Thanks
