### ISSUE TITLE
Possible to add custom HTML and/or JavaScript

### ISSUE THREAD

**Issue by codinginbarn** [danpros/htmly#746]
Not an issue, but I do not know where else to ask...

I have been tasked to find a platform such as HTMLY for a non-profit organization. The top team members all need separate blogs and HTMLY would fit nicely.

One important requirement is ability to add custom HTML and/or JavaScript to posts/pages. Kind of like a WordPress custom HTML block. Is this possible with HTMLY?

Thanks for your time.

**Comment by danpros** [comment]
Hello,

Short answer, yes. HTMLy text editor allow HTML tags and JavaScript.

For automated addition, use custom config or put the tags and javascript directly to the template files.

**Comment by codinginbarn** [comment]
Ok, thanks. Thought there may be a way to insert directly from editor without setting up custom tags.

Cheers!
