### ISSUE TITLE
Commentics

### ISSUE THREAD

**Issue by philips300-code** [danpros/htmly#747]
https://commentics.com/integration

Hello, 
when you add integration code

post.html.php
```
<?php session_start(); ?>
<!DOCTYPE html>
```

```
<?php
**$cmtx_identifier = '1';
$cmtx_reference  = 'Page One';
$cmtx_folder     = '/comments/';
require($_SERVER['DOCUMENT_ROOT'] . $cmtx_folder . 'frontend/index.php');
?>**
```

I have an error in the console.
_PHP Notice:  session_start(): Ignoring session_start() because a session is already active in /home/...../public_html/themes/doks/post.html.php on line 1_

**Comment by danpros** [comment]
Hello,

You just need to remove this one `<?php session_start(); ?>` because we already called it.

**Comment by philips300-code** [comment]
Hello,
When I remove when `<?php session_start(); ?>`
When there is a new comment, it is not visible on the new device.

When cleared from here, a comment is displayed
/admin/clear-cache

**Comment by danpros** [comment]
For users who are not logged in, each visit will be given a cache page if the cache feature enabled. So if you are using PHP integration (the comments included directly to the page) with cache enable, ideally you need to delete the post cache every time new comment added and this requires a custom code.

The simplest way, of course, uses iframes like in their WordPress plugins.

**Comment by philips300-code** [comment]
thank you for the information

**Comment by philips300-code** [comment]
Hello,
From here I need to take the code and link to the cache.
But I don't understand where the file is located.

Link:
https://commentics.com/events

```
<?php
/* Event for when a new comment is added */
if ($event == 'comment_added') {
  // add your own code here
}
```

**Comment by danpros** [comment]
The cache is in cache/page folder. 

Try in `post.html.php`

```php
<?php
$id = strtok($_SERVER["REQUEST_URI"],'?');
$cmtx_identifier = $id;
$cmtx_reference  = $p->title;
$cmtx_folder     = '/comments/';
require($_SERVER['DOCUMENT_ROOT'] . $cmtx_folder . 'frontend/index.php');
?>
```

And `all.php` example:

```php
<?php
/* Event for when a new comment is added */
if ($event == 'comment_added') {
    $c = str_replace('/', '#', rawurldecode($page_identifier));
    $cachefile = 'cache/page/' . $c . '.cache';
    if (file_exists($cachefile)) {
        unlink($cachefile);
    }
}
```

**Comment by philips300-code** [comment]
Hello
i can't figure out where i should create the folder **all.php**

**Comment by danpros** [comment]
Well already written here: https://commentics.com/events

> To listen for an event, create a file called all.php inside the folder below: `/comments/system/events/`

**Comment by philips300-code** [comment]
Thank you for your help.

**Comment by danpros** [comment]
Updated the answer.
