### ISSUE TITLE
new Install white page no theme

### ISSUE THREAD

**Issue by riaanp78** [danpros/htmly#749]
Don't know if this is a bug or a missing step in the documentation, but after the online installer saves the config and I refresh the page the page shows basic html without any themes. Almost like it is not finding it. 

Just want to point out again that this is a initial install, nothing else has been done yet (no changes made expect the online installer)

php version: 8.2
nginx
Debian 12

**Comment by danpros** [comment]
Hello,

Please install php-fpm, php-mbstring, php-xml, php-common, php-cli, php-curl, php-zip, and php-intl.

Example [nginx configuration](https://docs.htmly.com/web-servers/nginx)

**Comment by riaanp78** [comment]
I was missing this package from your list: php-curl, still only a white screen instead of theme.

![image](https://github.com/danpros/htmly/assets/15311970/e4ec4d8c-62ff-493d-936d-0c7340002ecd)

**Comment by riaanp78** [comment]
[info.pdf](https://github.com/danpros/htmly/files/15305554/info.pdf)

If it helps. I created a php info pdf to show all the modules.

**Comment by danpros** [comment]
Seems the CSS not loaded, please check the server error log. Is this visiting the site using https URL? if yes make sure the site url in admin also using the https and not just http.

**Comment by riaanp78** [comment]
Server log has no 404 errors. I was testing it on LAN without https .e.g http://192.168.1.101:8080/.

**Comment by danpros** [comment]
It doesn't have to be an error 404, it can be another error message related to theme resources. Try to visiting the CSS file using the browser. Example:

```
https://www.htmly.com/themes/htmly/assets/css/bootstrap.min.css
```

**Comment by riaanp78** [comment]
I got a 404 error when i tried to access the CSS directly. let me try something first. Could be my PHP install is no working 100%, will install wordpress or any other PHP based application and check quick.

**Comment by vdbhb59** [comment]
You seem to have access error for direct files and resources. That is why the theme or anything else is not loading. Do a clean install after a system reboot. See what happens.
