### ISSUE TITLE
Adding sub-categories

### ISSUE THREAD

**Issue by ashraf21c** [danpros/htmly#753]
Hello, I love HTMLy, it`s pretty nice and easy to use.
I have a question, is there anyway to create sub-categories?
Let`s say an HTMLy blog has a category named "Languages", and it needs sub categories "Japanese", "Arabic", etc...
Yes, I can add them all as categories, but I would prefer to have them in subcategories, to organize them and to make it easier for site visitors.

**Comment by danpros** [comment]
Hello,

With current folder structure is not possible to create sub-category. From the readme:

```
content/my-username/blog/my-category/post/2024-01-10-15-35-45_tag1,tag2_my-post-slug.md
```

For simplicity we will keep current folder structure.

**Comment by danpros** [comment]
You are welcome to create pull request to fix that.
