### ISSUE TITLE
What is the safe way to disable all navigation menu items? (Grid Zone Theme)

### ISSUE THREAD

**Issue by ashraf21c** [danpros/htmly#754]
Hello,
Thank you very much for this awesome CMS.

I don`t want to play with the core, so, I`m asking if there`s a safe way to hide all navigation menu items.

The main page is set to "latest posts", the theme has a search box and a thumbnail grid items of posts. There is no other pages. 
I have 2 items in the navigation bar.. "blog" and "home".

"home" is set inside the settings, I don`t want it.. I tried to leave it blank but requires a name to be inserted and automatically puts "home"..

"blog" is not needed as well.. as from my experience with another theme in HTMLy, I can omit "blog" by just creating a static page.

However, I want both items to disappear.. it`s a one page website with image grid, no distractions.

I can search for relative codes in CSS and html and delete/hide them. Is this way safe? or do you recommend me using another method for this?

**Comment by danpros** [comment]
Hello,

Please use the menu editor/manager to manage the menu.

**Comment by ashraf21c** [comment]
> Hello,
> 
> Please use the menu editor/manager to manage the menu.

It has no items.. and tells me that I will create a custom menu.
However, in fact, there are two items in the menu. "home" and "blog".
I`ll back it up then modify the css.

**Comment by danpros** [comment]
Just create menu with empty title and empty link or # and save. This should display empty menu. If there is no menu in manager than it will auto generated.
