### ISSUE TITLE
How to customize the sidebar (Grid Zone Theme)

### ISSUE THREAD

**Issue by ashraf21c** [danpros/htmly#755]
Hello,
I want to show ONLY "tags" in the sidebar, and nothing else.. no categories, no archives.
Shall I delete corresponging values in the CSS? or is there another way for this?
Thanks.

**Comment by danpros** [comment]
Hello,

Please read [htmly docs](https://docs.htmly.com/theming). You just need to remove it manually in `layout,html.php`.

For specific theme issue please create it in those theme repository.
