### ISSUE TITLE
How to Submit Enquiry Form together

### ISSUE THREAD

**Issue by ledlig** [danpros/htmly#760]
We have code like this:

`<form class="m-auto" style="max-width: 600px;" accept-charset="UTF-8" action="https://forms.zohopublic.com/zhangkaihui22/form/Html5/formperma/XXXXID/htmlRecords/submit" enctype="multipart/form-data" method="POST">
 <input name="zf_referrer_name" type="hidden" value="">
 <input name="zf_redirect_url" type="hidden" value="">
 <input name="zc_gad" type="hidden" value="">
 <input name="utm_source" type="hidden" value=""> <input name="utm_medium" type="hidden" value=""> <input name="utm_campaign" type="hidden" value="">
 <input name="utm_term" type="hidden" value=""> <input name="utm_content" type="hidden" value="">
 <input name="gclid" type="hidden" value="">
<h3 class="my-4">Contact Us</h3>
<hr class="my-4"><input class="d-none" name="bot-field" type="text">
<div class="form-group mb-3 row"><label class="col-md-5 col-form-label star" for="your-name2">Your Name:</label>
<div class="col-md-7"><input id="your-name2" class="form-control form-control-lg" maxlength="255" name="SingleLine" required="" type="text" value="" placeholder="Full name.."></div>
</div>
<div class="form-group mb-3 row"><label class="col-md-5 col-form-label star" for="your-email3">Your Subject:</label>
<div class="col-md-7"><input id="your-email3" class="form-control form-control-lg" maxlength="255" name="Email" required="" type="text" value="" placeholder="Your Email."><small class="form-text text-muted"> Please enter a valid email address</small></div>
</div>
<div class="form-group mb-3 row"><label class="col-md-5 col-form-label star" for="your-Subject4">Your Email:</label>
<div class="col-md-7"><input id="your-Subject4" class="form-control form-control-lg" maxlength="255" name="SingleLine1" required="" type="text" value="" placeholder="Your Subject."><small class="form-text text-muted"> Please enter a the Subject</small></div>
</div>
<hr class="bg-transparent border-0 py-1">
<div class="form-group mb-3 row"><label class="col-md-5 col-form-label star" for="your-message6">Your Message:</label>
<div class="col-md-7"><textarea id="your-message6" class="form-control form-control-lg" maxlength="65535" name="MultiLine" required="" placeholder="Product Name, Quantity, Parameters, Packages.."></textarea></div>
</div>
<hr class="my-4">
<div class="form-group mb-3 row"><label class="col-md-5 col-form-label" for="send-a-message8"></label>
<div class="col-md-7"><button class="btn btn-primary btn-lg" type="submit">Send a Message!</button></div>
</div>
</form>`

**Comment by danpros** [comment]
Hello,

HTMLy allow custom template file for individual page. [Read the docs](https://docs.htmly.com/theming/structure#custom-layout.subpage-structure).

If you have Contact Us page with slug `contact-us`. You can create `static--contact-us.html.php` and use your PHP code there. 

And HTMLy also automatically include the `functions.php` if this file exist in theme folder. When naming the function in theme `functions.php`, use `themeName_functionName()`, to make sure not conflicted with existing function.

So you need custom code to achieve what you need.

**Comment by danpros** [comment]
I will close this one.
