### ISSUE TITLE
Article summary at home page getting error

### ISSUE THREAD

**Issue by ayahanike** [danpros/htmly#761]
My config:

Blog posts displayed as: Summary
Summary character: 200
Summary behavior: Default

But showing this
document.addEventListener("DOMContentLoaded", function() { if (document.getElementById('toc-wrapper.post-1716175195').parentNode.classList.contains('post-1716175195')) { 

Help please :(

Screenshoot my home page:
![summary](https://github.com/danpros/htmly/assets/143980987/2f53fe72-c14f-4fb5-8791-585c4126355a)

**Comment by danpros** [comment]
Which version? htmly latest version already fix this TOC issue.

**Comment by danpros** [comment]
I will close this one. Thanks.
