### ISSUE TITLE
[FEATURE REQUEST] Admin to User Problem 

### ISSUE THREAD

**Issue by followthwhiterabbit** [danpros/htmly#768]
I was previously admin of my blog and accidentally made myself user and lost a lot of privileges to edit my site. Now, I cannot roll it back. 

It would be really nice if it would not be possible to make yourself user when there is only one user in the website.

**Comment by danpros** [comment]
Hello,

Simply use your hosting file manager, go to `config/users/` folder, edit username.ini, change the role to `admin`.

Yes we need an extra check for it.
