### ISSUE TITLE
[BUG REPORT]Theme Issue

### ISSUE THREAD

**Issue by followthwhiterabbit** [danpros/htmly#769]
I changed the theme and now i cannot reach my blog page, how can i revert back to the previous theme ? 

![Screenshot from 2024-05-25 23-53-48](https://github.com/danpros/htmly/assets/62688580/e249127b-f14b-4de2-a6ff-d7f09b600f37)

**Comment by danpros** [comment]
Not the theme but there are characters that shouldn't be in config.ini, for example in blog descriptions etc. Please read this: #750

Pay attention to the quotation marks. We should filter it in our next release.
