### ISSUE TITLE
[QUESTION] Sitemap.xml - is listing only my current year OR max 39 rows

### ISSUE THREAD

**Issue by vvcares** [danpros/htmly#770]
[BUG REPORT] /blog/sitemap.post.xml- is listing only my current year OR max 39 rows.
Is there any limitations of max rows.?
A sitemap supposed to show all my existing pages. Kindly advise. Thank you

**Comment by danpros** [comment]
There is no limit.

How many published blog posts? I see a blog with 10K posts and its work fine.

**Comment by vvcares** [comment]
SORRY.. Im wrong. I was overlooked as sitemap - MOD-DATE.
Seems all posts are listed well. Thank you

**Comment by danpros** [comment]
NP! Perhaps in the future I will split up the sitemap.post.xml, per 500-1000 posts for performance reason (example: sitemap.post.1.xml, sitemap.post.2.xml etc.)
