### ISSUE TITLE
Errror On Installation

### ISSUE THREAD

**Issue by afoster1955** [danpros/htmly#772]
I'm trying to install HTMLy version 2.98 onto a site running PHP 7.4.33 and I am getting the following error message:

Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". 

Since when is php version 8.x needed to run HTMLy? Hopefully this is an anomaly as I will not be able to upgrade if that is the case as my webhost has not moved to php 8.x as yet

**Comment by danpros** [comment]
Hello,

Please install the latest version and not the master branch. https://github.com/danpros/htmly/releases

The libraries used for MFA feature require PHP 8.1 (in master branch). I'll try to find a solution to solve it.

**Comment by danpros** [comment]
The minimum PHP version from the master branch now PHP 7.2.
