### ISSUE TITLE
Ukrainian language

### ISSUE THREAD

**Issue by mrRomanko** [danpros/htmly#774]
Please add the Ukrainian language for HTMLy.

Here is the .ini file for HTMLy version 2.9.8: https://github.com/mrRomanko/uk_UA_HTMLy

**Comment by danpros** [comment]
Great, thank you! Added it to the master branch [4ced874](https://github.com/danpros/htmly/commit/4ced874ba315bc94e8a9e7621878eb89cfc373c3)
