### ISSUE TITLE
Subscribe Module

### ISSUE THREAD

**Issue by afoster1955** [danpros/htmly#776]
I am trying to add a module to the right hand panel for my users to subscribe to the blog.  I have a file (subscribe.php) and the process file (process-subscribe.php) in the theme folder and running the files separate will add the subscriber email to the text file, but I can't get it working if I add a module in the panel.  I can figure out why it doesn't work and any help will be appreciated.

**Comment by KuJoe** [comment]
Are you able to share the code you're using and any error messages you might be seeing in the webservers error logs?

**Comment by afoster1955** [comment]
I went in a different direction...using a link to the file and it seems to be working. Thanks for the follow up

**Comment by danpros** [comment]
I will close this one. Thanks
