### ISSUE TITLE
Hello, there is some error on the sitemap

### ISSUE THREAD

**Issue by philips300-code** [danpros/htmly#777]
I don't know why this is coming out post.1.xml

1. /sitemap.xml
![Без име2](https://github.com/danpros/htmly/assets/57016132/c972be40-1d39-4b3b-b346-eeb65d62ef36)

2. /sitemap.post.xml
![Без име](https://github.com/danpros/htmly/assets/57016132/dc3964ea-d2bd-4850-a626-e7e457208658)

**Comment by danpros** [comment]
That is not an error but by design. Starting from version 2.9.9, `sitemap.post.xml` is a sitemapindex. I split the `sitemap.post.x.xml` per 500 posts. Let say if we have 1500 posts than there is `sitemap.post.1.xml` `sitemap.post.2.xml` `sitemap.post.3.xml`. Why? for performance reason. Its work like pagination.

**Comment by philips300-code** [comment]
It shows me **the google search console** error
![Без име](https://github.com/danpros/htmly/assets/57016132/39ca0782-8c65-4007-ac06-5fc6ca306d96)

**Comment by philips300-code** [comment]
When you add this card sitemap.post.1.xml
![Без име](https://github.com/danpros/htmly/assets/57016132/bcc80e7a-add5-4ca9-aa88-336c919f438c)
It shows me the error

**Comment by danpros** [comment]
Can you translate it to English?

**Comment by danpros** [comment]
I try to add it a few moment ago not it success in my case

**Comment by philips300-code** [comment]
It works
![Без име](https://github.com/danpros/htmly/assets/57016132/a8345816-4925-4ca0-aa2b-d85fbda71d9e)

But on 
/sitemap.xml >/sitemap.post.xml shows an error
![Без име](https://github.com/danpros/htmly/assets/57016132/c3fae971-8666-46c0-9b28-7668bb94ebcf)

**Comment by NazgulCoder** [comment]
> It was fixed by re-adding /sitemap.xml
> 
> Thank you for your quick reply.

Hey I know this issue is already closed, but how did you get it?

I'm having the same issue you had above (1 error)

**Comment by Joduai** [comment]
Check if this sitemap is available from web and contains links to sub sitemaps.
You can always add links directly to sitemaps containing links to blog posts and static posts.
And dont rely on G webmasters, as its full of false errors, and it takes time to process.
Delete sitemapindex and try again after couple days.
