### ISSUE TITLE
[FEATURE REQUEST] Menu editor, supports relative URL

### ISSUE THREAD

**Issue by word-x** [danpros/htmly#779]
**Is your feature request related to a problem? Please describe.**
When I test locally, I should us

**Comment by danpros** [comment]
Hello,

If this is menu editor, we just need to add slash before the URL, example  `/about` and not just `about`

**Comment by danpros** [comment]
@cuixiping at the moment the menu field does not support variables in the menu yet. Perhaps we can just simply replace  the `{site.url}` to the `site_url()` during menu generation.

**Comment by Joduai** [comment]
This shouldn't be hardcoded as I'm fully for relative urls, and adding automatically domain to menu links should be optional.  
Maybe as a checkbox + short info about adding "/" before URI or just checking and adding automatically a missing slash
