### ISSUE TITLE
May be we should not put tags in the markdown file title

### ISSUE THREAD

**Issue by Louisna123** [danpros/htmly#780]
**Describe the bug**
If the user has many tags,  there would be error that the file name is too long to be renamed.

Warning: rename(content/user/blog/how-to-use/post/2024-07-05-11-57-39_post_sample-post.md, the filename, directory name, or volume label syntax is incorrect (code: 123) in ...\system\admin\admin.php on line 418
**To Reproduce**
Insert 20 tags

**Comment by danpros** [comment]
Hi,

This is a previously known limitation. This limitation comes from the OS itself which results in limitations to HTMLy as well, and for performance reason I will keep the structure as it is now.
