### ISSUE TITLE
Link previews not reflecting the real logos or the favicon - HTMLY/Ignite

### ISSUE THREAD

**Issue by ashraf21c** [danpros/htmly#785]
Hello,
I replaced all logos and the favicon, with correct size and extension.
However, link previews still showing this one:

<img width="431" alt="image" src="https://github.com/user-attachments/assets/9c781e32-ffe0-4314-86cd-5471e99b4b41">

How to fix it?
Thanks in advance.

**Comment by danpros** [comment]
Hello,

Perhaps it browser cache, try to clear it or reload the page. If using cloudflare try to purge the cache there.

**Comment by ashraf21c** [comment]
I already did this.
In addition, the screenshot is for Telegram.
The favicon is OK in the browser.
However, link previews are not.. anywhere.

**Comment by danpros** [comment]
When everything has been replaced and it still displays the old one, it's probably just cache, whether it's from the browser or Telegram.
