### ISSUE TITLE
Supporting Arabic commas under "tags"[FEATURE REQUEST]

### ISSUE THREAD

**Issue by ashraf21c** [danpros/htmly#786]
**Is your feature request related to a problem? Please describe.**
Under "New Post/ Tags" - If you type tags with Arabic comma you will get an "Internal Server Error 500", that can be easily recovered by refreshing or returning back.
If using English comma no problem happen, but it is very hard because Arabic is an RTL language.

**Describe the solution you'd like**
Defining the Arabic comma "،" so that it gets recognized and used with no need for the English comma between non-English keywords. The Unicode code is: U+060C.

**Describe alternatives you've considered**
I type English commas, then paste Arabic keywords between them.. this workaround works, but their order changes multiple times after every paste.
This is the first time for me facing such a problem. I don`t have this problem in the other alternatives.

**Comment by ashraf21c** [comment]
Hello, 
I found that the keywords are automatically saved for next times.. they can be entered with no problems (from the second time).
So, this is not important. Just define the keyword in the first time.

**Comment by danpros** [comment]
Hello,

Yes we only need to save it once. So this has been fixed?
