### ISSUE TITLE
[FEATURE REQUEST] STATUS heading/column in posts list

### ISSUE THREAD

**Issue by blork-mtl** [danpros/htmly#790]
OK, please ignore this request. I had a problem where I couldn't tell a draft from a published post, but I see that they appear in separate lists. There was still a problem where PUBLISHED posts were appearing in my DRAFTs list, but I fixed that by re-publishing. Anyway, this feature request can be ignored.

**Comment by danpros** [comment]
It's good that you've found the solution. I will close this one.
