### ISSUE TITLE
[QA] How can we list the blog (latest blog snippets) on the homepage which is outside the htmly folder?

### ISSUE THREAD

**Issue by virtualvinay** [danpros/htmly#792]
Didnt find any forum to post this question so added it here as a big report.

Is there a way in HTMLy, like in wordpress we can get the list of latest posts (max 4) on the homepage or any other page outside the Wordpress installation. I Suearched through the HTMLy docs but didnt find any. Also there is nothing related on the internet too.
Can you help me on this. i am planning to use HTMLy for blogs in all my future websites.

Appreciate your help
Thanks 
Vinay Acharya

**Comment by danpros** [comment]
Hello, I don't think this is a bug, similar topic #783
