### ISSUE TITLE
[NO Sub dirs]

### ISSUE THREAD

**Issue by kc0dxf** [danpros/htmly#795]
**Describe the bug**
I unzipped into the root of the web site and ran the installer.  I get the home page but clicking on anything doesn't work

Using Debian 12 bookworm and Apache.  Using https.

**To Reproduce**
Unzip into web server root.  Run install.php

**Expected behavior**
Web site should build and be functional

**Screenshots/Errors**
If applicable, add screenshots and/or error messages to help explain your problem. You may need to check your webserver's error logs.

**HTMLy Version**
Please list the exact version you are using (can be found on /admin/update next to "Installed Version").

**Server Info (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04.4, Debian 12, etc...]
 - Webserver [e.g. Apache 2.4, nginx 1.25, lighttpd 1.4.76, etc...]
 - PHP Version [e.g. PHP 5.6, PHP 7.4, PHP 8.3, etc...]

**Link to installation (optional, but usually helpful)**

**Additional context**

**Comment by danpros** [comment]
Hello, 

You need to configure the Apache, the docs: https://docs.htmly.com/web-servers/apache
