### ISSUE TITLE
[FEATURE REQUEST] Enable HTML compression

### ISSUE THREAD

**Issue by sadbird520** [danpros/htmly#796]
Thank you to the developer for this fantastic work!
Hopefully, developers will add this HTML compression feature.
[https://github.com/pfaciana/tiny-html-minifier](https://github.com/pfaciana/tiny-html-minifier)

**Comment by Joduai** [comment]
is minifying outputted html really worth the hassle?

With serverside enabled http compression, and user's browser content-encoding enabled by default, such minifying techniques became a relict of the past, when almost all website's traffic is compressed using gzip,deflate or brotli algorithm. 

If only purpose is getting rid of white spaces and new lines in outputted html, you can use a _preg_replace_ function in your template. There are dozens of snippets about this on stackoverflow.  But the real compression gain using such method is unnoticeable.
