### ISSUE TITLE
Comment system for HTMLy

### ISSUE THREAD

**Issue by thopanX** [danpros/htmly#798]
I saw someone asking about Yellow Comment and I myself asked about Activity Pub support as a comment system and federation perspective. So I thought I'd bring this up as a separate ticket.

I'd rather not have people having to register for Disqus or Facebook Comments.

**Describe the solution you'd like**
An easy commenting system which is hosted inside HTMLy and does not rely on big corp companies.

**Comment by Joduai** [comment]
Basically you are requesting additional 3rd party system comments like for example implementing activitypub or something from fediverse?
Or incorporating a 3rd party comment system into htmly?

For the second thing I was thinking about using interact script
https://github.com/CGrassin/interact_php

but didn't had time to try this one out
seems that there are couple fine solutions like the one @sadbird520 posted

**Comment by danpros** [comment]
Please move the discussion #803 Thanks
