### ISSUE TITLE
[BUG REPORT]Admin Panel (maybe not a bug)

### ISSUE THREAD

**Issue by Coeur2louve** [danpros/htmly#835]
Admin panel like a list

I am not a coder or informatician, so maybe it is not a bug.
I upload le latest Htmly on my host with online-installer.php, it's ok.
BUT
The admin panel has no css form and I don't know how to fix it, maybe there is something not installed or I made wrong.

**Screenshots/Errors**

<img width="826" alt="Capture d’écran 2024-11-09 à 11 28 02" src="https://github.com/user-attachments/assets/2642f682-5a38-4cdc-b611-ed1fdf8df861">

**HTMLy Version**
3.0.1

**Server Info (please complete the following information):**
 - OS: linux
 - Webserver Apache 2.4.62
 - PHP Version , PHP 7.4,
 - Cpanel 122.0
 - Perl 5.26.3

This panel is functional but not friendly to use.
I hope you can help me.
Thank you so much for this free blog engine

Regards

**Comment by danpros** [comment]
Hello,

If you visit the blog with an https address, make sure the blog address in the config uses the https format.

Try clicking `view page source` in your browser when on the admin page.  You will find the following:

```
https://www.example.com/system/resources/css/adminlte.min.css
```

Try visiting the URL to see if the file exists or not. You can also view the error log to find out what the problem is.

**Comment by Coeur2louve** [comment]
Hello Dear,
Thank you for help.
The adress site was set to http, so I forced the https in cpanel, but still issue in source code because css file was http, so conflict with mixed content.
I found the solution in some forum by adding in .httaccess file
_Header always set Content-Security-Policy: upgrade-insecure-requests_
That's it, it works.
So glad if it can help some other noob like me 
Regards

**Comment by danpros** [comment]
Hello,

Glad you could find the solution. You can also to go to the `admin/config` page and update the blog address to use the https URL instead of http.

Regards,

**Comment by Coeur2louve** [comment]
Hi,
Oh, your way is much more easy ! I didn't understood you mean to go in htmly admin panel in your first answer. Thank you again.
