### ISSUE TITLE
[Support]CSRF Token not correct

### ISSUE THREAD

**Issue by vdbhb59** [danpros/htmly#844]
**Describe the bug**
When I try to login, I get CSRF token not correct and am unable to login.

**To Reproduce**
Steps to reproduce the behavior: Just try to login on 

**Expected behavior**
I should be allowed to login

**Screenshots/Errors**
https://pb.flossboxin.org.in/?b0614cd0e48903bf#6hW3wcFLiEvZGVVodeFbrJnfnhNYEW26r1fDLKj2Bgw2

**HTMLy Version**
3.0.2 (Maintenance Release) https://github.com/danpros/htmly/releases/tag/v3.0.2.

**Server Info (please complete the following information):**
 - OS: [e.g. Debian 12.8]
 - Webserver [2.4.62, linux cPanel]
 - PHP Version [altphp8.3]

**Comment by danpros** [comment]
Hello,

```
[09-Dec-2024 07:37:26 UTC] PHP Warning:  session_start(): open(/var/cpanel/php/sessions/alt-php83/sess_ao68cbqtpssi8rjppsnv199s3i, O_RDWR) failed: No such file or directory (2) in /PATH/public_html/blog/system/includes/session.php on line 9
```

If this is in cpanel make sure the /tmp` are present. This error indicates that htmly cannot create a session.

**Comment by vdbhb59** [comment]
Thanks mate. Where exactly should this /tmp folder be in? I just use a shared hosting, so I will need to tell my provider if it is somewhere in root folder or like that.

**Comment by danpros** [comment]
You can try [this](https://stackoverflow.com/questions/58336354/session-start-opensession-file-o-rdwr-failed-no-such-file-or-directory-2) solution. Usually we just need to create the `tmp` folder inside the website directory.

**Comment by vdbhb59** [comment]
Those are already present and were always there. Even the etc folder is there all under my cpanel/userhome/
![image](https://github.com/user-attachments/assets/2a8b05d2-b9dd-4efa-8419-0dc36cafc21c)
![image](https://github.com/user-attachments/assets/c1a791cb-bbad-4cf6-812a-c463194dd896)

**Comment by danpros** [comment]
Try to adjust the write permission to allow group etc.

**Comment by vdbhb59** [comment]
Got it resolved. php.ini had missing tmp folder. For some weird reason. :(
Sorry for wasting your time mate.
