### ISSUE TITLE
[BUG REPORT] Failure to Render Markdown within <details> on Final Page (v3.0.2)

### ISSUE THREAD

**Issue by NikoBlank** [danpros/htmly#847]
I use `<details>` tags somewhat frequently for in-line notes and other functions. When I write them in a post, they mix with Markdown and render as expected in the preview pane. When I save the post to the site, however, the Markdown fails to parse within the tags. For example, the post body

```
<details>
No space before

Isolated paragraph

### Isolated header

No space after
</details>

<details>

Isolated paragraph

### Isolated header

Isolated paragraph

</details>

<details>
<summary>No space summary</summary>
No space before

Isolated paragraph

### Isolated header

No space after
</details>

<details>

<summary>Isolated summary</summary>

Isolated paragraph

### Isolated header

Isolated paragraph

</details>
```
renders like so: https://nikoblankworks.com/testing-page

Note that there are no `<p>` tags added to the `<details>` content, regardless of whether or not the content is isolated by line breaks or has a summary within it. I can add `<p>` tags manually and they render fine, but considering I expect to put some posts completely within a `<details>` tag for content warning reasons, I'd appreciate having a corrected Markdown renderer so I don't have to effectively write in raw HTML.

**Comment by danpros** [comment]
Hello,

Checking it and this is https://github.com/michelf/php-markdown behavior. See this line https://github.com/danpros/htmly/blob/788ccf36be20f63befe57dd4a3b62cacbd303d54/system/vendor/michelf/php-markdown/Michelf/MarkdownExtra.php#L349

You can delete the `|details|summary` to fix it. 

```
protected $block_tags_re = 'p|div|h[1-6]|blockquote|pre|table|dl|ol|ul|address|form|fieldset|iframe|hr|legend|article|section|nav|aside|hgroup|header|footer|figcaption|figure';
```

**Comment by NikoBlank** [comment]
Thanks for the response! I dug into this, and it seems like this is intended and even desirable behavior for PHP-Markdown; see [the pull request establishing this behavior](https://github.com/michelf/php-markdown/pull/329) and [a recent closed issue affirming this is accepted behavior](https://github.com/michelf/php-markdown/issues/404). It's a way to ensure these tags don't get wrapped in `<p>` tags erroneously despite the line breaks, it looks like. I'm not sure how GitHub and the post preview Markdown renderers differ in their solution to this problem ([GitHub's renderer doesn't have this problem](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab), while it seems like the preview pane may just let the `<p>` tags ride?), but I can confirm that you end up with empty `<p>` tags above and below the `<details>` block (and associated sequential lines) if you delete `|details|summary` from `MarkdownExtra.php`. I assume this is because you're technically getting
```
<p>
<details>
<summary>Foo</summary>
</p>
```
and the browser is automatically closing/opening the erroneously added `<p>` tags.

The intended solution by PHP-Markdown is to add `markdown="1"` to any block elements like `<details>` or `<summary>`, and that seems to make things work exactly as I originally expected; I've updated the test page so you can see for yourself. Given that there's this disparity between the preview pane and the actual on-site renderer, though, is there a way to bring the two of them into alignment?

**Comment by danpros** [comment]
Good to know you found a solution. Didn't realize php-markdown had that option.

> is there a way to bring the two of them into alignment?

If this is the style, you just need to override it using your theme css.

```css
details p {
text-indent: 0;
}
```

**Comment by NikoBlank** [comment]
Clarifying, I was wondering if there was a way to bring the preview pane's treatment of `<details>` and `<summary>` into alignment with PHP-Markdown's syntax, since it seems two different renderers are being used in these two contexts. Given that the preview pane adds the erroneous `<p>` tags, it seems like the one that should be altered. I'm more than comfortable editing my theme CSS, since I've been messing with it a fair bit to get articles looking how I want.

**Comment by danpros** [comment]
If you check the editor it has similar behavior with the `|details|summary` removed in Markdown PHP (use your browser inspect element to check the preview). htmly use pagedown https://github.com/StackExchange/pagedown for the text editor.

So the best solution right now is to delete `|details|summary` or using `markdown="1"`.

**Comment by NikoBlank** [comment]
Hm, yeah, it looks like Pagedown's lack of blocking out `<details>` and `<summary>` is a known (and longstanding) issue. I think I could figure out the spot where you'd add them to the list for treatment as block elements, but it also doesn't have Markdown Extra flavoring to appropriately handle the `markdown="1"` tag. Since updating Pagedown isn't feasible, I guess this is just the status quo; I'll go ahead and close this issue.
